import Foundation

enum AccessibilityGuides {
    private static let pass = DirectorySource(name: "Sozialministeriumservice · Behindertenpass", url: "https://www.sozialministeriumservice.gv.at/Menschen_mit_Behinderung/Behindertenpass_und_Parkausweis/Behindertenpass/Behindertenpass.de.html")
    private static let entries = DirectorySource(name: "Sozialministeriumservice · Zusatzeintragungen", url: "https://www.sozialministeriumservice.gv.at/Menschen_mit_Behinderung/Behindertenpass_und_Parkausweis/Behindertenpass/zusatzeintragungen/zusatzeintragungen.de.html")
    private static let parking = DirectorySource(name: "Sozialministeriumservice · Parkausweis", url: "https://sozialministeriumservice.gv.at/Menschen_mit_Behinderung/Behindertenpass_und_Parkausweis/Parkausweis/Parkausweis.de.html")
    private static let fund = DirectorySource(name: "Sozialministeriumservice · Unterstützungsfonds", url: "https://sozialministeriumservice.gv.at/Menschen_mit_Behinderung/Finanzielle_Unterstuetzung/Sonstige_finanzielle_Vorteile/Unterstuetzungsfonds/Unterstuetzungsfonds.de.html")
    private static let equality = DirectorySource(name: "Sozialministeriumservice · Schlichtung bei Diskriminierung", url: "https://www.sozialministeriumservice.gv.at/Menschen_mit_Behinderung/Gleichstellung/Schlichtung/Schlichtung.de.html")
    private static let workAssistance = DirectorySource(name: "Sozialministeriumservice · Persönliche Assistenz am Arbeitsplatz", url: "https://sozialministeriumservice.gv.at/weitere_Zielgruppen/Sonstige_Massnahmen_und_Projekte/Persoenliche_Assistenz_am_Arbeitsplatz/Persoenliche-Assistenz-am-Arbeitsplatz.de.html")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "disability": return disability
        case "accessible-services": return services
        case "assistive-devices": return devices
        default: return nil
        }
    }

    private static let disability = DirectoryGuide(
        cardSummary: .init(ukrainian: "Behindertenpass, підтвердження інвалідності й пільги", german: "Behindertenpass, Feststellung und mögliche Vorteile"),
        introduction: .init(ukrainian: "Іноземний документ про інвалідність не замінює автоматично австрійський Behindertenpass. Право та ступінь оцінює австрійська служба.", german: "Ein ausländischer Behindertenausweis ersetzt den österreichischen Behindertenpass nicht automatisch. Anspruch und Grad prüft die österreichische Stelle."),
        sections: [
            .init("eligibility", "person.crop.rectangle", "Перевірте право", "Anspruch prüfen", "Для Behindertenpass зазвичай потрібен ступінь інвалідності щонайменше 50 % та проживання або звичайне перебування в Австрії. Подайте заяву до земельного відділення Sozialministeriumservice; додайте медичні висновки, документи про особу та доступні переклади. Сама подача й видача посвідчення безплатні.", "Für den Behindertenpass sind grundsätzlich mindestens 50 % Grad der Behinderung und Wohnsitz oder gewöhnlicher Aufenthalt in Österreich nötig. Antrag bei Landesstelle des Sozialministeriumservice mit Befunden, Ausweis und verfügbaren Übersetzungen stellen. Antrag und Ausstellung sind gebührenfrei.", source: pass),
            .init("decision", "doc.text.magnifyingglass", "Отримайте рішення й перевірте записи", "Bescheid und Eintragungen prüfen", "Служба може провести медичну оцінку. Після рішення звірте ступінь, строк дії та потрібні додаткові записи: неможливість користуватися громадським транспортом, супровідна особа, знижка на проїзд. Ці записи вимагають окремих умов і не виникають автоматично.", "Es kann eine ärztliche Begutachtung geben. Nach Entscheidung Grad, Gültigkeit und benötigte Zusatzeintragungen prüfen: Unzumutbarkeit öffentlicher Verkehrsmittel, Begleitperson, Fahrpreisermäßigung. Dafür gelten eigene Voraussetzungen; Einträge entstehen nicht automatisch.", source: entries),
            .init("challenge", "arrow.uturn.backward", "Якщо ступінь визначено неправильно", "Bei falscher Einstufung", "Порівняйте висновок із поданими медичними документами й перевірте дату вручення Bescheid. Sozialministeriumservice повідомляє про шеститижневий строк оскарження після вручення; вирішальне значення має інструкція у вашому рішенні. Додайте конкретні пропущені обмеження та нові висновки, не подавайте лише загальне незадоволення результатом.", "Gutachten mit eingereichten Befunden vergleichen und Zustelldatum notieren. Das Sozialministeriumservice nennt sechs Wochen ab Zustellung für ein Rechtsmittel; maßgeblich ist die Belehrung im eigenen Bescheid. Konkret übersehene Einschränkungen und neue Befunde beilegen statt nur allgemeiner Unzufriedenheit.", source: pass),
            .init("use", "checkmark.shield", "Використовуйте документ правильно", "Pass richtig nutzen", "Behindertenpass підтверджує інвалідність, але сам по собі не є Parkausweis і не дає будь-якої пільги без перевірки її умов. Для конкретної знижки чи послуги запитайте організатора, який саме запис або інший доказ потрібний.", "Behindertenpass bestätigt die Behinderung, ist aber nicht selbst Parkausweis und gewährt nicht jede Vergünstigung ohne deren Voraussetzungen. Beim jeweiligen Anbieter nach nötigem Eintrag oder Nachweis fragen.", source: pass),
            .init("parking", "parkingsign.circle", "Паркування", "Parkausweis", "Parkausweis за §29b StVO видає Sozialministeriumservice без плати за наявності Behindertenpass із відповідним записом про неможливість користуватися транспортом або сліпоту. Подайте окрему заяву; не користуйтеся місцем для осіб з інвалідністю лише на підставі іноземного посвідчення без перевірки правил.", "Den kostenlosen Parkausweis nach §29b StVO stellt das Sozialministeriumservice bei Behindertenpass mit einschlägigem Eintrag zur Unzumutbarkeit öffentlicher Verkehrsmittel oder Blindheit aus. Separat beantragen; fremden Ausweis nicht ohne Prüfung der Regeln als Parkberechtigung annehmen.", source: parking),
        ], sources: [pass, entries, parking]
    )

    private static let services = DirectoryGuide(
        cardSummary: .init(ukrainian: "Доступ до послуг, допомога на роботі та скарги", german: "Zugang zu Diensten, Arbeitsassistenz und Beschwerden"),
        introduction: .init(ukrainian: "Для прийому в установі чи роботи заздалегідь уточніть доступний спосіб участі. Маршрути й допомога в поїздах докладно описані в розділі «Транспорт».", german: "Für Behörden und Arbeit einen zugänglichen Weg rechtzeitig klären. Reisewege und Bahnhilfe sind im Bereich Mobilität beschrieben."),
        sections: [
            .init("prepare", "building.2", "Попросіть доступний спосіб звернення", "Zugänglichen Zugang verlangen", "Перед прийомом повідомте установу, що саме потрібно: доступний вхід, формат документа, жестовий переклад, супровід або можливість подати заяву іншим способом. Попросіть письмове підтвердження домовленості. Якщо бар’єр залишився, запишіть конкретну послугу, дату й відповідь установи для подальшого звернення.", "Vor einem Termin konkret mitteilen, was benötigt wird: stufenloser Zugang, zugängliches Dokument, Gebärdensprachdolmetschung, Begleitung oder alternativer Antragsweg. Vereinbarung schriftlich bestätigen lassen. Bleibt eine Barriere, Dienst, Datum und Antwort für die weitere Beschwerde dokumentieren.", source: equality),
            .init("work", "briefcase", "Підтримка на роботі чи навчанні", "Unterstützung bei Arbeit und Ausbildung", "Якщо засіб потрібен для виконання роботи, професійного навчання або першого навчання у виші, окремо запитайте Sozialministeriumservice про Persönliche Assistenz am Arbeitsplatz. Це інша програма, ніж медичний засіб від страховика: служба перевіряє потребу й відповідність умовам, а регіональна Assistenz-Servicestelle організовує допомогу.", "Wird Unterstützung bei Arbeit, Berufsausbildung oder Erststudium gebraucht, Sozialministeriumservice nach Persönlicher Assistenz am Arbeitsplatz fragen. Das ist ein anderer Weg als ein medizinisches Hilfsmittel der Kasse: Anspruchsvoraussetzungen werden geprüft, die regionale Assistenz-Servicestelle vermittelt Hilfe.", source: workAssistance),
            .init("access", "building.2", "Послуга недоступна?", "Dienst nicht zugänglich?", "Перед відвідуванням запитайте про безбар’єрний вхід, жестовий переклад чи доступний формат документа. Якщо послугу відмовляються надати або перешкоду не усувають, зафіксуйте дату, місце, наслідок і відповідь організації. Для дискримінації через інвалідність можна безплатно й без адвоката подати заяву на Schlichtung до земельного Sozialministeriumservice; Behindertenpass для цього не є обов’язковим.", "Vor Besuch stufenlosen Zugang, Gebärdensprachdolmetschung oder zugängliches Format klären. Bei verweigerter Leistung Datum, Ort, Folgen und Antwort der Stelle dokumentieren. Bei Benachteiligung wegen Behinderung kann bei der Landesstelle des Sozialministeriumservice kostenfrei und ohne Anwalt Schlichtung beantragt werden; ein Behindertenpass ist dafür nicht erforderlich.", source: equality)
        ], sources: [equality, workAssistance]
    )

    private static let devices = DirectoryGuide(
        cardSummary: .init(ukrainian: "Кому подати заявку на допоміжний засіб і коли не купувати завчасно", german: "Hilfsmittel finanzieren und vor Kauf klären"),
        introduction: .init(ukrainian: "Оплата візка, слухового, комунікаційного чи побутового засобу залежить від медичної потреби, страхування та програми фінансування.", german: "Finanzierung von Rollstuhl, Hör-, Kommunikations- oder Alltagshilfe hängt von Bedarf, Versicherung und Förderweg ab."),
        sections: [
            .init("medical", "cross.case", "Опис потреби", "Bedarf dokumentieren", "Попросіть лікаря або терапевта описати, який засіб потрібний, для чого й на який строк. Зберіть медичні висновки та кошторис. Спершу зверніться до свого страхування щодо рецепта, погодження, власної доплати й постачальника.", "Ärztin oder Therapeut soll Bedarf, Zweck und Dauer dokumentieren. Befunde und Kostenvoranschlag sammeln. Zuerst bei Krankenversicherung Rezept, Bewilligung, Selbstbehalt und Vertragspartner klären.", source: fund),
            .init("fund", "eurosign.circle", "Додаткове фінансування", "Weitere Förderung", "Якщо страхування не покриває витрати, перевірте земельну допомогу та Unterstützungsfonds Sozialministeriumservice. Фонд може підтримати комунікаційні засоби, адаптацію житла й мобільність у соціальній скруті, але немає автоматичного права на виплату. Заяву зазвичай подають до реалізації витрат.", "Falls Versicherung nicht zahlt, Landesförderung und Unterstützungsfonds des Sozialministeriumservice prüfen. Dieser kann bei sozialer Not Kommunikationshilfen, Wohnungsanpassung und Mobilität unterstützen, ohne automatischen Rechtsanspruch. Antrag grundsätzlich vor Durchführung stellen.", source: fund),
            .init("order", "checklist", "Послідовність дій", "Reihenfolge", "1. Медичний висновок. 2. Письмовий кошторис. 3. Запит до страхування та землі. 4. За потреби заявка до фонду. 5. Лише після з’ясування оплати замовлення. Візьміть письмове рішення й умови ремонту/повернення.", "1. Befund. 2. Schriftlicher Kostenvoranschlag. 3. Anfrage bei Versicherung und Land. 4. Gegebenenfalls Fondsantrag. 5. Erst nach Klärung der Finanzierung bestellen. Schriftliche Entscheidung und Reparatur-/Rückgaberegeln sichern.", source: fund)
        ], sources: [pass, fund]
    )
}
