import Foundation

extension CitizenshipGuides {
    static let overview = DirectoryGuide(
        cardSummary: .init(ukrainian: "Оберіть підставу, перевірте роки та загальні умови", german: "Weg, Aufenthaltsjahre und allgemeine Bedingungen prüfen"),
        introduction: .init(ukrainian: "Австрійське громадянство не виникає автоматично після певної кількості років або шлюбу. Потрібна заява, відповідний шлях і виконання всіх загальних умов.", german: "Die österreichische Staatsbürgerschaft entsteht weder nach einer bestimmten Zahl von Jahren noch durch Ehe automatisch. Antrag, passender Weg und sämtliche allgemeinen Voraussetzungen sind nötig."),
        sections: [
            .init("choose", "point.topleft.down.curvedto.point.bottomright.up", "Знайдіть свій шлях", "Den eigenen Weg finden", "Основні шляхи: 6 років законного безперервного проживання плюс особлива підстава (наприклад B2 або шлюб з австрійцем); або 10 років законного проживання, з яких 5 років статусу поселення. Для визнаних біженців існує окрема десятирічна підстава. Дитина австрійського батька чи матері може вже мати громадянство за походженням.", "Hauptwege: 6 Jahre rechtmäßiger ununterbrochener Aufenthalt plus besonderer Grund (etwa B2 oder Ehe mit Österreicher*in); oder 10 Jahre rechtmäßiger Aufenthalt, davon 5 Jahre Niederlassung. Für Asylberechtigte gibt es einen eigenen Zehnjahresweg. Ein Kind eines österreichischen Elternteils kann bereits durch Abstammung Staatsbürger sein.", source: six),
            .init("timeline", "calendar", "Роки самі по собі не достатні", "Jahre allein reichen nicht", "Перевіряють дати й підстави перебування, перерви та поїздки, доходи, німецьку, тест, правопорушення й попереднє громадянство. Місцева земельна влада оцінює особисту справу; у Відні це MA 35.", "Geprüft werden Aufenthaltszeiten und -titel, Unterbrechungen und Reisen, Einkommen, Deutsch, Test, Rechtsverstöße und bisherige Staatsangehörigkeit. Die zuständige Landesbehörde prüft den Einzelfall; in Wien ist das MA 35.", source: conditions),
            .init("status", "person.text.rectangle", "Назва картки має значення", "Der Titel ist entscheidend", "Meldezettel доводить адресу, але не право перебування. Посвідка студента, Ausweis für Vertriebene, RWR-Karte, Familienangehöriger та Daueraufenthalt EU мають різне значення для строку поселення. Зберіть усі старі картки й рішення без прогалин.", "Ein Meldezettel belegt eine Adresse, kein Aufenthaltsrecht. Studierendenbewilligung, Vertriebenenausweis, RWR-Karte, Familienangehöriger und Daueraufenthalt EU wirken unterschiedlich auf Niederlassungszeiten. Sammeln Sie alle früheren Karten und Bescheide lückenlos.", source: ten)
        ], sources: [six, ten, conditions, vienna]
    )

    static let sixYears = DirectoryGuide(
        cardSummary: .init(ukrainian: "B2, шлюб, народження в Австрії або стала інтеграція", german: "B2, Ehe, Geburt in Österreich oder nachhaltige Integration"),
        introduction: .init(ukrainian: "Через 6 років можливе дострокове надання, якщо весь період проживання був законним і безперервним та виконана хоча б одна спеціальна умова.", german: "Nach 6 Jahren ist eine vorzeitige Verleihung möglich, wenn der Aufenthalt durchgehend rechtmäßig und ununterbrochen war und mindestens ein besonderer Grund vorliegt."),
        sections: [
            .init("grounds", "6.circle", "Підстави для шести років", "Gründe für sechs Jahre", "Підстави: 5 років чинного шлюбу/партнерства й спільного господарства з громадянином Австрії; підтверджений німецький B2; народження в Австрії; громадянство держави ЄЕЗ. Достатньо однієї відповідної підстави, але кожна вимагає ще шести років законного безперервного перебування та загальних умов.", "Gründe sind 5 Jahre aufrechte Ehe/Partnerschaft und gemeinsamer Haushalt mit Österreicher*in, nachgewiesenes B2-Deutsch, Geburt in Österreich oder EWR-Staatsangehörigkeit. Ein passender Grund genügt, doch zusätzlich sind 6 Jahre rechtmäßiger ununterbrochener Aufenthalt und die allgemeinen Voraussetzungen erforderlich.", source: six),
            .init("integration", "hands.sparkles", "Інтеграція без B2", "Integration ohne B2", "Інша підстава — стала особиста й професійна інтеграція: зокрема щонайменше 3 роки волонтерства в суспільно корисній організації, роботи в освіті, соціальній сфері або медицині з постійним доходом не нижче межі geringfügig, чи функції в об’єднанні інтересів. Підготуйте підтвердження строку, ролі й користі діяльності. Звичайної роботи самої по собі недостатньо.", "Ein weiterer Grund ist nachhaltige persönliche und berufliche Integration: insbesondere mindestens 3 Jahre gemeinnützige Freiwilligenarbeit, Arbeit in Bildung, Sozialem oder Gesundheit mit durchgehend mindestens der monatlichen Geringfügigkeitsgrenze entsprechendem Einkommen oder eine Funktion in einer Interessenvertretung. Belegen Sie Dauer, Rolle und Nutzen der Tätigkeit. Eine beliebige Beschäftigung allein reicht nicht.", source: six),
            .init("common", "checkmark.shield", "Загальні умови залишаються", "Allgemeine Bedingungen bleiben", "І за шестирічним шляхом перевіряють забезпечення доходу, відсутність суттєвих порушень, німецьку та знання країни за відповідним порядком, а також питання попереднього громадянства. B2 як підстава раннього звернення відрізняється від звичайного мінімуму B1.", "Auch beim Sechsjahresweg werden gesicherter Lebensunterhalt, relevante Verstöße, Deutsch- und Staatskenntnisse nach den einschlägigen Regeln sowie die bisherige Staatsangehörigkeit geprüft. B2 als Grund für die frühe Antragstellung unterscheidet sich vom regulären Mindestniveau B1.", source: conditions)
        ], sources: [six, conditions, language]
    )

    static let tenYears = DirectoryGuide(
        cardSummary: .init(ukrainian: "10 років законно, із них 5 років у статусі поселення", german: "10 Jahre rechtmäßig, davon 5 Jahre niedergelassen"),
        introduction: .init(ukrainian: "Звичайний шлях: щонайменше 10 років законного безперервного проживання в Австрії, з яких щонайменше 5 років — у статусі Niederlassung.", german: "Regelweg: mindestens 10 Jahre rechtmäßiger ununterbrochener Aufenthalt in Österreich, davon mindestens 5 Jahre Niederlassung."),
        sections: [
            .init("count", "calendar.badge.clock", "Що зараховують", "Was zählt", "Законний час перебування і час поселення — різні лічильники. Aufenthaltsbewilligung – Student може входити до законного часу, але сама не є Niederlassung. RWR-Karte, Familienangehöriger і Daueraufenthalt EU — приклади статусів поселення. Перехід на відповідний титул потрібен достатньо рано, щоб набрати 5 років.", "Rechtmäßiger Aufenthalt und Niederlassung sind zwei verschiedene Zählungen. Aufenthaltsbewilligung – Student kann zur rechtmäßigen Zeit zählen, ist selbst aber keine Niederlassung. RWR-Karte, Familienangehöriger und Daueraufenthalt EU sind Beispiele für Niederlassung. Der Wechsel muss früh genug erfolgen, um 5 Jahre zu erreichen.", source: ten),
            .init("asylum", "person.crop.rectangle.badge.checkmark", "Для визнаних біженців", "Für Asylberechtigte", "Окрема десятирічна підстава передбачає 10 років законного безперервного перебування як визнана особа з правом притулку (Asylberechtigte*r). Субсидіарний захист і тимчасовий захист українців — інші статуси; не застосовуйте до них цю підставу автоматично.", "Ein eigener Weg sieht 10 Jahre rechtmäßigen ununterbrochenen Aufenthalt als Asylberechtigte*r vor. Subsidiärer Schutz und ukrainischer vorübergehender Schutz sind andere Status; diese Sonderregel gilt für sie nicht automatisch.", source: ten),
            .init("other", "clock", "Якщо десятирічна схема не підходить", "Falls der Zehnjahresweg nicht passt", "Офіційний портал також описує окремі шляхи після 15 років із доказом сталої інтеграції або 30 років безперервного основного місця проживання. Це не звільняє від загальних вимог. Перевірте, чи не доступний вам шестирічний шлях.", "Das amtliche Portal nennt außerdem Wege nach 15 Jahren mit nachhaltiger Integration oder 30 Jahren ununterbrochenem Hauptwohnsitz. Allgemeine Bedingungen bleiben. Prüfen Sie auch den Sechsjahresweg.", source: DirectorySource(name: "Österreich.gv.at · Weitere Wege", url: "https://www.oesterreich.gv.at/de/themen/menschen_aus_anderen_staaten/staatsbuergerschaft"))
        ], sources: [ten, six, vienna]
    )
}
