import Foundation

extension CitizenshipGuides {
    static let languageAndTest = DirectoryGuide(
        cardSummary: .init(ukrainian: "Зазвичай B1; B2 — окрема підстава для 6 років", german: "Regelmäßig B1; B2 ist ein eigener Grund für 6 Jahre"),
        introduction: .init(ukrainian: "Мовна вимога для звичайного надання і B2 як підстава дострокового надання — різні питання. Вид сертифіката теж важливий.", german: "Das reguläre Deutschniveau und B2 als Grund für die vorzeitige Verleihung sind verschiedene Fragen. Auch die Art des Nachweises ist wichtig."),
        sections: [
            .init("b1", "text.book.closed", "Звичайний мінімум", "Reguläres Mindestniveau", "Зазвичай потрібен B1 з поглибленими знаннями цінностей (модуль 2 інтеграційної угоди) або інший офіційно прийнятний доказ. Мовні звільнення залежать від віку, навчання або підтвердженого стану здоров’я. Сертифікат A1 для деяких видів посвідки не достатній для громадянства.", "Regelmäßig ist B1 mit vertieften Wertekenntnissen (Modul 2 der Integrationsvereinbarung) oder ein anderer amtlich anerkannter Nachweis nötig. Ausnahmen hängen unter anderem von Alter, Schulbildung oder bescheinigter Gesundheit ab. A1 für manche Aufenthaltstitel reicht für die Einbürgerung nicht.", source: language),
            .init("b2", "star", "B2 для шести років", "B2 für sechs Jahre", "Підтверджений B2 або вищий рівень — самостійна спеціальна підстава шестирічного шляху. У Відні для цього приймають визначені сертифікати ÖIF, ÖSD, Goethe, telc та інші перелічені докази. B2 за цим шляхом може замінити доказ поглиблених цінностей у мовному модулі; окремий тест з громадянства перевірте за своїм випадком.", "Nachgewiesenes B2 oder höher ist ein eigener Grund für den Sechsjahresweg. Wien nennt dafür bestimmte Nachweise von ÖIF, ÖSD, Goethe, telc und weitere Zeugnisse. B2 kann dabei den vertieften Werte-Nachweis des Sprachmoduls ersetzen; prüfen Sie den gesonderten Staatsbürgerschaftstest für Ihren Fall.", source: language),
            .init("test", "checklist", "Тест з громадянства", "Staatsbürgerschaftstest", "Зазвичай перевіряють демократичний лад, історію Австрії та відповідної землі. Для окремих дітей та інших визначених випадків є звільнення. Відень публікує навчальні матеріали й онлайн-тренування; в іншій землі шукайте її офіційні матеріали.", "Regelmäßig werden demokratische Ordnung, Geschichte Österreichs und des Bundeslandes geprüft. Für bestimmte Kinder und andere geregelte Fälle gibt es Ausnahmen. Wien bietet Lernunterlagen und Online-Übung; für andere Länder nutzen Sie deren amtliche Materialien.", source: test)
        ], sources: [language, integration, test, six]
    )

    static let livelihood = DirectoryGuide(
        cardSummary: .init(ukrainian: "36 місяців доходу за останні 6 років та інші перевірки", german: "36 Einkommensmonate in 6 Jahren und weitere Prüfungen"),
        introduction: .init(ukrainian: "Навіть за достатнього строку перебування орган перевіряє забезпечення життя, правопорядок та інші загальні умови.", german: "Auch bei erfüllter Aufenthaltsdauer prüft die Behörde Lebensunterhalt, Rechtsverstöße und weitere allgemeine Voraussetzungen."),
        sections: [
            .init("income", "eurosign.circle", "Дохід і витрати", "Einkommen und Ausgaben", "Потрібен стабільний власний дохід від праці, законних аліментів/утримання чи страхових виплат у середньому за 36 місяців із останніх 6 років; останні 6 із них мають безпосередньо передувати заяві. Оцінюють також оренду, кредити й утриманців. Конкретну суму й можливі винятки визначає орган за вашою ситуацією; довільна «зарплатна межа» для всіх неправдива.", "Erforderlich sind feste regelmäßige Einkünfte aus Arbeit, gesetzlichen Unterhaltsansprüchen oder Versicherungsleistungen im Durchschnitt von 36 Monaten der letzten 6 Jahre; die letzten 6 Monate müssen unmittelbar vor dem Antrag liegen. Miete, Kredite und Unterhaltspflichten werden mitgeprüft. Den konkreten Bedarf und Ausnahmen bestimmt die Behörde im Einzelfall; eine pauschale Gehaltsgrenze für alle wäre falsch.", source: conditions),
            .init("conduct", "checkmark.shield", "Правопорушення й безпека", "Rechtsverstöße und Sicherheit", "Перевіряють судимості, поточні кримінальні провадження в Австрії та за кордоном, часті або серйозні адміністративні порушення, заборони перебування, рішення про повернення та загрозу громадському порядку. Не приховуйте старі рішення: оцінку робить компетентний орган.", "Geprüft werden Verurteilungen, laufende Strafverfahren im In- und Ausland, häufige oder schwere Verwaltungsübertretungen, Aufenthaltsverbote, Rückkehrentscheidungen und Gefahren für die öffentliche Ordnung. Verschweigen Sie ältere Bescheide nicht; die zuständige Behörde bewertet sie.", source: conditions),
            .init("benefits", "questionmark.circle", "Соціальна допомога", "Sozialleistungen", "Не робіть висновок лише з факту отримання Grundversorgung чи Familienbeihilfe. Вирішальним є розрахунок «gesicherter Lebensunterhalt» за законом, видом виплати, доходами та витратами за потрібний період. Перед заявою попросіть орган перевірити вашу фінансову історію.", "Schließen Sie aus Grundversorgung oder Familienbeihilfe allein nichts Endgültiges. Entscheidend ist die gesetzliche Berechnung des gesicherten Lebensunterhalts nach Art der Leistung, Einnahmen und Ausgaben im maßgeblichen Zeitraum. Lassen Sie Ihre Finanzhistorie vor dem Antrag prüfen.", source: conditions)
        ], sources: [conditions, documents, vienna]
    )

    static let absences = DirectoryGuide(
        cardSummary: .init(ukrainian: "Межа перебування за кордоном і безперервний статус", german: "Auslandszeiten und lückenloser Status"),
        introduction: .init(ukrainian: "Для шестирічного й десятирічного шляху проживання має бути безперервним. Зберігайте історію поїздок, а не лише реєстрацію адреси.", german: "Für den Sechs- und Zehnjahresweg muss der Aufenthalt ununterbrochen sein. Bewahren Sie Reisenachweise auf, nicht nur Meldezettel."),
        sections: [
            .init("twenty", "airplane", "Правило 20 %", "20-Prozent-Regel", "За офіційним поясненням загальний час за межами Австрії не може перевищувати 20 % відповідного строку проживання; рахують до дати рішення. Для 6 років це приблизно 1 рік і 2 місяці, для 10 — 2 роки. Це сумарна межа, а не дозвіл на будь-яку окрему поїздку без впливу на ваш статус.", "Laut amtlicher Erklärung darf die gesamte Auslandszeit höchstens 20 % des maßgeblichen Aufenthaltszeitraums betragen, gerechnet bis zum Bescheid. Bei 6 Jahren sind das ungefähr 1 Jahr und 2 Monate, bei 10 Jahren 2 Jahre. Das ist eine Gesamtschranke, keine Erlaubnis für beliebige Einzelreisen unabhängig vom Aufenthaltstitel.", source: vienna),
            .init("proof", "doc.text.magnifyingglass", "Чим підтвердити", "Nachweise", "Зберігайте всі паспорти, штампи, квитки, дати виїзду та повернення, картки й рішення про перебування, Meldebestätigungen, страхові й трудові записи. Якщо були перерви права перебування або довгі поїздки, попросіть орган перевірити розрахунок до витрат на документи.", "Bewahren Sie Pässe, Stempel, Tickets, Reise- und Rückkehrdaten, Aufenthaltstitel und Bescheide, Meldebestätigungen sowie Versicherungs- und Arbeitsnachweise auf. Bei Rechtslücken oder langen Reisen lassen Sie die Berechnung vor kostspieliger Dokumentenbeschaffung prüfen.", source: documents)
        ], sources: [six, ten, vienna, documents]
    )
}
