import Foundation

extension CitizenshipGuides {
    static let dualCitizenship = DirectoryGuide(
        cardSummary: .init(ukrainian: "Війна не скасовує вимогу Австрії; винятки індивідуальні", german: "Der Krieg hebt Österreichs Grundregel nicht auf; Ausnahmen sind individuell"),
        introduction: .init(ukrainian: "Український закон про множинне громадянство й австрійська вимога виходу з попереднього громадянства — два різні правопорядки. Перевіряти потрібно обидва.", german: "Das ukrainische Recht zur Mehrstaatigkeit und Österreichs Voraussetzung des Ausscheidens aus der bisherigen Staatsangehörigkeit sind zwei verschiedene Rechtsordnungen. Beide müssen geprüft werden."),
        sections: [
            .init("austria", "checkmark.shield", "Австрійське загальне правило", "Österreichische Grundregel", "При натуралізації Австрія зазвичай вимагає виходу з попереднього громадянства. Часто спершу видають Zusicherungsbescheid — обіцянку надати громадянство за умови підтвердження виходу протягом 2 років, якщо це можливо й розумно вимагати. Не відмовляйтеся від українського громадянства до офіційної вказівки компетентного органу.", "Bei Einbürgerung verlangt Österreich grundsätzlich das Ausscheiden aus der bisherigen Staatsangehörigkeit. Häufig folgt zunächst ein Zusicherungsbescheid mit bis zu 2 Jahren zum Nachweis, soweit dies möglich und zumutbar ist. Verlassen Sie die ukrainische Staatsangehörigkeit nicht vor Anweisung der zuständigen Behörde.", source: dual),
            .init("war", "exclamationmark.triangle", "Що змінює війна", "Was der Krieg ändert", "Війна сама по собі не створює автоматичний австрійський виняток для всіх українців. Якщо вихід фактично неможливий або нерозумно вимагати його у вашому випадку, подайте докази та письмове пояснення до земельного органу й попросіть рішення саме щодо вас. Не покладайтеся на усні поради чи припущення про загальне звільнення.", "Der Krieg bewirkt keine automatische österreichische Ausnahme für alle Ukrainer. Ist das Ausscheiden in Ihrem konkreten Fall unmöglich oder unzumutbar, legen Sie Nachweise und eine schriftliche Begründung bei der Landesbehörde vor und verlangen Sie eine Einzelfallentscheidung. Verlassen Sie sich nicht auf mündliche Zusagen oder eine pauschale Ausnahme.", source: dual),
            .init("ukraine", "globe.europe.africa", "Українські правила з 2026 року", "Ukrainische Regeln seit 2026", "Україна з 16.01.2026 визнає визначені випадки множинного громадянства. Це не означає, що Австрія автоматично дозволяє зберегти українське при натуралізації. Перелік держав і умови українського закону змінні; ДМС називає окремі держави для спрощеного набуття, тож не вважайте Австрію включеною без перевірки чинного переліку.", "Die Ukraine erkennt seit 16.01.2026 bestimmte Fälle von Mehrstaatigkeit an. Das verpflichtet Österreich nicht, bei Einbürgerung die ukrainische Staatsangehörigkeit zu belassen. Staatenliste und Bedingungen des ukrainischen Rechts können sich ändern; die DMS nennt bestimmte Staaten für vereinfachten Erwerb. Nehmen Sie Österreich nicht ohne Prüfung der aktuellen Liste als erfasst an.", source: ukrainianLaw),
            .init("exit", "doc.text", "Як оформлюють вихід з України", "Ausscheiden aus der Ukraine", "МЗС описує окреме клопотання, документи про постійне проживання за кордоном та наявне або гарантоване інше громадянство. Австрійський Meldezettel не є автоматично українським оформленням ПМП. Громадянство України припиняється лише з відповідним указом Президента; заява сама по собі цього не робить. Перевірте поточний комплект у консульстві після отримання австрійського рішення.", "Das ukrainische MFA beschreibt einen gesonderten Antrag, Nachweise über dauerhaftes Auslandsleben und bestehende oder zugesicherte andere Staatsangehörigkeit. Ein österreichischer Meldezettel ist keine ukrainische Auslands-Permanentregistrierung. Die ukrainische Staatsangehörigkeit endet erst mit dem entsprechenden Präsidialerlass, nicht mit dem Antrag. Prüfen Sie aktuelle Unterlagen beim Konsulat nach dem österreichischen Bescheid.", source: ukrainianExit)
        ], sources: [dual, ukrainianLaw, ukrainianExit, conditions]
    )

    static let childrenGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Походження, спільна заява з батьками й власний шлях", german: "Abstammung, Miteinbürgerung und eigener Weg"),
        introduction: .init(ukrainian: "Місце народження дитини та громадянство її батьків — різні речі. Народження в Австрії саме по собі зазвичай не дає австрійського паспорта.", german: "Geburtsort und Staatsangehörigkeit der Eltern sind verschieden. Geburt in Österreich allein verleiht gewöhnlich keinen österreichischen Pass."),
        sections: [
            .init("birth", "figure.child", "Австрійський батько або мати", "Österreichischer Elternteil", "Якщо при народженні хоча б один з батьків мав австрійське громадянство, дитина зазвичай набуває його за походженням; окремі правила залежать від встановлення батьківства та сімейної ситуації. Якщо обидва батьки українці, австрійське свідоцтво про народження не робить дитину австрійцем.", "Ist bei Geburt mindestens ein Elternteil österreichischer Staatsbürger, erwirbt das Kind die Staatsbürgerschaft grundsätzlich durch Abstammung; Einzelheiten hängen von Elternschaft und Familienlage ab. Sind beide Eltern Ukrainer, macht eine österreichische Geburtsurkunde das Kind nicht zum Österreicher.", source: children),
            .init("extend", "person.2", "Разом із батьком або матір’ю", "Mit einem Elternteil", "Коли батькові чи матері надають австрійське громадянство, його можна поширити на неповнолітню дитину за встановлених умов. Для дитини при такому поширенні немає окремого мінімального строку проживання. Потрібні опіка, згода інших законних представників у відповідних випадках і власні документи дитини.", "Wird ein Elternteil eingebürgert, kann die Verleihung unter Voraussetzungen auf ein minderjähriges Kind erstreckt werden. Dafür gibt es keine eigene Mindestaufenthaltsdauer des Kindes. Obsorge, gegebenenfalls Zustimmung weiterer Sorgeberechtigter und Unterlagen des Kindes sind nötig.", source: children),
            .init("own", "person.crop.rectangle", "Окрема заява лише для дитини", "Eigener Antrag nur für das Kind", "Якщо батьки не подають на громадянство, для неповнолітньої дитини можлива власна заява через особу з правом опіки. Тоді дитина сама має виконати умови обраного шляху, зокрема потрібний строк перебування; відсутність мінімального строку стосується саме поширення громадянства батька або матері. Якщо опіку мають двоє, потрібна згода іншого представника.", "Wenn die Eltern keinen Antrag stellen, kann für ein minderjähriges Kind eine eigene Verleihung über eine obsorgeberechtigte Person beantragt werden. Dann muss das Kind selbst die Voraussetzungen des gewählten Weges einschließlich Aufenthaltsdauer erfüllen. Der Weg ohne eigene Mindestaufenthaltsdauer gilt nur bei Erstreckung der Verleihung eines Elternteils. Bei gemeinsamer Obsorge ist die Zustimmung der anderen Person nötig.", source: children),
            .init("adoption", "heart.text.square", "Усиновлення австрійцем", "Adoption durch Österreicher*in", "Усиновлення саме по собі не змінює громадянство дитини. Якщо дитину усиновив громадянин Австрії, існує окремий шлях надання; для неповнолітньої дитини при закордонному усиновленні офіційний портал описує правову вимогу на отримання за встановлених умов. Перевірте вік, рішення про усиновлення, проживання та опіку перед заявою.", "Die Adoption allein ändert die Staatsangehörigkeit des Kindes nicht. Bei Adoption durch Österreicher*in gibt es einen eigenen Verleihungsweg; bei Auslandsadoption eines minderjährigen Kindes beschreibt das amtliche Portal unter Voraussetzungen einen Rechtsanspruch. Prüfen Sie Alter, Adoptionsentscheidung, Aufenthalt und Obsorge vor dem Antrag.", source: children),
            .init("language", "text.book.closed", "Мова та тест для дітей", "Deutsch und Test bei Kindern", "Для дітей до 14 років мовний доказ і тест із громадянства зазвичай не потрібні; для старших діють окремі шкільні та мовні докази. Попросіть орган перевірити вік на момент рішення й конкретний вид заяви.", "Unter 14 Jahren sind Deutschnachweis und Staatsbürgerschaftstest grundsätzlich nicht nötig; für ältere Kinder gelten besondere Schul- und Sprachnachweise. Lassen Sie Alter zum Entscheidungszeitpunkt und Antragsart prüfen.", source: language)
        ], sources: [children, language, test]
    )

    static let applicationDocuments = DirectoryGuide(
        cardSummary: .init(ukrainian: "Особа, історія перебування, дохід, мова, сім’я", german: "Identität, Aufenthalt, Einkommen, Sprache, Familie"),
        introduction: .init(ukrainian: "Точний список залежить від сім’ї, статусу та федеральної землі. Почніть зі збору незмінних документів і попросіть перелік органу до витрат на довідки та переклади.", german: "Die genaue Liste hängt von Familie, Titel und Bundesland ab. Sammeln Sie dauerhafte Urkunden zuerst und holen Sie die Behördenliste vor teuren Bescheinigungen und Übersetzungen ein."),
        sections: [
            .init("identity", "person.text.rectangle", "Особа й сім’я", "Identität und Familie", "Паспорт, свідоцтво про народження, свідоцтва про шлюб/розлучення або зміну імені, документи дітей та партнера. Для іноземних свідоцтв перевірте апостиль і присяжний переклад; різне написання ПІБ потрібно документально пов’язати.", "Pass, Geburtsurkunde, Ehe-/Scheidungs- oder Namensurkunden sowie Unterlagen von Kindern und Partnern. Für ausländische Urkunden Apostille und beglaubigte Übersetzung prüfen; abweichende Namensschreibweisen belegen.", source: documents),
            .init("residence", "calendar", "Перебування, мова, інтеграція", "Aufenthalt, Sprache, Integration", "Зберіть усі старі посвідки й рішення, адресні та страхові підтвердження, історію поїздок, мовний сертифікат або інший дозволений доказ, а також документи для підстави через 6 років: B2, шлюб або докази суспільно корисної діяльності.", "Sammeln Sie alte Titel und Bescheide, Melde- und Versicherungsnachweise, Reisenachweise, Sprachzertifikat oder anerkannte Alternative sowie Belege für den Sechsjahresgrund: B2, Ehe oder gemeinnützige Tätigkeit.", source: documents),
            .init("income", "eurosign.circle", "Фінанси та нові довідки", "Finanzen und aktuelle Nachweise", "Підготуйте підтвердження доходів, оренди, аліментів, кредитів і страхування за період, який запитає орган. Довідки з коротким строком актуальності та фото замовляйте ближче до подання. Відень публікує окремий актуальний список; інші землі можуть вимагати свій комплект.", "Bereiten Sie Einkommens-, Miet-, Unterhalts-, Kredit- und Versicherungsnachweise für den verlangten Zeitraum vor. Kurz gültige Bescheinigungen und Foto erst näher am Antrag besorgen. Wien veröffentlicht eine aktuelle Liste; andere Länder können eigene Unterlagen verlangen.", source: documents),
            .init("police", "checkmark.shield", "Довідки про несудимість з інших країн", "Strafregister aus anderen Staaten", "За віденським списком з 14 років потрібні довідки з держав громадянства, а також із країн, де ви протягом останніх 20 років або після 14-річчя перебували понад 3 місяці безперервно. Для Австрії та Німеччини їх не подають. Довідка з країни громадянства має бути не старшою за 12 місяців; для колишньої країни проживання є окремі правила. Спершу складіть хронологію країн, потім замовляйте довідки, апостилі та переклади.", "Nach der Wiener Liste brauchen Personen ab 14 Jahren Auszüge aus ihren Staatsangehörigkeitsstaaten sowie aus Staaten, in denen sie in den letzten 20 Jahren oder seit dem 14. Geburtstag länger als 3 Monate durchgehend waren. Aus Österreich und Deutschland müssen keine Auszüge vorgelegt werden. Auszüge aus Staatsangehörigkeitsstaaten dürfen höchstens 12 Monate alt sein; für frühere Aufenthaltsstaaten gelten Sonderregeln. Erstellen Sie zuerst die Länderliste und bestellen Sie dann Auszüge, Apostillen und Übersetzungen.", source: documents)
        ], sources: [documents, conditions, DocumentGuides.translators, DocumentGuides.ukrainianApostille]
    )

    static let application = DirectoryGuide(
        cardSummary: .init(ukrainian: "Заява в земельний орган, послідовність і конкретні збори", german: "Antrag im Bundesland, Reihenfolge und konkrete Gebühren"),
        introduction: .init(ukrainian: "Заяву приймає орган з питань громадянства федеральної землі основного місця проживання; у Відні — MA 35. Рішення приймають після перевірки індивідуальної справи.", german: "Zuständig ist die Staatsbürgerschaftsbehörde des Bundeslandes Ihres Hauptwohnsitzes; in Wien MA 35. Die Behörde entscheidet nach Prüfung des Einzelfalls."),
        sections: [
            .init("prepare", "list.bullet.clipboard", "Послідовність", "Reihenfolge", "1. Визначте підставу та порахуйте законні роки, роки поселення і виїзди.\n2. У Відні пройдіть офіційне онлайн-опитування й запишіться на первинну інформаційну зустріч; в іншій землі перевірте її порядок.\n3. Зберіть постійні свідоцтва, а потім довідки з обмеженим строком. Візьміть оригінали й копії.\n4. Запишіться на особисте подання; у Відні офіційний номер +43 1 4000-3535.\n5. Якщо видано Zusicherungsbescheid, далі виконуйте письмові вимоги щодо попереднього громадянства у встановлений строк.", "1. Bestimmen Sie den Weg und zählen Sie rechtmäßige Jahre, Niederlassungsjahre und Auslandszeiten.\n2. In Wien machen Sie die amtliche Online-Befragung und buchen eine Erstinformation; in anderen Ländern prüfen Sie deren Verfahren.\n3. Sammeln Sie dauerhaft gültige Urkunden zuerst, kurz gültige Nachweise später. Bringen Sie Originale und Kopien mit.\n4. Vereinbaren Sie die persönliche Antragstellung; in Wien unter +43 1 4000-3535.\n5. Bei Zusicherungsbescheid erfüllen Sie danach die schriftlichen Vorgaben zur bisherigen Staatsangehörigkeit fristgerecht.", source: documents),
            .init("cost", "eurosign.circle", "Витрати й момент оплати", "Kosten und Zahlungszeitpunkt", "Для однієї дорослої особи Відень указує 163 € за заяву, 60 € за можливий Zusicherungsbescheid, 1 236–1 678 € при наданні громадянства та щонайменше два протоколи по 6 €. Плата за заяву стягується і при відмові, але не при відкликанні до рішення. Оплату за надання громадянства вносять у день надання. Документи, переклади й апостилі оплачуються окремо; для дітей та інших земель звірте таблицю свого органу.", "Für eine erwachsene Person nennt Wien 163 € für den Antrag, gegebenenfalls 60 € für den Zusicherungsbescheid, 1.236–1.678 € bei Verleihung und mindestens zwei Niederschriften zu je 6 €. Die Antragsgebühr fällt auch bei Ablehnung an, nicht aber bei Rücknahme vor dem Bescheid. Die Verleihungsgebühr ist am Verleihungstag fällig. Urkunden, Übersetzungen und Apostillen kosten zusätzlich; für Kinder und andere Länder prüfen Sie die zuständige Tabelle.", source: costs),
            .init("contact", "building.columns", "Якщо живете не у Відні", "Außerhalb Wiens", "Зверніться до відділу громадянства своєї Landesregierung, а не до MA 35. Федеральний портал містить посилання на органи всіх земель. У листі або під час передбаченої консультації подайте точні дати статусів і поїздок та сформулюйте окремі питання про їх зарахування і можливість зберегти українське громадянство. Остаточну оцінку орган зробить у вашій справі.", "Wenden Sie sich an die Staatsbürgerschaftsabteilung Ihrer Landesregierung, nicht an MA 35. Das Bundesportal verlinkt alle Länderbehörden. Legen Sie schriftlich oder bei der vorgesehenen Erstinformation genaue Titel- und Reisedaten vor und fragen Sie getrennt nach Anrechnung und möglichem Beibehalt der ukrainischen Staatsangehörigkeit. Die endgültige Bewertung erfolgt im Verfahren.", source: six)
        ], sources: [vienna, six, ten, costs, documents, dual]
    )
}
