import Foundation

extension CitizenshipGuides {
    static let temporaryProtection = DirectoryGuide(
        cardSummary: .init(ukrainian: "«Синя картка» дає законне перебування, але не паспорт", german: "Vertriebenenausweis erlaubt Aufenthalt, verleiht aber keinen Pass"),
        introduction: .init(ukrainian: "Для українців немає автоматичного громадянства через війну або окремої загальної шестирічної пільги. Важливі особисті строки перебування та відповідна правова підстава.", german: "Für Ukrainer gibt es wegen des Krieges weder automatische Einbürgerung noch eine pauschale Sechsjahresausnahme. Individuelle Aufenthaltszeiten und der passende Rechtsweg sind entscheidend."),
        sections: [
            .init("lawful", "checkmark.shield", "Час тимчасового захисту", "Zeit mit vorübergehendem Schutz", "Ausweis für Vertriebene підтверджує право тимчасового перебування від в’їзду. Це законне перебування, але сама картка не дорівнює RWR-Karte чи постійному поселенню. Для шестирічного шляху перевіряйте безперервність і особливу підставу; для десятирічного — додатково 5 років поселення. Попросіть земельний орган письмово перевірити ваші конкретні періоди.", "Der Vertriebenenausweis dokumentiert das vorübergehende Aufenthaltsrecht ab Einreise. Das ist rechtmäßiger Aufenthalt, die Karte ist aber nicht selbst eine RWR-Karte oder ein Daueraufenthaltstitel. Für 6 Jahre braucht es die besondere Grundlage; für 10 Jahre zusätzlich 5 Jahre Niederlassung. Lassen Sie die konkreten Zeiten von der Landesbehörde schriftlich prüfen.", source: protection),
            .init("switch", "arrow.triangle.2.circlepath", "Перехід на RWR-Karte plus", "Wechsel zur RWR-Karte plus", "Для частини переселенців можливий перехід на RWR-Karte plus за умовами BMI, зокрема щодо повністю застрахованої роботи. BMI пояснює, що безпосередні попередні періоди права перебування переселенця після такого переходу можуть зараховуватися як Niederlassung для Daueraufenthalt EU. Це правило про Daueraufenthalt EU не слід автоматично переносити на громадянство: розрахунок для вашої заяви підтвердить орган громадянства.", "Für manche Vertriebene ist bei Erfüllung der BMI-Voraussetzungen, etwa vollversicherter Arbeit, der Wechsel zur RWR-Karte plus möglich. Laut BMI können unmittelbar davor liegende Vertriebenenzeiten danach für Daueraufenthalt EU als Niederlassung zählen. Diese Regel zum Daueraufenthalt EU lässt sich nicht ungeprüft auf die Staatsbürgerschaft übertragen; die Staatsbürgerschaftsbehörde bestätigt Ihre Berechnung.", source: transition),
            .init("now", "calendar", "Що зробити вже зараз", "Was jetzt sinnvoll ist", "Зберігайте всі Ausweis für Vertriebene, рішення, Meldebestätigungen, договори роботи й страховий стаж. Вивчайте німецьку до B1, а для окремої шестирічної підстави — до B2. Стежте за строком тимчасового захисту на сторінці BMI й не плутайте продовження захисту з наданням громадянства.", "Bewahren Sie Vertriebenenausweise, Bescheide, Meldebestätigungen, Arbeitsverträge und Versicherungszeiten auf. Lernen Sie Deutsch bis B1, für den besonderen Sechsjahresgrund bis B2. Prüfen Sie die Schutzdauer beim BMI; eine Schutzverlängerung ist keine Einbürgerung.", source: protection)
        ], sources: [protection, transition, six, ten]
    )

    static let studentRoute = DirectoryGuide(
        cardSummary: .init(ukrainian: "Студентські роки законні, але не роки поселення", german: "Studienjahre sind rechtmäßig, aber keine Niederlassungsjahre"),
        introduction: .init(ukrainian: "Австрійський Aufenthaltstitel «Aufenthaltsbewilligung – Student» дає законне проживання, проте не вважається статусом поселення для звичайного десятирічного шляху.", german: "Die österreichische Aufenthaltsbewilligung – Student erlaubt rechtmäßigen Aufenthalt, zählt aber beim regulären Zehnjahresweg nicht selbst als Niederlassung."),
        sections: [
            .init("six", "6.circle", "Чи можна через 6 років навчання?", "Sind 6 Studienjahre genug?", "Офіційна шестирічна норма вимагає 6 років законного безперервного проживання, але не формулює додаткових 5 років Niederlassung. Тож студентський період може бути важливим, якщо є окрема підстава, наприклад підтверджений B2, та виконано всі загальні умови, особливо доходи. Сам диплом або студентська картка не замінюють B2 чи іншої підстави.", "Der amtliche Sechsjahresweg verlangt 6 Jahre rechtmäßigen ununterbrochenen Aufenthalt, nennt aber keine zusätzlichen 5 Niederlassungsjahre. Studienzeiten können daher relevant sein, wenn ein besonderer Grund wie nachgewiesenes B2 und alle allgemeinen Bedingungen, besonders Einkommen, erfüllt sind. Abschluss oder Studierendenkarte ersetzen B2 bzw. einen anderen Grund nicht.", source: six),
            .init("ten", "10.circle", "Шлях через 10 років", "Weg nach 10 Jahren", "Для звичайного шляху потрібні 10 законних років і 5 років Niederlassung. Якщо ви весь час мали лише Aufenthaltsbewilligung – Student, другої умови немає. Після навчання перевірте перехід на RWR-Karte для випускників або інший статус поселення; стежте, щоб право перебування не перервалося.", "Für den Regelweg braucht es 10 rechtmäßige Jahre und 5 Niederlassungsjahre. Wer ausschließlich eine Aufenthaltsbewilligung – Student hatte, erfüllt die zweite Bedingung nicht. Prüfen Sie nach dem Studium eine RWR-Karte für Absolvent*innen oder einen anderen Niederlassungstitel und vermeiden Sie Aufenthaltslücken.", source: ten),
            .init("language", "text.book.closed", "Диплом і мовний доказ", "Abschluss und Sprachnachweis", "Навчання німецькою може за певних умов підтвердити мовний рівень за правилами інтеграційного модуля; англомовна програма автоматично не підтверджує німецьку. Для раннього шляху через B2 орган перевіряє прийнятний доказ окремо.", "Ein deutschsprachiges Studium kann unter bestimmten Bedingungen einen Sprachnachweis nach den Regeln des Integrationsmoduls liefern; ein englischsprachiges Studium belegt Deutsch nicht automatisch. Für den frühen B2-Weg prüft die Behörde einen passenden Nachweis gesondert.", source: language)
        ], sources: [student, graduates, six, ten, language]
    )

    static let austrianSpouse = DirectoryGuide(
        cardSummary: .init(ukrainian: "6 років проживання плюс 5 років шлюбу й спільного дому", german: "6 Jahre Aufenthalt plus 5 Jahre Ehe und gemeinsamer Haushalt"),
        introduction: .init(ukrainian: "Шлюб з австрійцем або австрійкою сам по собі не дає громадянства і не скорочує строк до п’яти років проживання.", german: "Die Ehe mit einem österreichischen Staatsbürger verleiht nicht automatisch die Staatsbürgerschaft und verkürzt die Aufenthaltsdauer nicht auf fünf Jahre."),
        sections: [
            .init("clock", "calendar", "Обидва строки одночасно", "Beide Fristen gleichzeitig", "Потрібні щонайменше 6 років законного безперервного проживання в Австрії, а також чинний шлюб або зареєстроване партнерство з громадянином Австрії й спільне господарство протягом щонайменше 5 років. Наприклад, шлюб після п’ятого року проживання не дає подати вже на шостому році.", "Nötig sind mindestens 6 Jahre rechtmäßiger ununterbrochener Aufenthalt in Österreich sowie eine aufrechte Ehe oder eingetragene Partnerschaft mit Österreicher*in und mindestens 5 Jahre gemeinsamer Haushalt. Wer erst im fünften Aufenthaltsjahr heiratet, kann daher nicht schon im sechsten Jahr über diesen Grund beantragen.", source: six),
            .init("proof", "house", "Що підтвердити", "Was nachzuweisen ist", "Підготуйте свідоцтво про шлюб, підтвердження австрійського громадянства партнера, спільної адреси й реального сімейного життя за потрібний період. Статус Familienangehöriger може бути статусом поселення, але сам факт його наявності не доводить 5 років шлюбу. Неодружене співжиття не є цією шлюбною підставою.", "Bereiten Sie Eheurkunde, Nachweis der österreichischen Staatsbürgerschaft des Partners sowie gemeinsamen Wohnsitzes und gelebter Gemeinschaft für die erforderliche Zeit vor. Familienangehöriger kann ein Niederlassungstitel sein, beweist aber nicht selbst 5 Ehejahre. Unverheiratetes Zusammenleben ist nicht dieser Ehegrund.", source: vienna),
            .init("other", "textformat.abc", "Мова й дохід", "Sprache und Einkommen", "Для цього шляху B2 не є окремою обов’язковою умовою: зазвичай потрібен загальний доказ німецької B1/модуля 2 або законний виняток, іспит та забезпечення доходу. Доходи й витрати подружжя перевіряють за правилами органу.", "B2 ist für diesen Eheweg kein eigener Pflichtgrund: regelmäßig braucht es den allgemeinen B1-/Modul-2-Nachweis oder eine gesetzliche Ausnahme, den Test und gesicherten Lebensunterhalt. Einkommen und Ausgaben der Ehepartner prüft die Behörde nach ihren Regeln.", source: language)
        ], sources: [six, conditions, language, documents]
    )

    static let otherStatuses = DirectoryGuide(
        cardSummary: .init(ukrainian: "RWR, Blue Card, сімейна посвідка, притулок", german: "RWR, Blaue Karte, Familientitel und Asyl"),
        introduction: .init(ukrainian: "Право працювати або проживати не дорівнює праву на громадянство. Для кожного статусу перевірте, чи це законний час, час поселення або окрема спеціальна підстава.", german: "Arbeits- oder Aufenthaltsrecht ist kein Anspruch auf Staatsbürgerschaft. Prüfen Sie für jeden Titel rechtmäßige Zeit, Niederlassungszeit und mögliche Sonderwege."),
        sections: [
            .init("settled", "briefcase", "Робота й родина", "Arbeit und Familie", "RWR-Karte, RWR-Karte plus, Familienangehöriger і Daueraufenthalt EU є прикладами титулів поселення для десятирічного шляху. Для Blue Card EU та інших конкретних карток попросіть орган підтвердити зарахування. Перехід між картками не має залишати прогалин у законному перебуванні.", "RWR-Karte, RWR-Karte plus, Familienangehöriger und Daueraufenthalt EU sind Beispiele für Niederlassungstitel beim Zehnjahresweg. Lassen Sie die Anrechnung einer Blauen Karte EU oder anderer konkreter Karten bestätigen. Titelwechsel dürfen keine Lücke im rechtmäßigen Aufenthalt erzeugen.", source: ten),
            .init("asylum", "person.crop.rectangle.badge.checkmark", "Притулок і субсидіарний захист", "Asyl und subsidiärer Schutz", "Для Asylberechtigte існує окрема десятирічна підстава. Субсидіарний захист не слід із ним ототожнювати: попросіть орган класифікувати кожен період. Для особи з українською «синьою карткою» тимчасовий захист — третій, окремий режим.", "Für Asylberechtigte gibt es einen eigenen Zehnjahresweg. Subsidiärer Schutz ist damit nicht gleichzusetzen; lassen Sie jeden Zeitraum einstufen. Der ukrainische Vertriebenenausweis beruht auf einem dritten, eigenen System.", source: ten),
            .init("six", "star", "Ранній шлях залишається можливістю", "Der frühe Weg bleibt möglich", "Незалежно від назви картки перевірте, чи маєте 6 років законного безперервного проживання та одну зі спеціальних підстав — наприклад B2 або п’ятирічний шлюб з австрійцем. Загальні умови діють для всіх.", "Unabhängig vom Kartennamen prüfen Sie 6 Jahre rechtmäßigen ununterbrochenen Aufenthalt und einen besonderen Grund, etwa B2 oder fünfjährige Ehe mit Österreicher*in. Allgemeine Bedingungen gelten für alle.", source: six)
        ], sources: [six, ten, conditions, transition]
    )
}
