import Foundation

extension CitizenshipGuides {
    static let dualCitizenship = DirectoryGuide(
        cardSummary: .init(ukrainian: "Війна не скасовує вимогу Австрії; винятки індивідуальні", german: "Der Krieg hebt Österreichs Grundregel nicht auf; Ausnahmen sind individuell"),
        introduction: .init(ukrainian: "Український закон про множинне громадянство й австрійська вимога виходу з попереднього громадянства — два різні правопорядки. Перевіряти потрібно обидва.", german: "Das ukrainische Recht zur Mehrstaatigkeit und Österreichs Voraussetzung des Ausscheidens aus der bisherigen Staatsangehörigkeit sind zwei verschiedene Rechtsordnungen. Beide müssen geprüft werden."),
        sections: [
            .init("austria", "checkmark.shield", "Австрійське загальне правило", "Österreichische Grundregel", "При натуралізації Австрія зазвичай вимагає виходу з попереднього громадянства. Часто спершу видають Zusicherungsbescheid — обіцянку надати громадянство за умови підтвердження виходу протягом 2 років, якщо це можливо й розумно вимагати. Не відмовляйтеся від українського громадянства до офіційної вказівки компетентного органу.", "Bei Einbürgerung verlangt Österreich grundsätzlich das Ausscheiden aus der bisherigen Staatsangehörigkeit. Häufig folgt zunächst ein Zusicherungsbescheid mit bis zu 2 Jahren zum Nachweis, soweit dies möglich und zumutbar ist. Verlassen Sie die ukrainische Staatsangehörigkeit nicht vor Anweisung der zuständigen Behörde.", source: dual),
            .init("war", "exclamationmark.triangle", "Що змінює війна", "Was der Krieg ändert", "Війна сама по собі не створює автоматичний австрійський виняток для всіх українців. Якщо вихід фактично неможливий або нерозумно вимагати його у вашому випадку, подайте докази та письмове пояснення до земельного органу й попросіть рішення саме щодо вас. Не покладайтеся на усні поради чи припущення про загальне звільнення.", "Der Krieg bewirkt keine automatische österreichische Ausnahme für alle Ukrainer. Ist das Ausscheiden in Ihrem konkreten Fall unmöglich oder unzumutbar, legen Sie Nachweise und eine schriftliche Begründung bei der Landesbehörde vor und verlangen Sie eine Einzelfallentscheidung. Verlassen Sie sich nicht auf mündliche Zusagen oder eine pauschale Ausnahme.", source: dual),
            .init("ukraine", "globe.europe.africa", "Українські правила з 2026 року", "Ukrainische Regeln seit 2026", "Україна з 16.01.2026 визнає визначені випадки множинного громадянства. Це не означає, що Австрія автоматично дозволяє зберегти українське при натуралізації. Перелік держав і умови українського закону змінні; ДМС називає окремі держави для спрощеного набуття, тож не вважайте Австрію включеною без перевірки чинного переліку.", "Die Ukraine erkennt seit 16.01.2026 bestimmte Fälle von Mehrstaatigkeit an. Das verpflichtet Österreich nicht, bei Einbürgerung die ukrainische Staatsangehörigkeit zu belassen. Staatenliste und Bedingungen des ukrainischen Rechts können sich ändern; die DMS nennt bestimmte Staaten für vereinfachten Erwerb. Nehmen Sie Österreich nicht ohne Prüfung der aktuellen Liste als erfasst an.", source: ukrainianLaw),
            .init("exit", "doc.text", "Як оформлюють вихід з України", "Ausscheiden aus der Ukraine", "МЗС описує окреме клопотання, документи про постійне проживання за кордоном та наявне або гарантоване інше громадянство. Австрійський Meldezettel не є автоматично українським оформленням ПМП. Громадянство України припиняється лише з відповідним указом Президента; заява сама по собі цього не робить. Перевірте поточний комплект у консульстві після отримання австрійського рішення.", "Das ukrainische MFA beschreibt einen gesonderten Antrag, Nachweise über dauerhaftes Auslandsleben und bestehende oder zugesicherte andere Staatsangehörigkeit. Ein österreichischer Meldezettel ist keine ukrainische Auslands-Permanentregistrierung. Die ukrainische Staatsangehörigkeit endet erst mit dem entsprechenden Präsidialerlass, nicht mit dem Antrag. Prüfen Sie aktuelle Unterlagen beim Konsulat nach dem österreichischen Bescheid.", source: ukrainianExit)
        ], sources: [dual, ukrainianLaw, ukrainianExit, conditions]
    )

    static let childrenGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Походження, спільна заява з батьками й власний шлях", german: "Abstammung, Miteinbürgerung und eigener Weg"),
        introduction: .init(ukrainian: "Місце народження дитини та громадянство її батьків — різні речі. Народження в Австрії саме по собі зазвичай не дає австрійського паспорта.", german: "Geburtsort und Staatsangehörigkeit der Eltern sind verschieden. Geburt in Österreich allein verleiht gewöhnlich keinen österreichischen Pass."),
        sections: [
            .init("birth", "figure.child", "Австрійський батько або мати", "Österreichischer Elternteil", "Якщо при народженні хоча б один з батьків мав австрійське громадянство, дитина зазвичай набуває його за походженням; окремі правила залежать від встановлення батьківства та сімейної ситуації. Якщо обидва батьки українці, австрійське свідоцтво про народження не робить дитину австрійцем.", "Ist bei Geburt mindestens ein Elternteil österreichischer Staatsbürger, erwirbt das Kind die Staatsbürgerschaft grundsätzlich durch Abstammung; Einzelheiten hängen von Elternschaft und Familienlage ab. Sind beide Eltern Ukrainer, macht eine österreichische Geburtsurkunde das Kind nicht zum Österreicher.", source: children),
            .init("extend", "person.2", "Разом із батьком або матір’ю", "Mit einem Elternteil", "Коли батькові чи матері надають австрійське громадянство, його можна поширити на неповнолітню дитину за встановлених умов. Для дитини при такому поширенні немає окремого мінімального строку проживання. Потрібні опіка, згода інших законних представників у відповідних випадках і власні документи дитини.", "Wird ein Elternteil eingebürgert, kann die Verleihung unter Voraussetzungen auf ein minderjähriges Kind erstreckt werden. Dafür gibt es keine eigene Mindestaufenthaltsdauer des Kindes. Obsorge, gegebenenfalls Zustimmung weiterer Sorgeberechtigter und Unterlagen des Kindes sind nötig.", source: children),
            .init("language", "text.book.closed", "Мова та тест для дітей", "Deutsch und Test bei Kindern", "Для дітей до 14 років мовний доказ і тест із громадянства зазвичай не потрібні; для старших діють окремі шкільні та мовні докази. Попросіть орган перевірити вік на момент рішення й конкретний вид заяви.", "Unter 14 Jahren sind Deutschnachweis und Staatsbürgerschaftstest grundsätzlich nicht nötig; für ältere Kinder gelten besondere Schul- und Sprachnachweise. Lassen Sie Alter zum Entscheidungszeitpunkt und Antragsart prüfen.", source: language)
        ], sources: [children, language, test]
    )

    static let applicationDocuments = DirectoryGuide(
        cardSummary: .init(ukrainian: "Особа, історія перебування, дохід, мова, сім’я", german: "Identität, Aufenthalt, Einkommen, Sprache, Familie"),
        introduction: .init(ukrainian: "Точний список залежить від сім’ї, статусу та федеральної землі. Почніть зі збору незмінних документів і попросіть перелік органу до витрат на довідки та переклади.", german: "Die genaue Liste hängt von Familie, Titel und Bundesland ab. Sammeln Sie dauerhafte Urkunden zuerst und holen Sie die Behördenliste vor teuren Bescheinigungen und Übersetzungen ein."),
        sections: [
            .init("identity", "person.text.rectangle", "Особа й сім’я", "Identität und Familie", "Паспорт, свідоцтво про народження, свідоцтва про шлюб/розлучення або зміну імені, документи дітей та партнера. Для іноземних свідоцтв перевірте апостиль і присяжний переклад; різне написання ПІБ потрібно документально пов’язати.", "Pass, Geburtsurkunde, Ehe-/Scheidungs- oder Namensurkunden sowie Unterlagen von Kindern und Partnern. Für ausländische Urkunden Apostille und beglaubigte Übersetzung prüfen; abweichende Namensschreibweisen belegen.", source: documents),
            .init("residence", "calendar", "Перебування, мова, інтеграція", "Aufenthalt, Sprache, Integration", "Зберіть усі старі посвідки й рішення, адресні та страхові підтвердження, історію поїздок, мовний сертифікат або інший дозволений доказ, а також документи для підстави через 6 років: B2, шлюб або докази суспільно корисної діяльності.", "Sammeln Sie alte Titel und Bescheide, Melde- und Versicherungsnachweise, Reisenachweise, Sprachzertifikat oder anerkannte Alternative sowie Belege für den Sechsjahresgrund: B2, Ehe oder gemeinnützige Tätigkeit.", source: documents),
            .init("income", "eurosign.circle", "Фінанси та нові довідки", "Finanzen und aktuelle Nachweise", "Підготуйте підтвердження доходів, оренди, аліментів, кредитів і страхування за період, який запитає орган. Довідки з коротким строком актуальності та фото замовляйте ближче до подання. Відень публікує окремий актуальний список; інші землі можуть вимагати свій комплект.", "Bereiten Sie Einkommens-, Miet-, Unterhalts-, Kredit- und Versicherungsnachweise für den verlangten Zeitraum vor. Kurz gültige Bescheinigungen und Foto erst näher am Antrag besorgen. Wien veröffentlicht eine aktuelle Liste; andere Länder können eigene Unterlagen verlangen.", source: documents)
        ], sources: [documents, conditions, DocumentGuides.translators, DocumentGuides.ukrainianApostille]
    )

    static let application = DirectoryGuide(
        cardSummary: .init(ukrainian: "Куди звернутися, коли виходити з громадянства, скільки коштує", german: "Zuständigkeit, Ausscheiden und Kosten"),
        introduction: .init(ukrainian: "Заяву приймає орган з питань громадянства федеральної землі основного місця проживання; у Відні — MA 35. Рішення приймають після перевірки індивідуальної справи.", german: "Zuständig ist die Staatsbürgerschaftsbehörde des Bundeslandes Ihres Hauptwohnsitzes; in Wien MA 35. Die Behörde entscheidet nach Prüfung des Einzelfalls."),
        sections: [
            .init("prepare", "list.bullet.clipboard", "Послідовність", "Reihenfolge", "1. Визначте шлях 6 або 10 років і перевірте статуси та поїздки. 2. Отримайте у земельного органу список документів. 3. Підготуйте дохід, мову, тест і свідоцтва. 4. Подайте особисто. 5. Якщо орган видав Zusicherungsbescheid, лише тоді з’ясовуйте вихід із попереднього громадянства та його строки.", "1. Wählen Sie den 6- oder 10-Jahresweg und prüfen Sie Titel und Reisen. 2. Holen Sie die Unterlagenliste der Landesbehörde. 3. Bereiten Sie Einkommen, Deutsch, Test und Urkunden vor. 4. Stellen Sie den Antrag persönlich. 5. Erst bei Zusicherungsbescheid klären Sie Ausscheiden aus der bisherigen Staatsangehörigkeit und Fristen.", source: vienna),
            .init("cost", "eurosign.circle", "Витрати", "Kosten", "Збори залежать від виду надання, сім’ї та землі. У Відні офіційна таблиця наводить окремі платежі за заяву, можливий Zusicherungsbescheid і кінцеве надання; ще оплачуються документи, переклади та апостилі. Не орієнтуйтеся на старі суми з форумів — перевірте чинну таблицю перед подачею.", "Gebühren hängen von Verleihungsart, Familie und Bundesland ab. Wien listet getrennte Zahlungen für Antrag, möglichen Zusicherungsbescheid und Verleihung; Urkunden, Übersetzungen und Apostillen kommen hinzu. Nutzen Sie vor Antrag die aktuelle amtliche Tabelle statt alter Forenbeträge.", source: costs),
            .init("contact", "building.columns", "Якщо живете не у Відні", "Außerhalb Wiens", "Зверніться до відділу громадянства своєї Landesregierung, а не до MA 35. Федеральний портал містить посилання на органи всіх земель. Попросіть письмово пояснити спірні періоди тимчасового захисту, студентського проживання чи звільнення від виходу з громадянства України.", "Wenden Sie sich an die Staatsbürgerschaftsabteilung Ihrer Landesregierung, nicht an MA 35. Das Bundesportal verlinkt alle Länderbehörden. Lassen Sie strittige Zeiten des Vertriebenenschutzes, Studiums oder eine Ausnahme vom Ausscheiden aus der ukrainischen Staatsangehörigkeit schriftlich klären.", source: six)
        ], sources: [vienna, six, ten, costs, documents, dual]
    )
}
