import Foundation

extension DirectoryCatalog {
    static let startCategories: [DirectoryCategory] = [
        category("safety", "Безпека та захист", "Sicherheit & Schutz",
                 summaryUK: "Важливі теми про захист і підтримку", summaryDE: "Wichtige Themen zu Schutz und Unterstützung",
                 symbol: "shield.lefthalf.filled", topics: [
            topic("emergency", "Невідкладна допомога", "Notfallhilfe"),
            topic("domestic-violence", "Домашнє насильство", "Häusliche Gewalt"),
            topic("women", "Допомога жінкам", "Hilfe für Frauen"),
            topic("children", "Захист дітей", "Kinderschutz"),
            topic("assault", "Напад і злочин", "Angriff und Straftat"),
            topic("discrimination", "Дискримінація та переслідування", "Diskriminierung & Belästigung"),
            topic("fire-gas", "Пожежа та запах газу", "Brand und Gasgeruch"),
            topic("mountains-water", "Гори та водойми", "Berge und Gewässer"),
            topic("poisoning", "Отруєння", "Vergiftung"),
            topic("disasters", "Негода та катастрофи", "Unwetter und Katastrophen"),
            topic("road-accident", "Дорожня пригода", "Verkehrsunfall"),
            topic("mental-crisis", "Психологічна криза", "Psychische Krise")
        ]),
        category("first-steps", "Перші кроки", "Erste Schritte",
                 summaryUK: "Що зробити сьогодні та в перший тиждень",
                 summaryDE: "Was heute und in der ersten Woche wichtig ist",
                 symbol: "figure.walk.arrival", topics: [
            topic("arrival", "Перший день: безпечна ночівля", "Erster Tag: sicher übernachten"),
            topic("checklist", "Перший тиждень: порядок дій", "Erste Woche: die nächsten Schritte")
        ]),
        category("registration", "Реєстрація", "Anmeldung",
                 summaryUK: "Адреса, тимчасовий захист, посвідчення й переїзд",
                 summaryDE: "Wohnsitz, Schutz, Ausweis und Umzug",
                 symbol: "checklist", topics: [
            topic("residence-registration", "Реєстрація адреси", "Wohnsitz anmelden"),
            topic("housing-types", "Якщо немає власного житла", "Wenn Sie keine eigene Wohnung haben"),
            topic("protection-registration", "Реєстрація для тимчасового захисту", "Erfassung für vorübergehenden Schutz"),
            topic("after-registration", "Посвідчення після реєстрації", "Ausweis nach der Erfassung"),
            topic("address-change", "Зміна адреси", "Adressänderung"),
            topic("leaving-austria", "Виїзд і зняття з обліку", "Wegzug und Abmeldung"),
            topic("appointments", "Запис до установ", "Behördentermine")
        ]),
        category("housing", "Житло", "Wohnen",
                 summaryUK: "Від першого прихистку до оренди, гуртожитку й купівлі",
                 summaryDE: "Von der ersten Unterkunft bis Miete, Wohnheim und Kauf",
                 symbol: "house.lodge.fill", topics: [
            topic("arrival-housing", "Де ночувати після прибуття", "Unterkunft nach der Ankunft"),
            topic("temporary-housing", "Тимчасове житло й Grundversorgung", "Vorübergehende Unterkunft und Grundversorgung"),
            topic("find-rental", "Де шукати квартиру", "Mietwohnung suchen"),
            topic("viewing", "Перегляд і перевірка квартири", "Besichtigung und Wohnungsprüfung"),
            topic("rental-contract", "Договір оренди та Mietanbot", "Mietvertrag und Mietanbot"),
            topic("rent-costs", "Оренда, комунальні та індексація", "Miete, Betriebskosten und Anpassungen"),
            topic("deposit", "Застава, Ablöse та передача ключів", "Kaution, Ablöse und Übergabe"),
            topic("rental-agents", "Маклер і комісія", "Makler und Provision"),
            topic("tenant-rights", "Права орендаря та ремонт", "Mieterrechte und Reparaturen"),
            topic("ending-lease", "Розірвання, виселення та виїзд", "Kündigung, Räumung und Auszug"),
            topic("shared-flat", "Кімната, WG і суборенда", "Zimmer, WG und Untermiete"),
            topic("student-housing", "Студентські гуртожитки", "Studierendenwohnheime"),
            topic("social-housing", "Муніципальне й кооперативне житло", "Gemeinde- und Genossenschaftswohnungen"),
            topic("housing-support", "Допомога з оплатою житла", "Wohnbeihilfe und Unterstützung"),
            topic("buying", "Купівля квартири чи будинку", "Wohnung oder Haus kaufen"),
            topic("buying-costs", "Кредит, податки й витрати на купівлю", "Kredit, Steuern und Kaufnebenkosten"),
            topic("foreign-buyers", "Правила для покупців з України", "Regeln für Käufer aus der Ukraine"),
            topic("moving", "Переїзд, Meldezettel і договори", "Umzug, Meldezettel und Verträge")
        ]),
        category("residence", "Статус перебування", "Aufenthalt",
                 summaryUK: "Захист, навчання, родина, робота й постійне проживання",
                 summaryDE: "Schutz, Studium, Familie, Arbeit und Daueraufenthalt",
                 symbol: "person.crop.rectangle", topics: [
            topic("residence-permits", "З чого почати: віза чи дозвіл?", "Einstieg: Visum oder Aufenthaltstitel?"),
            topic("temporary-protection", "Тимчасовий захист", "Vorübergehender Schutz"),
            topic("international-protection", "Притулок і субсидіарний захист", "Asyl und subsidiärer Schutz"),
            topic("student-residence", "Навчання й студентський статус", "Studium und Aufenthaltsbewilligung"),
            topic("austrian-family", "Шлюб і сім’я громадянина Австрії", "Ehe und Familie österreichischer Staatsbürger"),
            topic("eu-family", "Родина громадянина ЄС / ЄЕЗ", "Familie von EU- und EWR-Bürgern"),
            topic("third-country-family", "Возз’єднання з іноземцем", "Familiennachzug zu Drittstaatsangehörigen"),
            topic("work-residence", "Робочий дозвіл: RWR і Blue Card", "Arbeit: RWR-Karte und Blaue Karte EU"),
            topic("rwr-plus", "Червона-біло-червона картка плюс", "Rot-Weiß-Rot-Karte plus"),
            topic("status-change", "Зміна підстави перебування", "Aufenthaltszweck ändern"),
            topic("residence-renewal", "Продовження дозволу", "Aufenthaltstitel verlängern"),
            topic("permanent-residence", "Довгострокове проживання", "Daueraufenthalt – EU")
        ]),
        category("documents", "Документи", "Dokumente",
                 summaryUK: "Паспорти, свідоцтва, права, апостиль і консульства",
                 summaryDE: "Pässe, Urkunden, Führerschein, Apostille und Konsulate",
                 symbol: "doc.text.fill", topics: [
            topic("identity", "Який документ для чого потрібен?", "Welches Dokument wofür?"),
            topic("passport", "Закордонний паспорт України", "Ukrainischer Reisepass"),
            topic("ukrainian-id", "Внутрішній паспорт та ID-картка", "Ukrainischer Inlandspass und ID-Karte"),
            topic("child-documents", "Документи дитини", "Dokumente für Kinder"),
            topic("civil-records", "Свідоцтва й витяги з ДРАЦС", "Personenstandsurkunden und Registerauszüge"),
            topic("name-change", "Шлюб, прізвище й заміна документів", "Ehe, Namensänderung und Dokumententausch"),
            topic("tax-number", "Український податковий номер", "Ukrainische Steuernummer"),
            topic("police-certificate", "Довідка про несудимість", "Strafregisterauszug"),
            topic("power-of-attorney", "Довіреність і нотаріальні дії", "Vollmacht und notarielle Handlungen"),
            topic("driving-licence", "Українське посвідчення водія", "Ukrainischer Führerschein"),
            topic("translations", "Переклади й завірені копії", "Übersetzungen und beglaubigte Kopien"),
            topic("apostille", "Апостиль і легалізація", "Apostille und Beglaubigung"),
            topic("austrian-documents", "Документи, видані в Австрії", "In Österreich ausgestellte Dokumente"),
            topic("lost-documents", "Втрата або крадіжка документів", "Verlorene oder gestohlene Dokumente"),
            topic("consulate-austria", "Консульство України у Відні", "Ukrainische Botschaft in Wien"),
            topic("consulates-nearby", "Консульства в сусідніх країнах", "Konsulate in Nachbarländern")
        ]),
        category("citizenship", "Громадянство", "Staatsbürgerschaft",
                 summaryUK: "Шляхи через 6 і 10 років, статус, мова, родина й громадянство України",
                 summaryDE: "Wege nach 6 und 10 Jahren, Status, Sprache, Familie und Ukraine",
                 symbol: "globe.europe.africa.fill", topics: [
            topic("overview", "З чого почати й хто може подати?", "Einstieg: Wer kann einen Antrag stellen?"),
            topic("six-years", "Шлях через 6 років", "Weg nach 6 Jahren"),
            topic("ten-years", "Шлях через 10 років", "Weg nach 10 Jahren"),
            topic("protection", "Тимчасовий захист українців", "Vorübergehender Schutz für Ukrainer"),
            topic("student", "Студентська віза й навчання", "Studium und Aufenthaltsbewilligung"),
            topic("austrian-spouse", "Шлюб з громадянином Австрії", "Ehe mit österreichischem Staatsbürger"),
            topic("other-statuses", "Робота, родина, притулок", "Arbeit, Familie und Asyl"),
            topic("language", "Німецька мова та іспит", "Deutsch und Staatsbürgerschaftstest"),
            topic("livelihood", "Доходи й інші умови", "Lebensunterhalt und weitere Bedingungen"),
            topic("absences", "Поїздки й переривання проживання", "Auslandszeiten und Unterbrechungen"),
            topic("dual-citizenship", "Українське громадянство й відмова", "Ukrainische Staatsangehörigkeit und Entlassung"),
            topic("children", "Діти та громадянство", "Kinder und Staatsbürgerschaft"),
            topic("documents", "Підготовка документів", "Unterlagen vorbereiten"),
            topic("application", "Заява, процедура й витрати", "Antrag, Verfahren und Kosten")
        ])
    ]
}
