import Foundation

extension EducationGuides {
    static let language = DirectoryGuide(
        cardSummary: .init(ukrainian: "Курси ÖIF, рівні A1–C1, онлайн-заняття й сертифікати", german: "ÖIF-Kurse A1–C1, Online-Lernen und Zertifikate"),
        introduction: .init(ukrainian: "Для переміщених українців ÖIF пропонує курси по всій Австрії. Вибір курсу залежить від поточного рівня, цілі та доступного часу.", german: "Der ÖIF bietet Vertriebenen aus der Ukraine Kurse in ganz Österreich. Wählen Sie nach Sprachniveau, Ziel und verfügbarer Zeit."),
        sections: [
            .init("start", "text.bubble", "Запишіться на консультацію ÖIF", "ÖIF-Beratung vereinbaren", "Для фінансованого курсу ÖIF зверніться до Integrationszentrum своєї землі. Візьміть картку переміщеної особи, Meldezettel, документ особи та наявні дані страхування. На консультації уточніть свій рівень, місце, дату початку й правила відвідування; запис через сам Sprachportal не замінює цю консультацію.", "Für einen geförderten ÖIF-Kurs das Integrationszentrum im Bundesland kontaktieren. Vertriebenenkarte, Meldezettel, Ausweis und vorhandene Versicherungsdaten mitbringen. Im Gespräch Niveau, Platz, Beginn und Anwesenheitsregeln klären; das Sprachportal ersetzt diese Beratung nicht.", source: german),
            .init("choice", "calendar", "Підберіть формат і догляд за дітьми", "Format und Kinderbetreuung wählen", "ÖIF пропонує переміщеним українцям курси від A1 до C1. На консультації попросіть варіант, сумісний із роботою, школою дітей і дорогою; за потреби запитайте про догляд за дітьми. Уточніть, чи курс фінансується для вас і чи є місце саме зараз. Підготовчі курси при університеті мають окремі умови й можуть бути платними.", "Der ÖIF bietet Vertriebenen aus der Ukraine Kurse von A1 bis C1. Im Beratungsgespräch ein mit Arbeit, Schulzeiten und Anfahrt vereinbares Angebot suchen und bei Bedarf Kinderbetreuung erfragen. Finanzierung und freien Platz für den eigenen Fall klären. Universitäre Vorstudienlehrgänge haben andere Regeln und können kostenpflichtig sein.", source: germanUkraine),
            .init("online", "laptopcomputer", "Навчання між заняттями", "Zwischen den Terminen lernen", "ÖIF має безкоштовні онлайн-заняття й вправи на Sprachportal. Поєднуйте їх із розмовною практикою, власним словником для роботи чи навчання і регулярним повторенням. Онлайн-участь не завжди замінює присутність на фінансованому курсі.", "Der ÖIF bietet kostenlose Online-Stunden und Übungen im Sprachportal. Kombinieren Sie sie mit Gesprächspraxis, beruflichem Wortschatz und Wiederholung. Online-Lernen ersetzt nicht automatisch Anwesenheit in einem geförderten Kurs.", source: germanOnline),
            .init("certificate", "checkmark.seal", "Визначте потрібний іспит", "Benötigte Prüfung bestimmen", "Курси ÖIF від рівня A2 завершуються іспитом; успішна здача дає мовний сертифікат. Але робота, вступ, перебування й громадянство можуть вимагати різні рівні або конкретні визнані іспити. Перед оплатою іншого іспиту попросіть установу назвати точний документ, рівень і допустимий строк його давності.", "ÖIF-Kurse schließen ab A2 mit einer Prüfung ab; nach positivem Abschluss gibt es ein Sprachzertifikat. Arbeit, Studienzulassung, Aufenthalt und Staatsbürgerschaft können jedoch unterschiedliche Niveaus oder bestimmte anerkannte Prüfungen verlangen. Vor Zahlung einer weiteren Prüfung Dokument, Niveau und Gültigkeit bei der zuständigen Stelle erfragen.", source: germanUkraine),
            .init("next", "arrow.right.circle", "Після курсу: збережіть результат", "Nach dem Kurs: Ergebnis sichern", "Збережіть сертифікат і перевірте, чи його вистачає для вашої наступної цілі. Якщо потрібен вищий рівень, обговоріть продовження на консультації ÖIF. Для навчання у виші перевірте вимоги саме вашої програми: курс відвідано — ще не означає, що мовну вимогу виконано.", "Zertifikat aufheben und prüfen, ob es für das nächste Ziel genügt. Ist ein höheres Niveau nötig, den Folgekurs mit dem ÖIF besprechen. Für ein Studium die Anforderungen des konkreten Studiengangs prüfen: Kursbesuch allein erfüllt die Sprachvorgabe nicht.", source: german)
        ], sources: [german, germanOnline, germanUkraine]
    )
}
