import Foundation

extension EducationGuides {
    static let schoolGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Зарахування, німецька підтримка й навчання до 18 років", german: "Einschreibung, Deutschförderung und Ausbildung bis 18"),
        introduction: .init(ukrainian: "Діти, що постійно живуть в Австрії, мають відвідувати школу незалежно від медичного страхування. Після переїзду зверніться до найближчої школи або Bildungsdirektion.", german: "Kinder mit dauerhaftem Aufenthalt in Österreich sind schulpflichtig, unabhängig vom Krankenversicherungsschutz. Nach Umzug Schule oder Bildungsdirektion kontaktieren."),
        sections: [
            .init("enroll", "building.2", "Зарахуйте дитину", "Kind anmelden", "Для початку Volksschule зазвичай реєструють у школі за адресою. Візьміть документ дитини, Meldezettel, попередні табелі й відомості про особливі потреби; якщо чогось немає, попросіть школу пояснити альтернативу. Для підлітка, який уже навчався в Україні, Bildungsdirektion допоможе підібрати клас і тип школи.", "Volksschuleinschreibung erfolgt meist bei der zuständigen Schule. Ausweis, Meldezettel, frühere Zeugnisse und Angaben zu Förderbedarf mitbringen; bei fehlenden Unterlagen nach Alternativen fragen. Für ältere Kinder hilft die Bildungsdirektion bei Stufe und Schulart.", source: school),
            .init("language", "text.bubble", "Мовна й навчальна підтримка", "Deutsch- und Lernförderung", "Попросіть школу пояснити результат оцінки німецької MIKA-D та індивідуальний план підтримки. З 2026/27 школа може організувати її автономно або за моделлю Deutschförderklasse/-kurs. Запитайте, як дитина навчатиметься з класом, коли перевірять прогрес і чи є предметна підтримка. Уроки української як рідної мови можуть доповнювати навчання.", "Lassen Sie sich das Ergebnis der Deutsch-Einstufung MIKA-D und den individuellen Förderplan erklären. Seit 2026/27 kann die Schule Förderung autonom oder als Deutschförderklasse/-kurs gestalten. Fragen Sie nach Unterricht im Klassenverband, nächster Überprüfung und Fachförderung. Ukrainischer Erstsprachenunterricht kann ergänzen.", source: schoolLanguage),
            .init("summer", "sun.max", "Літня школа: перевірте обов’язок", "Sommerschule: Teilnahmepflicht prüfen", "Якщо дитина має статус außerordentliche/r Schüler/in у Deutschförderklasse, участь у Sommerschule з 2026 року є обов’язковою. Для інших дітей вона може бути добровільною. Перед канікулами попросіть школу письмово уточнити статус дитини, місце занять і порядок повідомлення про відсутність.", "Für außerordentliche Schüler:innen in Deutschförderklassen ist die Sommerschule seit 2026 verpflichtend; für andere kann sie freiwillig sein. Vor den Ferien Status, Standort und Regeln für Abwesenheit schriftlich mit der Schule klären.", source: summerSchool),
            .init("path", "arrow.triangle.branch", "Після початкової школи", "Nach der Volksschule", "Після чотирьох років Volksschule порівняйте Mittelschule та AHS-Unterstufe за умовами вступу й потребами дитини. Пізніше є Polytechnische Schule, професійна школа, Lehre або AHS-Oberstufe. Попросіть консультацію в школі й перевірте строки подання до конкретного закладу.", "Nach vier Jahren Volksschule Mittelschule und AHS-Unterstufe anhand von Aufnahmebedingungen und Bedürfnissen des Kindes vergleichen. Später kommen Polytechnische Schule, Berufsbildung, Lehre oder AHS-Oberstufe infrage. Schulberatung nutzen und Fristen der konkreten Einrichtung prüfen.", source: schoolDuty),
            .init("until-18", "calendar.badge.clock", "Дев’ять років школи — і навчання до 18", "Neun Schuljahre – und Ausbildung bis 18", "Шкільний обов’язок зазвичай починається 1 вересня після шостого дня народження й триває дев’ять навчальних років. Після нього підлітки, які постійно живуть в Австрії, мають до 18 років продовжувати школу або професійну підготовку, якщо раніше не завершили подальшу освіту. Якщо дитина хоче залишити школу, попросіть консультацію про допустимий наступний шлях.", "Die Schulpflicht beginnt grundsätzlich am 1. September nach dem sechsten Geburtstag und dauert neun Schuljahre. Danach müssen Jugendliche mit dauerhaftem Aufenthalt bis 18 in Schule oder Ausbildung bleiben, sofern sie nicht früher eine weiterführende Ausbildung abgeschlossen haben. Vor einem Schulabbruch den zulässigen Anschlussweg beraten lassen.", source: schoolUntil18),
            .init("move", "arrow.triangle.2.circlepath", "Переїзд і труднощі", "Umzug und Schwierigkeiten", "При переїзді повідомте стару й нову школу, передайте табель і підтвердіть нове місце. Якщо є цькування, дискримінація або тривала хвороба, спершу обговоріть конкретні випадки з класним керівником і директором. Для незалежної консультації зверніться до Schulpsychologie; контакти за землями є на її сайті.", "Bei Umzug beide Schulen informieren, Zeugnisse übergeben und neuen Platz bestätigen. Bei Mobbing, Diskriminierung oder längerer Krankheit konkrete Vorfälle mit Klassenleitung und Direktion besprechen. Für unabhängige Beratung die Schulpsychologie kontaktieren; Länderstellen stehen auf ihrer Website.", source: schoolCounseling)
        ], sources: [school, schoolDuty, schoolLanguage, schoolUntil18, schoolCounseling, summerSchool]
    )
}
