import Foundation

extension EducationGuides {
    static let kindergartenGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Запис, обов’язковий рік, витрати й правила вашої землі", german: "Anmeldung, Pflichtjahr, Kosten und Landesregeln"),
        introduction: .init(ukrainian: "Садочки організовують землі й громади, тому місця, години та ціни різняться. Почніть пошук рано, навіть якщо ще не маєте всіх документів.", german: "Kindergärten werden von Ländern und Gemeinden geregelt; Plätze, Zeiten und Preise unterscheiden sich. Suchen Sie früh, auch wenn noch Unterlagen fehlen."),
        sections: [
            .init("type", "figure.child", "Виберіть форму догляду", "Betreuungsform wählen", "Для дітей до трьох років шукайте Kinderkrippe або Tageseltern; старшим — Kindergarten, після школи — Hort. Порівняйте відстань, години, канікули, харчування, підтримку німецької й особливих потреб. У місті та селі перелік і наявність місць різні.", "Unter Dreijährige können in Krippe oder bei Tageseltern betreut werden, ältere Kinder im Kindergarten, Schulkinder im Hort. Weg, Zeiten, Ferien, Essen, Deutschförderung und besonderen Bedarf vergleichen. Plätze variieren je nach Gemeinde.", source: kindergarten),
            .init("apply", "calendar", "Подайте заявку якомога раніше", "Möglichst früh anmelden", "Зверніться до Gemeinde/Magistrat або приватного закладу; у Відні за міські місця відповідає MA 10. Попросіть чинні строки, список документів, критерії розподілу й письмове підтвердження заявки. Сама заявка безкоштовна, але місце ще не гарантоване.", "Gemeinde/Magistrat oder private Einrichtung kontaktieren; in Wien ist MA 10 für städtische Plätze zuständig. Fristen, Unterlagen, Vergabekriterien und Eingangsbestätigung erfragen. Die Anmeldung ist kostenlos, ein Platz dadurch noch nicht zugesichert.", source: kindergarten),
            .init("no-place", "person.2", "Якщо місця немає", "Wenn kein Platz frei ist", "Попросіть письмово уточнити місце у списку очікування, наступну дату розподілу та альтернативи: інший садочок, Kinderkrippe чи Tageseltern відповідно до віку. Якщо дитині потрібна підтримка через інвалідність або затримку розвитку, обговоріть із громадою відповідну форму догляду. Не відмовляйтеся від наявного місця, доки не підтверджено нове.", "Wartelistenplatz, nächsten Vergabetermin und Alternativen wie andere Einrichtung, Krippe oder Tageseltern je nach Alter erfragen. Bei Behinderung oder Entwicklungsbedarf mit der Gemeinde eine geeignete Betreuung klären. Einen bestehenden Platz erst nach Bestätigung eines neuen aufgeben.", source: kindergarten),
            .init("year", "checkmark.circle", "Останній рік перед школою", "Letztes Jahr vor der Schule", "Якщо дитині виповнилося п’ять років до 31 серпня, від вересня до червня діє обов’язок відвідувати садок щонайменше 20 годин на тиждень. Ці 20 годин без обіду безкоштовні. Звільнення, наприклад через стан здоров’я, потребує письмової заяви; правила відсутності перевірте в закладі.", "Ist das Kind bis 31. August fünf Jahre alt geworden, gilt von September bis Juni eine Besuchspflicht von mindestens 20 Wochenstunden. Diese 20 Stunden ohne Mittagessen sind beitragsfrei. Eine Befreiung etwa wegen Krankheit erfordert einen schriftlichen Antrag; Fehlzeitenregeln bei der Einrichtung prüfen.", source: kindergartenRules),
            .init("cost", "eurosign.circle", "Плата й допомога з доглядом", "Kosten und Betreuungsbeihilfe", "Додаткові години, обід та попередні роки можуть коштувати по-різному за землями і громадами. Попросіть повний місячний тариф та знижки. Якщо витрати на догляд заважають почати роботу або програму AMS, запитайте AMS про Kinderbetreuungsbeihilfe до початку роботи й догляду; рішення залежить від умов.", "Mehrstunden, Essen und frühere Jahre kosten je nach Bundesland und Gemeinde unterschiedlich. Gesamten Monatstarif und Ermäßigungen erfragen. Erschweren Betreuungskosten Arbeitsaufnahme oder AMS-Maßnahme, Kinderbetreuungsbeihilfe beim AMS vor Beginn von Arbeit und Betreuung prüfen; die Förderung ist an Voraussetzungen gebunden.", source: childcareSupport)
        ], sources: [kindergarten, kindergartenRules, childcareSupport]
    )
}
