import Foundation

extension EducationGuides {
    static let higherEducation = DirectoryGuide(
        cardSummary: .init(ukrainian: "Вступ, українські документи, студентський статус і вартість", german: "Zulassung, ukrainische Nachweise, Aufenthalt und Studienkosten"),
        introduction: .init(ukrainian: "Університет, Fachhochschule й Pädagogische Hochschule мають різні правила вступу. Звільнення від плати перевіряйте для кожного нового семестру в конкретному закладі.", german: "Universität, Fachhochschule und Pädagogische Hochschule haben unterschiedliche Aufnahmeverfahren. Eine Gebührenbefreiung für jedes neue Semester direkt an der Hochschule prüfen."),
        sections: [
            .init("program", "graduationcap", "Оберіть програму й перевірте вступ", "Studiengang und Zulassung prüfen", "Знайдіть конкретну програму й на її сторінці Zulassung перевірте мову викладання, потрібну попередню освіту, вступний іспит та дедлайн. Університети, Fachhochschulen і педагогічні виші встановлюють різні процедури. Зверніться до приймальної комісії письмово, якщо ваш документ або освітній шлях не збігається з прикладами на сайті.", "Den konkreten Studiengang wählen und auf seiner Zulassungsseite Unterrichtssprache, Vorbildung, Aufnahmeprüfung und Frist prüfen. Universitäten, Fachhochschulen und Pädagogische Hochschulen haben unterschiedliche Verfahren. Bei abweichenden Bildungsnachweisen die Studienabteilung schriftlich fragen.", source: ukraineHigher),
            .init("ukraine", "doc.on.doc", "Якщо освіта отримана в Україні", "Mit ukrainischen Bildungsnachweisen", "Сторінка OeAD для українських вступників називає інформаційну картку результатів НМТ серед нових доказів 2026 року. Перевірте перелік саме обраної програми: атестат або диплом, додаток, переклади, результат НМТ, мовний сертифікат та, якщо потрібно, вступний іспит. Якщо документ втрачено, напишіть Zulassungsstelle до дедлайну й попросіть допустиму альтернативу письмово.", "Die OeAD-Information für Bewerber:innen aus der Ukraine nennt seit 2026 die NMT-Ergebniskarte als neuen Nachweis. Die konkrete Studiengangliste zu Zeugnis/Abschluss, Beilage, Übersetzungen, NMT, Sprachnachweis und Aufnahmeprüfung prüfen. Bei verlorenen Unterlagen vor Fristablauf die Zulassungsstelle schriftlich nach einer Alternative fragen.", source: ukraineHigher),
            .init("preparation", "text.book.closed", "Підготовчий курс — окрема процедура", "Vorstudienlehrgang ist ein eigener Schritt", "Якщо бракує німецької чи предметних знань, запитайте виш про Vorstudienlehrgang. Для підготовчого курсу німецької OeAD вимагає попереднього допуску до університету та щонайменше A2. Перевірте окремі строки й плату за курс: звільнення від Studienbeitrag не покриває його автоматично.", "Fehlen Deutsch- oder Fachkenntnisse, bei der Hochschule nach einem Vorstudienlehrgang fragen. Für den Deutsch-Vorbereitungskurs nennt der OeAD eine vorherige Universitätszulassung und mindestens A2. Eigene Fristen und Kursgebühren prüfen: Ein Erlass des Studienbeitrags deckt sie nicht automatisch.", source: preparation),
            .init("cost", "eurosign.circle", "Плата за конкретний семестр", "Gebühren für das konkrete Semester", "Попросіть заклад назвати Studienbeitrag, обов’язковий ÖH-Beitrag, пільги та строк сплати саме за майбутній семестр. OeAD підтверджує звільнення громадян України в державних вишах за літній семестр 2026, але це не доказ звільнення на наступний семестр. Університети, FH і приватні заклади мають різні правила; збережіть письмове рішення вишу.", "Studienbeitrag, verpflichtenden ÖH-Beitrag, Ausnahmen und Frist für das kommende Semester bei der Hochschule erfragen. Der OeAD bestätigt die Befreiung ukrainischer Staatsangehöriger an öffentlichen Hochschulen im Sommersemester 2026; daraus folgt keine automatische Befreiung für spätere Semester. Universitäten, FH und private Hochschulen haben unterschiedliche Regeln; die Auskunft der Hochschule aufheben.", source: ukraineHigher),
            .init("scholarship", "banknote", "Окремо шукайте стипендії", "Stipendien gesondert suchen", "Вартість життя, страхування та матеріалів рахуйте окремо від плати за навчання. У базі grants.at можна шукати програми фінансування; перевіряйте громадянство, тип навчання, дедлайн і потрібні документи в кожній програмі. Стипендія не виникає автоматично після вступу.", "Lebenshaltung, Versicherung und Material getrennt von Studiengebühren kalkulieren. In grants.at nach Förderprogrammen suchen und je Programm Staatsangehörigkeit, Studienart, Frist und Unterlagen prüfen. Eine Zulassung begründet kein automatisches Stipendium.", source: scholarships),
            .init("status", "person.text.rectangle", "Перебування і страхування", "Aufenthalt und Versicherung", "Вступ сам по собі не створює дозволу на проживання або страхування. Для Aufenthaltstitel Student завчасно перевірте вимоги до коштів, житла, страхування, права працювати та строку заяви. Якщо вже маєте тимчасовий захист, порівняйте права перед зміною статусу; навчатися можна й за чинним захистом, якщо виконані умови вступу.", "Die Zulassung schafft allein weder Aufenthaltstitel noch Versicherung. Für die Aufenthaltsbewilligung Student früh Geldmittel, Unterkunft, Versicherung, Arbeitsrecht und Antragsfrist prüfen. Bei bestehendem Vertriebenenschutz Rechte vor einem Wechsel vergleichen; Studium ist auch mit aufrechtem Schutz möglich, wenn die Zulassungsvoraussetzungen erfüllt sind.", source: studentPermit)
        ], sources: [higher, ukraineHigher, preparation, scholarships, studentPermit]
    )
}
