import Foundation

enum EducationGuides {
    private static let kindergarten = DirectorySource(name: "oesterreich.gv.at · Kindergartenanmeldung", url: "https://www.oesterreich.gv.at/de/themen/familie_und_partnerschaft/geburt-eines-kindes/3/1/Seite.080800")
    private static let kindergartenRules = DirectorySource(name: "oesterreich.gv.at · Kindergärten nach Bundesland", url: "https://www.oesterreich.gv.at/de/themen/familie_und_partnerschaft/familie-und-kinderfuersorge/kinderbetreuung/2/Seite.370130")
    private static let school = DirectorySource(name: "oesterreich.gv.at · Schuleinschreibung", url: "https://www.oesterreich.gv.at/de/themen/bildung_und_ausbildung/schulen/4/Seite.110031")
    private static let schoolDuty = DirectorySource(name: "oesterreich.gv.at · Bildung und Schulpflicht", url: "https://www.oesterreich.gv.at/de/lebenslagen/Ich-bin-f%C3%BCr-die-Erziehung-eines-Kindes-verantwortlich/bildung-und-ausbildung")
    private static let schoolChanges = DirectorySource(name: "oesterreich.gv.at · Schuljahr 2026/27", url: "https://www.oesterreich.gv.at/de/themen/bildung_und_ausbildung/schulen/Seite.110007")
    private static let summerSchool = DirectorySource(name: "oesterreich.gv.at · Sommerschule", url: "https://www.oesterreich.gv.at/de/themen/bildung_und_ausbildung/schulen/sommerschule")
    private static let higher = DirectorySource(name: "OeAD · Studium in Österreich", url: "https://studyinaustria.at/en/tuition")
    private static let ukraineHigher = DirectorySource(name: "OeAD · Informationen für Studierende aus der Ukraine", url: "https://studyinaustria.at/en/studium/oead4refugees/informacija-dlja-studentiv-ta-doslidnikiv-z-ukrajini")
    private static let german = DirectorySource(name: "ÖIF · Deutschkurse für Vertriebene", url: "https://www.integrationsfonds.at/ukraine/deutschkurse")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "kindergarten": kindergartenGuide
        case "school": schoolGuide
        case "higher-education": higherEducation
        case "language": language
        default: nil
        }
    }

    private static let kindergartenGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Запис, обов’язковий рік, витрати й правила вашої землі", german: "Anmeldung, Pflichtjahr, Kosten und Landesregeln"),
        introduction: .init(ukrainian: "Садочки організовують землі й громади, тому місця, години та ціни різняться. Почніть пошук рано, навіть якщо ще не маєте всіх документів.", german: "Kindergärten werden von Ländern und Gemeinden geregelt; Plätze, Zeiten und Preise unterscheiden sich. Suchen Sie früh, auch wenn noch Unterlagen fehlen."),
        sections: [
            .init("type", "figure.child", "Виберіть форму догляду", "Betreuungsform wählen", "Для дітей до трьох років шукайте Kinderkrippe або Tageseltern; старшим — Kindergarten, після школи — Hort. Порівняйте відстань, години, канікули, харчування, підтримку німецької й особливих потреб. У місті та селі перелік і наявність місць різні.", "Unter Dreijährige können in Krippe oder bei Tageseltern betreut werden, ältere Kinder im Kindergarten, Schulkinder im Hort. Weg, Zeiten, Ferien, Essen, Deutschförderung und besonderen Bedarf vergleichen. Plätze variieren je nach Gemeinde.", source: kindergarten),
            .init("apply", "calendar", "Подайте заявку", "Anmelden", "Зверніться до Gemeinde/Magistrat або приватного закладу; у Відні за міські місця відповідає MA 10. Попросіть чинні строки, список документів, критерії розподілу й письмове підтвердження заявки. Якщо місць немає, запитайте про список очікування й альтернативні установи.", "Gemeinde/Magistrat oder private Einrichtung kontaktieren; in Wien ist MA 10 für städtische Plätze zuständig. Fristen, Unterlagen, Vergabekriterien und Eingangsbestätigung erfragen. Ohne Platz Warteliste und Alternativen klären.", source: kindergarten),
            .init("year", "checkmark.circle", "Останній рік перед школою", "Letztes Jahr vor der Schule", "У рік перед школою діє обов’язкове відвідування у визначеному обсязі; базові 20 годин на тиждень без обіду безкоштовні. Можливі винятки й правила відсутності. Додаткові години, харчування та ранні роки можуть коштувати по-різному за землями — уточніть тариф і пільги письмово.", "Im letzten Jahr vor Schuleintritt gilt eine Besuchspflicht im vorgeschriebenen Umfang; 20 Wochenstunden ohne Mittagessen sind beitragsfrei. Ausnahmen und Fehlzeiten sind geregelt. Mehrstunden, Essen und frühere Jahre können je Land verschieden kosten – Tarif und Ermäßigung schriftlich klären.", source: kindergartenRules)
        ], sources: [kindergarten, kindergartenRules]
    )

    private static let schoolGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Зарахування, 9 років навчання, німецька підтримка й перехід між школами", german: "Einschreibung, neun Schuljahre, Deutschförderung und Schulwechsel"),
        introduction: .init(ukrainian: "Діти, що постійно живуть в Австрії, мають відвідувати школу незалежно від медичного страхування. Після переїзду зверніться до найближчої школи або Bildungsdirektion.", german: "Kinder mit dauerhaftem Aufenthalt in Österreich sind schulpflichtig, unabhängig vom Krankenversicherungsschutz. Nach Umzug Schule oder Bildungsdirektion kontaktieren."),
        sections: [
            .init("enroll", "building.2", "Зарахуйте дитину", "Kind anmelden", "Для початку Volksschule зазвичай реєструють у школі за адресою. Візьміть документ дитини, Meldezettel, попередні табелі й відомості про особливі потреби; якщо чогось немає, попросіть школу пояснити альтернативу. Для підлітка, який уже навчався в Україні, Bildungsdirektion допоможе підібрати клас і тип школи.", "Volksschuleinschreibung erfolgt meist bei der zuständigen Schule. Ausweis, Meldezettel, frühere Zeugnisse und Angaben zu Förderbedarf mitbringen; bei fehlenden Unterlagen nach Alternativen fragen. Für ältere Kinder hilft die Bildungsdirektion bei Stufe und Schulart.", source: school),
            .init("language", "text.bubble", "Мовна й навчальна підтримка", "Deutsch- und Lernförderung", "Попросіть школу пояснити результат оцінки німецької та конкретну форму підтримки. З 2026/27 школа може організувати її автономно або за попередньою моделлю Deutschförderklasse/-kurs. Запитайте про предметну підтримку, письмовий план та дату повторної оцінки. Навчання рідною мовою доповнює, але не замінює школу.", "Lassen Sie sich die Deutsch-Einstufung und die konkrete Förderung erklären. Seit 2026/27 kann die Schule diese autonom oder im bisherigen Modell Deutschförderklasse/-kurs gestalten. Fragen Sie nach Fachförderung, schriftlichem Plan und nächster Überprüfung. Erstsprachenunterricht ergänzt, ersetzt aber nicht die Schule.", source: schoolChanges),
            .init("summer", "sun.max", "Літня школа: перевірте обов’язок", "Sommerschule: Teilnahmepflicht prüfen", "Якщо дитина має статус außerordentliche/r Schüler/in у Deutschförderklasse, участь у Sommerschule з 2026 року є обов’язковою. Для інших дітей вона може бути добровільною. Перед канікулами попросіть школу письмово уточнити статус дитини, місце занять і порядок повідомлення про відсутність.", "Für außerordentliche Schüler:innen in Deutschförderklassen ist die Sommerschule seit 2026 verpflichtend; für andere kann sie freiwillig sein. Vor den Ferien Status, Standort und Regeln für Abwesenheit schriftlich mit der Schule klären.", source: summerSchool),
            .init("path", "arrow.triangle.branch", "Наступний освітній шлях", "Nächster Bildungsweg", "Загальна шкільна обов’язковість триває дев’ять років. Після Volksschule вибір між Mittelschule та AHS залежить від успішності, місць і цілей; пізніше є професійні школи, Lehre або старша школа. До рішення попросіть консультацію школи й перевірте строки заяв.", "Die allgemeine Schulpflicht dauert neun Jahre. Nach Volksschule hängen Mittelschule oder AHS von Leistung, Plätzen und Zielen ab; später kommen Berufsbildung, Lehre oder Oberstufe infrage. Vor der Wahl Schule beraten lassen und Anmeldefristen prüfen.", source: schoolDuty),
            .init("move", "arrow.triangle.2.circlepath", "Переїзд і проблеми", "Umzug und Probleme", "При зміні адреси повідомте стару й нову школу, передайте табель і підтвердіть нове місце. Якщо є булінг, дискримінація чи довга відсутність через хворобу, попросіть письмовий план допомоги та зверніться до Schulpsychologie або Bildungsdirektion. Не чекайте до кінця семестру.", "Bei Umzug beide Schulen informieren, Zeugnisse übergeben und neuen Platz bestätigen. Bei Mobbing, Diskriminierung oder längerer Krankheit schriftlichen Unterstützungsplan erbitten und Schulpsychologie oder Bildungsdirektion einschalten. Nicht bis Semesterende warten.", source: schoolDuty)
        ], sources: [school, schoolDuty, schoolChanges, summerSchool]
    )

    private static let higherEducation = DirectoryGuide(
        cardSummary: .init(ukrainian: "Вступ, українські документи, студентський статус і вартість", german: "Zulassung, ukrainische Nachweise, Aufenthalt und Studienkosten"),
        introduction: .init(ukrainian: "Університет, Fachhochschule й Pädagogische Hochschule мають різні правила вступу. Не орієнтуйтеся на торішнє звільнення від плати для українців: перевірте поточний семестр у конкретному закладі.", german: "Universität, Fachhochschule und Pädagogische Hochschule haben unterschiedliche Aufnahmeverfahren. Verlassen Sie sich nicht auf frühere ukrainische Gebührenbefreiungen; prüfen Sie das aktuelle Semester an Ihrer Hochschule."),
        sections: [
            .init("program", "graduationcap", "Оберіть програму й вимоги", "Studiengang und Zugang prüfen", "Перевірте мову, дедлайн, конкурс або вступний тест, потрібний попередній диплом і формат навчання. На сторінці Zulassung закладу знайдіть вимоги саме для освіти з України; у 2026 році могли змінитися підтвердження вступних результатів. Поставте приймальній комісії конкретне письмове запитання, якщо документ відсутній.", "Sprache, Frist, Aufnahmeprüfung, Vorabschluss und Studienform prüfen. Auf der Zulassungsseite Anforderungen für ukrainische Bildungsnachweise nachlesen; 2026 können zusätzliche Aufnahme-Nachweise gelten. Fehlende Dokumente konkret schriftlich mit der Studienabteilung klären.", source: ukraineHigher),
            .init("ukraine", "doc.on.doc", "Якщо освіта отримана в Україні", "Mit ukrainischen Bildungsnachweisen", "Сторінка OeAD для українських вступників називає інформаційну картку результатів НМТ серед нових доказів 2026 року. Перевірте перелік саме обраної програми: атестат або диплом, додаток, переклади, результат НМТ, мовний сертифікат та, якщо потрібно, вступний іспит. Якщо документ втрачено, напишіть Zulassungsstelle до дедлайну й попросіть допустиму альтернативу письмово.", "Die OeAD-Information für Bewerber:innen aus der Ukraine nennt seit 2026 die NMT-Ergebniskarte als neuen Nachweis. Die konkrete Studiengangliste zu Zeugnis/Abschluss, Beilage, Übersetzungen, NMT, Sprachnachweis und Aufnahmeprüfung prüfen. Bei verlorenen Unterlagen vor Fristablauf die Zulassungsstelle schriftlich nach einer Alternative fragen.", source: ukraineHigher),
            .init("preparation", "text.book.closed", "Підготовчий курс — окрема плата", "Vorstudienlehrgang kostet extra", "Якщо програмі бракує німецької чи предметних знань, запитайте про Vorstudienlehrgang. Для німецького підготовчого курсу OeAD описує попереднє зарахування до вишу та рівень німецької щонайменше A2; просто записатися без Zulassungsbescheid не можна. Навіть якщо для українського студента скасовано Studienbeitrag, це не покриває автоматично плату за підготовчий курс.", "Fehlen Deutsch- oder Fachkenntnisse, nach Vorstudienlehrgang fragen. Für einen Deutsch-Vorbereitungskurs nennt der OeAD vorherige Hochschulzulassung und mindestens A2 Deutsch; ohne Zulassungsbescheid ist die Einschreibung nicht möglich. Ein Erlass des Studienbeitrags deckt Kurskosten nicht automatisch.", source: ukraineHigher),
            .init("cost", "eurosign.circle", "Плата й фінансування", "Gebühren und Finanzierung", "Попросіть заклад назвати Studienbeitrag, ÖH-Beitrag, пільги, строк сплати й можливість повернення. Правила різні для державних університетів, FH і приватних закладів; статус перебування теж має значення. До сплати перевірте актуальну сторінку OeAD й рішення саме вашого закладу.", "Hochschule nach Studienbeitrag, ÖH-Beitrag, Ausnahmen, Zahlungsfrist und Rückzahlung fragen. Regeln unterscheiden sich bei öffentlichen Universitäten, FH und privaten Einrichtungen; Aufenthaltsstatus zählt mit. Aktuelle OeAD-Seite und Entscheidung Ihrer Hochschule prüfen.", source: higher),
            .init("status", "person.text.rectangle", "Перебування і страхування", "Aufenthalt und Versicherung", "Вступ на навчання сам по собі не створює дозволу на проживання або страхування. Якщо плануєте студентський Aufenthaltstitel, заздалегідь перевірте кошти, страховку, право працювати та строки подання. Якщо вже маєте тимчасовий захист, не змінюйте статус без порівняння прав.", "Zulassung schafft allein weder Aufenthaltstitel noch Krankenversicherung. Für einen Studierendentitel früh Geldmittel, Versicherung, Arbeitsrecht und Fristen prüfen. Besteht bereits Vertriebenenschutz, Rechte vor einem Titelwechsel vergleichen.", source: ukraineHigher)
        ], sources: [higher, ukraineHigher]
    )

    private static let language = DirectoryGuide(
        cardSummary: .init(ukrainian: "Курси ÖIF, рівні A1–C1, онлайн-заняття й сертифікати", german: "ÖIF-Kurse A1–C1, Online-Lernen und Zertifikate"),
        introduction: .init(ukrainian: "Для переміщених українців ÖIF пропонує курси по всій Австрії. Вибір курсу залежить від поточного рівня, цілі та доступного часу.", german: "Der ÖIF bietet Vertriebenen aus der Ukraine Kurse in ganz Österreich. Wählen Sie nach Sprachniveau, Ziel und verfügbarer Zeit."),
        sections: [
            .init("start", "text.bubble", "Запишіться на консультацію", "Beratung vereinbaren", "Знайдіть Integrationszentrum ÖIF своєї землі. Візьміть Ausweis für Vertriebene та Meldezettel, пройдіть визначення рівня й запитайте про денний, вечірній або курс із доглядом за дітьми. Підтвердіть місце, дату початку й правила відвідування до того, як відмовлятися від іншого курсу.", "ÖIF-Integrationszentrum im Bundesland finden. Vertriebenenausweis und Meldezettel mitbringen, Niveau feststellen lassen und nach Tages-, Abendkurs oder Kinderbetreuung fragen. Platz, Beginn und Anwesenheit klären, bevor ein anderer Kurs abgesagt wird.", source: german),
            .init("online", "laptopcomputer", "Навчання між заняттями", "Zwischen den Terminen lernen", "ÖIF має безкоштовні онлайн-заняття й вправи на Sprachportal. Поєднуйте їх із розмовною практикою, власним словником для роботи чи навчання і регулярним повторенням. Онлайн-участь не завжди замінює присутність на фінансованому курсі.", "Der ÖIF bietet kostenlose Online-Stunden und Übungen im Sprachportal. Kombinieren Sie sie mit Gesprächspraxis, beruflichem Wortschatz und Wiederholung. Online-Lernen ersetzt nicht automatisch Anwesenheit in einem geförderten Kurs.", source: german),
            .init("certificate", "checkmark.seal", "Визначте потрібний доказ мови", "Benötigten Nachweis bestimmen", "Для роботи, навчання, дозволу на перебування й громадянства можуть вимагати різні рівні та визнані іспити. Перед оплатою іспиту попросіть установу назвати точний сертифікат, рівень і допустимий строк давності. Сам факт відвідування курсу може не бути достатнім.", "Arbeit, Studium, Aufenthalt und Staatsbürgerschaft können unterschiedliche Niveaus und anerkannte Prüfungen verlangen. Vor Prüfungszahlung genaue Zertifikatsart, Niveau und Gültigkeit bei der zuständigen Stelle erfragen. Kursbesuch allein genügt nicht immer.", source: german)
        ], sources: [german]
    )
}
