import Foundation

extension FamilyGuides {
    static let childcareGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Ясла, садок, Hort, Tageseltern і допомога з оплатою", german: "Krippe, Kindergarten, Hort, Tageseltern und Kostenhilfe"),
        introduction: .init(ukrainian: "Оберіть догляд за віком дитини, робочим графіком і потребами сім’ї. Про запис і обов’язковий рік садка детально написано в категорії «Освіта».", german: "Wählen Sie Betreuung nach Alter, Arbeitszeiten und Familienbedarf. Anmeldung und Pflichtjahr stehen ausführlich unter „Bildung“."),
        sections: [
            .init("options", "figure.child", "Оберіть форму догляду", "Betreuungsform wählen", "Для малюків порівняйте Kinderkrippe й Tageseltern; для старших дітей — Kindergarten, для школярів — Hort або цілоденну школу. Зіставте вік прийому, години, дорогу і потреби дитини. Правила запису до садка та обов’язковий рік — у категорії «Освіта».", "Für Kleinkinder Krippe und Tageseltern vergleichen, später Kindergarten, für Schulkinder Hort oder Ganztagsschule. Aufnahmealter, Zeiten, Weg und Bedürfnisse des Kindes abgleichen. Kindergartenanmeldung und Pflichtjahr stehen unter „Bildung“.", source: childcare),
            .init("schedule", "calendar", "Перевірте реальний графік", "Tatsächliche Zeiten prüfen", "Попросіть заклад письмово підтвердити час прийому й видачі, канікулярні перерви, харчування, догляд у разі хвороби та можливість додаткових годин. Для позмінної роботи одразу запитайте Gemeinde/Magistrat про ранні, пізні та канікулярні місця. Запис у список очікування не означає, що місце надано.", "Annahme- und Abholzeiten, Ferien, Essen, Krankheitsregeln und Zusatzstunden schriftlich klären. Bei Schichtarbeit Gemeinde/Magistrat früh nach Randzeiten und Ferienplätzen fragen. Ein Wartelistenplatz ist keine Zusage.", source: childcare),
            .init("day-parents", "person.crop.circle", "Якщо потрібен гнучкий догляд", "Bei flexiblem Betreuungsbedarf", "Tageseltern можуть мати гнучкіший графік. Перевірте дозвіл на діяльність, години й заміну на випадок відсутності вихователя. До підписання договору з’ясуйте строк розірвання, оплату за пропуски та хто має право забирати дитину.", "Tageseltern können flexiblere Zeiten bieten. Bewilligung, Zeiten und Vertretung bei Ausfall prüfen. Vor Vertragsabschluss Kündigungsfrist, Entgelt bei Fehlzeiten und abholberechtigte Personen klären.", source: dayParents),
            .init("cost", "eurosign.circle", "Розрахуйте повну вартість", "Gesamtkosten berechnen", "Окремо запитайте про внесок, харчування, додаткові години й канікулярний догляд: тарифи залежать від землі та закладу. Зверніться до земельного уряду щодо місцевих знижок. Не плутайте допомогу AMS на оплату догляду з Kinderbetreuungsgeld після народження дитини.", "Beitrag, Essen, Zusatzstunden und Ferienbetreuung getrennt erfragen: Tarife unterscheiden sich nach Land und Einrichtung. Landesförderungen beim Land prüfen. Die AMS-Beihilfe für Betreuungskosten nicht mit Kinderbetreuungsgeld nach der Geburt verwechseln.", source: childcareFunding),
            .init("ams", "checkmark.seal", "Допомога AMS: до початку догляду", "AMS-Beihilfe: vor Betreuungsbeginn", "Якщо догляд потрібен через нову роботу, зміну робочого часу, погіршення фінансів або участь у заході AMS, домовтеся про консультацію з AMS до початку роботи чи заходу І до початку догляду. Запитайте про вікові та дохідні умови, потрібні рахунки й оплату саме догляду; харчування не входить. Рішення про виплату ухвалює AMS.", "Bei neuer Arbeit, geänderten Arbeitszeiten, schlechterer Finanzlage oder AMS-Maßnahme vor Arbeits- bzw. Maßnahmenbeginn UND vor Betreuungsbeginn einen AMS-Termin vereinbaren. Alters- und Einkommensgrenzen, Belege und förderfähige reine Betreuungskosten prüfen; Essen zählt nicht dazu. Über die Förderung entscheidet das AMS.", source: childcareFunding)
        ], sources: [childcare, dayParents, childcareFunding]
    )
}
