import Foundation

extension FamilyGuides {
    static let familyServices = DirectoryGuide(
        cardSummary: .init(ukrainian: "Захист прав дитини, Kinder- und Jugendhilfe та питання опіки", german: "Kinderrechte, Kinder- und Jugendhilfe und Obsorge"),
        introduction: .init(ukrainian: "Різні установи вирішують різні питання: консультації підтримують добровільно, Kinder- und Jugendhilfe організовує допомогу та захист, суд розглядає спори про опіку.", german: "Stellen haben unterschiedliche Aufgaben: Beratung unterstützt freiwillig, Kinder- und Jugendhilfe organisiert Hilfe und Schutz, Gerichte entscheiden Obsorgekonflikte."),
        sections: [
            .init("route", "list.bullet", "Оберіть відповідну установу", "Die passende Stelle wählen", "Для поради щодо виховання оберіть Familienberatung; для незалежної оцінки прав дитини — KiJA; для підтримки сім’ї чи повідомлення про загрозу дитині — Kinder- und Jugendhilfe. Спір щодо опіки й контактів вирішує суд. Запишіть, яка саме допомога потрібна, перш ніж звертатися.", "Für Erziehungsfragen Familienberatung, für unabhängige Kinderrechteberatung KiJA, für Familienhilfe oder Meldung einer Kindeswohlgefährdung Kinder- und Jugendhilfe wählen. Über Obsorge- und Kontaktstreit entscheidet das Gericht. Vor Kontakt das konkrete Anliegen notieren.", source: familyAdvice),
            .init("advocate", "person.text.rectangle", "Незалежний захист прав дитини", "Unabhängige Kinderrechteberatung", "У кожній землі працює Kinder- und Jugendanwaltschaft (KiJA). Дитина або дорослий може звернутися туди, коли права дитини не враховують у школі, установі чи родині. У державному переліку знайдіть контакт своєї землі, опишіть подію і попросіть пояснити наступний крок. Консультація безкоштовна й конфіденційна.", "In jedem Land gibt es eine Kinder- und Jugendanwaltschaft (KiJA). Kinder oder Erwachsene können sich melden, wenn Kinderrechte in Schule, Behörde oder Familie übergangen werden. Im amtlichen Verzeichnis Landeskontakt suchen, Ereignis schildern und nächsten Schritt erfragen. Die Beratung ist kostenlos und vertraulich.", source: childrenAdvocate),
            .init("support", "heart.text.square", "Підтримка від Kinder- und Jugendhilfe", "Hilfe durch Kinder- und Jugendhilfe", "Якщо сім’ї потрібна допомога у вихованні, догляді або подоланні кризи, зв’яжіться з Kinder- und Jugendhilfe свого округу чи Magistrat. Опишіть потребу й попросіть пояснити можливі форми підтримки. Сам факт звернення не означає автоматичного вилучення дитини; служба спочатку оцінює обставини й можливу допомогу сім’ї.", "Wenn die Familie Hilfe bei Erziehung, Betreuung oder einer Krise braucht, Kinder- und Jugendhilfe bei Bezirk oder Magistrat kontaktieren. Bedarf schildern und mögliche Hilfen erklären lassen. Eine Anfrage bedeutet keine automatische Abnahme des Kindes; die Stelle prüft die Lage und mögliche Unterstützung der Familie.", source: youthWelfare),
            .init("welfare", "hand.raised", "Повідомте про загрозу дитині", "Kindeswohlgefährdung melden", "Якщо є обґрунтована підозра на насильство, занедбання чи іншу загрозу, повідомте Kinder- und Jugendhilfe за місцем проживання дитини. Назвіть конкретні спостереження, коли вони сталися, терміновість і безпечний спосіб зв’язку. Служба перевіряє загрозу й визначає подальші заходи. При негайній небезпеці телефонуйте поліції 133; дитина може звернутися на 147.", "Bei begründetem Verdacht auf Gewalt, Vernachlässigung oder andere Gefährdung Kinder- und Jugendhilfe am Wohnort des Kindes informieren. Konkrete Beobachtungen, Zeitpunkt, Dringlichkeit und sicheren Rückruf nennen. Die Stelle prüft die Gefahr und weitere Schritte. Bei akuter Gefahr Polizei 133; Kinder können 147 anrufen.", phoneNumber: "133", source: youthProtection),
            .init("custody", "doc.text", "Опіка та контакт після розлуки", "Obsorge und Kontakt nach Trennung", "Збережіть судові рішення й письмові домовленості. Якщо згоди щодо опіки чи контакту немає, отримайте сімейну або юридичну консультацію та з’ясуйте, який суд компетентний. Повідомте суд про ризики насильства й просіть безпечну форму контакту для дитини. Рішення про опіку й контакт ухвалює суд.", "Gerichtsentscheidungen und schriftliche Absprachen aufbewahren. Bei Streit über Obsorge oder Kontakt Familien- bzw. Rechtsberatung einholen und das zuständige Gericht klären. Gewaltgefahren dem Gericht mitteilen und sichere Kontaktregelungen für das Kind ansprechen. Über Obsorge und Kontakt entscheidet das Gericht.", source: familyCourt),
            .init("court-help", "building.columns", "Роль Familiengerichtshilfe", "Rolle der Familiengerichtshilfe", "Familiengerichtshilfe діє лише за дорученням суду: може збирати інформацію, допомагати з врегулюванням спору й організацією контактів. Не подавайте туди звичайну заявку замість звернення до суду чи незалежної юридичної консультації. Запитайте суд, який саме етап і можливі витрати стосуються вашої справи.", "Die Familiengerichtshilfe wird nur im Gerichtsauftrag tätig: Sie kann Informationen erheben, bei Einigungen und Kontakten helfen. Sie ist keine allgemeine Antragsstelle und ersetzt keine unabhängige Rechtsberatung. Beim Gericht nach Verfahrensschritt und möglichen Kosten im eigenen Fall fragen.", source: familyCourt)
        ], sources: [familyAdvice, childrenAdvocate, youthWelfare, youthProtection, familyCourt]
    )
}
