import Foundation

enum FamilyGuides {
    private static let childcare = DirectorySource(name: "oesterreich.gv.at · Kinderbetreuung", url: "https://www.oesterreich.gv.at/de/themen/familie_und_partnerschaft/familie-und-kinderfuersorge/kinderbetreuung/2/Seite.370110")
    private static let childcareFunding = DirectorySource(name: "oesterreich.gv.at · Kinderbetreuungsbeihilfe", url: "https://www.oesterreich.gv.at/de/themen/familie_und_partnerschaft/familie-und-kinderfuersorge/kinderbetreuung/Seite.370300")
    private static let familyAdvice = DirectorySource(name: "oesterreich.gv.at · Familienberatungsstellen", url: "https://www.oesterreich.gv.at/de/themen/familie_und_partnerschaft/online_services_zu_familie_und_partnerschaft/Aktuelle-Apps")
    private static let familySearch = DirectorySource(name: "Bundeskanzleramt · Familienberatung", url: "https://www.familienberatung.gv.at/beratungsstellen/")
    private static let childHelp = DirectorySource(name: "Gesundheitsportal · Hilfe für Kinder und Jugendliche", url: "https://www.gesundheit.gv.at/service/beratungsstellen/gesund-leben/gesunde-lebenswelten/schulberatung.html")
    private static let childrenAdvocate = DirectorySource(name: "oesterreich.gv.at · Kinder- und Jugendanwaltschaften", url: "https://www.oesterreich.gv.at/de/themen/hilfe_und_finanzielle_unterstuetzung_erhalten/ombudsstellen_und_anwaltschaften/Seite.3240006")
    private static let familyCourt = DirectorySource(name: "Justiz · Familiengerichtshilfe", url: "https://www.justiz.gv.at/service/familienrecht/obsorge-und-kontaktrecht/familiengerichtshilfe.fed.de.html")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "childcare": childcareGuide
        case "parenting": parenting
        case "family-services": familyServices
        default: nil
        }
    }

    private static let childcareGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Ясла, садок, Hort, Tageseltern і допомога з оплатою", german: "Krippe, Kindergarten, Hort, Tageseltern und Kostenhilfe"),
        introduction: .init(ukrainian: "Оберіть догляд за віком дитини, робочим графіком і потребами сім’ї. Про запис і обов’язковий рік садка детально написано в категорії «Освіта».", german: "Wählen Sie Betreuung nach Alter, Arbeitszeiten und Familienbedarf. Anmeldung und Pflichtjahr stehen ausführlich unter „Bildung“."),
        sections: [
            .init("options", "figure.child", "Порівняйте варіанти", "Angebote vergleichen", "До трьох років зазвичай доступні Kinderkrippe або Tageseltern; старшим — Kindergarten, школярам — Hort чи цілоденна школа. Запитайте про реальний час відкриття, закриття на канікули, харчування, доступність для дитини з інвалідністю й правила відсутності через хворобу.", "Für Kinder unter drei kommen Krippe oder Tageseltern infrage, später Kindergarten, für Schulkinder Hort oder Ganztagsschule. Tatsächliche Öffnungszeiten, Ferien, Essen, Inklusion und Regeln bei Krankheit erfragen.", source: childcare),
            .init("search", "magnifyingglass", "Шукайте через громаду", "Über die Gemeinde suchen", "Попросіть Gemeinde/Magistrat перелік місць і строки заяв, паралельно спитайте приватні заклади. Не вважайте внесення до списку очікування гарантією місця. Якщо працюєте позмінно, попросіть одразу пояснити ранні, вечірні або канікулярні варіанти.", "Gemeinde/Magistrat nach Plätzen und Fristen fragen und private Einrichtungen parallel kontaktieren. Warteliste ist keine Platzzusage. Bei Schichtarbeit früh nach Randzeiten und Ferienbetreuung fragen.", source: childcare),
            .init("cost", "eurosign.circle", "Вартість та AMS-допомога", "Kosten und AMS-Beihilfe", "Порівняйте внесок, харчування й додаткові години; суми залежать від землі та установи. Якщо догляд потрібен для роботи чи курсу, запитайте AMS про Kinderbetreuungsbeihilfe ще до початку роботи, заходу й догляду: пізня заява може не покрити витрати. Земля може мати власні пільги.", "Beitrag, Essen und Zusatzstunden vergleichen; Kosten hängen von Land und Einrichtung ab. Für Arbeit oder Kurs AMS vor Arbeits-, Maßnahmen- und Betreuungsbeginn nach Kinderbetreuungsbeihilfe fragen: spätere Anträge können zu spät sein. Landeseigene Förderung prüfen.", source: childcareFunding)
        ], sources: [childcare, childcareFunding]
    )

    private static let parenting = DirectoryGuide(
        cardSummary: .init(ukrainian: "Безкоштовна розмова про виховання, стосунки та кризу в родині", german: "Kostenlose Beratung zu Erziehung, Beziehung und Familienkrisen"),
        introduction: .init(ukrainian: "По допомогу можна звернутися до того, як ситуація стане кризою. Державою підтримувані сімейні консультації безкоштовні й конфіденційні.", german: "Hilfe ist schon vor einer Krise möglich. Staatlich geförderte Familienberatung ist kostenlos und vertraulich."),
        sections: [
            .init("find", "person.2", "Знайдіть консультацію", "Beratung finden", "На державному порталі оберіть землю, тему й спосіб консультації. Запитайте про мову, участь другого з батьків, конфіденційність і можливість онлайн-розмови. На першу зустріч підготуйте короткий опис проблеми й питання, яких хочете торкнутися.", "Auf dem staatlichen Portal Bundesland, Thema und Beratungsform auswählen. Nach Sprache, Einbeziehung des anderen Elternteils, Vertraulichkeit und Online-Termin fragen. Für das Erstgespräch Anliegen und Fragen kurz notieren.", source: familySearch),
            .init("access", "phone", "Безкоштовно й анонімно", "Kostenlos und anonym", "Державою підтримувані Familienberatungsstellen консультують безкоштовно й анонімно. Знайдіть установу за землею та темою на familienberatung.gv.at. Якщо не знаєте, який вид підтримки потрібен, сімейна інформаційна лінія 0800 240 262 допоможе зорієнтуватися щодо федеральних сімейних послуг. Перед розмовою запитайте про доступну мову.", "Öffentlich geförderte Familienberatungsstellen beraten kostenlos und anonym. Stelle nach Bundesland und Thema auf familienberatung.gv.at suchen. Für Orientierung zu Bundes-Familienleistungen gibt es das Familienservice unter 0800 240 262. Vorher nach Beratungssprache fragen.", phoneNumber: "0800 240 262", source: familyAdvice),
            .init("child", "figure.child", "Якщо складно дитині", "Wenn das Kind belastet ist", "Запитайте дитину, з ким вона хоче говорити, та зверніться до педіатра, шкільної психології або відповідної консультації. Для дитини й підлітка доступна анонімна безкоштовна лінія 147. При безпосередній загрозі життю чи насильстві телефонуйте 144 або 133.", "Fragen Sie das Kind nach einer vertrauten Person und kontaktieren Sie Kinderarzt, Schulpsychologie oder Beratung. Kinder und Jugendliche erreichen anonym und kostenlos 147. Bei unmittelbarer Lebens- oder Gewaltgefahr 144 oder 133 wählen.", phoneNumber: "147", source: childHelp),
            .init("plan", "checklist", "Домовтеся про наступний крок", "Nächsten Schritt vereinbaren", "Попросіть консультанта сформулювати, яку допомогу можна отримати далі: батьківські зустрічі, психолог, медіація або соціальна служба. Якщо проблема пов’язана з насильством, не погоджуйтеся на спільну розмову без оцінки безпеки; зверніться до центру захисту в категорії «Безпека».", "Mit der Beratung nächste Schritte festlegen: Elternberatung, Psychologie, Mediation oder Sozialdienst. Bei Gewalt keine gemeinsame Aussprache ohne Sicherheitsklärung vereinbaren; nutzen Sie die Gewaltschutzhilfe unter „Sicherheit“.", source: familyAdvice)
        ], sources: [familySearch, familyAdvice, childHelp]
    )

    private static let familyServices = DirectoryGuide(
        cardSummary: .init(ukrainian: "Захист прав дитини, Kinder- und Jugendhilfe та питання опіки", german: "Kinderrechte, Kinder- und Jugendhilfe und Obsorge"),
        introduction: .init(ukrainian: "Різні установи вирішують різні питання: консультації підтримують добровільно, Kinder- und Jugendhilfe організовує допомогу та захист, суд розглядає спори про опіку.", german: "Stellen haben unterschiedliche Aufgaben: Beratung unterstützt freiwillig, Kinder- und Jugendhilfe organisiert Hilfe und Schutz, Gerichte entscheiden Obsorgekonflikte."),
        sections: [
            .init("advocate", "person.text.rectangle", "Незалежна допомога дитині", "Unabhängige Hilfe für Kinder", "У кожній землі є Kinder- und Jugendanwaltschaft (KiJA). Якщо дитина або батьки вважають, що права дитини не враховані у школі, установі чи родині, знайдіть контакт своєї KiJA в офіційному переліку й коротко опишіть ситуацію. Це інший шлях, ніж добровільна сімейна консультація або заявка на допомогу Kinder- und Jugendhilfe.", "In jedem Bundesland gibt es eine Kinder- und Jugendanwaltschaft (KiJA). Werden Kinderrechte in Schule, Behörde oder Familie übersehen, Kontakt der zuständigen KiJA aus dem amtlichen Verzeichnis wählen und Sachverhalt schildern. Dies unterscheidet sich von Familienberatung und einem Antrag bei der Kinder- und Jugendhilfe.", source: childrenAdvocate),
            .init("welfare", "hand.raised", "Якщо дитині потрібен захист", "Wenn ein Kind Schutz braucht", "Зверніться до Kinder- und Jugendhilfe місцевої Bezirksverwaltungsbehörde або Magistrat. Опишіть конкретні факти, безпечний спосіб зв’язку і терміновість. При безпосередній небезпеці — поліція 133; дитина може також самостійно зателефонувати 147. Місцева служба визначить форму підтримки з урахуванням інтересів дитини.", "Kontaktieren Sie Kinder- und Jugendhilfe bei Bezirksverwaltungsbehörde oder Magistrat. Konkrete Beobachtungen, sicheren Rückruf und Dringlichkeit nennen. Bei akuter Gefahr Polizei 133; das Kind kann selbst 147 anrufen. Die lokale Stelle prüft passende Hilfe im Kindeswohlinteresse.", source: childHelp),
            .init("custody", "doc.text", "Опіка та контакт після розлуки", "Obsorge und Kontakt nach Trennung", "Збережіть рішення суду та письмові домовленості про опіку й контакт. Якщо домовитися не вдається, отримайте юридичну консультацію до заяви в суд; Familiengerichtshilfe працює за дорученням суду, збирає інформацію та допомагає знайти рішення, але не замінює адвоката. При ризику насильства спочатку забезпечте безпеку дитини й повідомте про ризик суду.", "Gerichtsentscheidungen und schriftliche Absprachen zu Obsorge und Kontakt aufbewahren. Ohne Einigung vor Gerichtsantrag Rechtsberatung holen; die Familiengerichtshilfe arbeitet im Gerichtsauftrag, klärt den Sachverhalt und unterstützt Lösungen, ersetzt aber keine anwaltliche Vertretung. Bei Gewaltgefahr zuerst Kind schützen und Gericht informieren.", source: familyCourt)
        ], sources: [familyAdvice, familySearch, childHelp, childrenAdvocate, familyCourt]
    )
}
