import Foundation

extension FamilyGuides {
    static let parenting = DirectoryGuide(
        cardSummary: .init(ukrainian: "Безкоштовна розмова про виховання, стосунки та кризу в родині", german: "Kostenlose Beratung zu Erziehung, Beziehung und Familienkrisen"),
        introduction: .init(ukrainian: "По допомогу можна звернутися до того, як ситуація стане кризою. Державою підтримувані сімейні консультації безкоштовні й конфіденційні.", german: "Hilfe ist schon vor einer Krise möglich. Staatlich geförderte Familienberatung ist kostenlos und vertraulich."),
        sections: [
            .init("find", "person.2", "Оберіть консультацію за питанням", "Beratung nach Anliegen wählen", "На familienberatung.gv.at знайдіть установу за темою та місцем. Там можна обговорити виховання, конфлікти, розлуку, вагітність або сімейне навантаження. Попросіть запис, перевірте мову й чи можна прийти одному: участь обох батьків не є обов’язковою умовою звернення.", "Auf familienberatung.gv.at eine Stelle nach Thema und Ort suchen. Dort können Erziehung, Konflikte, Trennung, Schwangerschaft oder familiäre Belastung besprochen werden. Termin und Sprache klären; man kann auch allein anfragen, ohne beide Eltern gemeinsam vorzustellen.", source: familySearch),
            .init("confidential", "lock.shield", "Підготуйте безпечну розмову", "Vertrauliches Gespräch vorbereiten", "Підтримувана державою сімейна консультація безкоштовна й анонімна. Коротко запишіть ситуацію та питання, які хочете вирішити. Особисті документи й чутливі деталі не надсилайте на загальну електронну адресу установи: її сайт радить використовувати пошту для контакту й запису.", "Geförderte Familienberatung ist kostenlos und anonym. Anliegen und gewünschte Fragen kurz notieren. Persönliche Unterlagen und sensible Details nicht an die allgemeine E-Mail-Adresse der Stelle senden: Laut Portal dient sie der Kontaktaufnahme und Terminvereinbarung.", source: familyAdvice),
            .init("online", "video", "Якщо особистий візит складний", "Wenn ein Besuch schwierig ist", "Перевірте онлайн-консультацію на державному порталі: деякі установи проводять її в чаті або відео. Перед бронюванням з’ясуйте доступну мову, дату, приватне місце для розмови й технічні умови. Онлайн-запис не замінює екстрену допомогу.", "Onlineberatung auf dem staatlichen Portal prüfen: Manche Stellen bieten Chat oder Video an. Vor Buchung Sprache, Termin, einen privaten Gesprächsort und Technik klären. Online-Termine ersetzen keine Notfallhilfe.", source: onlineAdvice),
            .init("child", "figure.child", "Коли допомога потрібна дитині", "Wenn das Kind Hilfe braucht", "Запитайте дитину, з ким їй безпечно говорити. Окрім педіатра чи шкільної психології, дитина й підліток можуть самі анонімно та безкоштовно зателефонувати на Rat auf Draht 147; лінія працює цілодобово. При безпосередній небезпеці телефонуйте 133 або 144.", "Das Kind fragen, mit wem es sicher sprechen kann. Neben Kinderarzt oder Schulpsychologie können Kinder und Jugendliche selbst kostenlos und anonym Rat auf Draht 147 anrufen; die Hotline ist rund um die Uhr erreichbar. Bei akuter Gefahr 133 oder 144 wählen.", phoneNumber: "147", source: childHelp),
            .init("plan", "checklist", "Завершіть розмову планом", "Gespräch mit einem Plan abschließen", "Попросіть узгодити один наступний крок, відповідальну особу та дату повторного контакту. Якщо питання про федеральні сімейні виплати, Familienservice відповідає за номером 0800 240 262 у робочі години, але не веде терапію. За насильства не плануйте спільну зустріч без оцінки безпеки; використайте контакти категорії «Безпека».", "Einen nächsten Schritt, Ansprechperson und Zeitpunkt für Rückmeldung vereinbaren. Zu Familienleistungen des Bundes informiert das Familienservice unter 0800 240 262 zu Dienstzeiten; es ist keine Therapie. Bei Gewalt kein gemeinsames Gespräch ohne Sicherheitsklärung planen; Kontakte unter „Sicherheit“ nutzen.", phoneNumber: "0800 240 262", source: familyAdvice)
        ], sources: [familySearch, familyAdvice, onlineAdvice, childHelp]
    )
}
