import Foundation

extension HealthGuides {
    static let pregnancy = DirectoryGuide(
        cardSummary: .init(ukrainian: "Eltern-Kind-Pass, нові правила 2026, пологовий і акушерка", german: "Eltern-Kind-Pass, Neuerungen 2026, Geburtsort und Hebamme"),
        introduction: .init(ukrainian: "Зверніться до гінеколога або іншого уповноваженого лікаря невдовзі після підтвердження вагітності. Програма Eltern-Kind-Pass розширена з 1 жовтня 2026 року; для вже виданого паперового паспорта нові огляди фіксують у додатковому зошиті.", german: "Nach Bestätigung der Schwangerschaft früh eine Frauenarztpraxis oder andere zuständige Praxis kontaktieren. Seit 1. Oktober 2026 ist das Eltern-Kind-Pass-Programm erweitert; neue Untersuchungen zu einem vorhandenen Papierpass werden im Zusatzheft dokumentiert."),
        sections: [
            .init("start", "cross.case", "Перший прийом", "Erster Termin", "Запишіться на ранній огляд, назвіть дату останньої менструації, хронічні хвороби, ліки й попередні вагітності. Попросіть Eltern-Kind-Pass і графік оглядів. Перевірте, чи ординація проводить саме ці огляди та чи є касовий договір; не кожен лікар їх виконує.", "Vereinbaren Sie früh einen Termin und nennen Sie letzte Regelblutung, Vorerkrankungen, Medikamente und frühere Schwangerschaften. Bitten Sie um Eltern-Kind-Pass und Terminplan. Prüfen Sie, ob die Praxis diese Untersuchungen mit Kassenvertrag anbietet; nicht jede Praxis tut das.", source: pregnancyChecks),
            .init("uninsured", "checkmark.shield", "Якщо ще немає страхування", "Wenn noch keine Versicherung besteht", "Eltern-Kind-Pass доступний і незастрахованим жінкам із центром життя в Австрії. Перед безкоштовним оглядом у касового лікаря отримайте в ÖGK підтвердження права (Anspruchsbeleg). У приватного лікаря спочатку платите самі; каса може відшкодувати лише частину. Окремо з’ясуйте покриття пологів — право на безкоштовні огляди не замінює медичного страхування.", "Auch nicht versicherte Frauen mit Lebensmittelpunkt in Österreich können den Eltern-Kind-Pass erhalten. Vor kostenlosen Untersuchungen bei Vertragsärzten bei der ÖGK einen Anspruchsbeleg holen. In der Wahlarztpraxis zahlen Sie zunächst selbst; die Kasse erstattet gegebenenfalls nur einen Teil. Klären Sie die Geburtskosten gesondert: Der Untersuchungsanspruch ersetzt keine Krankenversicherung.", source: parentChildPass),
            .init("schedule", "calendar", "Терміни й дитячі виплати", "Fristen und Kinderbetreuungsgeld", "Для повного Kinderbetreuungsgeld важливі п’ять визначених оглядів під час вагітності у встановлені проміжки, а згодом перші п’ять дитячих оглядів. Нові додаткові консультації та УЗД з жовтня 2026 року не всі впливають на суму виплати. Перевірте персональні терміни в офіційному плані й попросіть записувати кожне обстеження в паперовий паспорт або Zusatzheft.", "Für volles Kinderbetreuungsgeld zählen fünf vorgeschriebene Schwangerschaftsuntersuchungen in bestimmten Zeitfenstern und später die ersten fünf Kindesuntersuchungen. Nicht alle seit Oktober 2026 zusätzlichen Beratungen und Ultraschalle sind dafür relevant. Prüfen Sie persönliche Fristen im amtlichen Plan und lassen Sie Untersuchungen in Papierpass oder Zusatzheft dokumentieren.", source: parentChildPass),
            .init("midwife", "person.2", "Акушерка та додаткова допомога", "Hebamme und weitere Betreuung", "Шукайте акушерку завчасно — місця можуть бути обмежені. Уточніть, чи має вона Kassenvertrag або працює як Wahlhebamme, які домашні візити після пологів покриває каса та за що потрібна доплата. Новий Eltern-Kind-Pass передбачає також консультації акушерки; запис і покриття перевіряйте до відвідування.", "Suchen Sie früh eine Hebamme; Kapazitäten können knapp sein. Fragen Sie nach Kassenvertrag oder Wahlhebamme, gedeckten Hausbesuchen nach der Geburt und Zusatzkosten. Der neue Eltern-Kind-Pass sieht auch Hebammenberatungen vor; Termin und Deckung vorher klären.", source: midwife),
            .init("birth", "building.2", "Виберіть місце пологів", "Geburtsort wählen", "Клініку з пологовим відділенням шукайте через Kliniksuche й реєструйтеся завчасно: терміни різняться. У Відні діє централізована система Geburtsinfo Wien. З’ясуйте покриття пологів, можливу оплату особистої акушерки та правила супроводу; при ризиковій вагітності обговоріть вибір лікарні з лікарем.", "Suchen Sie eine Klinik mit Geburtsabteilung über Kliniksuche und melden Sie sich früh an; Fristen unterscheiden sich. In Wien gibt es das zentrale System Geburtsinfo Wien. Klären Sie Deckung, Kosten einer Beleghebamme und Begleitung; bei Risikoschwangerschaft die Klinikwahl ärztlich besprechen.", source: birth),
            .init("urgent", "exclamationmark.triangle", "Якщо є гострі симптоми", "Bei akuten Beschwerden", "При сильній кровотечі, тяжкому раптовому болю або іншій безпосередній небезпеці телефонуйте 144. Для неекстрених сумнівів зв’яжіться з гінекологом, пологовим відділенням або 1450. Не покладайтеся на загальні статті для оцінки індивідуального ризику.", "Bei starker Blutung, plötzlich starken Schmerzen oder anderer unmittelbarer Gefahr 144 wählen. Bei nicht akuten Fragen Frauenarztpraxis, Geburtsabteilung oder 1450 kontaktieren. Allgemeine Artikel beurteilen kein individuelles Risiko.", phoneNumber: "144", source: hotline)
        ], sources: [parentChildPass, pregnancyChecks, midwife, birth, hotline]
    )

    static let childHealth = DirectoryGuide(
        cardSummary: .init(ukrainian: "Педіатр, Eltern-Kind-Pass, щеплення й допомога при хворобі дитини", german: "Kinderarzt, Eltern-Kind-Pass, Impfungen und Hilfe bei Krankheit"),
        introduction: .init(ukrainian: "Для дитини потрібен власний доступ до медичної допомоги. Підготуйте її страховий документ, попередні висновки й українську карту щеплень; відсутні записи обговоріть із лікарем.", german: "Kinder brauchen einen eigenen Zugang zur Versorgung. Bereiten Sie Versicherungsnachweis, Vorbefunde und ukrainischen Impfpass vor; fehlende Einträge ärztlich klären."),
        sections: [
            .init("doctor", "figure.child", "Знайдіть педіатра", "Kinderarzt finden", "У пошуку лікарів виберіть Kinder- und Jugendheilkunde, землю та місце. Запитайте, чи є місця, касовий договір і прийом при гострій хворобі. Частину оглядів може провести також лікар загальної медицини; якщо дитині зле й ви не знаєте, куди звернутися, телефонуйте 1450, при загрозі життю — 144.", "Suchen Sie Kinder- und Jugendheilkunde nach Land und Ort. Fragen Sie nach Aufnahme, Kassenvertrag und Akutterminen. Manche Untersuchungen kann auch eine Hausarztpraxis durchführen; bei Unsicherheit 1450, bei Lebensgefahr 144 anrufen.", source: doctorSearch),
            .init("pass", "book.closed", "Огляди Eltern-Kind-Pass", "Eltern-Kind-Pass-Untersuchungen", "Після народження в Eltern-Kind-Pass заплановані огляди до раннього дитинства. Перші п’ять дитячих оглядів у визначені терміни важливі для повного Kinderbetreuungsgeld. З 1 жовтня 2026 року діє розширена програма; для паперового паспорта може знадобитися Zusatzheft. Попросіть педіатра розписати дати й перевірити, що вже зроблено в Україні чи Австрії.", "Nach der Geburt sind Eltern-Kind-Pass-Untersuchungen bis ins frühe Kindesalter vorgesehen. Die ersten fünf in den vorgeschriebenen Zeitfenstern sind für volles Kinderbetreuungsgeld wichtig. Seit 1. Oktober 2026 gilt ein erweitertes Programm; zum Papierpass kann ein Zusatzheft nötig sein. Lassen Sie Termine und bereits in Ukraine oder Österreich erfolgte Untersuchungen prüfen.", source: childChecks),
            .init("vaccines", "syringe", "Карта щеплень", "Impfpass", "Покажіть лікарю наявну карту щеплень із датами й назвами препаратів. Лікар звірить її з чинним австрійським Impfplan і визначить, чи потрібне надолуження; самостійно не починайте схему з нуля. Для дітей, які живуть в Австрії, діє безкоштовна програма частини рекомендованих щеплень; інші можуть бути платними.", "Zeigen Sie vorhandene Impfnachweise mit Daten und Präparaten. Die Praxis gleicht sie mit dem aktuellen österreichischen Impfplan ab und klärt nötige Nachholimpfungen; nicht eigenständig von vorne beginnen. Für in Österreich lebende Kinder gibt es ein kostenloses Programm für bestimmte empfohlene Impfungen, andere können kostenpflichtig sein.", source: childVaccines),
            .init("sick", "thermometer", "Коли дитина захворіла", "Wenn das Kind krank ist", "Зателефонуйте педіатру та опишіть вік, симптоми, тривалість, температуру й пиття. Якщо ординація зачинена, зателефонуйте 1450; служба 141 призначена для чергової лікарської допомоги. Для хворої дитини до року офіційна сторінка служби 141 скеровує до найближчої дитячої амбулаторії, оскільки черговий лікар загальної практики може не мати потрібного обладнання. При безпосередній небезпеці — 144. Дозування ліків для дитини узгоджуйте з медичним фахівцем.", "Rufen Sie die Kinderarztpraxis an und nennen Sie Alter, Beschwerden, Dauer, Temperatur und Trinkmenge. Ist die Praxis geschlossen, hilft 1450 bei der Orientierung; 141 ist der ärztliche Bereitschaftsdienst. Für erkrankte Kinder unter einem Jahr verweist die amtliche 141-Seite an die nächste Kinderambulanz, weil dem hausärztlichen Bereitschaftsdienst nötige Geräte fehlen können. Bei unmittelbarer Gefahr 144 wählen. Arzneidosen für Kinder fachlich klären.", source: onCallDoctors)
        ], sources: [doctorSearch, childChecks, childVaccines, hotline, onCallDoctors]
    )
}
