import Foundation

extension HealthGuides {
    static let whereToGo = DirectoryGuide(
        cardSummary: .init(ukrainian: "144 у небезпеці, 1450 для орієнтації, сімейний лікар для планового лікування", german: "144 im Notfall, 1450 zur Orientierung, Hausarzt für planbare Hilfe"),
        introduction: .init(ukrainian: "Спочатку оцініть терміновість. Телефонна консультація не замінює екстрену допомогу й не встановлює діагноз.", german: "Klären Sie zuerst die Dringlichkeit. Telefonberatung ersetzt weder den Notruf noch eine Diagnose."),
        sections: [
            .init("emergency", "cross.case.fill", "Безпосередня небезпека — 144", "Akute Gefahr – 144", "При загрозі життю, тяжкій травмі або раптовому тяжкому стані викликайте рятувальну службу 144 або європейський номер 112. Назвіть точне місце, що сталося, кількість постраждалих і виконуйте вказівки диспетчера. Не чекайте відповіді від довідника чи 1450.", "Bei Lebensgefahr, schwerer Verletzung oder plötzlich schwerem Zustand wählen Sie 144 oder 112. Nennen Sie den genauen Ort, was geschehen ist und wie viele Personen betroffen sind; folgen Sie der Leitstelle. Warten Sie nicht auf eine Antwort aus dem Wegweiser oder von 1450.", phoneNumber: "144", source: hotline),
            .init("uncertain", "phone.arrow.up.right", "Не знаєте, куди йти — 1450", "Unsicher, wohin? 1450", "Для медичної проблеми без очевидної загрози життю телефонуйте 1450: служба працює цілодобово по всій Австрії та підкаже відповідний рівень допомоги. Підготуйте адресу, вік пацієнта, симптоми, початок скарг і відомості про ліки. Якщо стан різко погіршується — 144.", "Bei einem Gesundheitsproblem ohne offensichtliche Lebensgefahr hilft 1450 österreichweit rund um die Uhr, die passende Versorgung zu finden. Halten Sie Ort, Alter, Beschwerden, Beginn und Medikamente bereit. Verschlechtert sich der Zustand rasch, wählen Sie 144.", phoneNumber: "1450", source: hotline),
            .init("out-of-hours", "moon.stars", "Коли ординація зачинена", "Wenn die Ordination geschlossen ist", "Якщо потрібна лікарська допомога ввечері, у вихідні або свята, але це не загроза життю, спитайте 1450 або зверніться до чергової лікарської служби 141. Доступність і місцевий порядок уточнюйте телефоном; лікарняна невідкладна служба потрібна для станів, які не можуть чекати.", "Wenn abends, am Wochenende oder Feiertag ärztliche Hilfe nötig ist, aber keine Lebensgefahr besteht, fragen Sie 1450 oder den Ärztenotdienst 141. Erreichbarkeit und örtlichen Ablauf telefonisch prüfen; die Spitalsnotaufnahme ist für nicht aufschiebbare Fälle da.", phoneNumber: "141", source: hotline),
            .init("planned", "person.crop.rectangle", "Планова допомога", "Planbare Behandlung", "Для тривалих або повторюваних скарг запишіться до лікаря загальної медицини чи до Primärversorgungseinheit. Він або вона оцінить стан, лікування та потребу в спеціалісті. Перед прийомом перевірте страхування, касовий договір ординації та оплату; детальні кроки — в темі «Лікарі та прийом».", "Bei länger bestehenden oder wiederkehrenden Beschwerden vereinbaren Sie einen Termin bei einer Hausarztpraxis oder Primärversorgungseinheit. Dort werden Untersuchung, Behandlung und nötige Fachüberweisung geklärt. Prüfen Sie Versicherung, Kassenvertrag und Kosten; Details stehen unter „Ärzte & Termine“.", source: providerSearch)
        ], sources: [hotline, providerSearch]
    )

    static let doctors = DirectoryGuide(
        cardSummary: .init(ukrainian: "Як знайти Kassenarzt, записатися й не отримати несподіваний рахунок", german: "Kassenarzt finden, Termin buchen und überraschende Kosten vermeiden"),
        introduction: .init(ukrainian: "Hausarzt — зручна перша точка для більшості неекстрених проблем. Обирайте ординацію за спеціальністю, місцем і договором саме з вашим страховиком.", german: "Die Hausarztpraxis ist bei den meisten nicht dringenden Beschwerden der erste Weg. Wählen Sie nach Fachgebiet, Ort und Vertrag mit Ihrer Kasse."),
        sections: [
            .init("search", "magnifyingglass", "Знайдіть ординацію", "Ordination finden", "На офіційному порталі виберіть федеральну землю, спеціальність і місце. Перевірте на сайті або телефоном, чи приймають нових пацієнтів, чи потрібен запис, якою мовою можна спілкуватися та чи є безбар’єрний доступ. Актуальні години роботи уточнюйте безпосередньо в ординації.", "Wählen Sie im amtlichen Portal Bundesland, Fachgebiet und Ort. Fragen Sie nach freien Plätzen, Terminpflicht, Sprache und Barrierefreiheit. Aktuelle Öffnungszeiten direkt bei der Ordination bestätigen.", source: doctorSearch),
            .init("type", "eurosign.circle", "Kassenarzt, Wahlarzt чи Privatarzt?", "Kassen-, Wahl- oder Privatarzt?", "Kassenarzt із договором вашої каси розраховує покриті послуги напряму; окремі послуги або страховики можуть передбачати доплату. У Wahlarzt ви спершу платите весь рахунок і можете подати його на часткове відшкодування; це не 80% вашого рахунку, а зазвичай 80% касового тарифу. У Privatordination відшкодування може не бути. Попросіть письмово пояснити ціну до лікування.", "Ein Kassenarzt mit Vertrag Ihrer Kasse rechnet gedeckte Leistungen direkt ab; bei manchen Leistungen oder Kassen gibt es Selbstbehalte. Beim Wahlarzt zahlen Sie zuerst selbst und können teilweise Erstattung beantragen: grundsätzlich 80 % des Kassentarifs, nicht 80 % Ihrer Rechnung. In der Privatordination kann jede Erstattung entfallen. Lassen Sie Kosten vorab erklären.", source: doctorCosts),
            .init("prepare", "checklist", "Підготуйте прийом", "Termin vorbereiten", "Візьміть e-card або інше підтвердження страхування, документ особи, попередні висновки, перелік усіх ліків з дозами й алергій. Запишіть скарги, коли вони почалися та які питання хочете поставити. Якщо e-card ще немає, попросіть страхову підтвердити право на лікування й повідомте ординації номер соціального страхування або Ersatzbeleg.", "Bringen Sie e-card oder Versicherungsnachweis, Ausweis, Vorbefunde, alle Medikamente mit Dosierung und Allergien mit. Notieren Sie Beschwerden, Beginn und Fragen. Fehlt die e-card noch, lassen Sie den Anspruch von der Kasse bestätigen und teilen der Ordination Versicherungsnummer oder Ersatzbeleg mit.", source: ecard),
            .init("after", "doc.text", "Після прийому", "Nach dem Termin", "Уточніть діагноз, план лікування, коли чекати результатів і за яких ознак звертатися знову. Збережіть рецепт, направлення й висновок. Якщо прийом був платним, попросіть детальний рахунок і підтвердження оплати для заяви на відшкодування до своєї каси.", "Klären Sie Diagnose, Behandlungsplan, Befundtermin und Warnzeichen für erneuten Kontakt. Bewahren Sie Rezept, Zuweisung und Befund auf. Bei bezahlter Behandlung verlangen Sie eine detaillierte Honorarnote und Zahlungsbestätigung für die Einreichung bei Ihrer Kasse.", source: doctorCosts)
        ], sources: [doctorSearch, doctorCosts, ecard]
    )

    static let specialists = DirectoryGuide(
        cardSummary: .init(ukrainian: "Коли потрібне направлення, як пройти лабораторію, МРТ або вузького спеціаліста", german: "Überweisung, Labor, MRT und Facharzt richtig organisieren"),
        introduction: .init(ukrainian: "Не кожен візит до спеціаліста потребує направлення, але для багатьох досліджень і спеціальних амбулаторій воно потрібне. Уточнюйте вимоги перед записом.", german: "Nicht jeder Facharztbesuch braucht eine Überweisung, viele Untersuchungen und Spezialambulanzen aber schon. Klären Sie die Vorgaben vor der Buchung."),
        sections: [
            .init("first", "stethoscope", "Почніть із лікаря загальної медицини", "Bei der Hausarztpraxis beginnen", "Опишіть скарги й покажіть попередні висновки. Лікар може лікувати самостійно або видати Überweisung до спеціаліста, Zuweisung на конкретне дослідження чи Einweisung до лікарні. Запитайте, чи потрібне погодження страховика та де саме виконують дослідження за касовим договором.", "Schildern Sie Beschwerden und zeigen Sie Vorbefunde. Die Praxis behandelt selbst oder stellt eine Überweisung zum Facharzt, Zuweisung zu einer Untersuchung oder Einweisung ins Spital aus. Fragen Sie nach Kassenbewilligung und einer Vertragsstelle für die Untersuchung.", source: referral),
            .init("book", "calendar", "Запис і документи", "Termin und Unterlagen", "Під час запису назвіть вид направлення, страховика й потрібну послугу; перевірте, чи дійсне воно на дату прийому. Для окремих обстежень, зокрема КТ і МРТ, може діяти електронне погодження eKOS або інша процедура. Візьміть e-card, направлення, попередні знімки та результати аналізів.", "Nennen Sie bei der Buchung Zuweisungsart, Kasse und Leistung und prüfen Sie die Gültigkeit am Termin. Für einzelne Untersuchungen wie CT oder MRT kann eKOS oder ein anderes Bewilligungsverfahren gelten. Nehmen Sie e-card, Zuweisung, frühere Bilder und Laborbefunde mit.", source: referral),
            .init("cost", "eurosign.circle", "Перевірте оплату до обстеження", "Kosten vor der Untersuchung klären", "Запитайте, чи заклад має договір із вашою касою та чи покривається саме призначена послуга. У приватному центрі або в Wahlarzt спершу може знадобитися повна оплата, а відшкодування буде лише частковим або відсутнім. Для дорогого обстеження попросіть оцінку витрат заздалегідь.", "Fragen Sie, ob die Stelle einen Vertrag mit Ihrer Kasse hat und genau diese Leistung gedeckt ist. In Privatstellen oder beim Wahlarzt zahlen Sie möglicherweise zuerst voll; Erstattung kann teilweise oder gar nicht erfolgen. Fordern Sie vor teuren Untersuchungen eine Kostenauskunft an.", source: doctorCosts),
            .init("results", "doc.text.magnifyingglass", "Хто пояснить результат?", "Wer erklärt den Befund?", "З’ясуйте, коли і кому надійде висновок. Домовтеся про повторний прийом у лікаря, який направив, щоб отримати пояснення і план дій. Якщо нові симптоми стають гострими, не чекайте планового результату — 1450 або 144 залежно від стану.", "Klären Sie, wann und an wen der Befund geht. Vereinbaren Sie die Besprechung bei der zuweisenden Praxis, damit Ergebnis und nächste Schritte erklärt werden. Bei akuter Verschlechterung nicht auf den planbaren Befund warten: je nach Lage 1450 oder 144.", source: referral)
        ], sources: [referral, doctorCosts, hotline]
    )

    static let clinics = DirectoryGuide(
        cardSummary: .init(ukrainian: "Невідкладна служба, госпіталізація, вибір клініки та витрати", german: "Notaufnahme, Aufnahme, Klinikwahl und Kosten"),
        introduction: .init(ukrainian: "Лікарняна амбулаторія і стаціонар виконують різні завдання. Для планового лікування перевірте відділення, направлення та страховий статус до прибуття.", german: "Spitalsambulanz und stationäre Aufnahme haben unterschiedliche Aufgaben. Für geplante Behandlung prüfen Sie Abteilung, Einweisung und Versicherung vorab."),
        sections: [
            .init("emergency", "cross.case.fill", "Гострий стан", "Akuter Zustand", "Якщо є загроза життю, телефонуйте 144; диспетчер визначить допомогу й маршрут. Якщо терміновість незрозуміла, 1450 підкаже відповідний заклад. Не їдьте до довільної спеціалізованої амбулаторії без уточнення годин, якщо стан дозволяє подзвонити.", "Bei Lebensgefahr 144 wählen; die Leitstelle organisiert die passende Hilfe. Wenn die Dringlichkeit unklar ist, nennt 1450 eine Anlaufstelle. Bei planbarer Situation vor Fahrt zu einer Spezialambulanz Öffnungszeiten klären.", phoneNumber: "144", source: hotline),
            .init("planned", "building.2.crop.circle", "Планове обстеження чи операція", "Geplante Untersuchung oder Operation", "Через Kliniksuche знайдіть лікарню та потрібне відділення. Зателефонуйте в амбулаторію: чи потрібне направлення, як записатися, які висновки принести, чи є договір із вашим страховиком. Для стаціонарного лікування лікар зазвичай оформлює Einweisung.", "Suchen Sie über Kliniksuche das Spital und die Fachabteilung. Fragen Sie die Ambulanz nach Zuweisung, Termin, Vorbefunden und Vertrag mit Ihrer Kasse. Für stationäre Behandlung stellt die ärztliche Praxis in der Regel eine Einweisung aus.", source: clinicSearch),
            .init("documents", "checklist", "Що взяти із собою", "Was mitbringen?", "Візьміть документ особи, e-card або Ersatzbeleg, направлення, актуальний список ліків, алергій і попередні висновки. Для планової госпіталізації уточніть у клініки правила підготовки, прибуття й контактної особи; самостійно не припиняйте призначені ліки.", "Nehmen Sie Ausweis, e-card oder Ersatzbeleg, Einweisung, aktuelle Medikamente, Allergien und Vorbefunde mit. Bei geplanter Aufnahme fragen Sie nach Vorbereitung, Ankunft und Kontaktperson; verordnete Medikamente nicht eigenmächtig absetzen.", source: clinicSearch),
            .init("cost", "eurosign.circle", "Оплата і Sonderklasse", "Kosten und Sonderklasse", "За перебування в загальному класі застраховані можуть сплачувати добовий внесок; його розмір визначається землею та щорічно змінюється. Для дітей, пологів та окремих інших випадків є винятки. Sonderklasse, приватна клініка й проживання супроводжуючої особи можуть мати окремі витрати. Попросіть письмову інформацію у відділі розрахунків до планового прийому.", "In der allgemeinen Gebührenklasse kann für Versicherte ein täglicher Spitalskostenbeitrag anfallen; Höhe und Jahr hängen vom Land ab. Für Kinder, Geburt und weitere Fälle gibt es Ausnahmen. Sonderklasse, Privatspital und Begleitperson können extra kosten. Vor planbarer Aufnahme schriftlich bei der Verrechnung fragen.", source: hospitalCosts),
            .init("discharge", "doc.text", "Перед випискою", "Vor der Entlassung", "Попросіть Entlassungsbrief, список ліків із дозами, рекомендації щодо перев’язок чи терапії, дату контролю та номер для запитань. Домовтеся, хто продовжить лікування — сімейний лікар, спеціаліст або домашня медична служба.", "Bitten Sie um Entlassungsbrief, Medikationsliste mit Dosierung, Hinweise zu Wundversorgung oder Therapie, Kontrolltermin und Kontakt bei Fragen. Klären Sie, wer die Weiterbehandlung übernimmt: Hausarzt, Facharzt oder häuslicher Dienst.", source: clinicSearch)
        ], sources: [hotline, clinicSearch, hospitalCosts]
    )
}
