import Foundation

extension HealthGuides {
    static let dentalCare = DirectoryGuide(
        cardSummary: .init(ukrainian: "Касовий стоматолог, біль, пломби та кошторис перед дорогим лікуванням", german: "Kassenzahnarzt, Schmerzen, Füllungen und Kostenvoranschlag"),
        introduction: .init(ukrainian: "Покриття стоматології залежить від послуги та страховика. Складні роботи не варто погоджувати без плану лікування й письмової ціни.", german: "Die Deckung der Zahnbehandlung hängt von Leistung und Kasse ab. Größere Arbeiten erst nach Behandlungsplan und schriftlicher Kostenauskunft zusagen."),
        sections: [
            .init("find", "tooth", "Знайдіть стоматолога", "Zahnbehandlung finden", "Шукайте Vertragszahnarzt із договором саме вашої каси або Zahngesundheitszentrum ÖGK у своїй землі. При гострому болю телефонуйте в центр чи чергову службу; 1450 допоможе зорієнтуватися поза звичайним часом. З’ясуйте, чи приймають зараз і чи потрібен запис.", "Suchen Sie einen Vertragszahnarzt Ihrer Kasse oder ein ÖGK-Zahngesundheitszentrum im Bundesland. Bei akuten Schmerzen rufen Sie Zentrum oder Bereitschaftsdienst an; außerhalb der Öffnungszeiten hilft 1450 bei der Orientierung. Fragen Sie nach Aufnahme und Termin.", source: dental),
            .init("coverage", "eurosign.circle", "Що покриває каса", "Was die Kasse zahlt", "Базові договірні стоматологічні послуги можуть розраховуватися через e-card; матеріал пломби, протезування, імплантати й естетичні рішення мають окремі правила, внески або приватну оплату. Перед лікуванням попросіть назвати касовий варіант, доплату й альтернативи, а для великої роботи — Heil- und Kostenplan та можливе погодження страховика.", "Vertragliche Grundleistungen können über die e-card abgerechnet werden. Füllungsmaterial, Zahnersatz, Implantate und ästhetische Lösungen haben eigene Regeln, Selbstbehalte oder Privatkosten. Fragen Sie vorab nach Kassenvariante, Aufpreis und Alternativen; bei größeren Arbeiten nach Heil- und Kostenplan sowie nötiger Kassenbewilligung.", source: dental),
            .init("private", "doc.text", "Якщо лікування приватне", "Bei privater Behandlung", "Попросіть деталізований кошторис до початку, збережіть рахунок і підтвердження оплати. До оплати уточніть у своєї каси, чи можливе й у якому розмірі відшкодування. Не вважайте, що будь-який приватний рахунок автоматично відшкодовується.", "Lassen Sie sich vor Beginn einen detaillierten Kostenvoranschlag geben und bewahren Sie Rechnung und Zahlungsnachweis auf. Fragen Sie Ihre Kasse vorab, ob und in welcher Höhe eine Erstattung möglich ist. Eine Privatrechnung wird nicht automatisch ersetzt.", source: dental),
            .init("children", "figure.child", "Дитина й профілактика", "Kinder und Vorsorge", "Запишіть дитину на огляд і уточніть у касового стоматолога профілактику, лікування та можливі витрати на ортодонтію. Окремі дитячі програми й виплати залежать від віку та медичних критеріїв — перевіряйте до підписання приватної пропозиції.", "Vereinbaren Sie einen Kontrolltermin für Ihr Kind und klären Sie Vorsorge, Behandlung und mögliche Kosten einer Zahnregulierung. Kinderleistungen hängen von Alter und medizinischen Kriterien ab; vor einer Privatvereinbarung prüfen.", source: dental)
        ], sources: [dental, providerSearch, hotline]
    )

    static let medicines = DirectoryGuide(
        cardSummary: .init(ukrainian: "e-Rezept, чергова аптека, українські препарати та доплати", german: "e-Rezept, Notdienstapotheke, mitgebrachte Medikamente und Kosten"),
        introduction: .init(ukrainian: "Для рецептурних препаратів потрібен належний рецепт; назва, склад, сила дії та форма можуть відрізнятися від українських. Заміну узгоджуйте з лікарем або фармацевтом.", german: "Für rezeptpflichtige Arzneien brauchen Sie ein gültiges Rezept. Name, Wirkstoff, Stärke und Form können von ukrainischen Präparaten abweichen. Austausch mit Arzt oder Apotheke klären."),
        sections: [
            .init("pharmacy", "cross.vial", "Знайдіть аптеку й чергування", "Apotheke und Notdienst finden", "Через офіційний пошук знайдіть найближчу аптеку, нічну або святкову службу. Перед поїздкою перевірте години й наявність препарату телефоном. Якщо це медична невідкладна ситуація, телефонуйте 144; 1450 допоможе визначити, чи потрібен лікар.", "Über die amtliche Suche finden Sie die nächste Apotheke und Nacht- oder Feiertagsdienst. Öffnungszeiten und Verfügbarkeit vor der Fahrt telefonisch klären. Bei medizinischem Notfall 144 wählen; 1450 hilft bei der Frage, ob ärztliche Hilfe nötig ist.", source: pharmacySearch),
            .init("erecipe", "barcode", "Як отримати ліки за e-Rezept", "e-Rezept einlösen", "Після призначення лікарем у аптеці пред’явіть e-card, код рецепта або Rezept-ID. Якщо картки ще немає, попросіть у лікаря код чи роздруківку й уточніть у страховика право на касовий рецепт. Рецептурні ліки зазвичай відпускають лише за чинним рецептом; у винятковій невідкладній ситуації рішення про видачу найменшої упаковки без пред’явлення рецепта приймає фармацевт за встановленими правилами.", "Nach ärztlicher Verordnung legen Sie in der Apotheke e-card, Rezeptcode oder Rezept-ID vor. Ohne Karte bitten Sie die Ordination um Code oder Ausdruck und klären den Kassenanspruch. Rezeptpflichtige Mittel werden grundsätzlich nur mit gültigem Rezept abgegeben; in einem besonderen Notfall entscheidet die Apotheke nach den geltenden Regeln über die kleinste Packung ohne Rezeptvorlage.", source: prescription),
            .init("cost", "eurosign.circle", "Скільки коштує", "Was kostet es?", "За відшкодовуваний касовий препарат зазвичай сплачують Rezeptgebühr за упаковку; розмір змінюється щороку, можливе звільнення. Якщо препарат дешевший за збір або рецепт приватний, правила оплати інші. Запитайте аптеку про фактичну ціну до видачі та касу — про звільнення чи ліміт витрат.", "Für erstattungsfähige Kassenmedikamente fällt üblicherweise eine Rezeptgebühr je Packung an; die Höhe ändert sich jährlich, Befreiung ist möglich. Ist das Mittel günstiger oder das Rezept privat, gelten andere Kosten. Fragen Sie vor Abgabe nach dem Endpreis und bei der Kasse nach Befreiung oder Ausgabengrenze.", source: prescription),
            .init("ukraine", "pills", "Препарат із України або іншої країни", "Arznei aus der Ukraine oder einem anderen Land", "Принесіть лікарю оригінальну упаковку чи фото, назву діючої речовини, дозу та схему прийому. У державному реєстрі BASG можна перевірити австрійські препарати за Wirkstoff. Не змінюйте самі дозу й не припиняйте постійні ліки; інша торгова назва не доводить повну взаємозамінність.", "Zeigen Sie der Ärztin oder dem Arzt Packung oder Foto, Wirkstoff, Stärke und Einnahmeschema. Im BASG-Register lassen sich österreichische Präparate nach Wirkstoff suchen. Dosis nicht selbst ändern und Dauermedikamente nicht eigenmächtig absetzen; ein anderer Handelsname beweist keine vollständige Austauschbarkeit.", source: medicationRegister),
            .init("safety", "exclamationmark.shield", "Безпека ліків", "Arzneimittelsicherheit", "Повідомте лікаря і фармацевта про всі препарати, включно з безрецептурними, а також про алергії, вагітність чи годування грудьми. Вони перевірять взаємодії та застосування. Рецептурні препарати не замовляйте через інтернет: в Австрії їх онлайн-продаж заборонено.", "Nennen Sie Arzt und Apotheke alle Arzneien einschließlich rezeptfreier Mittel sowie Allergien, Schwangerschaft und Stillzeit. Wechselwirkungen und Anwendung prüfen lassen. Rezeptpflichtige Mittel nicht online bestellen: ihr Onlineverkauf ist in Österreich verboten.", source: onlinePharmacy)
        ], sources: [pharmacySearch, prescription, medicationRegister, eMedication, onlinePharmacy]
    )

    static let ongoingCare = DirectoryGuide(
        cardSummary: .init(ukrainian: "Безперервність ліків, план лікування, фізіотерапія та реабілітація", german: "Dauermedikamente, Behandlungsplan, Physiotherapie und Rehabilitation"),
        introduction: .init(ukrainian: "Якщо хвороба потребує регулярного лікування, важливо заздалегідь організувати лікаря, рецепти й контроль. Не чекайте, поки закінчиться запас ліків.", german: "Bei laufender Behandlung sollten Arztkontakt, Rezepte und Kontrollen früh organisiert werden. Warten Sie nicht, bis Dauermedikamente aufgebraucht sind."),
        sections: [
            .init("records", "doc.text", "Підготуйте історію хвороби", "Befunde vorbereiten", "Зберіть діагнози, виписки, результати аналізів, знімки, перелік ліків із діючими речовинами та дозами. Якщо документи українською, попросіть лікаря сказати, які саме частини потрібні в перекладі. Тримайте короткий перелік алергій і важливих станів при собі.", "Sammeln Sie Diagnosen, Entlassungsbriefe, Laborwerte, Bilder und Medikamente mit Wirkstoffen und Dosierung. Bei ukrainischen Unterlagen fragen Sie, welche Teile übersetzt werden müssen. Eine kurze Allergie- und Erkrankungsliste griffbereit halten.", source: eMedication),
            .init("plan", "calendar.badge.clock", "Складіть план з лікарем", "Mit der Praxis einen Plan erstellen", "Запишіться до лікаря загальної медицини, поясніть, коли закінчуються препарати, і разом визначте австрійський рецепт, потребу в спеціалісті та контрольні аналізи. Запитайте, хто відповідає за повторні рецепти й куди звертатися при погіршенні; для складного лікування попросіть письмовий план.", "Vereinbaren Sie einen Hausarzttermin, nennen Sie das Ende Ihres Medikamentenvorrats und klären Sie österreichische Rezepte, Facharztbedarf und Kontrollwerte. Fragen Sie nach Folgerezepten und Kontakt bei Verschlechterung; bei komplexer Therapie um einen schriftlichen Plan bitten.", source: prescription),
            .init("therapy", "figure.walk", "Фізіотерапія й інші терапії", "Physiotherapie und weitere Therapien", "Для відшкодування фізіотерапії зазвичай потрібне лікарське призначення; залежно від каси може знадобитися попереднє погодження. Дізнайтеся, чи терапевт має касовий договір, скільки сеансів призначено, чи є власний внесок і як подавати приватний рахунок. Без призначення лікування може бути повністю приватним.", "Für Erstattung von Physiotherapie ist meist eine ärztliche Verordnung nötig; je nach Kasse kann vorab eine Bewilligung nötig sein. Fragen Sie nach Kassenvertrag, Anzahl der Einheiten, Selbstbehalt und Einreichung einer Wahltherapie. Ohne Verordnung kann die Leistung vollständig privat sein.", source: physiotherapy),
            .init("hospital", "building.2", "Після лікарні або переїзду", "Nach Spital oder Umzug", "Попросіть виписку з остаточним списком ліків, термінами контролю й направленнями. Запишіться до наступного лікаря завчасно; якщо переїхали, передайте копії висновків новій ординації. При втраті страхування негайно уточніть покриття в касі чи відповідальному органі — старий рецепт не доводить чинного права на оплату.", "Bitten Sie um Entlassungsbrief mit aktueller Medikation, Kontrollfristen und Zuweisungen. Vereinbaren Sie den Folgetermin früh; nach Umzug Kopien an die neue Praxis geben. Bei Wegfall der Versicherung den Anspruch sofort mit Kasse oder zuständiger Stelle klären – ein altes Rezept beweist keinen aktuellen Kostenanspruch.", source: ecard)
        ], sources: [eMedication, prescription, physiotherapy, ecard]
    )
}
