import Foundation

extension HealthGuides {
    static let prevention = DirectoryGuide(
        cardSummary: .init(ukrainian: "Безкоштовний Gesundheits-Check від 18 років і план щеплень", german: "Kostenloser Gesundheits-Check ab 18 und aktueller Impfplan"),
        introduction: .init(ukrainian: "Профілактика корисна навіть без скарг. Конкретні обстеження й щеплення залежать від віку, стану здоров’я та чинних державних програм.", german: "Vorsorge ist auch ohne Beschwerden sinnvoll. Untersuchungen und Impfungen hängen von Alter, Gesundheitslage und aktuellen öffentlichen Programmen ab."),
        sections: [
            .init("screening", "heart.text.square", "Щорічний Gesundheits-Check", "Jährlicher Gesundheits-Check", "Особи від 18 років із місцем проживання в Австрії можуть раз на рік пройти безкоштовну Vorsorgeuntersuchung. Знайдіть ординацію з договором на цю програму й запишіться. Якщо немає медичного страхування, уточніть у земельному відділенні ÖGK Ersatzkrankenschein саме для профілактичного огляду; це не загальна страховка.", "Personen ab 18 mit Wohnsitz in Österreich können einmal jährlich kostenlos zur Vorsorgeuntersuchung. Suchen Sie eine Praxis mit entsprechendem Vertrag und vereinbaren Sie einen Termin. Ohne Krankenversicherung fragen Sie bei der ÖGK-Landesstelle nach einem Ersatzkrankenschein nur für diese Untersuchung; das ist keine allgemeine Versicherung.", source: screening),
            .init("bring", "checklist", "Що взяти й що запитати", "Vorbereitung und Nachbesprechung", "Візьміть e-card або Ersatzkrankenschein, попередні висновки й список ліків. Попросіть пояснити результати, особисті ризики й дату наступного контролю. Додаткові аналізи поза програмою можуть оплачуватися окремо — уточніть це до проведення.", "Bringen Sie e-card oder Ersatzkrankenschein, Vorbefunde und Medikamentenliste mit. Lassen Sie Ergebnisse, persönliche Risiken und nächsten Kontrolltermin erklären. Zusätzliche Tests außerhalb des Programms können kostenpflichtig sein; vorher fragen.", source: screening),
            .init("vaccines", "syringe", "Перевірте щеплення", "Impfungen prüfen", "Покажіть лікарю австрійську й українську карти щеплень; разом звірте записи з чинним Impfplan Österreich. Попросіть особистий план надолуження, якщо записи неповні. Які вакцини безкоштовні, залежить від віку, програми й часу; перевірте перед записом, а не покладайтеся на торішні ціни.", "Zeigen Sie österreichische und ukrainische Impfnachweise und vergleichen Sie sie mit dem aktuellen Impfplan Österreich. Lassen Sie bei Lücken einen persönlichen Nachholplan erstellen. Kostenfreiheit hängt von Alter, Programm und Zeitpunkt ab; vor der Buchung prüfen statt alte Preise anzunehmen.", source: vaccines),
            .init("follow", "calendar", "Скринінг за віком і ризиком", "Screening nach Alter und Risiko", "Під час профілактичного огляду спитайте про рекомендовані програми раннього виявлення для вашого віку та ризиків. Не записуйтеся на платні «пакети» без розуміння користі, можливих хибнопозитивних результатів і покриття касою. При симптомах потрібна діагностика, а не очікування наступного профілактичного огляду.", "Fragen Sie beim Gesundheits-Check nach empfohlenen Früherkennungsprogrammen für Alter und Risikoprofil. Buchen Sie keine privaten Pakete ohne Kenntnis von Nutzen, möglichen Fehlbefunden und Kassendeckung. Bei Beschwerden ist Diagnostik nötig, nicht das Warten auf die nächste Vorsorge.", source: screening)
        ], sources: [screening, vaccines, childVaccines]
    )

    static let rights = DirectoryGuide(
        cardSummary: .init(ukrainian: "Згода на лікування, доступ до висновків, рахунки та незалежна скарга", german: "Einwilligung, Befunde, Rechnungen und unabhängige Beschwerde"),
        introduction: .init(ukrainian: "Пацієнт має право зрозуміти запропоноване лікування й витрати. Скарга на медичний заклад — окрема від повідомлення про неточність у цьому довіднику.", german: "Patientinnen und Patienten dürfen Behandlung und Kosten verstehen. Eine Beschwerde über eine Gesundheitseinrichtung ist etwas anderes als die Meldung eines Fehlers in diesem Wegweiser."),
        sections: [
            .init("explain", "text.bubble", "Пояснення й згода", "Aufklärung und Einwilligung", "До планового втручання попросіть пояснити діагноз, мету, ризики, альтернативи, наслідки відмови й очікувані витрати зрозумілою вам мовою. Якщо не розумієте пояснення, скажіть про це до підпису й запитайте про мовну підтримку. У невідкладних ситуаціях можливі винятки з порядку отримання згоди.", "Vor einem planbaren Eingriff lassen Sie Diagnose, Ziel, Risiken, Alternativen, Folgen des Verzichts und voraussichtliche Kosten verständlich erklären. Wenn Sie etwas nicht verstehen, sagen Sie es vor der Unterschrift und fragen Sie nach Sprachhilfe. In Notfällen kann es Ausnahmen beim Einwilligungsverfahren geben.", source: patientRights),
            .init("records", "doc.text.magnifyingglass", "Висновки й медична документація", "Befunde und Dokumentation", "Попросіть копію висновку, виписки та плану лікування. Ви маєте право ознайомитися зі своєю медичною документацією; за копії можуть стягувати витрати. Перевірте правильність імені, дати народження, препаратів та алергій і повідомте про помилки лікувальній установі.", "Bitten Sie um Befund, Entlassungsbrief und Behandlungsplan. Sie dürfen Ihre medizinische Dokumentation einsehen; für Kopien können Kosten entstehen. Prüfen Sie Name, Geburtsdatum, Medikamente und Allergien und melden Sie Fehler der behandelnden Stelle.", source: patientRights),
            .init("bill", "eurosign.circle", "Незрозумілий рахунок", "Unklare Rechnung", "Попросіть деталізований рахунок і пояснення, чи це касова послуга, власний внесок або приватне лікування. Збережіть направлення, рахунки й листування; за потреби зверніться до своєї каси. Платні додаткові послуги мають бути зрозумілими до їх надання, якщо ситуація дозволяє.", "Verlangen Sie eine detaillierte Rechnung und Erklärung, ob es Kassenleistung, Selbstbehalt oder Privatbehandlung war. Bewahren Sie Zuweisung, Belege und Schriftverkehr auf und fragen Sie nötigenfalls Ihre Kasse. Kostenpflichtige Zusatzleistungen sollten vorab verständlich sein, soweit die Situation dies erlaubt.", source: patientRights),
            .init("complaint", "person.crop.rectangle", "Куди подати скаргу", "Beschwerde einreichen", "Спершу письмово опишіть проблему закладу: дата, відділення, подія та бажане вирішення. Якщо питання не вирішене, зверніться до безкоштовної незалежної Patientenanwaltschaft тієї землі, де розташована установа, а не обов’язково вашого місця проживання. Повноваження щодо приватних лікарів різняться за землями; перевірте їх у списку.", "Schildern Sie das Problem zunächst schriftlich der Einrichtung: Datum, Abteilung, Ereignis und gewünschte Lösung. Bleibt es offen, wenden Sie sich an die kostenlose unabhängige Patientenanwaltschaft des Landes, in dem die Einrichtung liegt – nicht zwingend Ihres Wohnsitzes. Zuständigkeit für niedergelassene Ärzte unterscheidet sich je Land; Liste prüfen.", source: patientAdvocacy),
            .init("limits", "exclamationmark.circle", "Якщо є підозра на шкоду", "Bei vermutetem Schaden", "Збережіть документи та хронологію, не змінюючи оригінали. Patientenanwaltschaft може допомогти із позасудовим з’ясуванням і посередництвом, але не представляє вас у суді. Строки та можливе відшкодування залежать від конкретної справи — за потреби отримайте індивідуальну правову консультацію.", "Bewahren Sie Unterlagen und Chronologie auf, ohne Originale zu verändern. Die Patientenanwaltschaft hilft bei außergerichtlicher Klärung und Vermittlung, vertritt aber nicht vor Gericht. Fristen und Ansprüche hängen vom Einzelfall ab; nötigenfalls individuelle Rechtsberatung einholen.", source: patientAdvocacy)
        ], sources: [patientRights, patientAdvocacy]
    )
}
