import Foundation

extension HousingGuides {
    static let social = DirectoryGuide(
        cardSummary: .init(ukrainian: "Gemeindewohnung, Genossenschaft і Wohn-Ticket", german: "Gemeindewohnung, Genossenschaft und Wohn-Ticket"),
        introduction: .init(ukrainian: "Доступне й соціальне житло організоване землями та громадами по-різному. Право на тимчасовий захист саме по собі не гарантує комунальну квартиру.", german: "Leistbares und gefördertes Wohnen ist je nach Land und Gemeinde anders organisiert. Vorübergehender Schutz allein garantiert keine Gemeindewohnung."),
        sections: [
            .init("types", "building.2", "Порівняйте муніципальне й кооперативне", "Gemeinde- und Genossenschaftswohnung vergleichen", "Муніципальне житло розподіляє громада за її умовами. Genossenschaftswohnung здає некомерційна житлова організація; може бути початковий Finanzierungsbeitrag. Уточніть до заяви вимоги щодо доходу, статусу, попереднього проживання й суми внеску. Для внеску запитайте письмовий розрахунок повернення: це не звичайна Kaution.", "Gemeindewohnungen vergibt die Gemeinde nach ihren Regeln. Genossenschaftswohnungen vermietet eine gemeinnützige Bauvereinigung; oft fällt ein Finanzierungsbeitrag an. Klären Sie vor Bewerbung Einkommen, Status, bisherige Wohnzeit und Beitrag. Lassen Sie sich dessen Rückzahlung schriftlich berechnen: Er ist keine gewöhnliche Kaution.", source: socialHousing),
            .init("vienna", "mappin", "Приклад: Відень", "Beispiel Wien", "Wohnberatung Wien веде Wiener Wohn-Ticket для Gemeindewohnungen і geförderte Wohnungen. Умови включають проживання й інші критерії, а система розподілу змінювалася у 2026 році. Перевіряйте чинні умови онлайн; для інших земель використовуйте місцевий орган, який показано нижче.", "Die Wohnberatung Wien vergibt das Wiener Wohn-Ticket für Gemeinde- und geförderte Wohnungen. Voraussetzungen umfassen Wohnsitz und weitere Kriterien; das Vergabesystem änderte sich 2026. Prüfen Sie aktuelle Regeln online; in anderen Ländern nutzen Sie die unten angezeigte Landesstelle.", source: viennaHousing),
            .init("apply", "checklist", "Перед заявою", "Vor der Bewerbung", "Зберіть документи всіх мешканців, підтвердження статусу, доходів, Hauptwohnsitz і нинішнього житла. Знайдіть програму саме свого міста або землі в регіональному блоці нижче. Не сплачуйте посереднику за обіцянку «місця в черзі»; офіційний орган повідомить про реальний порядок подання.", "Sammeln Sie Ausweise aller Bewohner, Nachweise zu Status, Einkommen, Hauptwohnsitz und bisheriger Unterkunft. Suchen Sie das Programm Ihrer Gemeinde oder Ihres Landes im Regionalteil unten. Zahlen Sie keinem Vermittler für einen angeblichen Wartelistenplatz; die zuständige Stelle erklärt den tatsächlichen Bewerbungsweg.", source: housingAidNational)
        ], sources: [socialHousing, viennaHousing, housingAidNational]
    )

    static let support = DirectoryGuide(
        cardSummary: .init(ukrainian: "Wohnbeihilfe, Grundversorgung і захист від втрати житла", german: "Wohnbeihilfe, Grundversorgung und Schutz vor Wohnungsverlust"),
        introduction: .init(ukrainian: "Допомога залежить від землі, доходів, статусу та типу житла. Немає одного австрійського розміру Wohnbeihilfe для всіх.", german: "Unterstützung hängt von Bundesland, Einkommen, Status und Wohnform ab. Es gibt keine einheitliche österreichweite Wohnbeihilfe für alle."),
        sections: [
            .init("land", "building.columns", "Земельна Wohnbeihilfe", "Wohnbeihilfe des Landes", "Перевірте в землі проживання, чи ваш статус і дохід дають право на Wohnbeihilfe, які типи договорів приймають і чи є ліміт площі або оренди. Не закладайте майбутню виплату в бюджет, доки не отримаєте рішення. Офіційне посилання саме вашої землі є в регіональному блоці нижче; у Відні, наприклад, не подають заяву наперед за майбутню квартиру.", "Prüfen Sie im Wohnbundesland, ob Status und Einkommen zur Wohnbeihilfe berechtigen, welche Verträge gelten und ob Fläche oder Miete begrenzt sind. Rechnen Sie eine künftige Leistung erst nach Bewilligung fest ein. Der amtliche Landeslink steht unten; in Wien kann man beispielsweise nicht im Voraus für eine künftige Wohnung beantragen.", source: housingAidNational),
            .init("protection", "person.crop.rectangle", "Grundversorgung для переселенців", "Grundversorgung für Vertriebene", "Якщо ви отримуєте Grundversorgung, окремо уточніть у її земельного органу допомогу на приватну оренду та сумісність з іншими виплатами. Не припускайте, що повна сума нового договору буде компенсована або що різні види допомоги можна додавати без перевірки.", "Beziehen Sie Grundversorgung, klären Sie bei der Landesstelle Mietunterstützung für Privatunterkunft und Kombination mit anderen Leistungen. Gehen Sie weder von voller Übernahme einer neuen Miete noch von frei kombinierbaren Beihilfen aus.", source: basic),
            .init("crisis", "lifepreserver", "Борги або загроза виселення", "Schulden oder drohende Räumung", "WOHNSCHIRM MIETE перевіряє допомогу з боргами за основне житло; WOHNSCHIRM ENERGIE — із загрозою відключення, Housing First — при бездомності. Консультація й подання заяви безкоштовні. Візьміть договір, листи про борг та підтвердження доходів і зверніться якомога раніше, навіть якщо вже отримали судовий лист.", "WOHNSCHIRM MIETE prüft Mietschulden am Hauptwohnsitz, ENERGIE drohende Abschaltung und Housing First Wohnungslosigkeit. Beratung und Antrag sind kostenlos. Bringen Sie Vertrag, Mahnungen und Einkommensnachweise mit und melden Sie sich so früh wie möglich, auch wenn bereits Gerichtspost eingetroffen ist.", source: housingHelp)
        ], sources: [housingAidNational, basic, housingHelp]
    )

    static let move = DirectoryGuide(
        cardSummary: .init(ukrainian: "Лічильники, електрика, газ, пошта та страхування", german: "Zähler, Strom, Gas, Post und Versicherung"),
        introduction: .init(ukrainian: "Це житловий список справ до й після переїзду. Реєстрацію нової адреси та повідомлення BFA окремо пояснено в категорії «Реєстрація».", german: "Diese Liste betrifft die Wohnung vor und nach dem Umzug. Wohnsitzmeldung und BFA-Mitteilung stehen ausführlich im Bereich „Anmeldung“."),
        sections: [
            .init("before", "calendar", "До дати переїзду", "Vor dem Umzugstermin", "Домовтеся про передачу обох квартир і прочитайте договори електрики, газу, інтернету й опалення: хто повідомляє постачальника та який строк розірвання. Повідомте страхову компанію про переїзд і за потреби оформіть переадресацію пошти. Збережіть підтвердження всіх заяв, щоб уникнути оплати після виїзду.", "Vereinbaren Sie beide Wohnungsübergaben und prüfen Sie Strom-, Gas-, Internet- und Wärmeverträge: Wer meldet den Wechsel und welche Kündigungsfrist gilt? Informieren Sie die Haushaltsversicherung und richten Sie bei Bedarf Postnachsendung ein. Bewahren Sie Bestätigungen auf, damit nach dem Auszug keine unnötigen Kosten weiterlaufen.", source: beforeMove),
            .init("meters", "bolt.fill", "У день передачі: показники", "Am Übergabetag: Zählerstände", "Запишіть і сфотографуйте показники електрики, газу, води й опалення у старому та новому житлі разом із датою й номерами лічильників. Передайте їх відповідному оператору чи постачальнику та збережіть копії: це відділяє ваше споживання від попереднього і наступного мешканця.", "Fotografieren und notieren Sie Strom-, Gas-, Wasser- und Wärmezähler in alter und neuer Wohnung mit Datum und Zählernummer. Übermitteln Sie die Werte dem zuständigen Netzbetreiber oder Versorger und behalten Sie Kopien: So wird Ihr Verbrauch von dem anderer Bewohner abgegrenzt.", source: energyMove),
            .init("new", "house.fill", "У новому житлі", "In der neuen Wohnung", "Переконайтеся, що постачання електрики й газу оформлене на правильну особу та адресу; для цього можуть знадобитися Zählpunktbezeichnung і договір із оператором мережі. Перевірте перший рахунок, авансовий платіж і страхове покриття квартири. Нову адресу зареєструйте окремо за правилами Meldezettel.", "Prüfen Sie, ob Strom und Gas auf die richtige Person und Adresse angemeldet sind; dafür können Zählpunktbezeichnung und Netzzugangsvertrag nötig sein. Kontrollieren Sie erste Rechnung, Teilbetrag und Versicherungsschutz. Melden Sie die neue Wohnadresse gesondert nach den Regeln zum Meldezettel.", source: energyMove)
        ], sources: [beforeMove, energyMove, afterMove]
    )
}
