import Foundation

extension HousingGuides {
    static let contract = DirectoryGuide(
        cardSummary: .init(ukrainian: "Mietanbot, строк, MRG та ключові пункти договору", german: "Mietanbot, Dauer, MRG und wichtige Vertragsklauseln"),
        introduction: .init(ukrainian: "В австрійській оренді правила залежать від типу будинку та сфери дії Mietrechtsgesetz (MRG). Просіть письмовий договір зрозумілою вам мовою до оплати.", german: "Im österreichischen Mietrecht hängt vieles vom Gebäude und der Geltung des Mietrechtsgesetzes (MRG) ab. Lassen Sie sich vor Zahlung einen verständlichen schriftlichen Vertrag geben."),
        sections: [
            .init("terms", "doc.text", "Що має бути зрозуміло", "Was klar geregelt sein muss", "Адреса й площа, сторони, початок, строк і розірвання, Hauptmietzins, Betriebskosten, опалення, електрика, індексація, застава, меблі, стан квартири та правила піднайму. Перевірте, чи оплата є Pauschalmiete чи окремими позиціями. Зберігайте підписану копію й додатки.", "Adresse und Fläche, Parteien, Beginn, Dauer und Kündigung, Hauptmietzins, Betriebskosten, Heizung, Strom, Wertsicherung, Kaution, Möbel, Zustand und Untermiete. Prüfen Sie Pauschalmiete oder Einzelpositionen. Bewahren Sie unterschriebene Kopie und Anlagen auf.", source: akContract),
            .init("term", "calendar", "Обмежений строк із 2026 року", "Befristung seit 2026", "Для багатьох квартир у багатоквартирних будинках мінімальний строк договору — 5 років, якщо орендодавець є підприємцем, або 3 роки, якщо він приватна особа. Після першого року наймач у відповідній сфері MRG може достроково розірвати договір із тримісячним попередженням. Для одно- й двосімейних будинків та інших винятків правила інші — перевірте тип об’єкта.", "Bei vielen Wohnungen im Mehrparteienhaus beträgt die Mindestbefristung 5 Jahre bei unternehmerischer Vermieterseite bzw. 3 Jahre bei privater Vermieterseite. Nach dem ersten Jahr kann die mietende Person im einschlägigen MRG-Bereich mit 3 Monaten Frist vorzeitig kündigen. Für Ein- und Zweifamilienhäuser und Ausnahmen gelten andere Regeln; prüfen Sie das Objekt.", source: akContract),
            .init("offer", "pencil", "Заява про оренду — не бронь", "Mietanbot ist keine Reservierung", "Mietanbot може зобов’язувати ще до підписання повного договору. Якщо власник прийме його, договір уже може бути укладений за основними умовами. Не підписуйте кілька паралельно й не передавайте «завдаток» без ясного документа про мету платежу.", "Ein Mietanbot kann schon vor dem ausführlichen Vertrag binden. Nimmt die Vermieterseite es an, kann der Vertrag zu den wesentlichen Punkten bereits bestehen. Unterzeichnen Sie nicht mehrere gleichzeitig und zahlen Sie keine „Anzahlung“ ohne klare schriftliche Zweckangabe.", source: akOffer)
        ], sources: [akContract, akOffer, akRent]
    )

    static let rentCosts = DirectoryGuide(
        cardSummary: .init(ukrainian: "Реальна місячна сума, Betriebskosten і підвищення", german: "Gesamtkosten, Betriebskosten und Erhöhungen"),
        introduction: .init(ukrainian: "Ціна в оголошенні може не охоплювати всі платежі. Розрахуйте бюджет до підписання.", german: "Der Inseratspreis enthält nicht zwingend alle Zahlungen. Rechnen Sie vor Unterschrift das Gesamtbudget."),
        sections: [
            .init("monthly", "eurosign.circle", "Повна вартість на місяць", "Monatliche Gesamtkosten", "Окремо запитайте про Hauptmietzins, Betriebskosten, опалення/гарячу воду, електрику/газ, інтернет, паркомісце й меблі. Дізнайтеся, хто укладає договори з постачальниками та чи є авансові платежі з річним перерахунком. Порівнюйте квартири за повною сумою, а не лише Nettomiete.", "Fragen Sie getrennt nach Hauptmietzins, Betriebskosten, Heizung/Warmwasser, Strom/Gas, Internet, Parkplatz und Möbeln. Klären Sie Verträge mit Versorgern und Vorauszahlungen mit Jahresabrechnung. Vergleichen Sie Gesamtkosten statt nur Nettomiete.", source: costs),
            .init("billing", "receipt", "Betriebskostenabrechnung", "Betriebskostenabrechnung", "Зберігайте щомісячні платежі й перевіряйте річний розрахунок експлуатаційних витрат. Які позиції можна перекласти на орендаря, залежить від MRG та чинної угоди. Попросіть детальну розбивку й документи, якщо сума незрозуміла; Arbeiterkammer допомагає перевірити.", "Bewahren Sie Monatszahlungen auf und prüfen Sie die jährliche Betriebskostenabrechnung. Welche Positionen umgelegt werden dürfen, hängt von MRG und wirksamer Vereinbarung ab. Verlangen Sie bei Unklarheit eine Aufschlüsselung und Belege; die Arbeiterkammer hilft bei der Prüfung.", source: DirectorySource(name: "AK Wien · Betriebskosten prüfen", url: "https://wien.arbeiterkammer.at/beratung/Wohnen/miete/Betriebskosten-pruefen-als-Mieter-in.html")),
            .init("increase", "chart.line.uptrend.xyaxis", "Індексація та підвищення", "Wertsicherung und Mieterhöhung", "Підвищення не є законним лише тому, що власник цього захотів. Важливі чинна Wertsicherungsklausel, тип оренди та чинні обмеження. Попросіть письмовий розрахунок і дату набрання чинності; перед згодою перевірте їх у AK або житловій консультації.", "Eine Erhöhung ist nicht schon deshalb zulässig, weil die vermietende Person sie wünscht. Entscheidend sind wirksame Wertsicherungsklausel, Mietart und aktuelle Grenzen. Verlangen Sie schriftliche Berechnung und Wirksamkeitsdatum und lassen Sie beides vor Zustimmung prüfen.", source: akRent)
        ], sources: [costs, akRent, akContract]
    )

    static let depositGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Платіж із квитанцією, акт приймання та повернення", german: "Zahlung mit Beleg, Übergabeprotokoll und Rückzahlung"),
        introduction: .init(ukrainian: "Застава (Kaution) забезпечує можливі борги чи пошкодження. Ablöse за речі попереднього мешканця — інший платіж, який треба оцінювати окремо.", german: "Die Kaution sichert mögliche Rückstände oder Schäden. Eine Ablöse für Gegenstände des Vormieters ist eine andere Zahlung und gesondert zu prüfen."),
        sections: [
            .init("pay", "creditcard", "Передача грошей", "Geldübergabe", "Сплачуйте лише після перевірки договору й того, кому належить рахунок; візьміть квитанцію з призначенням суми. Не переказуйте заставу за квартиру, яку ніхто не показав. Запитайте, коли передають ключі та якими є умови повернення застави.", "Zahlen Sie erst nach Prüfung von Vertrag und Kontoinhaber und verlangen Sie einen Beleg mit Zahlungszweck. Überweisen Sie keine Kaution für eine ungesehene Wohnung. Klären Sie Schlüsselübergabe und Rückzahlungsbedingungen.", source: akContract),
            .init("protocol", "camera", "Акт приймання", "Übergabeprotokoll", "На вході й виході складіть протокол із фото дефектів, показниками лічильників, кількістю ключів, станом меблів і підписами сторін. Передайте дефекти письмово негайно. Зберігайте фото та листування до остаточного повернення застави.", "Erstellen Sie bei Ein- und Auszug ein Protokoll mit Mängelfotos, Zählerständen, Schlüsselanzahl, Möbelzustand und Unterschriften. Melden Sie Mängel sofort schriftlich. Bewahren Sie Fotos und Korrespondenz bis zur Kautionsabrechnung auf.", source: deposit),
            .init("return", "arrow.uturn.backward", "Що можна утримати", "Was einbehalten werden darf", "За звичайний знос житла заставу зазвичай утримувати не можна; за реальні пошкодження або борги можуть утримати обґрунтовану суму. Попросіть письмовий розрахунок; якщо заставу не повертають, зверніться до Arbeiterkammer чи житлової консультації. Ablöse за старі меблі перевіряйте за фактичною вартістю.", "Für normale Abnutzung darf die Kaution grundsätzlich nicht einbehalten werden; für tatsächliche Schäden oder Rückstände kann ein begründeter Betrag abgezogen werden. Verlangen Sie eine schriftliche Abrechnung und holen Sie bei Streit Beratung ein. Prüfen Sie Ablösen für alte Möbel anhand ihres tatsächlichen Werts.", source: deposit)
        ], sources: [deposit, akContract, akOffer]
    )

    static let agents = DirectoryGuide(
        cardSummary: .init(ukrainian: "Хто платить комісію при оренді й купівлі", german: "Wer die Provision bei Miete und Kauf zahlt"),
        introduction: .init(ukrainian: "Правило Bestellerprinzip стосується посередництва оренди житла; до купівлі його не можна механічно застосовувати.", german: "Das Bestellerprinzip betrifft die Vermittlung von Wohnungsmietverträgen; es gilt nicht automatisch für Käufe."),
        sections: [
            .init("rent", "person.2", "Оренда: платить перший замовник", "Miete: Erstauftraggeber zahlt", "З 2023 року маклерську комісію за оренду житла зазвичай платить той, хто першим найняв маклера, найчастіше власник. Якщо маклер уже рекламував квартиру за дорученням власника, він не може просто перекласти оплату на орендаря. Орендар може платити, якщо сам першим замовив послугу пошуку за відповідних умов.", "Seit 2023 zahlt bei Wohnungsmiete grundsätzlich der erste Auftraggeber des Maklers, meist die Vermieterseite. Hat der Makler die Wohnung bereits für den Vermieter beworben, darf er die Provision nicht einfach dem Mieter auferlegen. Wer selbst zuerst einen Suchauftrag erteilt, kann unter Voraussetzungen zahlungspflichtig sein.", source: broker),
            .init("purchase", "house", "Купівля: інша модель", "Kauf: andere Regeln", "При купівлі нерухомості комісію можуть платити й покупець, і продавець; розмір та обмеження перевіряйте до підпису Kaufanbot чи договору. Попросіть письмово вказати, хто саме замовив послугу, суму з ПДВ і момент виникнення обов’язку платити.", "Beim Immobilienkauf können Käufer und Verkäufer Provision schulden; Höhe und Grenzen prüfen Sie vor Kaufanbot oder Vertrag. Verlangen Sie schriftlich Auftraggeber, Betrag einschließlich Umsatzsteuer und Zeitpunkt der Zahlungspflicht.", source: purchaseCosts),
            .init("pressure", "exclamationmark.triangle", "Якщо вимагають сумнівний платіж", "Bei fragwürdiger Forderung", "Не платіть «комісію», «сервісний внесок» чи «резервування» лише на словах. Попросіть правову підставу, договір посередництва й рахунок. Якщо вимогу не можете перевірити, зверніться до AK або консультації захисту споживачів.", "Zahlen Sie „Provision“, „Servicegebühr“ oder „Reservierung“ nicht bloß auf Zuruf. Verlangen Sie Rechtsgrundlage, Maklervertrag und Rechnung. Lassen Sie zweifelhafte Forderungen bei AK oder Verbraucherberatung prüfen.", source: broker)
        ], sources: [broker, purchaseCosts, purchaseOffer]
    )
}
