import Foundation

extension HousingGuides {
    static let buying = DirectoryGuide(
        cardSummary: .init(ukrainian: "Grundbuch, стан будинку, Kaufanbot і Treuhand", german: "Grundbuch, Gebäudezustand, Kaufanbot und Treuhand"),
        introduction: .init(ukrainian: "Купівля житла — юридична й фінансова угода. До підпису Kaufanbot перевірте право власності, обтяження, дозволи та повну вартість.", german: "Der Immobilienkauf ist ein rechtliches und finanzielles Geschäft. Prüfen Sie vor dem Kaufanbot Eigentum, Lasten, Genehmigungen und Gesamtkosten."),
        sections: [
            .init("check", "doc.text.magnifyingglass", "Перевірка до підпису", "Prüfung vor Unterschrift", "Отримайте актуальний Grundbuchsauszug: хто власник, іпотеки, сервітути, заборони й частки. Для квартири запитайте документи Wohnungseigentum, протоколи зборів власників, резерв на ремонт (Rücklage), майбутні ремонти й заборгованості. Огляньте дах, фасад, вологу, інженерію й Energieausweis; за потреби залучіть фахівця.", "Holen Sie einen aktuellen Grundbuchsauszug zu Eigentum, Pfandrechten, Dienstbarkeiten, Verboten und Anteilen. Bei Eigentumswohnungen fragen Sie nach Wohnungseigentumsunterlagen, Eigentümerversammlungen, Rücklage, geplanten Sanierungen und Rückständen. Prüfen Sie Dach, Fassade, Feuchte, Technik und Energieausweis; ziehen Sie bei Bedarf Fachleute bei.", source: registry),
            .init("offer", "pencil", "Kaufanbot уже може зобов’язувати", "Kaufanbot kann bereits binden", "Підписана пропозиція на купівлю — не просто резервація. Якщо продавець прийме її, можуть виникнути договірні обов’язки й комісія. Перед підписом перевірте ціну, фінансування, предмет купівлі, умови виходу, строки й можливий дозвіл на купівлю для громадянина третьої країни.", "Ein unterschriebenes Kaufanbot ist keine bloße Reservierung. Mit Annahme durch den Verkäufer können Vertragspflichten und Provision entstehen. Prüfen Sie vorher Preis, Finanzierung, Kaufgegenstand, Rücktrittsbedingungen, Fristen und mögliche Ausländergrunderwerbsgenehmigung.", source: purchaseOffer),
            .init("settlement", "lock.shield", "Безпечний розрахунок", "Sichere Abwicklung", "Договір зазвичай готує нотаріус або адвокат; платіж часто проходить через зареєстрований Treuhandkonto. Кошти продавцю перераховують після виконання умов, зокрема очищення обтяжень і внесення права покупця в Grundbuch. Не переказуйте повну ціну безпосередньо незнайомому продавцю за усною домовленістю.", "Der Vertrag wird meist von Notar*in oder Anwalt/Anwältin erstellt; Zahlungen laufen häufig über ein registriertes Treuhandkonto. Die Auszahlung erfolgt nach Erfüllung der Bedingungen, etwa Lastenfreistellung und Grundbucheintragung des Käufers. Überweisen Sie den Gesamtpreis nicht mündlich vereinbart direkt an unbekannte Verkäufer.", source: escrow)
        ], sources: [registry, escrow, purchaseOffer, energy]
    )

    static let buyingCosts = DirectoryGuide(
        cardSummary: .init(ukrainian: "Ціна плюс податок, Grundbuch, маклер, нотаріус і кредит", german: "Preis plus Steuer, Grundbuch, Makler, Notar und Kredit"),
        introduction: .init(ukrainian: "Покупець має підготувати бюджет понад вартість квартири. Пільги та тарифи можуть змінюватися, тому перед угодою потрібен актуальний розрахунок.", german: "Käufer brauchen ein Budget über den Kaufpreis hinaus. Begünstigungen und Gebühren ändern sich; rechnen Sie vor dem Geschäft aktuell nach."),
        sections: [
            .init("taxes", "percent", "Основні витрати", "Wichtige Nebenkosten", "Стандартний Grunderwerbsteuer зазвичай 3,5 % ціни, реєстрація власності в Grundbuch — 1,1 %, за іпотечного забезпечення додаткова реєстрація Pfandrecht — 1,2 % суми заставного права. Можуть бути інші збори або тимчасові пільги. Розрахунок нотаріуса/адвоката й комісію маклера отримайте письмово до Kaufanbot.", "Die Grunderwerbsteuer beträgt regulär 3,5 % des Kaufpreises, die Grundbuchseintragung 1,1 % und die Eintragung eines Pfandrechts bei Kredit zusätzlich 1,2 % des Pfandrechtsbetrags. Weitere Gebühren oder befristete Begünstigungen sind möglich. Lassen Sie Notar-/Anwaltskosten und Maklerprovision vor Kaufanbot schriftlich berechnen.", source: purchaseCosts),
            .init("finance", "building.columns", "Кредит і резерв", "Kredit und Rücklage", "Порівняйте ефективну процентну ставку, фіксований/змінний процент, строк, дострокове погашення, страхування й власний внесок. Для Eigentumswohnung додайте щомісячні Betriebskosten і Rücklage, можливі Sonderumlagen на ремонт. Попереднє рішення банку не замінює остаточного кредитного договору.", "Vergleichen Sie Effektivzins, fixen/variablen Zins, Laufzeit, vorzeitige Tilgung, Versicherung und Eigenmittel. Bei Eigentumswohnungen kommen monatliche Betriebskosten, Rücklage und mögliche Sonderumlagen hinzu. Eine vorläufige Bankzusage ist kein endgültiger Kreditvertrag.", source: purchaseCosts),
            .init("agent", "person.2", "Комісія при продажі", "Maklerprovision beim Kauf", "Bestellerprinzip для оренди квартир не означає автоматичну відсутність комісії в купівлі. Офіційний портал наводить максимальні ставки залежно від ціни; комісія може бути договірною і до неї додається ПДВ. Уточніть це до зобов’язувальної пропозиції.", "Das Bestellerprinzip für Wohnungsmiete bedeutet beim Kauf keinen automatischen Entfall der Provision. Das amtliche Portal nennt preisabhängige Höchstsätze; Provision ist verhandelbar und Umsatzsteuer kommt hinzu. Klären Sie das vor einem bindenden Anbot.", source: purchaseCosts)
        ], sources: [purchaseCosts, escrow, foreignBuyer]
    )

    static let foreignBuyers = DirectoryGuide(
        cardSummary: .init(ukrainian: "Дозвіл землі для громадян третіх країн і винятки", german: "Landesgenehmigung für Drittstaatsangehörige und Ausnahmen"),
        introduction: .init(ukrainian: "Українське громадянство — громадянство третьої країни для правил Ausländergrunderwerb. Умови купівлі визначає федеральна земля, де розташована нерухомість.", german: "Die Ukraine ist für den Ausländergrunderwerb ein Drittstaat. Die Regeln bestimmt das Bundesland, in dem die Immobilie liegt."),
        sections: [
            .init("approval", "building.columns", "Потрібен дозвіл?", "Ist eine Genehmigung nötig?", "У більшості земель для громадян третіх країн потрібен дозвіл на придбання або підтвердження, що він не потрібен. Є різні винятки: наприклад, в окремих випадках подружжя з громадянином Австрії чи правила для певного міста. Наявність Ausweis für Vertriebene або RWR-Karte сама по собі не відповідає на це питання. Зверніться до органу землі до Kaufanbot.", "In vielen Ländern brauchen Drittstaatsangehörige eine Erwerbsgenehmigung oder Negativbestätigung. Ausnahmen unterscheiden sich, etwa bei Ehe mit österreichischer Person oder für bestimmte Orte. Vertriebenenausweis oder RWR-Karte beantworten die Frage allein nicht. Fragen Sie die Landesbehörde vor dem Kaufanbot.", source: foreignBuyer),
            .init("land", "map", "Місце об’єкта важливіше адреси покупця", "Objektlage ist entscheidend", "Право залежить від землі розташування квартири, а для землі сільськогосподарського/лісового призначення можуть бути додаткові дозволи. Нотаріус або адвокат має перевірити конкретний об’єкт, громадянство покупців і виконання умов перед реєстрацією в Grundbuch. Офіційний орган вашої землі наведено нижче.", "Maßgeblich ist das Bundesland der Liegenschaft; für land- oder forstwirtschaftliche Grundstücke können weitere Genehmigungen nötig sein. Notar*in oder Anwalt/Anwältin soll Objekt, Staatsangehörigkeit der Käufer und Voraussetzungen vor Grundbucheintragung prüfen. Die Landesstelle finden Sie unten.", source: foreignBuyer),
            .init("not-residence", "person.crop.rectangle", "Власність не дорівнює статусу", "Eigentum ist kein Aufenthaltstitel", "Купівля квартири не надає автоматично права перебування, громадянства чи доступу до допомоги. Окремо перевірте ваш паспорт, посвідку, дозвіл на купівлю, джерело коштів та податкові наслідки.", "Wohnungskauf verleiht weder automatisch Aufenthaltsrecht noch Staatsbürgerschaft oder Sozialleistungen. Prüfen Sie Pass, Aufenthaltstitel, Erwerbsgenehmigung, Mittelherkunft und Steuern getrennt.", source: foreignBuyer)
        ], sources: [foreignBuyer, registry, escrow]
    )
}
