import Foundation

extension HousingGuides {
    static let social = DirectoryGuide(
        cardSummary: .init(ukrainian: "Gemeindewohnung, Genossenschaft і Wohn-Ticket", german: "Gemeindewohnung, Genossenschaft und Wohn-Ticket"),
        introduction: .init(ukrainian: "Доступне й соціальне житло організоване землями та громадами по-різному. Право на тимчасовий захист саме по собі не гарантує комунальну квартиру.", german: "Leistbares und gefördertes Wohnen ist je nach Land und Gemeinde anders organisiert. Vorübergehender Schutz allein garantiert keine Gemeindewohnung."),
        sections: [
            .init("types", "building.2", "Які є програми", "Wohnformen", "Gemeindewohnung належить громаді; geförderte або Genossenschaftswohnung — субсидовані чи кооперативні формати з власними умовами доходу, проживання, статусу й інколи Finanzierungsbeitrag. Перед оплатою внеску перевірте правила його повернення.", "Gemeindewohnungen gehören der Gemeinde; geförderte und Genossenschaftswohnungen haben eigene Regeln zu Einkommen, Wohnsitz, Status und teils Finanzierungsbeitrag. Prüfen Sie vor Zahlung, wie dieser Beitrag zurückgezahlt wird.", source: viennaHousing),
            .init("vienna", "mappin", "Приклад: Відень", "Beispiel Wien", "Wohnberatung Wien веде Wiener Wohn-Ticket для Gemeindewohnungen і geförderte Wohnungen. Умови включають проживання й інші критерії, а система розподілу змінювалася у 2026 році. Перевіряйте чинні умови онлайн; для інших земель використовуйте місцевий орган, який показано нижче.", "Die Wohnberatung Wien vergibt das Wiener Wohn-Ticket für Gemeinde- und geförderte Wohnungen. Voraussetzungen umfassen Wohnsitz und weitere Kriterien; das Vergabesystem änderte sich 2026. Prüfen Sie aktuelle Regeln online; in anderen Ländern nutzen Sie die unten angezeigte Landesstelle.", source: viennaHousing),
            .init("apply", "checklist", "Перед заявою", "Vor der Bewerbung", "Зберіть документи всіх мешканців, підтвердження статусу, доходів, Hauptwohnsitz і нинішнього житла. Не продавайте чи не купуйте «місце в черзі»; звертайтеся лише через офіційні канали землі, міста або кооперативу.", "Sammeln Sie Ausweise aller Bewohner, Status-, Einkommens-, Hauptwohnsitz- und Wohnungsnachweise. Kaufen oder verkaufen Sie keinen „Wartelistenplatz“; nutzen Sie nur offizielle Landes-, Gemeinde- oder Genossenschaftswege.", source: viennaHousing)
        ], sources: [viennaHousing, housingHelp]
    )

    static let support = DirectoryGuide(
        cardSummary: .init(ukrainian: "Wohnbeihilfe, Grundversorgung і захист від втрати житла", german: "Wohnbeihilfe, Grundversorgung und Schutz vor Wohnungsverlust"),
        introduction: .init(ukrainian: "Допомога залежить від землі, доходів, статусу та типу житла. Немає одного австрійського розміру Wohnbeihilfe для всіх.", german: "Unterstützung hängt von Bundesland, Einkommen, Status und Wohnform ab. Es gibt keine einheitliche österreichweite Wohnbeihilfe für alle."),
        sections: [
            .init("land", "building.columns", "Земельна Wohnbeihilfe", "Wohnbeihilfe des Landes", "У своїй землі перевірте, хто має право подати, мінімальний дохід, обмеження щодо розміру житла та потрібні документи. Наприклад, у Відні Wohnbeihilfe запитують лише для квартири, в якій уже проживаєте; за майбутню оренду її наперед не призначають. Посилання вашої землі наведено в регіональному блоці нижче.", "Prüfen Sie im Bundesland Berechtigte, Mindesteinkommen, Wohnungsgröße und Unterlagen. In Wien kann Wohnbeihilfe etwa nur für eine bereits bewohnte Wohnung beantragt werden, nicht im Voraus für eine künftige Miete. Der Landeslink steht im regionalen Block unten.", source: viennaSupport),
            .init("protection", "person.crop.rectangle", "Grundversorgung для переселенців", "Grundversorgung für Vertriebene", "Якщо ви отримуєте Grundversorgung, окремо уточніть у її земельного органу допомогу на приватну оренду та сумісність з іншими виплатами. Не припускайте, що повна сума нового договору буде компенсована або що різні види допомоги можна додавати без перевірки.", "Beziehen Sie Grundversorgung, klären Sie bei der Landesstelle Mietunterstützung für Privatunterkunft und Kombination mit anderen Leistungen. Gehen Sie weder von voller Übernahme einer neuen Miete noch von frei kombinierbaren Beihilfen aus.", source: basic),
            .init("crisis", "lifepreserver", "Борги або загроза виселення", "Schulden oder drohende Räumung", "WOHNSCHIRM MIETE перевіряє допомогу з боргами за основне житло; WOHNSCHIRM ENERGIE — із загрозою відключення, Housing First — при бездомності. Консультація безкоштовна; зверніться до рішення суду, а не після нього.", "WOHNSCHIRM MIETE prüft Mietschulden am Hauptwohnsitz, ENERGIE drohende Abschaltung und Housing First Wohnungslosigkeit. Die Beratung ist kostenlos; suchen Sie Hilfe vor einer Gerichtsentscheidung.", source: housingHelp)
        ], sources: [viennaSupport, basic, housingHelp]
    )

    static let move = DirectoryGuide(
        cardSummary: .init(ukrainian: "Адреса за 3 дні, BFA/MA 35, електрика й страхування", german: "Wohnsitz binnen 3 Tagen, BFA/MA 35, Energie und Versicherung"),
        introduction: .init(ukrainian: "Переїзд змінює не лише адресу доставки пошти. Він може вплинути на допомогу, посвідку й договори постачання.", german: "Ein Umzug ändert mehr als die Postadresse. Er kann Leistungen, Aufenthaltstitel und Versorgungsverträge betreffen."),
        sections: [
            .init("register", "mappin", "Meldezettel", "Wohnsitz anmelden", "Після фактичного заселення зареєструйте основне або додаткове місце проживання протягом 3 днів у Meldebehörde чи, за умов, онлайн. Формуляр підписує той, хто реально надає житло — власник, головний наймач або інший Unterkunftgeber. Підтвердження адреси не замінює орендний договір.", "Melden Sie nach tatsächlichem Einzug Haupt- oder Nebenwohnsitz binnen 3 Tagen bei der Meldebehörde oder unter Voraussetzungen online an. Das Formular unterschreibt die Person, die tatsächlich Unterkunft gewährt — Eigentümer*in, Hauptmieter*in oder andere Unterkunftgeber*in. Meldebestätigung ersetzt keinen Mietvertrag.", source: moving),
            .init("tell", "envelope", "Повідомте важливі служби", "Wichtige Stellen informieren", "Оновіть адресу в BFA або органі посвідки, Grundversorgung, страховій касі, роботодавця, банку, школі й постачальників. При переїзді між землями спершу уточніть порядок переведення підтримки. Збережіть фото лічильників на день виїзду та в’їзду.", "Aktualisieren Sie die Adresse bei BFA oder Aufenthaltsbehörde, Grundversorgung, Krankenkasse, Arbeitgeber, Bank, Schule und Versorgern. Bei Bundeslandwechsel klären Sie die Übertragung von Leistungen vorab. Fotografieren Sie Zählerstände am Aus- und Einzugstag.", source: bmi),
            .init("contracts", "bolt", "Комунальні договори", "Versorgungsverträge", "Перевірте, хто закриває й відкриває рахунки за електрику, газ, опалення та інтернет; запишіть номер точки обліку й показники. За потреби оформіть переадресацію пошти. Договір страхування домашнього майна (Haushaltsversicherung) перевірте для нової квартири.", "Klären Sie Ab- und Anmeldung von Strom, Gas, Wärme und Internet; notieren Sie Zählpunkt und Zählerstände. Richten Sie bei Bedarf Nachsendung ein. Prüfen Sie Ihre Haushaltsversicherung für die neue Wohnung.", source: moving)
        ], sources: [moving, bmi, basic]
    )
}
