import Foundation

extension HousingGuides {
    static let arrival = DirectoryGuide(
        cardSummary: .init(ukrainian: "Перший нічліг, реєстрація та безпечні контакти", german: "Erste Unterkunft, Erfassung und sichere Anlaufstellen"),
        introduction: .init(ukrainian: "Якщо вам ніде ночувати після прибуття, зверніться до офіційної системи прийому землі перебування; адреси й доступність місць змінюються.", german: "Wenn Sie nach der Ankunft keinen Schlafplatz haben, wenden Sie sich an die offizielle Aufnahme im Bundesland; Adressen und freie Plätze ändern sich."),
        sections: [
            .init("first", "bed.double", "Попросіть організоване місце", "Organisierten Platz erfragen", "Сторінка BMI для переселенців пояснює реєстрацію й направляє до чинних пунктів прийому та допомоги. Якщо ви не маєте приватного житла, скажіть про це одразу. Після реєстрації місце можуть надати в іншій землі; конкретний регіон зазвичай не обирають.", "Die BMI-Seite für Vertriebene erklärt Erfassung und aktuelle Anlaufstellen. Sagen Sie sofort, wenn Sie keine Privatunterkunft haben. Nach der Erfassung kann eine Unterkunft in einem anderen Bundesland zugeteilt werden; die Region ist meist nicht frei wählbar.", source: bmi),
            .init("vulnerable", "cross.case", "Особливі потреби", "Besonderer Bedarf", "Повідомте про дітей, вагітність, інвалідність, хронічні хвороби, потребу в ліках, тварин або загрозу насильства до розміщення. Якщо сьогодні небезпечно повертатися до місця ночівлі, зверніться до поліції 133 або до відповідної служби захисту із розділу «Безпека».", "Nennen Sie Kinder, Schwangerschaft, Behinderung, chronische Krankheiten, Medikamente, Tiere oder Gewaltgefahr vor der Zuteilung. Ist die Rückkehr zur Unterkunft heute gefährlich, kontaktieren Sie Polizei 133 oder die zuständige Schutzstelle im Bereich „Sicherheit“.", source: bmi),
            .init("private", "house", "Якщо ночуєте в знайомих", "Bei Freunden oder Familie", "За фактичним проживанням зареєструйте адресу в установленому порядку. Безоплатне проживання у знайомих, оренда й організований прихисток мають різні договори та умови допомоги. Не підписуйте порожні бланки й не віддавайте паспорт як «заставу».", "Melden Sie Ihren tatsächlichen Wohnsitz nach den Regeln an. Kostenloses Wohnen bei Bekannten, Miete und organisierte Unterkunft haben verschiedene Verträge und Unterstützungsregeln. Unterschreiben Sie keine leeren Formulare und hinterlegen Sie Ihren Pass nicht als „Pfand“.", source: moving)
        ], sources: [bmi, basic, moving]
    )

    static let temporary = DirectoryGuide(
        cardSummary: .init(ukrainian: "Організований прихисток, приватне житло та зміна адреси", german: "Organisierte Unterkunft, Privatwohnung und Adresswechsel"),
        introduction: .init(ukrainian: "Grundversorgung може включати організоване проживання або допомогу при приватному житлі. Правила й розміри підтримки залежать від федеральної землі та обставин.", german: "Grundversorgung kann organisierte Unterkunft oder Unterstützung bei Privatunterbringung umfassen. Regeln und Beträge hängen von Bundesland und Einzelfall ab."),
        sections: [
            .init("types", "building.2", "Два способи розміщення", "Zwei Wohnformen", "В організованому житлі місце й забезпечення координує земля або її партнер. Для індивідуального приватного житла підтримку перевіряють через земельну Grundversorgungsstelle; може знадобитися договір оренди. Допомога не означає автоматичного покриття повної ринкової оренди.", "Organisierte Quartiere koordiniert das Land oder sein Partner. Bei individueller Privatunterkunft prüft die Landes-Grundversorgungsstelle Leistungen; ein Mietvertrag kann nötig sein. Unterstützung deckt nicht automatisch die volle Marktmiete.", source: basic),
            .init("move", "arrow.right", "Переїзд із прихистку", "Aus der Unterkunft ausziehen", "До підписання приватного договору уточніть у своїй Grundversorgungsstelle, чи зміниться допомога, чи можна перевезти її в іншу землю й коли повідомити нову адресу. Не приховуйте роботу, доходи та членів домогосподарства: вони можуть впливати на право на виплати.", "Klären Sie vor privater Anmietung mit Ihrer Grundversorgungsstelle, wie sich Leistungen ändern, ob ein Bundeslandwechsel möglich ist und wann die neue Adresse mitzuteilen ist. Verschweigen Sie Arbeit, Einkommen und Haushaltsmitglieder nicht; sie können Leistungen beeinflussen.", source: basic),
            .init("agreement", "doc.text", "Що перевірити в тимчасовому житлі", "Regeln im Quartier", "Попросіть письмові правила проживання: хто живе в кімнаті, доступ до санвузла й кухні, гості, відсутність, тварини, скарги й умови виїзду. Для житла від приватної особи уточніть, чи це оренда, піднайм або безоплатне користування; від цього залежать права та витрати.", "Bitten Sie um schriftliche Hausregeln: Zimmerbelegung, Bad und Küche, Gäste, Abwesenheit, Tiere, Beschwerden und Auszug. Bei privater Unterbringung klären Sie, ob Miete, Untermiete oder kostenlose Überlassung vorliegt; davon hängen Rechte und Kosten ab.", source: basic)
        ], sources: [bmi, basic, housingHelp]
    )

    static let search = DirectoryGuide(
        cardSummary: .init(ukrainian: "Портали, фільтри та захист від шахрайства", german: "Portale, Filter und Schutz vor Betrug"),
        introduction: .init(ukrainian: "Оголошення — відправна точка, а не гарантія правдивості. Порівнюйте повну щомісячну вартість і перевіряйте особу, яка здає житло.", german: "Inserate sind ein Startpunkt, keine Echtheitsgarantie. Vergleichen Sie vollständige Monatskosten und prüfen Sie die vermietende Person."),
        sections: [
            .init("sites", "magnifyingglass", "Де шукати", "Wo suchen", "Приватні оголошення є на willhaben й ImmoScout24; кімнати та WG — на WG-Gesucht. Для соціального житла шукайте офіційну Wohnberatung своєї землі; для студентів — OeAD і операторів гуртожитків. Портали не є державними органами, а доступність і ціни змінюються щодня.", "Private Inserate finden Sie bei willhaben und ImmoScout24, Zimmer und WGs bei WG-Gesucht. Für gefördertes Wohnen nutzen Sie die offizielle Wohnberatung Ihres Landes, für Studierende OeAD und Wohnheimbetreiber. Portale sind keine Behörden; Angebote und Preise ändern sich täglich.", source: willhaben),
            .init("filters", "slider.horizontal.3", "Корисні фільтри", "Sinnvolle Filter", "Перевіряйте загальну оренду (Gesamtmiete), Betriebskosten, опалення, електрику, заставу, строк договору, можливість Anmeldung, тварин, доступність транспорту та бар’єрність. «Provisionsfrei» стосується комісії, а не застави чи інших витрат.", "Prüfen Sie Gesamtmiete, Betriebskosten, Heizung, Strom, Kaution, Befristung, Anmeldung, Haustiere, Verkehrsanbindung und Barrierefreiheit. „Provisionsfrei“ betrifft die Maklerprovision, nicht Kaution und Nebenkosten.", source: akRent),
            .init("fraud", "exclamationmark.triangle", "Перед оплатою", "Vor jeder Zahlung", "Огляньте житло особисто або через довірену людину; вимагайте адресу, дані власника/управителя, договір і підтвердження платежу. Не переказуйте заставу на невідомий іноземний рахунок за «резервування ключів». Якщо власник нібито за кордоном і не може показати квартиру, це сигнал перевірити оголошення особливо ретельно.", "Besichtigen Sie selbst oder durch eine Vertrauensperson; verlangen Sie Adresse, Eigentümer-/Verwalterdaten, Vertrag und Zahlungsbeleg. Überweisen Sie keine Kaution auf ein unbekanntes Auslandskonto für eine „Schlüsselreservierung“. Kann der angebliche Eigentümer im Ausland die Wohnung nicht zeigen, prüfen Sie das Inserat besonders gründlich.", source: akOffer)
        ], sources: [willhaben, immoscout, wgGesucht, oeAD, akOffer]
    )

    static let viewing = DirectoryGuide(
        cardSummary: .init(ukrainian: "Стан житла, документи та підсумкова ціна", german: "Zustand, Unterlagen und Gesamtkosten prüfen"),
        introduction: .init(ukrainian: "На перегляді перевіряйте не лише площу й вигляд, а й юридичні та щомісячні умови.", german: "Bei der Besichtigung zählen nicht nur Fläche und Eindruck, sondern rechtliche und monatliche Bedingungen."),
        sections: [
            .init("physical", "house", "Фізичний стан", "Zustand der Wohnung", "Перевірте вологу й цвіль, вікна, опалення, гарячу воду, електрику, вентиляцію, шум, інтернет, ліфт і підвал. Зробіть фото помічених дефектів і попросіть підтвердження, хто та коли їх виправить. Запитайте про Energieausweis і очікувані витрати на опалення.", "Prüfen Sie Feuchte und Schimmel, Fenster, Heizung, Warmwasser, Strom, Lüftung, Lärm, Internet, Lift und Keller. Fotografieren Sie Mängel und lassen Sie Reparatur und Termin bestätigen. Fragen Sie nach Energieausweis und zu erwartenden Heizkosten.", source: energy),
            .init("legal", "doc.text.magnifyingglass", "Хто здає й що входить", "Wer vermietet und was dazugehört", "Уточніть, чи це Hauptmiete або Untermiete, хто підписує договір, які приміщення та меблі входять, чи можна зареєструвати адресу. Вимагайте проект договору, повну розбивку платежів і підтвердження повноважень представника.", "Klären Sie Haupt- oder Untermiete, Unterzeichner, mitvermietete Räume und Möbel sowie Wohnsitzanmeldung. Verlangen Sie Vertragsentwurf, vollständige Kostenaufstellung und Vertretungsnachweis.", source: akContract),
            .init("offer", "pencil", "Не поспішайте з Mietanbot", "Mietanbot nicht voreilig unterschreiben", "Підписаний Mietanbot часто є зобов’язувальною пропозицією, а після прийняття орендодавцем договір може вже виникнути. Це не просто «бронь». Перевірте умови й строк дії до підпису; правила відмови обмежені.", "Ein unterschriebenes Mietanbot ist oft eine bindende Erklärung; mit Annahme durch die Vermieterseite kann der Vertrag bereits zustande kommen. Es ist keine bloße Reservierung. Prüfen Sie Bedingungen und Bindungsfrist vor Unterschrift; Rücktrittsrechte sind begrenzt.", source: akOffer)
        ], sources: [energy, akContract, akOffer]
    )
}
