import Foundation

extension HousingGuides {
    static let contract = DirectoryGuide(
        cardSummary: .init(ukrainian: "Mietanbot, строк, MRG та ключові пункти договору", german: "Mietanbot, Dauer, MRG und wichtige Vertragsklauseln"),
        introduction: .init(ukrainian: "В австрійській оренді правила залежать від типу будинку та сфери дії Mietrechtsgesetz (MRG). Просіть письмовий договір зрозумілою вам мовою до оплати.", german: "Im österreichischen Mietrecht hängt vieles vom Gebäude und der Geltung des Mietrechtsgesetzes (MRG) ab. Lassen Sie sich vor Zahlung einen verständlichen schriftlichen Vertrag geben."),
        sections: [
            .init("terms", "doc.text", "Що має бути зрозуміло", "Was klar geregelt sein muss", "Адреса й площа, сторони, початок, строк і розірвання, Hauptmietzins, Betriebskosten, опалення, електрика, індексація, застава, меблі, стан квартири та правила піднайму. Перевірте, чи оплата є Pauschalmiete чи окремими позиціями. Зберігайте підписану копію й додатки.", "Adresse und Fläche, Parteien, Beginn, Dauer und Kündigung, Hauptmietzins, Betriebskosten, Heizung, Strom, Wertsicherung, Kaution, Möbel, Zustand und Untermiete. Prüfen Sie Pauschalmiete oder Einzelpositionen. Bewahren Sie unterschriebene Kopie und Anlagen auf.", source: akContract),
            .init("term", "calendar", "Обмежений строк із 2026 року", "Befristung seit 2026", "Для договорів оренди квартир у повній або частковій сфері MRG, укладених чи продовжених із 2026 року, мінімальний строк — 5 років, якщо орендодавець є підприємцем, або 3 роки, якщо він ним не є. Після першого року такого строкового договору наймач може розірвати його на кінець місяця з тримісячним попередженням; найраніше — на кінець 16-го місяця. Для одно- й двосімейних будинків та інших винятків правила інші.", "Bei ab 2026 abgeschlossenen oder verlängerten Wohnungsmietverträgen im Voll- oder Teilbereich des MRG beträgt die Mindestdauer fünf Jahre bei unternehmerischer Vermieterseite, sonst drei Jahre. Nach einem Jahr dieses befristeten Vertrags können Mietende zum Monatsletzten mit drei Monaten Frist kündigen, frühestens zum Ende des 16. Monats. Für Ein- und Zweifamilienhäuser und andere Ausnahmen gelten andere Regeln.", source: rentalTerm),
            .init("offer", "pencil", "Заява про оренду — не бронь", "Mietanbot ist keine Reservierung", "Mietanbot може зобов’язувати ще до підписання повного договору. Якщо власник прийме його, договір уже може бути укладений за основними умовами. Не підписуйте кілька паралельно й не передавайте «завдаток» без ясного документа про мету платежу.", "Ein Mietanbot kann schon vor dem ausführlichen Vertrag binden. Nimmt die Vermieterseite es an, kann der Vertrag zu den wesentlichen Punkten bereits bestehen. Unterzeichnen Sie nicht mehrere gleichzeitig und zahlen Sie keine „Anzahlung“ ohne klare schriftliche Zweckangabe.", source: akOffer)
        ], sources: [akContract, rentalTerm, akOffer]
    )

    static let rentCosts = DirectoryGuide(
        cardSummary: .init(ukrainian: "Реальна місячна сума, Betriebskosten і підвищення", german: "Gesamtkosten, Betriebskosten und Erhöhungen"),
        introduction: .init(ukrainian: "Ціна в оголошенні може не охоплювати всі платежі. Розрахуйте бюджет до підписання.", german: "Der Inseratspreis enthält nicht zwingend alle Zahlungen. Rechnen Sie vor Unterschrift das Gesamtbudget."),
        sections: [
            .init("monthly", "eurosign.circle", "Повна вартість на місяць", "Monatliche Gesamtkosten", "Окремо запитайте про Hauptmietzins, Betriebskosten, опалення/гарячу воду, електрику/газ, інтернет, паркомісце й меблі. Дізнайтеся, хто укладає договори з постачальниками та чи є авансові платежі з річним перерахунком. Порівнюйте квартири за повною сумою, а не лише Nettomiete.", "Fragen Sie getrennt nach Hauptmietzins, Betriebskosten, Heizung/Warmwasser, Strom/Gas, Internet, Parkplatz und Möbeln. Klären Sie Verträge mit Versorgern und Vorauszahlungen mit Jahresabrechnung. Vergleichen Sie Gesamtkosten statt nur Nettomiete.", source: costs),
            .init("billing", "receipt", "Betriebskostenabrechnung", "Betriebskostenabrechnung", "Зберігайте щомісячні платежі й перевіряйте річний розрахунок експлуатаційних витрат. Які позиції можна перекласти на орендаря, залежить від MRG та чинної угоди. Попросіть детальну розбивку й документи, якщо сума незрозуміла; Arbeiterkammer допомагає перевірити.", "Bewahren Sie Monatszahlungen auf und prüfen Sie die jährliche Betriebskostenabrechnung. Welche Positionen umgelegt werden dürfen, hängt von MRG und wirksamer Vereinbarung ab. Verlangen Sie bei Unklarheit eine Aufschlüsselung und Belege; die Arbeiterkammer hilft bei der Prüfung.", source: operatingCosts),
            .init("increase", "chart.line.uptrend.xyaxis", "Як перевірити підвищення з 2026 року", "Mieterhöhung ab 2026 prüfen", "Для квартир у повній або частковій сфері MRG індексація Hauptmietzins можлива не частіше разу на рік і не раніше квітня; для нового договору — не раніше наступного року. Правило стосується саме основної оренди, а не всіх Betriebskosten. Перевірте дійсну умову індексації, тип будинку, попередню інфляцію й письмовий розрахунок; кооперативне й деяке субсидоване житло має інші правила.", "Bei Wohnungen im Voll- oder Teilbereich des MRG darf der Hauptmietzins höchstens einmal jährlich und frühestens im April indexiert werden; bei neuen Verträgen nicht vor dem Folgejahr. Betriebskosten sind davon nicht insgesamt erfasst. Prüfen Sie wirksame Wertsicherung, Gebäudetyp, Vorjahresinflation und schriftliche Berechnung; Genossenschafts- und manche geförderte Wohnungen folgen anderen Regeln.", source: rentalIncrease)
        ], sources: [costs, operatingCosts, rentalIncrease]
    )

    static let depositGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Платіж із квитанцією, акт приймання та повернення", german: "Zahlung mit Beleg, Übergabeprotokoll und Rückzahlung"),
        introduction: .init(ukrainian: "Застава (Kaution) забезпечує можливі борги чи пошкодження. Ablöse за речі попереднього мешканця — інший платіж, який треба оцінювати окремо.", german: "Die Kaution sichert mögliche Rückstände oder Schäden. Eine Ablöse für Gegenstände des Vormieters ist eine andere Zahlung und gesondert zu prüfen."),
        sections: [
            .init("pay", "creditcard", "Передача грошей", "Geldübergabe", "Сплачуйте лише після перевірки договору й того, кому належить рахунок; візьміть квитанцію з призначенням суми. Не переказуйте заставу за квартиру, яку ніхто не показав. Запитайте, коли передають ключі та якими є умови повернення застави.", "Zahlen Sie erst nach Prüfung von Vertrag und Kontoinhaber und verlangen Sie einen Beleg mit Zahlungszweck. Überweisen Sie keine Kaution für eine ungesehene Wohnung. Klären Sie Schlüsselübergabe und Rückzahlungsbedingungen.", source: akContract),
            .init("protocol", "camera", "Акт приймання", "Übergabeprotokoll", "На вході й виході складіть протокол із фото дефектів, показниками лічильників, кількістю ключів, станом меблів і підписами сторін. Передайте дефекти письмово негайно. Зберігайте фото та листування до остаточного повернення застави.", "Erstellen Sie bei Ein- und Auszug ein Protokoll mit Mängelfotos, Zählerständen, Schlüsselanzahl, Möbelzustand und Unterschriften. Melden Sie Mängel sofort schriftlich. Bewahren Sie Fotos und Korrespondenz bis zur Kautionsabrechnung auf.", source: deposit),
            .init("return", "arrow.uturn.backward", "Повернення застави", "Kaution zurückbekommen", "Після завершення договору й повернення житла заставу з процентами мають повернути без зайвого зволікання. За звичайний знос її не утримують; за доведені пошкодження чи борги — лише обґрунтовану суму. Попросіть письмовий розрахунок. Якщо кошти не повернули, надішліть письмову вимогу зі строком відповіді та зверніться до AK за наступним кроком.", "Nach Vertragsende und Wohnungsrückgabe ist die Kaution samt Zinsen unverzüglich zurückzuzahlen. Normale Abnutzung rechtfertigt keinen Abzug; für belegte Schäden oder Rückstände nur den begründeten Betrag. Verlangen Sie eine schriftliche Abrechnung. Bleibt die Zahlung aus, setzen Sie schriftlich eine Frist und fragen Sie die AK nach dem nächsten Schritt.", source: depositReturn),
            .init("transfer", "shippingbox.fill", "Ablöse — окремий платіж", "Ablöse ist eine eigene Zahlung", "Попросіть точний список меблів чи поліпшень, фото, вік і підтвердження їхньої вартості. Порівняйте запитану суму з поточною вартістю (Zeitwert), а не з ціною нової речі. Платіж лише за право отримати квартиру або надмірна сума можуть бути забороненою Ablöse; письмову домовленість і квитанцію збережіть для перевірки в AK.", "Verlangen Sie eine genaue Liste der Möbel oder Investitionen mit Fotos, Alter und Wertnachweis. Vergleichen Sie die Forderung mit dem Zeitwert statt dem Neupreis. Eine Zahlung bloß für den Zuschlag zur Wohnung oder ein überhöhter Betrag kann eine verbotene Ablöse sein; sichern Sie Vereinbarung und Beleg für die Prüfung bei der AK.", source: transferPayment)
        ], sources: [akContract, deposit, depositReturn, transferPayment]
    )

    static let agents = DirectoryGuide(
        cardSummary: .init(ukrainian: "Хто платить комісію при оренді й купівлі", german: "Wer die Provision bei Miete und Kauf zahlt"),
        introduction: .init(ukrainian: "Правило Bestellerprinzip стосується посередництва оренди житла; до купівлі його не можна механічно застосовувати.", german: "Das Bestellerprinzip betrifft die Vermittlung von Wohnungsmietverträgen; es gilt nicht automatisch für Käufe."),
        sections: [
            .init("rent", "person.2", "Оренда: платить перший замовник", "Miete: Erstauftraggeber zahlt", "З 2023 року маклерську комісію за оренду житла зазвичай платить той, хто першим найняв маклера, найчастіше власник. Якщо маклер уже рекламував квартиру за дорученням власника, він не може просто перекласти оплату на орендаря. Орендар може платити, якщо сам першим замовив послугу пошуку за відповідних умов.", "Seit 2023 zahlt bei Wohnungsmiete grundsätzlich der erste Auftraggeber des Maklers, meist die Vermieterseite. Hat der Makler die Wohnung bereits für den Vermieter beworben, darf er die Provision nicht einfach dem Mieter auferlegen. Wer selbst zuerst einen Suchauftrag erteilt, kann unter Voraussetzungen zahlungspflichtig sein.", source: broker),
            .init("purchase", "house", "Купівля: інша модель", "Kauf: andere Regeln", "При купівлі нерухомості комісію можуть платити й покупець, і продавець; розмір та обмеження перевіряйте до підпису Kaufanbot чи договору. Попросіть письмово вказати, хто саме замовив послугу, суму з ПДВ і момент виникнення обов’язку платити.", "Beim Immobilienkauf können Käufer und Verkäufer Provision schulden; Höhe und Grenzen prüfen Sie vor Kaufanbot oder Vertrag. Verlangen Sie schriftlich Auftraggeber, Betrag einschließlich Umsatzsteuer und Zeitpunkt der Zahlungspflicht.", source: purchaseCosts),
            .init("pressure", "exclamationmark.triangle", "Якщо вимагають сумнівний платіж", "Bei fragwürdiger Forderung", "Не платіть «комісію», «сервісний внесок» чи «резервування» лише на словах. Попросіть правову підставу, договір посередництва й рахунок. Якщо вимогу не можете перевірити, зверніться до AK або консультації захисту споживачів.", "Zahlen Sie „Provision“, „Servicegebühr“ oder „Reservierung“ nicht bloß auf Zuruf. Verlangen Sie Rechtsgrundlage, Maklervertrag und Rechnung. Lassen Sie zweifelhafte Forderungen bei AK oder Verbraucherberatung prüfen.", source: broker)
        ], sources: [broker, purchaseCosts, purchaseOffer]
    )
}
