import Foundation

extension HousingGuides {
    static let tenantRights = DirectoryGuide(
        cardSummary: .init(ukrainian: "Ремонт, цвіль, тиша, приватність і зменшення оренди", german: "Reparaturen, Schimmel, Ruhe, Privatsphäre und Mietminderung"),
        introduction: .init(ukrainian: "Обсяг прав залежить від договору та дії MRG, але дефекти й небезпеку слід одразу документувати й повідомляти письмово.", german: "Der genaue Umfang hängt von Vertrag und MRG ab; dokumentieren und melden Sie Mängel und Gefahren sofort schriftlich."),
        sections: [
            .init("repair", "wrench", "Хто ремонтує", "Wer repariert", "Власник або управитель має виконувати визначені законом ремонти, зокрема серйозні пошкодження будинку, небезпечні дефекти та обслуговування зданої разом із квартирою опалювальної техніки. Наймач має берегти квартиру, повідомляти про проблеми та виконувати свої договірні обов’язки. Не замовляйте дорогий ремонт за чужий рахунок без погодження або правової поради.", "Vermietung oder Verwaltung muss gesetzlich geschuldete Erhaltung leisten, etwa schwere Gebäudeschäden, gefährliche Mängel und Reparaturen mitvermieteter Heizgeräte. Mietende müssen sorgfältig nutzen, Schäden melden und eigene Vertragspflichten erfüllen. Beauftragen Sie teure Arbeiten auf fremde Rechnung nicht ohne Abstimmung oder Rechtsrat.", source: DirectorySource(name: "AK Wien · Erhaltungspflichten", url: "https://wien.arbeiterkammer.at/beratung/Wohnen/miete/Erhaltungspflicht_des_Vermieters.html")),
            .init("mould", "drop.triangle", "Цвіль і відсутність тепла", "Schimmel und Heizungsausfall", "Сфотографуйте дефект, запишіть дату, повідомте орендодавця/управителя письмово та попросіть усунення. Якщо користування житлом істотно обмежено, може виникнути право на Mietzinsminderung. Не зменшуйте платіж самостійно без консультації: неправильно розрахована сума створює борг.", "Fotografieren Sie den Mangel, notieren Sie das Datum und fordern Sie Vermietung/Verwaltung schriftlich zur Behebung auf. Bei beeinträchtigter Nutzbarkeit kann Mietzinsminderung entstehen. Kürzen Sie nicht ohne Beratung eigenmächtig; eine falsche Höhe erzeugt Rückstände.", source: defects),
            .init("conflict", "person.2", "Спір із власником", "Streit mit Vermietung", "Зберігайте договір, платежі, фото й листування. Для перевірки оренди, експлуатаційних витрат або застави зверніться до Arbeiterkammer, Mietervereinigung або, де доступно, Schlichtungsstelle. Не підписуйте відмову від прав чи визнання боргу, якщо не розумієте наслідків.", "Bewahren Sie Vertrag, Zahlungen, Fotos und Schriftverkehr auf. Lassen Sie Miete, Betriebskosten oder Kaution bei Arbeiterkammer, Mietervereinigung oder zuständiger Schlichtungsstelle prüfen. Unterschreiben Sie keinen Rechtsverzicht oder ein Schuldanerkenntnis ohne Verständnis der Folgen.", source: akRent)
        ], sources: [akRent, defects, deposit]
    )

    static let ending = DirectoryGuide(
        cardSummary: .init(ukrainian: "Попередження, повернення житла й допомога при боргах", german: "Kündigung, Rückgabe und Hilfe bei Mietschulden"),
        introduction: .init(ukrainian: "Право та строк дострокового виходу залежать від договору й типу житла. Не покладайтеся лише на усну домовленість.", german: "Recht und Frist der vorzeitigen Kündigung hängen von Vertrag und Wohnform ab. Verlassen Sie sich nicht auf mündliche Absprachen."),
        sections: [
            .init("notice", "calendar", "Як розірвати", "Wie kündigen", "Перевірте, чи договір строковий, чи діє MRG і яка форма повідомлення потрібна. Для багатьох строкових квартир MRG наймач може після першого року розірвати з попередженням за 3 місяці; для одно- й двосімейних будинків можливості можуть залежати від договору. Надішліть повідомлення так, щоб зберегти доказ отримання.", "Prüfen Sie Befristung, MRG-Geltung und verlangte Form. Bei vielen befristeten MRG-Wohnungen können Mietende nach dem ersten Jahr mit 3 Monaten Frist kündigen; bei Ein- und Zweifamilienhäusern kann es vom Vertrag abhängen. Senden Sie die Kündigung mit Zustellnachweis.", source: akContract),
            .init("handover", "key", "Повернення квартири", "Wohnungsrückgabe", "Узгодьте дату передачі, складіть протокол із фото, показниками лічильників і всіма ключами. Звичайний знос не є підставою автоматично втратити заставу. Вимагайте письмовий розрахунок будь-яких утримань.", "Vereinbaren Sie die Übergabe, dokumentieren Sie Zustand, Fotos, Zählerstände und sämtliche Schlüssel. Normale Abnutzung rechtfertigt nicht automatisch Kautionsabzüge. Verlangen Sie eine schriftliche Abrechnung aller Abzüge.", source: deposit),
            .init("arrears", "lifepreserver", "Якщо загрожує виселення", "Bei drohender Räumung", "Не ігноруйте листи суду, власника чи управителя. WOHNSCHIRM MIETE пропонує безкоштовну перевірку допомоги з боргом за житло або необхідним переїздом; при бездомності дивіться Housing First. Зверніться до консультації якомога раніше й візьміть договір, доходи та листи про борг.", "Ignorieren Sie Schreiben von Gericht, Vermietung oder Verwaltung nicht. WOHNSCHIRM MIETE prüft kostenlos Hilfe bei Mietschulden oder notwendigem Umzug; bei Wohnungslosigkeit gibt es Housing First. Suchen Sie früh Beratung mit Vertrag, Einkommen und Mahnungen.", source: housingHelp)
        ], sources: [akContract, deposit, housingHelp]
    )

    static let shared = DirectoryGuide(
        cardSummary: .init(ukrainian: "WG, головний наймач, піднайм і спільні витрати", german: "WG, Hauptmiete, Untermiete und gemeinsame Kosten"),
        introduction: .init(ukrainian: "Кімната в WG може бути дешевшою, але ваші права залежать від того, з ким саме укладено договір.", german: "Ein WG-Zimmer kann günstiger sein; Ihre Rechte hängen davon ab, mit wem der Vertrag besteht."),
        sections: [
            .init("models", "person.3", "Три схеми WG", "Drei WG-Modelle", "Можна бути співнаймачем у спільному договорі, піднаймачем головного наймача або мати окрему оренду кімнати. Перевірте відповідальність за повну оренду, право на кімнату, користування кухнею, строк і можливість виходу. Застава має бути підтверджена тим, хто її отримав.", "Möglich sind gemeinsamer Mietvertrag, Untermiete bei Hauptmieter*in oder eigener Zimmervertrag. Prüfen Sie Haftung für Gesamtmiete, Zimmerrecht, Küchennutzung, Dauer und Ausstieg. Die Kaution muss von der empfangenden Person quittiert werden.", source: akContract),
            .init("permission", "checkmark.shield", "Піднайм та адреса", "Untermiete und Anmeldung", "Уточніть, чи дозволений піднайм за головним договором і законом; попросіть його показати. Людина, яка фактично надає вам проживання (власник або головний наймач), підписує Meldezettel. Реєстрація адреси не перетворює піднайм на головну оренду.", "Prüfen Sie, ob Untervermietung nach Hauptvertrag und Gesetz zulässig ist; lassen Sie den Vertrag zeigen. Wer Ihnen tatsächlich Unterkunft gewährt (Eigentümer*in oder Hauptmieter*in), unterschreibt den Meldezettel. Eine Anmeldung macht aus Untermiete keine Hauptmiete.", source: moving),
            .init("daily", "list.bullet", "Домовленості всередині WG", "WG-Absprachen", "Запишіть, хто платить електрику, інтернет, опалення, побутові речі, як змінюються співмешканці й повертається застава. Для навчання чи статусу перебування перевірте, чи прийме орган саме цей договір як доказ належного житла.", "Halten Sie Strom, Internet, Heizung, gemeinsame Anschaffungen, Bewohnerwechsel und Kautionsrückgabe schriftlich fest. Für Studium oder Aufenthalt klären Sie, ob die Behörde genau diesen Vertrag als Unterkunftsnachweis akzeptiert.", source: akContract)
        ], sources: [akContract, moving, wgGesucht]
    )

    static let studentHomes = DirectoryGuide(
        cardSummary: .init(ukrainian: "OeAD, студентські будинки, кімнати та строки подачі", german: "OeAD, Wohnheime, Zimmer und Bewerbungsfristen"),
        introduction: .init(ukrainian: "В Австрії університет зазвичай не видає кімнату автоматично разом із зарахуванням. Подаватися на житло потрібно окремо й завчасно.", german: "In Österreich vergeben Hochschulen mit der Zulassung normalerweise nicht automatisch ein Zimmer. Bewerben Sie sich getrennt und frühzeitig."),
        sections: [
            .init("options", "building.2", "Які є формати", "Wohnformen", "Порівняйте студентський гуртожиток, OeAD student housing, WG і приватну квартиру. У гуртожитку перевірте, чи ціна за кімнату або місце, що включено, чи є кухня, пральня, літнє проживання та кімнати для сімей. Місць може не бути вже до початку семестру.", "Vergleichen Sie Wohnheim, OeAD student housing, WG und Privatwohnung. Im Heim prüfen Sie Zimmer- oder Bettpreis, Leistungen, Küche, Waschen, Sommernutzung und Familienzimmer. Plätze können schon vor Semesterbeginn ausgebucht sein.", source: oeAD),
            .init("apply", "calendar.badge.clock", "Як податися", "Wie bewerben", "Відкрийте офіційний сайт оператора, оберіть місто й подайте заявку з підтвердженням навчання, документом особи та датами проживання. Уточніть вступний внесок, заставу, правила скасування й дату отримання ключів. Не надсилайте кошти людині, яка видає себе за адміністратора в месенджері.", "Nutzen Sie die offizielle Betreiberseite, wählen Sie Stadt und bewerben Sie sich mit Studiennachweis, Ausweis und Wohnzeitraum. Prüfen Sie Bearbeitungsgebühr, Kaution, Storno und Schlüsseltermin. Zahlen Sie nicht an Personen, die sich im Messenger als Heimverwaltung ausgeben.", source: oeADHomes),
            .init("contract", "doc.text", "Правила гуртожитку", "Heimvertrag", "Студентський Heimvertrag може мати інші правила, ніж звичайна квартира за MRG. Прочитайте тривалість, право розірвання, правила гостей, інтернет, прибирання й умови продовження. Якщо живете в WG, перевірте, хто головний наймач.", "Ein Heimvertrag kann anderen Regeln folgen als eine gewöhnliche MRG-Wohnung. Lesen Sie Dauer, Kündigung, Gäste, Internet, Reinigung und Verlängerung. Bei WG prüfen Sie, wer Hauptmieter*in ist.", source: oeAD)
        ], sources: [oeAD, oeADHomes, wgGesucht]
    )
}
