import Foundation

enum InsuranceGuides {
    private static let displaced = DirectorySource(name: "ÖGK · Krankenversicherung für Ukraine-Vertriebene", url: "https://www.oegk.at/cdscontent/?contentid=10007.884366&portal=oegkportal")
    private static let basicCare = DirectorySource(name: "BBU · Ukraine FAQ", url: "https://www.bbu.gv.at/ukraine-info-faq-ukrainian")
    private static let insurers = DirectorySource(name: "Gesundheitsportal · Sozialversicherungsträger", url: "https://www.gesundheit.gv.at/service/gesundheitssuche/sozialversicherungstraeger.html")
    private static let selfInsurance = DirectorySource(name: "ÖGK · Selbstversicherung", url: "https://www.oegk.at/cdscontent/?contentid=10007.867315&portal=oegkportal")
    private static let studentInsurance = DirectorySource(name: "ÖGK · Selbstversicherung für Studierende", url: "https://www.oegk.at/cdscontent/?contentid=10007.913304&portal=oegkportal")
    private static let familyInsurance = DirectorySource(name: "ÖGK · Mitversicherung", url: "https://www.oegk.at/cdscontent/?contentid=10007.867502")
    private static let household = DirectorySource(name: "Arbeiterkammer · Haushaltsversicherung", url: "https://ooe.arbeiterkammer.at/beratung/konsumentenschutz/versichern/Haushaltsversicherung.html")
    private static let car = DirectorySource(name: "Arbeiterkammer · Kfz-Versicherung", url: "https://www.arbeiterkammer.at/beratung/konsument/Versicherungen/versicherung-auswaehlen/Kfz-Versicherung.html")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "ukrainian-cover": ukrainianCover
        case "health-cover": healthCover
        case "family-cover": familyCover
        case "other-cover": otherCover
        default: nil
        }
    }

    private static let ukrainianCover = DirectoryGuide(
        cardSummary: .init(ukrainian: "Посвідчення переміщеної особи більше не означає автоматичного страхування", german: "Vertriebenenausweis bedeutet keine automatische Krankenversicherung"),
        introduction: .init(ukrainian: "Автоматичне медичне страхування переміщених осіб завершилося у 2025 році. Перевірте актуальний страховий статус кожного члена сім’ї, навіть якщо маєте e-card.", german: "Die automatische Krankenversicherung für Vertriebene endete 2025. Prüfen Sie den aktuellen Anspruch jedes Familienmitglieds, auch wenn eine e-card vorhanden ist."),
        sections: [
            .init("check", "checkmark.shield", "Перевірте статус у касі", "Anspruch bei der Kasse prüfen", "Зверніться до ÖGK або свого страховика й запитайте письмово, чи є зараз право на лікування, на якій підставі та з якої дати. Наявність e-card або посвідчення переміщеної особи сама по собі цього не доводить. Окремо перевірте дітей і партнерів.", "Fragen Sie ÖGK oder Ihren Träger schriftlich, ob aktuell ein Leistungsanspruch besteht, auf welcher Grundlage und seit wann. e-card und Vertriebenenausweis allein beweisen keinen Anspruch. Kinder und Partner getrennt prüfen.", source: displaced),
            .init("paths", "arrow.triangle.branch", "Виберіть законну підставу", "Passenden Versicherungsweg wählen", "Залежно від ситуації можливі обов’язкове страхування через роботу, Mitversicherung через члена сім’ї, самострахування або страхування в межах Grundversorgung при нужденності. Для студента перевірте пільгове самострахування та його умови. Не подавайтеся на дорогий тариф, поки не перевірили інші підстави.", "Je nach Lage kommen Pflichtversicherung durch Arbeit, Mitversicherung über Angehörige, Selbstversicherung oder bei Hilfsbedürftigkeit die Grundversorgung infrage. Studierende prüfen die begünstigte Selbstversicherung. Beantragen Sie keinen teuren Tarif, bevor andere Wege geklärt sind.", source: displaced),
            .init("basic", "building.2", "Страхування через Grundversorgung", "Versicherung über Grundversorgung", "Якщо не можете забезпечити проживання з власних коштів, подайте заяву до відповідної служби вашої землі. Може надаватися й окрема частина допомоги для медичного забезпечення; рішення залежить від перевірки потреби. Попросіть підтвердження включення до страхування, не вважайте, що подання заяви вже дало покриття.", "Wenn Sie Ihren Lebensunterhalt nicht selbst bestreiten können, beantragen Sie Grundversorgung bei der zuständigen Landesstelle. Auch Krankenversorgung als Teilleistung kann geprüft werden. Lassen Sie sich die tatsächliche Aufnahme in den Versicherungsschutz bestätigen; der Antrag allein ist keine Deckung.", source: basicCare),
            .init("gap", "exclamationmark.triangle", "Якщо між страховками є перерва", "Lücke im Versicherungsschutz", "До планового лікування з’ясуйте дату початку нового покриття і можливий період очікування самострахування. Негайна медична допомога доступна й без оформленої картки, але рахунок може лишитися на вас. При загрозі життю телефонуйте 144, а питання оплати вирішуйте після надання допомоги.", "Vor planbarer Behandlung Beginn des neuen Anspruchs und mögliche Wartezeit der Selbstversicherung klären. Notfallhilfe ist auch ohne Karte möglich, Kosten können aber bei Ihnen bleiben. Bei Lebensgefahr 144 wählen und die Finanzierung danach klären.", source: selfInsurance)
        ], sources: [displaced, basicCare, selfInsurance, studentInsurance]
    )

    private static let healthCover = DirectoryGuide(
        cardSummary: .init(ukrainian: "ÖGK, SVS, BVAEB, самострахування й періоди очікування", german: "ÖGK, SVS, BVAEB, Selbstversicherung und Wartezeiten"),
        introduction: .init(ukrainian: "Тип страхування залежить від роботи, навчання, сім’ї та соціальної допомоги. Страховик і дата початку покриття важливіші за наявність картки.", german: "Die Versicherungsart hängt von Arbeit, Studium, Familie und Sozialleistungen ab. Zuständiger Träger und Beginn sind wichtiger als die Karte."),
        sections: [
            .init("identify", "person.text.rectangle", "Хто є вашим страховиком", "Zuständigen Träger ermitteln", "За звичайною найманою роботою це часто ÖGK, для самозайнятості — SVS, для деяких державних службовців — BVAEB. Попросіть роботодавця підтвердити реєстрацію й дату; самозайняті перевіряють обов’язки в SVS. Якщо ви безробітні, уточніть окремо, чи дає ваша виплата або статус право на покриття.", "Bei üblicher Anstellung ist oft die ÖGK zuständig, bei Selbständigkeit die SVS, für manche öffentliche Beschäftigte die BVAEB. Arbeitgeber nach Anmeldung und Beginn fragen; Selbständige prüfen SVS-Pflichten. Bei Arbeitslosigkeit klären Sie, ob Ihre konkrete Leistung oder Ihr Status Deckung auslöst.", source: insurers),
            .init("self", "doc.text", "Самострахування", "Selbstversicherung", "Якщо немає іншої підстави, подайте заяву до ÖGK та попросіть обчислити дату початку, внесок і право на зниження внеску. У звичайному самострахуванні може діяти шестимісячне очікування; попередні страхові періоди можуть його усунути. Заява невдовзі після завершення попереднього страхування важлива для безперервності. Не припускайте, що оплата першого внеску означає негайне покриття всіх послуг.", "Ohne andere Grundlage können Sie Selbstversicherung bei der ÖGK beantragen. Fragen Sie nach Beginn, Beitrag und möglicher Herabsetzung. Bei allgemeiner Selbstversicherung kann eine Wartezeit von sechs Monaten gelten; Vorversicherungszeiten können sie beseitigen. Rascher Antrag nach Ende der Vorversicherung ist für nahtlosen Anschluss wichtig. Die erste Zahlung allein garantiert keinen sofortigen vollen Anspruch.", source: selfInsurance),
            .init("study", "graduationcap", "Якщо навчаєтеся", "Während des Studiums", "Для студентів існує окремий пільговий тариф за виконання умов. Перевірте зарахування, вік, попередню тривалість навчання, дохід і дату початку; правила відрізняються від звичайного самострахування. Порівняйте цей шлях із безкоштовною Mitversicherung, якщо вона ще можлива.", "Für Studierende gibt es bei erfüllten Bedingungen eine begünstigte Selbstversicherung. Prüfen Sie Zulassung, Alter, Studiendauer, Einkommen und Beginn; Regeln unterscheiden sich von der allgemeinen Selbstversicherung. Vergleichen Sie mit möglicher kostenfreier Mitversicherung.", source: studentInsurance),
            .init("proof", "checkmark.circle", "Перед прийомом перевірте право", "Anspruch vor dem Termin prüfen", "Попросіть у страховика підтвердження страхового статусу або Versicherungsdatenauszug. Для планового приватного лікування з’ясуйте, чи послуга покривається та чи потрібне направлення. Зміна роботи, статусу або адреси може змінити умови — перевірте повторно.", "Lassen Sie Anspruch oder Versicherungsdatenauszug bestätigen. Vor geplanter privater Behandlung Deckung und Überweisung prüfen. Änderungen bei Arbeit, Status oder Wohnsitz können den Anspruch ändern – erneut nachfragen.", source: insurers)
        ], sources: [insurers, selfInsurance, studentInsurance]
    )

    private static let familyCover = DirectoryGuide(
        cardSummary: .init(ukrainian: "Як застрахувати дитину або партнера й коли є додатковий внесок", german: "Kinder und Partner mitversichern und Zusatzbeitrag klären"),
        introduction: .init(ukrainian: "Mitversicherung перевіряється для кожного члена сім’ї окремо. Родинний зв’язок не завжди означає автоматичне включення.", german: "Mitversicherung wird für jedes Familienmitglied gesondert geprüft. Verwandtschaft allein bewirkt nicht immer automatische Aufnahme."),
        sections: [
            .init("children", "figure.child", "Діти", "Kinder", "Повідомте страховику про народження або переїзд дитини й перевірте, чи внесено її як Angehörige. Підготуйте свідоцтво про народження, дані батьків, документи про перебування та навчання для старших дітей. Вікові межі й продовження під час навчання залежать від умов — запитайте письмово.", "Melden Sie Geburt oder Zuzug eines Kindes dem Träger und prüfen Sie die Aufnahme als Angehörige. Bereiten Sie Geburtsurkunde, Elternangaben, Aufenthalts- und bei älteren Kindern Ausbildungsnachweise vor. Altersgrenzen und Verlängerung während Ausbildung schriftlich klären.", source: familyInsurance),
            .init("partner", "person.2", "Подружжя та партнери", "Ehe und Partnerschaft", "Партнер може бути співзастрахований за встановлених умов, якщо не має власного страхування. Для подружжя та зареєстрованих партнерів може стягуватися додатковий внесок, але є винятки, зокрема за виховання дітей. Для фактичного партнерства діють окремі вимоги щодо спільного проживання. Не покладайтеся лише на Meldezettel — подайте потрібні документи до каси.", "Partner können unter Voraussetzungen mitversichert sein, wenn keine eigene Versicherung besteht. Für Ehe- und eingetragene Partner kann ein Zusatzbeitrag gelten; Ausnahmen gibt es etwa bei Kindererziehung. Für Lebensgemeinschaften gelten weitere Anforderungen an den gemeinsamen Haushalt. Meldezettel allein reicht nicht: Unterlagen beim Träger einreichen.", source: familyInsurance),
            .init("change", "arrow.triangle.2.circlepath", "Коли сімейний статус змінюється", "Bei Änderungen im Haushalt", "Після початку роботи, завершення навчання, розлучення або переїзду повідомте касу. Попросіть дату припинення попереднього й початку нового покриття. Для дитини після розлучення батьків перевірте, через кого й далі діє страхування.", "Arbeitsbeginn, Ausbildungsende, Trennung oder Umzug der Kasse melden. Lassen Sie Ende und Beginn des Anspruchs bestätigen. Nach Trennung der Eltern prüfen, über wen das Kind weiter versichert ist.", source: familyInsurance)
        ], sources: [familyInsurance]
    )

    private static let otherCover = DirectoryGuide(
        cardSummary: .init(ukrainian: "Приватна відповідальність, житло, авто й подорожі без зайвих полісів", german: "Privathaftpflicht, Haushalt, Auto und Reisen sinnvoll prüfen"),
        introduction: .init(ukrainian: "Державне медичне страхування не замінює захисту від інших ризиків. Перш ніж купувати поліс, визначте ризик, покриття та вже наявні договори.", german: "Gesetzliche Krankenversicherung ersetzt keinen Schutz gegen andere Risiken. Vor Abschluss Bedarf, Deckung und bestehende Verträge prüfen."),
        sections: [
            .init("liability", "person.crop.circle.badge.checkmark", "Приватна відповідальність і житло", "Privathaftpflicht und Haushalt", "Haushaltsversicherung зазвичай поєднує захист домашнього майна з приватною відповідальністю перед третіми особами. Порівняйте страхову суму, самостійний внесок, збитки від води, крадіжки, грубої необережності та склад сім’ї. Дізнайтеся, чи договір орендодавця покриває саме ваше майно — зазвичай це різні ризики.", "Haushaltsversicherung verbindet meist Hausrat mit Privathaftpflicht. Vergleichen Sie Versicherungssumme, Selbstbehalt, Wasser-, Diebstahl- und grobe Fahrlässigkeitsschäden sowie mitversicherte Personen. Vermieterversicherung deckt gewöhnlich andere Risiken als Ihr Hausrat.", source: household),
            .init("car", "car", "Автомобіль", "Auto", "Для зареєстрованого в Австрії авто потрібна Kfz-Haftpflicht; Teilkasko та Vollkasko є додатковими. Перевірте, де й на кого авто зареєстроване, територію дії полісу, бонус-малус, франшизу та покриття водіїв. Не плутайте захист потерпілих з оплатою ремонту власного авто.", "Für ein in Österreich zugelassenes Auto ist Kfz-Haftpflicht Pflicht; Teil- und Vollkasko sind Zusatzschutz. Prüfen Sie Zulassung, Gebiet, Bonus-Malus, Selbstbehalt und Fahrer. Haftpflicht für Dritte ist nicht gleich Reparatur des eigenen Autos.", source: car),
            .init("travel", "airplane", "Подорожі та приватні поліси", "Reisen und private Policen", "Перед поїздкою перевірте, чи діє ваш державний страховий захист за кордоном і які витрати він не покриває, наприклад повернення додому. Для приватного полісу порівняйте виключення, хронічні стани, початок дії, строк та процедуру звернення. Зберігайте номер допомоги й договір окремо від телефона.", "Vor Reisen prüfen, wo die gesetzliche Deckung gilt und welche Kosten sie nicht trägt, etwa Rücktransport. Bei Privatpolicen Ausschlüsse, Vorerkrankungen, Beginn, Laufzeit und Meldeweg vergleichen. Notrufnummer und Police getrennt vom Telefon aufbewahren.", source: insurers),
            .init("claim", "doc.text.magnifyingglass", "Як діяти при збитку", "Im Schadenfall", "Спочатку забезпечте безпеку людей і за потреби викличте 144, 122 або поліцію. Зафіксуйте дату, місце, фото та контакти свідків. Повідомте страховика у строк договору й не визнавайте спірну відповідальність без консультації. Попросіть письмову відповідь, якщо виплату відхилено.", "Zuerst Menschen schützen und nötigenfalls 144, 122 oder Polizei rufen. Datum, Ort, Fotos und Zeugen festhalten. Schaden innerhalb der Vertragsfrist melden und strittige Haftung nicht vorschnell anerkennen. Ablehnung schriftlich verlangen.", source: household)
        ], sources: [household, car, insurers]
    )
}
