import Foundation

enum InsuranceGuides {
    private static let displaced = DirectorySource(name: "ÖGK · Krankenversicherung für Ukraine-Vertriebene", url: "https://www.oegk.at/cdscontent/?contentid=10007.884366&portal=oegkportal")
    private static let basicCare = DirectorySource(name: "BBU · Ukraine FAQ", url: "https://www.bbu.gv.at/ukraine-info-faq-ukrainian")
    private static let insurers = DirectorySource(name: "Gesundheitsportal · Sozialversicherungsträger", url: "https://www.gesundheit.gv.at/service/gesundheitssuche/sozialversicherungstraeger.html")
    private static let insuranceRecord = DirectorySource(name: "Meine ÖGK · Versicherungsdatenauszug", url: "https://meine.oegk.at/cdscontent/?contentid=10007.883235&portal=oegkportal")
    private static let selfInsurance = DirectorySource(name: "ÖGK · Selbstversicherung", url: "https://www.oegk.at/cdscontent/?contentid=10007.867315&portal=oegkportal")
    private static let studentInsurance = DirectorySource(name: "ÖGK · Selbstversicherung für Studierende", url: "https://www.oegk.at/cdscontent/?contentid=10007.913304&portal=oegkportal")
    private static let marginalInsurance = DirectorySource(name: "ÖGK · Selbstversicherung bei geringfügiger Beschäftigung", url: "https://www.oegk.at/cdscontent/?contentid=10007.870435&portal=oegkportal")
    private static let familyInsurance = DirectorySource(name: "ÖGK · Mitversicherung", url: "https://www.oegk.at/cdscontent/?contentid=10007.867502")
    private static let childInsurance = DirectorySource(name: "ÖGK · Mitversicherung Kinder", url: "https://www.oegk.at/cdscontent/?contentid=10007.870502")
    private static let partnerInsurance = DirectorySource(name: "ÖGK · Mitversicherung Partner", url: "https://www.oegk.at/cdscontent/?contentid=10007.905085")
    private static let household = DirectorySource(name: "Arbeiterkammer · Haushaltsversicherung", url: "https://ooe.arbeiterkammer.at/beratung/konsumentenschutz/versichern/Haushaltsversicherung.html")
    private static let householdClaim = DirectorySource(name: "Arbeiterkammer OÖ · Pflichten im Schadensfall", url: "https://ooe.arbeiterkammer.at/beratung/konsumentenschutz/versichern/Obliegenheiten-beachten-damit-Versicherung-zahlt.html")
    private static let car = DirectorySource(name: "Arbeiterkammer · Kfz-Versicherung", url: "https://www.arbeiterkammer.at/beratung/konsument/Versicherungen/versicherung-auswaehlen/Kfz-Versicherung.html")
    private static let travel = DirectorySource(name: "ÖGK · Urlaub im Ausland", url: "https://www.oegk.at/cdscontent/?contentid=10007.907080")
    private static let privateHealth = DirectorySource(name: "Arbeiterkammer OÖ · Private Krankenversicherung", url: "https://ooe.arbeiterkammer.at/beratung/konsumentenschutz/versichern/Private_Krankenversicherung.html")
    private static let privateAccident = DirectorySource(name: "Arbeiterkammer OÖ · Private Unfallversicherung", url: "https://ooe.arbeiterkammer.at/beratung/konsumentenschutz/versichern/Private_Unfallversicherung.html")
    private static let legalProtection = DirectorySource(name: "Arbeiterkammer OÖ · Rechtsschutzversicherung", url: "https://ooe.arbeiterkammer.at/beratung/konsumentenschutz/versichern/Rechtsschutzversicherung-Preise-und-Leistungen.html")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "ukrainian-cover": ukrainianCover
        case "health-cover": healthCover
        case "family-cover": familyCover
        case "other-cover": otherCover
        default: nil
        }
    }

    private static let ukrainianCover = DirectoryGuide(
        cardSummary: .init(ukrainian: "Посвідчення переміщеної особи більше не означає автоматичного страхування", german: "Vertriebenenausweis bedeutet keine automatische Krankenversicherung"),
        introduction: .init(ukrainian: "Автоматичне медичне страхування переміщених осіб завершилося 31 травня 2025 року; перехідний строк закінчився 12 липня. Тепер перевіряйте окрему підставу страхування для кожного члена сім’ї — навіть за наявності e-card.", german: "Die automatische Krankenversicherung für Vertriebene endete am 31. Mai 2025; die Übergangsfrist lief am 12. Juli aus. Prüfen Sie nun für jedes Familienmitglied eine eigene Anspruchsgrundlage – auch mit e-card."),
        sections: [
            .init("check", "checkmark.shield", "Перевірте статус у касі", "Anspruch bei der Kasse prüfen", "Зверніться до ÖGK або свого страховика й запитайте письмово, чи є зараз право на лікування, на якій підставі та з якої дати. Наявність e-card або посвідчення переміщеної особи сама по собі цього не доводить. Окремо перевірте дітей і партнерів.", "Fragen Sie ÖGK oder Ihren Träger schriftlich, ob aktuell ein Leistungsanspruch besteht, auf welcher Grundlage und seit wann. e-card und Vertriebenenausweis allein beweisen keinen Anspruch. Kinder und Partner getrennt prüfen.", source: displaced),
            .init("paths", "arrow.triangle.branch", "Виберіть підставу покриття", "Anspruchsgrundlage wählen", "Після завершення автоматичного страхування послідовно перевірте: роботу з повним соціальним страхуванням; Mitversicherung через застрахованого члена сім’ї; Grundversorgung за потреби; відповідне самострахування. Окрема e-card не створює права на послуги. Для кожного шляху попросіть дату початку й підтвердження в ÖGK або відповідного страховика.", "Nach Ende der automatischen Versicherung der Reihe nach prüfen: vollversicherte Arbeit, Mitversicherung über versicherte Angehörige, Grundversorgung bei Bedarf und passende Selbstversicherung. Eine e-card allein begründet keinen Leistungsanspruch. Beginn und Bestätigung beim jeweiligen Träger erfragen.", source: displaced),
            .init("basic", "building.2", "Страхування через Grundversorgung", "Versicherung über Grundversorgung", "Якщо не можете забезпечити проживання з власних коштів, подайте заяву до відповідної служби вашої землі. Може надаватися й окрема частина допомоги для медичного забезпечення; рішення залежить від перевірки потреби. Попросіть підтвердження включення до страхування, не вважайте, що подання заяви вже дало покриття.", "Wenn Sie Ihren Lebensunterhalt nicht selbst bestreiten können, beantragen Sie Grundversorgung bei der zuständigen Landesstelle. Auch Krankenversorgung als Teilleistung kann geprüft werden. Lassen Sie sich die tatsächliche Aufnahme in den Versicherungsschutz bestätigen; der Antrag allein ist keine Deckung.", source: basicCare),
            .init("gap", "exclamationmark.triangle", "Якщо є перерва", "Lücke im Versicherungsschutz", "Запитайте страховика, з якої дати діє нове покриття та чи є очікування на послуги. При звичайному самострахуванні попередні періоди можуть скасувати шестимісячне очікування, але ÖGK має це перевірити. Перед плановим лікуванням уточніть оплату; у невідкладній ситуації телефонуйте 144, незалежно від наявності картки.", "Fragen Sie den Träger nach Beginn und Wartezeit. Bei allgemeiner Selbstversicherung können Vorversicherungszeiten die sechsmonatige Wartezeit beseitigen; die ÖGK muss dies prüfen. Vor planbarer Behandlung Kosten klären; im Notfall 144 wählen, unabhängig von der Karte.", source: selfInsurance)
        ], sources: [displaced, basicCare, selfInsurance, studentInsurance]
    )

    private static let healthCover = DirectoryGuide(
        cardSummary: .init(ukrainian: "ÖGK, SVS, BVAEB, самострахування й періоди очікування", german: "ÖGK, SVS, BVAEB, Selbstversicherung und Wartezeiten"),
        introduction: .init(ukrainian: "Тип страхування залежить від роботи, навчання, сім’ї та соціальної допомоги. Страховик і дата початку покриття важливіші за наявність картки.", german: "Die Versicherungsart hängt von Arbeit, Studium, Familie und Sozialleistungen ab. Zuständiger Träger und Beginn sind wichtiger als die Karte."),
        sections: [
            .init("identify", "person.text.rectangle", "Хто є вашим страховиком", "Zuständigen Träger ermitteln", "За звичайною найманою роботою це часто ÖGK, для самозайнятості — SVS, для деяких державних службовців — BVAEB. Попросіть роботодавця підтвердити реєстрацію й дату; самозайняті перевіряють обов’язки в SVS. Якщо ви безробітні, уточніть окремо, чи дає ваша виплата або статус право на покриття.", "Bei üblicher Anstellung ist oft die ÖGK zuständig, bei Selbständigkeit die SVS, für manche öffentliche Beschäftigte die BVAEB. Arbeitgeber nach Anmeldung und Beginn fragen; Selbständige prüfen SVS-Pflichten. Bei Arbeitslosigkeit klären Sie, ob Ihre konkrete Leistung oder Ihr Status Deckung auslöst.", source: insurers),
            .init("self", "doc.text", "Звичайне самострахування", "Allgemeine Selbstversicherung", "Якщо іншої підстави немає, подайте заяву до ÖGK. Внесок у 2026 році — 565,25 € на місяць; за фінансових підстав можна просити зниження. Подайте заяву протягом шести тижнів після завершення попереднього страхування, щоб уникнути розриву. Право на послуги зазвичай настає після шести місяців; очікування не діє за наявності шести тижнів безперервного попереднього страхування або 26 тижнів за попередні 12 місяців. Попросіть ÖGK письмово встановити дати й внесок.", "Ohne andere Grundlage bei der ÖGK beantragen. 2026 kostet dies 565,25 € monatlich; bei finanziellen Gründen kann eine Herabsetzung beantragt werden. Für einen nahtlosen Anschluss binnen sechs Wochen nach Ende der Vorversicherung beantragen. Leistungen gibt es grundsätzlich nach sechs Monaten; die Wartezeit entfällt bei sechs Wochen ununterbrochener Vorversicherung unmittelbar davor oder 26 Wochen in den letzten zwölf Monaten. Beginn und Beitrag schriftlich klären.", source: selfInsurance),
            .init("study", "graduationcap", "Якщо навчаєтеся", "Während des Studiums", "Спочатку перевірте безкоштовну Mitversicherung через батьків. Якщо вона недоступна, студентське самострахування коштує 78,84 € на місяць у 2026 році. Потрібні звичайне проживання в Австрії, відсутність іншого обов’язкового страхування та виконання правил щодо навчання, успішності й доходу. Подайте заяву до ÖGK й уточніть дату початку; сам статус студента страхування не створює.", "Zuerst die kostenlose Mitversicherung über die Eltern prüfen. Sonst kostet die studentische Selbstversicherung 2026 monatlich 78,84 €. Erforderlich sind gewöhnlicher Aufenthalt in Österreich, keine andere Pflichtversicherung und die Erfüllung der Studien-, Erfolgs- und Einkommensregeln. Antrag bei der ÖGK stellen und Beginn klären; der Studierendenstatus allein versichert nicht.", source: studentInsurance),
            .init("marginal", "briefcase", "Робота з малим доходом", "Geringfügige Beschäftigung", "Якщо заробіток не перевищує межу geringfügig (551,10 € на місяць у 2026 році), сама така робота зазвичай дає лише страхування від нещасних випадків. У ÖGK можна подати заяву на добровільне медичне й пенсійне страхування: 83,49 € на місяць у 2026 році. Якщо маєте кілька робіт, перевірте загальний дохід і фактичний страховий статус: правила можуть змінитися.", "Bei Verdienst bis zur Geringfügigkeitsgrenze (2026: 551,10 € monatlich) besteht durch diese Beschäftigung allein grundsätzlich nur Unfallversicherung. Bei der ÖGK kann eine freiwillige Kranken- und Pensionsversicherung beantragt werden: 2026 monatlich 83,49 €. Bei mehreren Jobs Gesamteinkommen und tatsächlichen Status prüfen; dann können andere Regeln gelten.", source: marginalInsurance),
            .init("proof", "checkmark.circle", "Підтвердіть право на послуги", "Leistungsanspruch bestätigen", "Через Meine ÖGK з ID Austria можна отримати Versicherungsdatenauszug про страхові періоди. Якщо потрібне лікування зараз, окремо запитайте ÖGK про поточне право на послуги: витяг за минулі періоди сам по собі його не підтверджує. Перед приватним прийомом уточніть покриття та частку відшкодування. Після зміни роботи чи статусу перевірте дані знову.", "Über Meine ÖGK mit ID Austria können Sie einen Versicherungsdatenauszug über Versicherungszeiten abrufen. Für eine Behandlung jetzt zusätzlich den aktuellen Leistungsanspruch bei der ÖGK erfragen; der Auszug über frühere Zeiten belegt ihn nicht allein. Vor einem Privattermin Deckung und Erstattung klären. Nach Arbeits- oder Statuswechsel erneut prüfen.", source: insuranceRecord)
        ], sources: [insurers, selfInsurance, studentInsurance, marginalInsurance, insuranceRecord]
    )

    private static let familyCover = DirectoryGuide(
        cardSummary: .init(ukrainian: "Як застрахувати дитину або партнера й коли є додатковий внесок", german: "Kinder und Partner mitversichern und Zusatzbeitrag klären"),
        introduction: .init(ukrainian: "Mitversicherung перевіряється для кожного члена сім’ї окремо. Родинний зв’язок не завжди означає автоматичне включення.", german: "Mitversicherung wird für jedes Familienmitglied gesondert geprüft. Verwandtschaft allein bewirkt nicht immer automatische Aufnahme."),
        sections: [
            .init("children", "figure.child", "Діти до 18 років", "Kinder bis 18", "Перевірте, чи дитину внесено до ÖGK як Angehörige після народження або переїзду; для народжених за кордоном підготуйте свідоцтво про народження. Діти зазвичай безкоштовно співзастраховані до дня перед 18-річчям, якщо виконані умови; для пасинків, прийомних дітей та онуків є додаткові вимоги. Попросіть підтвердження права на послуги окремо для кожної дитини.", "Prüfen Sie nach Geburt oder Zuzug die Aufnahme des Kindes als Angehörige bei der ÖGK; für im Ausland geborene Kinder die Geburtsurkunde vorlegen. Kinder sind unter den Voraussetzungen grundsätzlich bis einen Tag vor dem 18. Geburtstag kostenlos mitversichert; bei Stief-, Pflegekindern und Enkeln gelten zusätzliche Regeln. Anspruch für jedes Kind gesondert bestätigen lassen.", source: childInsurance),
            .init("adult-child", "graduationcap", "Після 18 років", "Nach dem 18. Geburtstag", "Після 18 років подайте докази навчання, якщо потрібне продовження. За шкільної, професійної або університетської освіти співстрахування може тривати до дня перед 27-річчям; під час навчання у виші ÖGK може вимагати щорічне підтвердження зарахування й успішності. Після завершення освіти для безробітної дитини за окремих умов можливе продовження до 24 місяців. Попросіть ÖGK перевірити конкретний випадок до завершення чинного покриття.", "Nach dem 18. Geburtstag nötige Ausbildungsnachweise für die Verlängerung einreichen. Bei Schul-, Berufs- oder Hochschulausbildung ist Mitversicherung bis einen Tag vor dem 27. Geburtstag möglich; beim Studium kann die ÖGK jährliche Studien- und Erfolgsnachweise verlangen. Nach Ausbildungsende sind bei Erwerbslosigkeit unter Bedingungen bis zu 24 weitere Monate möglich. Den Einzelfall vor Ablauf des bisherigen Anspruchs prüfen lassen.", source: childInsurance),
            .init("partner", "person.2", "Подружжя та партнери", "Ehe und Partnerschaft", "За відсутності власного державного страхування подружжя або зареєстрований партнер можуть подати заяву на Mitversicherung. Для фактичного партнера ÖGK, зокрема, вимагає щонайменше десять місяців спільного проживання й безоплатного ведення господарства. Додатковий внесок, якщо застосовується, становить 3,4% бази внесків застрахованої особи; існують винятки, зокрема для догляду за дітьми й соціальної потреби. Попросіть рішення та розрахунок у касі.", "Ohne eigene gesetzliche Versicherung können Ehe- oder eingetragene Partner die Mitversicherung beantragen. Für Lebensgefährten verlangt die ÖGK unter anderem mindestens zehn Monate gemeinsamen Haushalt und unentgeltliche Haushaltsführung. Der Zusatzbeitrag beträgt, falls fällig, 3,4 % der Beitragsgrundlage der versicherten Person; Ausnahmen gelten etwa bei Kindererziehung und sozialer Schutzbedürftigkeit. Entscheidung und Berechnung beim Träger einholen.", source: partnerInsurance),
            .init("change", "arrow.triangle.2.circlepath", "Коли сімейний статус змінюється", "Bei Änderungen im Haushalt", "Після початку роботи, завершення навчання, розлучення або переїзду повідомте касу. Попросіть дату припинення попереднього й початку нового покриття. Для дитини після розлучення батьків перевірте, через кого й далі діє страхування.", "Arbeitsbeginn, Ausbildungsende, Trennung oder Umzug der Kasse melden. Lassen Sie Ende und Beginn des Anspruchs bestätigen. Nach Trennung der Eltern prüfen, über wen das Kind weiter versichert ist.", source: familyInsurance)
        ], sources: [familyInsurance, childInsurance, partnerInsurance]
    )

    private static let otherCover = DirectoryGuide(
        cardSummary: .init(ukrainian: "Приватна відповідальність, житло, авто й подорожі без зайвих полісів", german: "Privathaftpflicht, Haushalt, Auto und Reisen sinnvoll prüfen"),
        introduction: .init(ukrainian: "Державне медичне страхування не замінює захисту від інших ризиків. Перш ніж купувати поліс, визначте ризик, покриття та вже наявні договори.", german: "Gesetzliche Krankenversicherung ersetzt keinen Schutz gegen andere Risiken. Vor Abschluss Bedarf, Deckung und bestehende Verträge prüfen."),
        sections: [
            .init("liability", "person.crop.circle.badge.checkmark", "Приватна відповідальність і житло", "Privathaftpflicht und Haushalt", "Haushaltsversicherung зазвичай поєднує захист домашнього майна з приватною відповідальністю перед третіми особами. Порівняйте страхову суму, самостійний внесок, збитки від води, крадіжки, грубої необережності та склад сім’ї. Дізнайтеся, чи договір орендодавця покриває саме ваше майно — зазвичай це різні ризики.", "Haushaltsversicherung verbindet meist Hausrat mit Privathaftpflicht. Vergleichen Sie Versicherungssumme, Selbstbehalt, Wasser-, Diebstahl- und grobe Fahrlässigkeitsschäden sowie mitversicherte Personen. Vermieterversicherung deckt gewöhnlich andere Risiken als Ihr Hausrat.", source: household),
            .init("car", "car", "Автомобіль", "Auto", "Для зареєстрованого в Австрії авто потрібна Kfz-Haftpflicht; Teilkasko та Vollkasko є додатковими. Перевірте, де й на кого авто зареєстроване, територію дії полісу, бонус-малус, франшизу та покриття водіїв. Не плутайте захист потерпілих з оплатою ремонту власного авто.", "Für ein in Österreich zugelassenes Auto ist Kfz-Haftpflicht Pflicht; Teil- und Vollkasko sind Zusatzschutz. Prüfen Sie Zulassung, Gebiet, Bonus-Malus, Selbstbehalt und Fahrer. Haftpflicht für Dritte ist nicht gleich Reparatur des eigenen Autos.", source: car),
            .init("private-health", "cross.case", "Додаткове медичне страхування", "Private Kranken-Zusatzversicherung", "Приватний поліс додає лише передбачені договором послуги до державного покриття: наприклад, Wahlärzte або Sonderklasse. Перед підписанням порівняйте річний ліміт, франшизу, строки очікування, виключення попередніх захворювань і порядок відшкодування. Уточніть, що саме покриває ваш базовий страховик, щоб не платити двічі за однакові послуги.", "Eine private Police ergänzt die gesetzliche Deckung nur um vertraglich vereinbarte Leistungen, etwa Wahlarzt oder Sonderklasse. Vor Abschluss Jahreslimits, Selbstbehalt, Wartezeiten, Ausschlüsse bei Vorerkrankungen und Erstattung prüfen. Erst die gesetzliche Leistung klären, damit identische Leistungen nicht doppelt bezahlt werden.", source: privateHealth),
            .init("accident", "figure.fall", "Нещасні випадки у вільний час", "Unfälle in der Freizeit", "Державне страхування від нещасних випадків переважно стосується роботи й дороги на роботу; лікування травми у вільний час може покривати медичне страхування, але це не означає додаткової виплати за постійну інвалідність. Якщо порівнюєте приватний поліс, перевірте страхову суму, шкалу інвалідності, рятувальні витрати, спорт і винятки. Окремо оцініть захист доходу при тривалій непрацездатності: це інший ризик.", "Die gesetzliche Unfallversicherung betrifft vor allem Arbeit und Arbeitsweg; die Krankenversicherung kann Freizeitverletzungen behandeln, gewährt aber deshalb keine zusätzliche Invaliditätsleistung. Bei einer privaten Police Versicherungssumme, Invaliditätsstaffel, Bergungskosten, Sport und Ausschlüsse vergleichen. Langfristigen Einkommensausfall bei Berufsunfähigkeit gesondert prüfen: Das ist ein anderer Schutz.", source: privateAccident),
            .init("legal", "building.columns", "Правовий захист", "Rechtsschutz", "Rechtsschutzversicherung може оплачувати визначені договором витрати спору, але не всі види справ. Перевірте модулі (житло, праця, транспорт), виключення, строк очікування, суму покриття й участь у витратах. Наявні суперечки часто не покриваються, а в трудових питаннях спочатку дізнайтеся про підтримку Arbeiterkammer. Не купуйте поліс, не прочитавши умови саме потрібного вам спору.", "Rechtsschutz kann vertraglich definierte Streitkosten tragen, aber nicht jeden Fall. Bausteine (Wohnen, Arbeit, Verkehr), Ausschlüsse, Wartefrist, Deckungssumme und Selbstbehalt prüfen. Bereits bestehende Konflikte sind oft nicht gedeckt; bei Arbeitsfragen zuerst die Unterstützung der Arbeiterkammer prüfen. Bedingungen für den konkret benötigten Streit lesen.", source: legalProtection),
            .init("travel", "airplane", "Подорожі", "Reisen", "Перевірте зворотний бік фізичної e-card: Європейська картка медичного страхування діє для необхідної допомоги під час тимчасового перебування в ЄС/ЄЕЗ, Швейцарії та Великій Британії. В інших країнах правила інші; ÖGK не оплачує медичне повернення додому. Перед поїздкою з’ясуйте країну дії, власні доплати й умови окремого полісу, зокрема щодо хронічних хвороб та евакуації.", "Rückseite der physischen e-card prüfen: Die Europäische Krankenversicherungskarte gilt für notwendige Versorgung bei vorübergehendem Aufenthalt in EU/EWR, Schweiz und Vereinigtem Königreich. Anderswo gelten andere Regeln; Krankenrücktransport zahlt die ÖGK nicht. Vor Reise Zielland, Eigenkosten und Bedingungen einer Zusatzpolice zu Vorerkrankungen und Rücktransport klären.", source: travel),
            .init("claim", "doc.text.magnifyingglass", "Як діяти при збитку", "Im Schadenfall", "Зменшіть подальшу шкоду, наскільки це безпечно. Зробіть фото, список пошкодженого, збережіть чеки та дані свідків. Негайно повідомте страховика, бажано письмово, і дотримуйтеся строку у своєму договорі. За пожежі, крадіжки або ДТП з неясними обставинами повідомте поліцію. До дорогого ремонту узгодьте дії зі страховиком; за відмови попросіть письмове обґрунтування.", "Weitere Schäden soweit gefahrlos mindern. Fotos, Liste beschädigter Sachen, Belege und Zeugendaten sichern. Versicherer unverzüglich, möglichst schriftlich informieren und die Vertragsfrist beachten. Bei Brand, Diebstahl oder Unfall mit unklarem Hergang die Polizei verständigen. Teure Reparaturen vorher mit dem Versicherer abstimmen; bei Ablehnung schriftliche Begründung verlangen.", source: householdClaim)
        ], sources: [household, car, privateHealth, privateAccident, legalProtection, travel, householdClaim]
    )
}
