import Foundation

enum LeisureGuides {
    private static let movement = DirectorySource(name: "Gesundheitsportal · Bewegungsempfehlungen", url: "https://www.gesundheit.gv.at/leben/bewegung/gesund-durch-sport.html")
    private static let activity = DirectorySource(name: "Gesundheitsportal · Bewegung im Alltag", url: "https://www.gesundheit.gv.at/leben/bewegung/gesunde-bewegung/alltag.html")
    private static let children = DirectorySource(name: "Gesundheitsportal · Kinder und Bewegung", url: "https://www.gesundheit.gv.at/leben/bewegung/gesunde-bewegung/kinder-bewegung.html")
    private static let centers = DirectorySource(name: "ÖIF · Integrationszentren", url: "https://www.integrationsfonds.at/der-oeif/standorte/uebersicht-standorte/")
    private static let discounts = DirectorySource(name: "oesterreich.gv.at · Weitere Beihilfen und Ermäßigungen", url: "https://www.oesterreich.gv.at/de/lebenslagen/Ich-ben%C3%B6tige-finanzielle-Unterst%C3%BCtzung/finanzielle-unterst%C3%BCtzung-sonstige-beihilfen")
    private static let culturePass = DirectorySource(name: "Hunger auf Kunst und Kultur · Kulturpass", url: "https://www.hungeraufkunstundkultur.at/")
    private static let clubs = DirectorySource(name: "oesterreich.gv.at · Vereinsregister", url: "https://www.oesterreich.gv.at/de/themen/reisen_und_freizeit/vereine/Seite.220700")

    static func guide(for topicID: String) -> DirectoryGuide? {
        guard topicID == "leisure" else { return nil }
        return DirectoryGuide(
            cardSummary: .init(ukrainian: "Знайти спорт, культуру й відпочинок у своїй місцевості", german: "Sport, Kultur und Erholung am Wohnort finden"),
            introduction: .init(ukrainian: "Для дозвілля важливі не лише події, а й регулярні доступні місця поруч із домом.", german: "Für Freizeit zählen neben Veranstaltungen auch regelmäßige, erreichbare Angebote in Wohnortnähe."),
            sections: [
                .init("local", "mappin.circle", "Почніть поруч із домом", "Am Wohnort beginnen", "Запитайте Gemeinde, бібліотеку, школу, спортивний Verein або інтеграційний центр про відкриті заняття та місця зустрічі. Перед відвідуванням уточніть вік, вартість, мову, доступність, потрібне спорядження та реєстрацію. Розклад локальних подій змінюється — перевіряйте у організатора.", "Gemeinde, Bibliothek, Schule, Sportverein oder Integrationszentrum nach offenen Angeboten fragen. Alter, Kosten, Sprache, Barrierefreiheit, Ausrüstung und Anmeldung vorab klären. Lokale Termine ändern sich; beim Veranstalter prüfen.", source: centers),
                .init("budget", "eurosign.circle", "Спочатку перевірте пільги", "Ermäßigungen zuerst prüfen", "Перед купівлею абонемента запитайте Gemeinde або Land про сімейний паспорт та місцеві знижки на спорт, культуру й дозвілля: умови й перелік партнерів різняться за землею. Порівняйте разовий вхід, пробне заняття та членський внесок Verein; уточніть строк відмови і чи потрібне власне спорядження.", "Vor einem Abo Gemeinde oder Land nach Familienpass und regionalen Vergünstigungen für Sport, Kultur und Freizeit fragen; Bedingungen und Partner variieren. Einzeleintritt, Schnupperstunde und Vereinsbeitrag vergleichen sowie Kündigungsfrist und Ausrüstung klären.", source: discounts),
                .init("culture", "theatermasks", "Культура при малому доході", "Kultur bei wenig Einkommen", "Kulturpass ініціативи «Hunger auf Kunst und Kultur» відкриває безплатний доступ до установ-партнерів для людей із низькими доходами за умовами програми. На офіційному сайті виберіть свою землю, перевірте право на картку, місце видачі та партнерів. Наявність місць і правила бронювання залежать від конкретної події; сам проїзд зазвичай не входить.", "Der Kulturpass von „Hunger auf Kunst und Kultur“ ermöglicht bei Erfüllung der Programmbedingungen Menschen mit wenig Einkommen freien Zugang zu Partnerhäusern. Auf der offiziellen Seite Bundesland, Anspruch, Ausgabestelle und Partner prüfen. Plätze und Reservierung hängen von der Veranstaltung ab; Anreise ist üblicherweise nicht enthalten.", source: culturePass),
                .init("club", "person.3", "Як вступити до спортивного гуртка", "Sportverein beitreten", "Знайдіть місцевий Verein через Gemeinde або федерацію виду спорту. Перед підписом попросіть статут чи правила участі, річний внесок, умови виходу, пробне заняття та правила щодо дітей. За назвою чи ZVR-номером перевірте зареєстрований Verein у безплатному Zentralen Vereinsregister; це підтверджує реєстрацію, але не якість занять.", "Verein über Gemeinde oder Sportverband suchen. Vor Beitritt Statuten oder Teilnahmebedingungen, Jahresbeitrag, Austritt, Probetraining und Kinderregeln erfragen. Mit Name oder ZVR-Zahl im kostenlosen Zentralen Vereinsregister prüfen; die Eintragung belegt den Verein, nicht die Qualität des Angebots.", source: clubs),
                .init("move", "figure.walk", "Рух без зайвих витрат", "Bewegung ohne hohe Kosten", "Прогулянки, ходьба й велосипед можуть бути частиною здорової активності. Починайте посильно, поступово збільшуйте навантаження; при хронічній хворобі обговоріть межі з лікарем. Перевірте безпечність маршруту, погоду й правила місцевості.", "Spazieren, Gehen und Radfahren können gesunde Bewegung sein. Belastung angepasst beginnen und steigern; bei chronischer Erkrankung ärztlich abstimmen. Wegsicherheit, Wetter und örtliche Regeln prüfen.", source: activity),
                .init("children", "figure.child", "Для дітей і підлітків", "Für Kinder und Jugendliche", "Питайте в школі й громаді про групи за віком, пробні заняття та знижки. Перед початком перевірте відповідальну особу, страхування, дорогу додому й потреби дитини. Дітям потрібний рух відповідно до віку та можливостей, без примусу до надмірного навантаження.", "Schule und Gemeinde nach altersgerechten Gruppen, Schnupperstunden und Ermäßigungen fragen. Betreuungsperson, Versicherung, Heimweg und Bedarf des Kindes vorab klären. Bewegung soll alters- und fähigkeitsgerecht sein, ohne Überforderung.", source: children)
            ], sources: [movement, activity, children, centers, discounts, culturePass, clubs]
        )
    }
}
