import Foundation

enum MentalHealthGuides {
    private static let therapy = DirectorySource(name: "Gesundheitsportal · Psychotherapie", url: "https://www.gesundheit.gv.at/gesundheitsleistungen/berufe/gesundheitsberufe-a-z/psychotherapie/psychotherapeut.html")
    private static let therapySearch = DirectorySource(name: "Gesundheitsportal · Psychotherapie nach Bundesland", url: "https://www.gesundheit.gv.at/service/beratungsstellen/gesund-leben/psyche-seele/psychotherapie-adressen.html")
    private static let psychology = DirectorySource(name: "Gesundheitsportal · Klinische Psychologie", url: "https://www.gesundheit.gv.at/gesundheitsleistungen/berufe/gesundheitsberufe-a-z/psychologische-berufe/klinische-psychologie.html")
    private static let crisisHelp = DirectorySource(name: "Gesundheitsportal · Krisenintervention", url: "https://www.gesundheit.gv.at/leben/psyche-seele/krisenintervention/krisenhilfe.html")
    private static let crisisNumbers = DirectorySource(name: "Gesundheitsportal · Krisen- und Notrufnummern", url: "https://www.gesundheit.gv.at/leben/suizidpraevention/anlaufstellen/notrufnummern.html")
    private static let schoolHelp = DirectorySource(name: "Gesundheitsportal · Schule und Psyche", url: "https://www.gesundheit.gv.at/service/beratungsstellen/gesund-leben/gesunde-lebenswelten/hilfe-bei-schulangst.html")
    private static let schoolBullying = DirectorySource(name: "Gesundheitsportal · Hilfe bei Mobbing in der Schule", url: "https://www.gesundheit.gv.at/leben/lebenswelt/schule/schulpsychologie/gewalt-mobbing-vorbeugen.html")
    private static let youthProgram = DirectorySource(name: "Gesund aus der Krise · Anmeldung", url: "https://gesundausderkrise.at/")
    private static let youthProgramFunding = DirectorySource(name: "Sozialministerium · Gesund aus der Krise", url: "https://www.sozialministerium.gv.at/Services/Aktuelles/archiv-2026/gesund-aus-de-krise.html")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "counseling": counseling
        case "crisis": crisis
        case "children": children
        default: nil
        }
    }

    private static let counseling = DirectoryGuide(
        cardSummary: .init(ukrainian: "Як обрати фахівця, знайти місце та перевірити покриття", german: "Fachperson finden, Termin und Kostendeckung klären"),
        introduction: .init(ukrainian: "Психологічна підтримка може бути потрібна і без кризової ситуації. Психотерапія, клінічна психологія та психіатрична допомога мають різні завдання й правила оплати.", german: "Psychische Unterstützung ist auch ohne akute Krise sinnvoll. Psychotherapie, klinische Psychologie und psychiatrische Behandlung haben unterschiedliche Aufgaben und Kostenregeln."),
        sections: [
            .init("choose", "person.crop.circle", "Визначте, яка допомога потрібна", "Passende Hilfe wählen", "Для розмовної терапії та опрацювання переживань шукайте психотерапевта; клінічний психолог проводить діагностику й психологічне лікування; психіатр — лікар, який також оцінює потребу в медикаментах. Якщо не впевнені, почніть із сімейного лікаря або 1450. При гострій небезпеці одразу 144.", "Für Gesprächstherapie und die Bearbeitung belastender Erfahrungen suchen Sie Psychotherapie. Klinische Psychologie bietet Diagnostik und Behandlung; Psychiatrie ist ein ärztliches Fach und prüft auch Medikamente. Bei Unsicherheit Hausarzt oder 1450 fragen; bei akuter Gefahr 144.", source: therapy),
            .init("search", "magnifyingglass", "Знайдіть фахівця", "Fachperson suchen", "На офіційному порталі відкрийте перелік психотерапевтів за федеральною землею. Запитайте про вільні місця, мову, очний чи дистанційний формат і досвід роботи з вашою проблемою. Для клінічної психології перевірте професійну реєстрацію й умови прийому. Якщо після перших зустрічей контакт не підходить, можна шукати іншого спеціаліста.", "Öffnen Sie die Psychotherapie-Adressen des Gesundheitsportals nach Bundesland. Fragen Sie nach freien Plätzen, Sprache, Präsenz- oder Online-Format und Erfahrung mit Ihrem Anliegen. Bei klinischer Psychologie Berufsberechtigung und Terminbedingungen prüfen. Passt die Zusammenarbeit nicht, können Sie eine andere Fachperson suchen.", source: therapySearch),
            .init("cost", "eurosign.circle", "Оплата до першого сеансу", "Kosten vor dem ersten Termin", "На психотерапію можна записатися без направлення. Перед записом запитайте, чи є місце з повним покриттям касою, часткове відшкодування чи це приватний прийом; з'ясуйте ціну й час очікування. Для відшкодування психотерапії зазвичай потрібні розлад, який підлягає лікуванню, та лікарське підтвердження. Зверніться до своєї страхової каси до першого платного сеансу: уточніть документи й розмір відшкодування.", "Psychotherapie können Sie ohne Überweisung beginnen. Fragen Sie vor dem Termin nach einem voll finanzierten Kassenplatz, Teilrefundierung oder Privatleistung sowie nach Preis und Wartezeit. Für eine Kostenerstattung sind in der Regel eine behandlungsbedürftige psychische Störung und eine ärztliche Bestätigung nötig. Fragen Sie Ihre Krankenkasse vor dem ersten bezahlten Termin nach Unterlagen und Zuschusshöhe.", source: therapy),
            .init("psychology-cost", "doc.text.magnifyingglass", "Клінічна психологія: інші правила", "Klinische Psychologie: andere Regeln", "До клінічного психолога теж можна звернутися напряму. Для оплати окремих видів діагностики страховою касою зазвичай потрібне направлення лікаря або психотерапевта; психологічне лікування може частково відшкодовуватися за окремих умов. Назвіть страховикові конкретну послугу — діагностика чи лікування — і перевірте вимоги до направлення до візиту.", "Auch klinische Psychologie können Sie direkt aufsuchen. Für die Kassenübernahme bestimmter Diagnostik ist in der Regel eine ärztliche oder psychotherapeutische Überweisung nötig; klinisch-psychologische Behandlung kann unter Voraussetzungen teilweise erstattet werden. Nennen Sie der Kasse die konkrete Leistung – Diagnostik oder Behandlung – und klären Sie die Überweisung vor dem Termin.", source: psychology),
            .init("prepare", "checklist", "Підготуйте першу розмову", "Erstgespräch vorbereiten", "Коротко запишіть, що турбує, як давно, що погіршує або полегшує стан, чи є ліки та попереднє лікування. Ви можете запитати про конфіденційність, цілі, частоту зустрічей і те, що робити при погіршенні між ними. Не припиняйте призначені препарати самостійно.", "Notieren Sie Beschwerden, Dauer, Belastungen, hilfreiche Faktoren, Medikamente und frühere Behandlung. Fragen Sie nach Vertraulichkeit, Zielen, Häufigkeit und einem Plan bei Verschlechterung zwischen Terminen. Verordnete Medikamente nicht eigenmächtig absetzen.", source: psychology)
        ], sources: [therapy, therapySearch, psychology]
    )

    private static let crisis = DirectoryGuide(
        cardSummary: .init(ukrainian: "Негайна небезпека — 144; розмова в кризі — 142; допомога дітям — 147", german: "Akute Gefahr: 144; Krisengespräch: 142; Kinderhilfe: 147"),
        introduction: .init(ukrainian: "Криза може виникнути раптово після втрати, насильства чи тривалого виснаження. Не потрібно чекати, поки стан стане нестерпним.", german: "Eine Krise kann nach Verlust, Gewalt oder langer Überlastung entstehen. Warten Sie nicht, bis die Lage unerträglich wird."),
        sections: [
            .init("danger", "cross.case.fill", "Якщо є негайний ризик", "Bei unmittelbarer Gefahr", "Якщо людина може зараз завдати собі чи іншому шкоди, зателефонуйте 144; якщо є загроза насильства, також 133. Назвіть місце й те, що відбувається, та виконуйте вказівки диспетчера. Не залишайте людину саму, якщо це безпечно для вас, і не обіцяйте тримати намір самогубства в таємниці.", "Wenn jemand sich oder andere unmittelbar gefährden könnte, rufen Sie 144; bei Gewaltgefahr auch 133. Nennen Sie Ort und Situation und folgen Sie der Leitstelle. Lassen Sie die Person nicht allein, soweit das für Sie sicher ist, und versprechen Sie nicht, Suizidabsichten geheim zu halten.", phoneNumber: "144", source: crisisNumbers),
            .init("talk", "phone.fill", "Потрібна розмова зараз — 142", "Jetzt mit jemandem sprechen: 142", "Telefonseelsorge 142 працює цілодобово, анонімно й безкоштовно. Можна сказати прямо, що ви в кризі або маєте думки про самогубство. Це підтримка й допомога з наступним кроком, але не заміна швидкої допомоги при безпосередній небезпеці.", "Die Telefonseelsorge 142 ist rund um die Uhr anonym und kostenlos erreichbar. Sagen Sie offen, dass Sie in einer Krise sind oder Suizidgedanken haben. Das Gespräch hilft beim nächsten Schritt, ersetzt bei unmittelbarer Gefahr aber nicht die Rettung.", phoneNumber: "142", source: crisisNumbers),
            .init("care", "person.2", "Отримайте допомогу після гострого моменту", "Hilfe nach der akuten Phase", "Кризова інтервенція дає короткострокову підтримку в період кризи. Зверніться до кризового центру, психіатричної амбулаторії або сімейного лікаря; якщо не знаєте, куди саме, зателефонуйте 1450. Скажіть, що трапилося, чи є зараз ризик для безпеки та чи потрібна допомога сьогодні. Запитайте, який наступний контакт можливий.", "Krisenintervention bietet kurzfristige Hilfe in einer Krise. Kontaktieren Sie ein Krisenzentrum, eine psychiatrische Ambulanz oder den Hausarzt; wenn Sie unsicher sind, rufen Sie 1450 an. Schildern Sie, was passiert ist, ob aktuell Gefahr besteht und ob Sie heute Hilfe brauchen. Fragen Sie nach dem nächsten möglichen Kontakt.", source: crisisHelp),
            .init("follow-up", "checklist", "План на найближчі дні", "Plan für die nächsten Tage", "Попросіть фахівця кризової служби разом визначити наступний контакт: хто з близьких може бути поруч, куди звернутися при погіршенні та коли відбудеться повторна розмова. Якщо потрібне триваліше лікування, попросіть направити вас до психотерапії або психіатричної допомоги. Уточніть у служби й страховика оплату до планового лікування.", "Vereinbaren Sie mit der Krisenstelle den nächsten Kontakt: Wer aus Ihrem Umfeld kann unterstützen, wen erreichen Sie bei Verschlechterung und wann folgt das nächste Gespräch? Falls längere Behandlung nötig ist, lassen Sie sich zu Psychotherapie oder Psychiatrie weitervermitteln. Kosten vor der planbaren Behandlung bei Stelle und Versicherung klären.", source: crisisHelp)
        ], sources: [crisisNumbers, crisisHelp]
    )

    private static let children = DirectoryGuide(
        cardSummary: .init(ukrainian: "Школа, родина, фахова допомога й анонімна лінія 147", german: "Schule, Familie, Fachhilfe und anonyme Nummer 147"),
        introduction: .init(ukrainian: "Дитині або підлітку може бути важко говорити про страх, пережиту втрату, булінг чи насильство. Реагуйте спокійно й шукайте допомогу разом із нею.", german: "Über Angst, Verlust, Mobbing oder Gewalt zu sprechen kann für Kinder schwer sein. Reagieren Sie ruhig und suchen Sie gemeinsam Unterstützung."),
        sections: [
            .init("listen", "bubble.left.and.bubble.right", "Почніть із безпечної розмови", "Sicheres Gespräch beginnen", "Слухайте без звинувачень і поспішного діагнозу; запитайте, що дитині зараз потрібно і з ким їй комфортно говорити. Якщо є ознаки небезпеки, негайно зверніться по допомогу 144 або 133. При підозрі на насильство не змушуйте дитину повторювати історію багатьом людям.", "Hören Sie ohne Schuldzuweisung oder vorschnelle Diagnose zu. Fragen Sie, was das Kind jetzt braucht und mit wem es sprechen möchte. Bei akuter Gefahr 144 oder 133 wählen. Bei Gewaltverdacht das Kind nicht zu wiederholtem Erzählen drängen.", source: schoolHelp),
            .init("school", "building.2", "Допомога у школі", "Hilfe in der Schule", "Зверніться до довіреного вчителя або шкільної психологічної служби. При булінгу запишіть конкретні події й дати, попросіть школу домовитися про заходи захисту та дату наступної розмови. Якщо підтримки немає, зверніться до освітньої дирекції (Bildungsdirektion) вашої землі або дитячого омбудсмена (Kinder- und Jugendanwaltschaft).", "Wenden Sie sich an eine Vertrauenslehrkraft oder die Schulpsychologie. Bei Mobbing konkrete Vorfälle mit Datum notieren und mit der Schule Schutzmaßnahmen sowie einen Folgetermin vereinbaren. Bleibt Unterstützung aus, wenden Sie sich an die Bildungsdirektion Ihres Landes oder die Kinder- und Jugendanwaltschaft.", source: schoolBullying),
            .init("free-program", "heart.text.square", "Безкоштовна програма до 21 року", "Kostenfreies Angebot bis 21", "На gesundausderkrise.at подайте заявку до програми «Gesund aus der Krise». Для дітей, підлітків і молодих дорослих до виповнення 21 року передбачено до 15 безкоштовних сеансів; із 14 років підлітки можуть податися самостійно. Програма фінансується до кінця червня 2027 року. Уточніть наявність місця та потрібну мову; питання щодо заявки можна поставити за номером 0800 800 122 у робочі дні з 8:00 до 18:00. За негайної небезпеки телефонуйте 144.", "Melden Sie sich auf gesundausderkrise.at für «Gesund aus der Krise» an. Für Kinder, Jugendliche und junge Erwachsene bis zum vollendeten 21. Lebensjahr sind bis zu 15 kostenfreie Einheiten möglich; ab 14 Jahren ist eine eigenständige Anmeldung möglich. Die Finanzierung ist bis Ende Juni 2027 gesichert. Fragen Sie nach freien Plätzen und der benötigten Sprache; Fragen zur Anmeldung beantwortet 0800 800 122 werktags von 8 bis 18 Uhr. Bei unmittelbarer Gefahr 144 wählen.", phoneNumber: "0800 800 122", source: youthProgram),
            .init("professional", "person.crop.circle", "Коли потрібна фахова допомога", "Wann professionelle Hilfe nötig ist", "Якщо зміни сну, настрою, поведінки чи навчання тривають або посилюються, почніть із педіатра чи сімейного лікаря й попросіть направлення до відповідного дитячого фахівця. Перед приватним прийомом уточніть ціну, страховий договір, можливість відшкодування та участь батьків у лікуванні.", "Halten Schlaf-, Stimmungs-, Verhaltens- oder Lernprobleme an oder nehmen zu, beginnen Sie bei Kinder- oder Hausarzt und fragen nach passender Fachhilfe. Vor privaten Terminen Preis, Kassenvertrag, Erstattung und Einbeziehung der Eltern klären.", source: psychology),
            .init("hotline", "phone.fill", "Дитина може звернутися сама — 147", "Kinder können selbst 147 anrufen", "Rat auf Draht 147 консультує дітей, підлітків і дорослих, які про них піклуються, цілодобово, анонімно й безкоштовно. Запишіть номер для дитини. Якщо вона говорить про негайний намір нашкодити собі, телефонуйте 144 зараз.", "Rat auf Draht 147 berät Kinder, Jugendliche und Betreuungspersonen rund um die Uhr anonym und kostenlos. Geben Sie dem Kind die Nummer. Spricht es von unmittelbarer Selbstgefährdung, jetzt 144 anrufen.", phoneNumber: "147", source: crisisNumbers)
        ], sources: [schoolHelp, schoolBullying, youthProgram, youthProgramFunding, psychology, crisisNumbers]
    )
}
