import Foundation

enum MentalHealthGuides {
    private static let therapy = DirectorySource(name: "Gesundheitsportal · Psychotherapie", url: "https://www.gesundheit.gv.at/gesundheitsleistungen/berufe/gesundheitsberufe-a-z/psychotherapie/psychotherapeut.html")
    private static let therapySearch = DirectorySource(name: "Gesundheitsportal · Psychotherapie nach Bundesland", url: "https://www.gesundheit.gv.at/service/beratungsstellen/gesund-leben/psyche-seele/psychotherapie-adressen.html")
    private static let psychology = DirectorySource(name: "Gesundheitsportal · Klinische Psychologie", url: "https://www.gesundheit.gv.at/gesundheitsleistungen/berufe/gesundheitsberufe-a-z/psychologische-berufe/klinische-psychologie.html")
    private static let crisisHelp = DirectorySource(name: "Gesundheitsportal · Krisenintervention", url: "https://www.gesundheit.gv.at/leben/psyche-seele/krisenintervention/krisenhilfe.html")
    private static let crisisNumbers = DirectorySource(name: "Gesundheitsportal · Krisen- und Notrufnummern", url: "https://www.gesundheit.gv.at/leben/suizidpraevention/anlaufstellen/notrufnummern.html")
    private static let schoolHelp = DirectorySource(name: "Gesundheitsportal · Schule und Psyche", url: "https://www.gesundheit.gv.at/service/beratungsstellen/gesund-leben/gesunde-lebenswelten/hilfe-bei-schulangst.html")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "counseling": counseling
        case "crisis": crisis
        case "children": children
        default: nil
        }
    }

    private static let counseling = DirectoryGuide(
        cardSummary: .init(ukrainian: "Як обрати фахівця, знайти місце та перевірити покриття", german: "Fachperson finden, Termin und Kostendeckung klären"),
        introduction: .init(ukrainian: "Психологічна підтримка може бути потрібна і без кризової ситуації. Психотерапія, клінічна психологія та психіатрична допомога мають різні завдання й правила оплати.", german: "Psychische Unterstützung ist auch ohne akute Krise sinnvoll. Psychotherapie, klinische Psychologie und psychiatrische Behandlung haben unterschiedliche Aufgaben und Kostenregeln."),
        sections: [
            .init("choose", "person.crop.circle", "Визначте, яка допомога потрібна", "Passende Hilfe wählen", "Для розмовної терапії та опрацювання переживань шукайте психотерапевта; клінічний психолог проводить діагностику й психологічне лікування; психіатр — лікар, який також оцінює потребу в медикаментах. Якщо не впевнені, почніть із сімейного лікаря або 1450. При гострій небезпеці одразу 144.", "Für Gesprächstherapie und die Bearbeitung belastender Erfahrungen suchen Sie Psychotherapie. Klinische Psychologie bietet Diagnostik und Behandlung; Psychiatrie ist ein ärztliches Fach und prüft auch Medikamente. Bei Unsicherheit Hausarzt oder 1450 fragen; bei akuter Gefahr 144.", source: therapy),
            .init("search", "magnifyingglass", "Знайдіть фахівця", "Fachperson suchen", "На офіційному порталі відкрийте перелік психотерапевтів за федеральною землею. Запитайте про вільні місця, мову, очний чи дистанційний формат і досвід роботи з вашою проблемою. Для клінічної психології перевірте професійну реєстрацію й умови прийому. Якщо після перших зустрічей контакт не підходить, можна шукати іншого спеціаліста.", "Öffnen Sie die Psychotherapie-Adressen des Gesundheitsportals nach Bundesland. Fragen Sie nach freien Plätzen, Sprache, Präsenz- oder Online-Format und Erfahrung mit Ihrem Anliegen. Bei klinischer Psychologie Berufsberechtigung und Terminbedingungen prüfen. Passt die Zusammenarbeit nicht, können Sie eine andere Fachperson suchen.", source: therapySearch),
            .init("cost", "eurosign.circle", "Оплата до першого сеансу", "Kosten vor dem ersten Termin", "Дізнайтеся, чи це повністю оплачуване касою місце, приватний прийом із частковим відшкодуванням або повністю приватна послуга. Для відшкодування психотерапії зазвичай потрібні медичні умови й лікарське підтвердження; для окремої клінічно-психологічної діагностики — направлення. Попросіть письмову ціну, порядок подання рахунку й можливі строки очікування.", "Klären Sie, ob es einen voll finanzierten Kassenplatz, eine private Leistung mit Zuschuss oder eine reine Privatleistung gibt. Für Psychotherapie-Erstattung sind meist medizinische Voraussetzungen und eine ärztliche Bestätigung nötig; bei bestimmter klinisch-psychologischer Diagnostik eine Überweisung. Preis, Einreichung und Wartezeit vorab erfragen.", source: therapy),
            .init("prepare", "checklist", "Підготуйте першу розмову", "Erstgespräch vorbereiten", "Коротко запишіть, що турбує, як давно, що погіршує або полегшує стан, чи є ліки та попереднє лікування. Ви можете запитати про конфіденційність, цілі, частоту зустрічей і те, що робити при погіршенні між ними. Не припиняйте призначені препарати самостійно.", "Notieren Sie Beschwerden, Dauer, Belastungen, hilfreiche Faktoren, Medikamente und frühere Behandlung. Fragen Sie nach Vertraulichkeit, Zielen, Häufigkeit und einem Plan bei Verschlechterung zwischen Terminen. Verordnete Medikamente nicht eigenmächtig absetzen.", source: psychology)
        ], sources: [therapy, therapySearch, psychology]
    )

    private static let crisis = DirectoryGuide(
        cardSummary: .init(ukrainian: "Негайна небезпека — 144; розмова в кризі — 142; допомога дітям — 147", german: "Akute Gefahr: 144; Krisengespräch: 142; Kinderhilfe: 147"),
        introduction: .init(ukrainian: "Криза може виникнути раптово після втрати, насильства чи тривалого виснаження. Не потрібно чекати, поки стан стане нестерпним.", german: "Eine Krise kann nach Verlust, Gewalt oder langer Überlastung entstehen. Warten Sie nicht, bis die Lage unerträglich wird."),
        sections: [
            .init("danger", "cross.case.fill", "Якщо є негайний ризик", "Bei unmittelbarer Gefahr", "Якщо людина може зараз завдати собі чи іншому шкоди, зателефонуйте 144; якщо є загроза насильства, також 133. Назвіть місце й те, що відбувається, та виконуйте вказівки диспетчера. Не залишайте людину саму, якщо це безпечно для вас, і не обіцяйте тримати намір самогубства в таємниці.", "Wenn jemand sich oder andere unmittelbar gefährden könnte, rufen Sie 144; bei Gewaltgefahr auch 133. Nennen Sie Ort und Situation und folgen Sie der Leitstelle. Lassen Sie die Person nicht allein, soweit das für Sie sicher ist, und versprechen Sie nicht, Suizidabsichten geheim zu halten.", phoneNumber: "144", source: crisisNumbers),
            .init("talk", "phone.fill", "Потрібна розмова зараз — 142", "Jetzt mit jemandem sprechen: 142", "Telefonseelsorge 142 працює цілодобово, анонімно й безкоштовно. Можна сказати прямо, що ви в кризі або маєте думки про самогубство. Це підтримка й допомога з наступним кроком, але не заміна швидкої допомоги при безпосередній небезпеці.", "Die Telefonseelsorge 142 ist rund um die Uhr anonym und kostenlos erreichbar. Sagen Sie offen, dass Sie in einer Krise sind oder Suizidgedanken haben. Das Gespräch hilft beim nächsten Schritt, ersetzt bei unmittelbarer Gefahr aber nicht die Rettung.", phoneNumber: "142", source: crisisNumbers),
            .init("care", "person.2", "Отримайте допомогу після гострого моменту", "Hilfe nach der akuten Phase", "Кризова інтервенція може бути короткостроковою підтримкою й переходом до психотерапії або психіатра. Зверніться до сімейного лікаря, кризового центру чи психіатричної амбулаторії; 1450 підкаже відповідну службу. Запитайте про оплату й страхове покриття до планового лікування.", "Krisenintervention kann kurzfristig stabilisieren und zu Psychotherapie oder Psychiatrie überleiten. Hausarzt, Krisenzentrum oder psychiatrische Ambulanz kontaktieren; 1450 hilft bei der Suche. Kosten und Versicherung vor planbarer Behandlung klären.", source: crisisHelp),
            .init("region", "map", "Служба у вашій землі", "Dienst im Bundesland", "На офіційній сторінці кризових номерів є окремі служби федеральних земель і їхній режим роботи. Перевірте саме свою землю: місцеві номери та години відрізняються. Загальноавстрійські 144 і 142 діють незалежно від регіону.", "Die amtliche Krisennummern-Seite führt Dienste der einzelnen Bundesländer und deren Erreichbarkeit auf. Prüfen Sie Ihr Land, denn Nummern und Zeiten unterscheiden sich. 144 und 142 gelten österreichweit.", source: crisisNumbers)
        ], sources: [crisisNumbers, crisisHelp]
    )

    private static let children = DirectoryGuide(
        cardSummary: .init(ukrainian: "Школа, родина, фахова допомога й анонімна лінія 147", german: "Schule, Familie, Fachhilfe und anonyme Nummer 147"),
        introduction: .init(ukrainian: "Дитині або підлітку може бути важко говорити про страх, пережиту втрату, булінг чи насильство. Реагуйте спокійно й шукайте допомогу разом із нею.", german: "Über Angst, Verlust, Mobbing oder Gewalt zu sprechen kann für Kinder schwer sein. Reagieren Sie ruhig und suchen Sie gemeinsam Unterstützung."),
        sections: [
            .init("listen", "bubble.left.and.bubble.right", "Почніть із безпечної розмови", "Sicheres Gespräch beginnen", "Слухайте без звинувачень і поспішного діагнозу; запитайте, що дитині зараз потрібно і з ким їй комфортно говорити. Якщо є ознаки небезпеки, негайно зверніться по допомогу 144 або 133. При підозрі на насильство не змушуйте дитину повторювати історію багатьом людям.", "Hören Sie ohne Schuldzuweisung oder vorschnelle Diagnose zu. Fragen Sie, was das Kind jetzt braucht und mit wem es sprechen möchte. Bei akuter Gefahr 144 oder 133 wählen. Bei Gewaltverdacht das Kind nicht zu wiederholtem Erzählen drängen.", source: schoolHelp),
            .init("school", "building.2", "Допомога у школі", "Hilfe in der Schule", "Зверніться до довіреної вчительки чи вчителя, шкільної психологічної служби або шкільного лікаря. При булінгу зафіксуйте дати й події, попросіть школу про конкретний план захисту та наступну зустріч. Якщо проблему не вирішено, зверніться до Bildungsdirektion або Kinder- und Jugendanwaltschaft землі.", "Sprechen Sie mit Vertrauenslehrkraft, Schulpsychologie oder Schularzt. Bei Mobbing Ereignisse mit Datum festhalten und die Schule um Schutzplan und Folgetermin bitten. Bleibt das Problem offen, Bildungsdirektion oder Kinder- und Jugendanwaltschaft des Landes kontaktieren.", source: schoolHelp),
            .init("professional", "person.crop.circle", "Коли потрібна фахова допомога", "Wann professionelle Hilfe nötig ist", "Якщо зміни сну, настрою, поведінки чи навчання тривають або посилюються, почніть із педіатра чи сімейного лікаря й попросіть направлення до відповідного дитячого фахівця. Перед приватним прийомом уточніть ціну, страховий договір, можливість відшкодування та участь батьків у лікуванні.", "Halten Schlaf-, Stimmungs-, Verhaltens- oder Lernprobleme an oder nehmen zu, beginnen Sie bei Kinder- oder Hausarzt und fragen nach passender Fachhilfe. Vor privaten Terminen Preis, Kassenvertrag, Erstattung und Einbeziehung der Eltern klären.", source: psychology),
            .init("hotline", "phone.fill", "Дитина може звернутися сама — 147", "Kinder können selbst 147 anrufen", "Rat auf Draht 147 консультує дітей, підлітків і дорослих, які про них піклуються, цілодобово, анонімно й безкоштовно. Запишіть номер для дитини. Якщо вона говорить про негайний намір нашкодити собі, телефонуйте 144 зараз.", "Rat auf Draht 147 berät Kinder, Jugendliche und Betreuungspersonen rund um die Uhr anonym und kostenlos. Geben Sie dem Kind die Nummer. Spricht es von unmittelbarer Selbstgefährdung, jetzt 144 anrufen.", phoneNumber: "147", source: crisisNumbers)
        ], sources: [schoolHelp, psychology, crisisNumbers]
    )
}
