import Foundation

enum QualificationGuides {
    private static let procedures = DirectorySource(name: "Berufsanerkennung · Verfahren", url: "https://www.berufsanerkennung.at/de/berufsanerkennung/verfahren-zur-anerkennung/")
    private static let advice = DirectorySource(name: "Berufsanerkennung · AST-Beratung", url: "https://www.berufsanerkennung.at/de/beratung/")
    private static let courses = DirectorySource(name: "AMS · Aus- und Weiterbildungsdatenbank", url: "https://www.ams.at/arbeitsuchende/aus-und-weiterbildung/ausbildungs--und-weiterbildungsdatenbank")
    private static let funding = DirectorySource(name: "AMS · Aus- und Weiterbildungsbeihilfen", url: "https://www.ams.at/arbeitsuchende/aus-und-weiterbildung/so-foerdern-wir-ihre-aus--und-weiterbildung-/aus--und-weiterbildungshilfen")
    private static let recognitionFunding = DirectorySource(name: "Berufsanerkennung · Finanzielle Unterstützung", url: "https://www.berufsanerkennung.at/de/berufsanerkennung/finanzielle-unterstuetzung/")
    private static let degreeEvaluation = DirectorySource(name: "BMFWF · Bewertung von Studienabschlüssen", url: "https://www.bmfwf.gv.at/wissenschaft/anerkennung/abschluss_beruf.html")
    private static let nostrification = DirectorySource(name: "BMFWF · Nostrifizierung", url: "https://www.bmfwf.gv.at/wissenschaft/anerkennung/nostrifizierung.html")
    private static let missingEvidence = DirectorySource(name: "Berufsanerkennung · Anerkennungs- und Bewertungsgesetz", url: "https://www.berufsanerkennung.at/de/berufsanerkennung/anerkennungs-und-bewertungsgesetz/")
    private static let healthRegister = DirectorySource(name: "Gesundheitsportal · Gesundheitsberuferegister", url: "https://www.gesundheit.gv.at/gesundheitsleistungen/gesundheitsberuferegister.html")
    private static let doctors = DirectorySource(name: "Österreichische Ärztekammer · Ärztliche Tätigkeit", url: "https://www.aerztekammer.at/aerztliche-taetigkeit-in-oesterreich")
    private static let trades = DirectorySource(name: "USP · Individuelle Befähigung", url: "https://www.usp.gv.at/gruendung/EAP/feststellung-individuelle-befaehigung.html")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "recognition": recognition
        case "regulated-professions": regulated
        case "training": training
        default: nil
        }
    }

    private static let recognition = DirectoryGuide(
        cardSummary: .init(ukrainian: "Університетський диплом, професійна освіта й нострифікація: різні шляхи", german: "Hochschulabschluss, Berufsausbildung und Nostrifizierung: verschiedene Wege"),
        introduction: .init(ukrainian: "В Австрії немає одного універсального «визнання диплома». Спочатку визначте, для чого потрібен документ: робота, вступ на навчання або право працювати в регламентованій професії.", german: "Eine einheitliche Anerkennung für alle Diplome gibt es in Österreich nicht. Klären Sie zuerst den Zweck: Arbeit, Studienzulassung oder Zugang zu einem reglementierten Beruf."),
        sections: [
            .init("goal", "scope", "Визначте мету", "Zweck festlegen", "Для нерегламентованої роботи офіційне визнання часто не є умовою; роботодавцю може вистачити диплома й оцінки. Для навчання рішення приймає заклад. Для регламентованої професії потрібна визначена законом процедура й компетентний орган. Не сплачуйте за нострифікацію, доки не перевірили, що вона потрібна саме вам.", "Für nicht reglementierte Arbeit ist formale Anerkennung oft nicht Pflicht; Diplom und Bewertung können genügen. Über Studienzulassung entscheidet die Hochschule. Reglementierte Berufe brauchen ein gesetzliches Verfahren bei der zuständigen Behörde. Keine Nostrifikation bezahlen, bevor deren Notwendigkeit geklärt ist.", source: procedures),
            .init("academic", "graduationcap", "Університетський диплом: оцінка ENIC NARIC", "Hochschulabschluss: Bewertung durch ENIC NARIC", "Для завершеної вищої освіти можна подати онлайн-заяву на оцінку через AAIS. Вона пояснює роботодавцю рівень кваліфікації, але не є формальним визнанням, нострифікацією чи дозволом на регламентовану роботу. Для незавершеного навчання та неуніверситетської освіти цей шлях не підходить.", "Für ein abgeschlossenes Hochschulstudium kann eine Bewertung online über AAIS beantragt werden. Sie beschreibt die Qualifikation für Arbeitgeber, ist aber weder formale Anerkennung noch Nostrifizierung oder Berufszulassung. Für nicht abgeschlossenes Studium und nicht hochschulische Ausbildung ist dieser Weg nicht vorgesehen.", source: degreeEvaluation),
            .init("vocational", "hammer", "Професійна освіта: оцінка або прирівняння", "Berufsausbildung: Bewertung oder Gleichhaltung", "Професійний диплом можна оцінити для орієнтації роботодавця або перевірити його прирівняння до австрійської Lehrabschlussprüfung. Це різні результати: для прирівняння можуть знадобитися докази досвіду чи додатковий іспит. Не подавайте такий диплом на університетську оцінку AAIS.", "Ein Berufsabschluss kann für den Arbeitsmarkt bewertet oder auf Gleichhaltung mit der österreichischen Lehrabschlussprüfung geprüft werden. Das sind verschiedene Ergebnisse; für die Gleichhaltung können Praxisnachweise oder Ergänzungsprüfungen nötig sein. Einen Berufsabschluss nicht für die Hochschulbewertung über AAIS einreichen.", source: procedures),
            .init("nostrification", "checkmark.seal", "Коли потрібна нострифікація", "Wann eine Nostrifizierung nötig ist", "Нострифікація прирівнює іноземний університетський диплом до австрійського. Вона передбачена, коли для професії закон вимагає австрійського ступеня й іншого шляху визнання немає. Компетентний університет, Fachhochschule або педагогічний виш порівнює навчання та може призначити додаткові іспити. Для звичайного пошуку роботи це не загальна вимога.", "Die Nostrifizierung stellt einen ausländischen Hochschulabschluss einem österreichischen gleich. Sie ist vorgesehen, wenn das Gesetz einen österreichischen Abschluss verlangt und kein anderer Anerkennungsweg möglich ist. Die zuständige Universität, Fachhochschule oder Pädagogische Hochschule vergleicht Inhalte und kann Ergänzungsprüfungen vorschreiben. Für die allgemeine Arbeitssuche ist sie keine pauschale Pflicht.", source: nostrification),
            .init("advisor", "person.crop.rectangle", "Безкоштовно з’ясуйте орган і документи", "Zuständigkeit und Unterlagen kostenlos klären", "AST консультує в усіх землях безкоштовно й кількома мовами. Покажіть диплом, додаток із предметами та годинами, докази стажу й бажану посаду. Попросіть назвати компетентний орган, потрібну процедуру та його перелік перекладів, засвідчень і зборів до оплати послуг.", "AST berät in allen Bundesländern kostenlos und mehrsprachig. Abschluss, Fächer- und Stundenübersicht, Praxisnachweise und Zielstelle mitbringen. Zuständige Stelle, Verfahren und deren Anforderungen an Übersetzungen, Beglaubigungen und Gebühren vor Bezahlung klären.", source: advice),
            .init("missing", "doc.badge.questionmark", "Якщо документи втрачено під час втечі", "Wenn Nachweise auf der Flucht verloren gingen", "Якщо диплом чи інші докази втрачено не з вашої вини під час втечі, повідомте AST й орган заяви. Для переміщених осіб можливе альтернативне встановлення кваліфікації, наприклад через співбесіду або перевірку навичок. Конкретний спосіб залежить від процедури.", "Wenn Zeugnisse unverschuldet auf der Flucht verloren gingen, AST und Antragsstelle informieren. Für Vertriebene sind alternative Wege zur Feststellung von Qualifikationen möglich, etwa Fachgespräch oder praktische Prüfung. Das konkrete Verfahren ist zu klären.", source: missingEvidence),
            .init("cost", "eurosign.circle", "Порахуйте витрати до подання", "Kosten vor Antrag klären", "Запитайте орган про збір, переклади, засвідчення й можливі іспити. Для окремих витрат на визнання ÖIF описує фінансову підтримку; умови перевіряють до оплати. Збережіть рахунки й письмове погодження. Оцінка диплома не надає права працювати або проживати без відповідного статусу.", "Behörde nach Gebühren, Übersetzungen, Beglaubigungen und Prüfungen fragen. Für bestimmte Anerkennungskosten beschreibt der ÖIF Fördermöglichkeiten; Voraussetzungen vor Zahlung klären. Belege und schriftliche Zusage aufheben. Eine Bewertung verschafft weder Arbeitsmarktzugang noch Aufenthaltstitel.", source: recognitionFunding)
        ], sources: [procedures, degreeEvaluation, nostrification, advice, missingEvidence, recognitionFunding]
    )

    private static let regulated = DirectoryGuide(
        cardSummary: .init(ukrainian: "Медицина, педагогіка та інші професії з обов’язковим допуском", german: "Gesundheit, Pädagogik und andere Berufe mit Berufszulassung"),
        introduction: .init(ukrainian: "У регламентованій професії диплом і право перебування не замінюють професійного допуску. Орган і вимоги залежать від конкретної професії та країни освіти.", german: "In reglementierten Berufen ersetzen Diplom und Aufenthaltsrecht nicht die Berufszulassung. Zuständige Stelle und Anforderungen hängen von Beruf und Ausbildungsland ab."),
        sections: [
            .init("check", "checkmark.shield", "Перевірте, чи професія регламентована", "Reglementierung prüfen", "Використайте офіційний Anerkennungs-Wegweiser й назвіть точну професію, наприклад Pflege, Arztberuf чи Lehramt. Однакові назви посад можуть мати різний обсяг дозволених дій. Не починайте виконувати захищені професійні функції до рішення компетентного органу.", "Im amtlichen Anerkennungs-Wegweiser den genauen Beruf nennen, etwa Pflege, Medizin oder Lehramt. Ähnliche Berufsbezeichnungen können unterschiedliche Befugnisse haben. Geschützte Tätigkeiten erst nach Entscheidung der zuständigen Stelle ausüben.", source: procedures),
            .init("route", "arrow.triangle.branch", "Орган, документи й мова", "Stelle, Unterlagen und Sprache", "Шлях для освіти з ЄС/ЄЕЗ/Швейцарії та третьої країни може відрізнятися. У визначеного органу попросіть письмовий перелік документів, вимог до мови, зборів та очікуваного строку. AST допоможе з вибором органу й заявою. Після рішення перевірте, чи призначено практику або іспити та який порядок оскарження.", "Für Ausbildungen aus EU/EWR/Schweiz und Drittstaaten können unterschiedliche Wege gelten. Bei der zuständigen Stelle Unterlagen, Sprachanforderungen, Gebühren und voraussichtliche Dauer schriftlich erfragen. AST hilft bei Zuständigkeit und Antrag. Nach dem Bescheid prüfen, ob Praxis oder Prüfungen vorgeschrieben sind und welche Rechtsmittel bestehen.", source: advice),
            .init("health-register", "cross.case", "Медсестринство й терапія: перевірте реєстрацію", "Pflege und Therapieberufe: Registrierung prüfen", "Для професій, які охоплює Gesundheitsberuferegister, після визнання освіти перед роботою потрібен також запис у реєстрі. Перевірте, чи входить ваша професія до нього та яка реєстраційна установа відповідає за ваш випадок. Для інших медичних професій діють інші правила й органи.", "Bei Berufen des Gesundheitsberuferegisters ist nach Anerkennung der Ausbildung vor Berufsausübung zusätzlich die Eintragung nötig. Prüfen, ob der eigene Beruf dazugehört und welche Registrierungsbehörde zuständig ist. Für andere Gesundheitsberufe gelten andere Regeln und Stellen.", source: healthRegister),
            .init("doctors", "stethoscope", "Лікарі: окремий запис до Ärzteliste", "Ärztinnen und Ärzte: Eintragung in die Ärzteliste", "Лікарям слід перевірити шлях визнання освіти й подальшої підготовки в Австрійській лікарській палаті. Перед лікарською діяльністю потрібен запис до Ärzteliste; оцінка диплома ENIC NARIC його не замінює. Вимоги до нострифікації, практики та мови залежать від конкретної освіти й ролі.", "Ärztinnen und Ärzte klären Anerkennung des Studiums und der weiteren Ausbildung bei der Österreichischen Ärztekammer. Vor ärztlicher Tätigkeit ist die Eintragung in die Ärzteliste nötig; eine ENIC-NARIC-Bewertung ersetzt sie nicht. Nostrifizierung, Praxis und Sprachanforderungen hängen von Ausbildung und Tätigkeit ab.", source: doctors),
            .init("trade", "wrench.adjustable", "Власна регламентована діяльність", "Selbstständiges reglementiertes Gewerbe", "Якщо плануєте власну справу в регламентованому Gewerbe, перевірте окремий Befähigungsnachweis. Коли стандартного доказу немає, компетентний орган може розглянути індивідуальну кваліфікацію за документами про знання, навички й досвід; інколи лише для частини діяльності. Це не тотожне допуску до роботи за наймом.", "Wer ein reglementiertes Gewerbe selbstständig ausüben will, muss den Befähigungsnachweis gesondert prüfen. Fehlt der übliche Nachweis, kann die Behörde eine individuelle Befähigung anhand von Kenntnissen, Fertigkeiten und Erfahrung feststellen, teils nur für eine Teiltätigkeit. Das ist nicht dasselbe wie die Zulassung zu unselbstständiger Arbeit.", source: trades),
            .init("interim", "briefcase", "Робота під час процедури", "Arbeit während des Verfahrens", "Запитайте, чи можна працювати на іншій, не захищеній посаді та які обов’язки дозволені. Не погоджуйтеся працювати під регламентованою назвою без допуску. Обговоріть із AMS або роботодавцем мовний курс, практику й фінансування необхідного донавчання.", "Prüfen Sie, ob eine andere, nicht geschützte Tätigkeit möglich ist und welche Aufgaben zulässig sind. Geschützte Berufsbezeichnung nicht ohne Zulassung verwenden. Sprachkurs, Praxis und Finanzierung von Anpassungsqualifizierung mit AMS oder Arbeitgeber besprechen.", source: procedures)
        ], sources: [procedures, advice, healthRegister, doctors, trades]
    )

    private static let training = DirectoryGuide(
        cardSummary: .init(ukrainian: "Знайти курс, оцінити сертифікат і погодити можливе фінансування", german: "Kurs finden, Zertifikat prüfen, Förderung vorab klären"),
        introduction: .init(ukrainian: "Курси відрізняються за вимогами, вартістю й результатом. Безкоштовна консультація до оплати допоможе не витратити час на сертифікат, який не потрібен для вашої професії.", german: "Kurse unterscheiden sich bei Zugang, Preis und Abschluss. Beratung vor Zahlung verhindert einen für den Zielberuf unnötigen Kurs."),
        sections: [
            .init("goal", "target", "Зіставте курс із вакансією", "Kurs mit Berufsziel abgleichen", "Візьміть конкретну вакансію або вимоги професії: потрібен сертифікат, Lehrabschluss, мовний рівень чи професійний допуск? У базі AMS відфільтруйте курси за фахом і місцем. Якщо бракує частини кваліфікації для регламентованої професії, спершу попросіть орган визнання підтвердити, яке довчання зарахують.", "Eine konkrete Stellenanzeige oder Berufsanforderung prüfen: Zertifikat, Lehrabschluss, Sprache oder Zulassung? In der AMS-Suche nach Fach und Ort filtern. Fehlt bei einem reglementierten Beruf ein Teil der Qualifikation, vorab von der Anerkennungsstelle bestätigen lassen, welche Nachqualifizierung zählt.", source: courses),
            .init("provider", "checkmark.seal", "Перевірте результат навчання", "Abschluss und Anbieter prüfen", "Запитайте провайдера про програму, тривалість, формат, мову, умови вступу, іспит та документ після завершення. Запитайте роботодавця або орган допуску, чи приймає він саме цей документ. Наявність курсу в базі AMS сама по собі не означає офіційного допуску або автоматичної оплати AMS.", "Beim Anbieter Lehrplan, Dauer, Format, Sprache, Aufnahmebedingungen, Prüfung und Abschlussdokument erfragen. Arbeitgeber oder zuständige Stelle fragen, ob genau dieser Nachweis zählt. Ein Eintrag in der AMS-Datenbank ist weder Berufszulassung noch eine automatische AMS-Förderzusage.", source: courses),
            .init("cost", "eurosign.circle", "Фінансування до початку", "Förderung vor Kursbeginn", "Якщо ви без роботи й зареєстровані в AMS, обговоріть курс із консультантом до його початку. AMS перевіряє, чи покращить він шанси на роботу; права на оплату кожного курсу немає. Уточніть у своєму випадку витрати на навчання, матеріали, іспит, дорогу й проживання. У деяких землях є додаткові програми.", "Wenn Sie arbeitslos und beim AMS vorgemerkt sind, den Kurs vor Beginn mit Ihrer Beratung besprechen. Das AMS prüft bessere Vermittlungschancen; ein Anspruch auf jeden Kurs besteht nicht. Kurs, Material, Prüfung, Fahrt und Unterkunft für den eigenen Fall klären. Manche Bundesländer bieten weitere Programme.", source: funding),
            .init("agreement", "doc.text", "Перед підписанням із провайдером", "Vor Vertrag mit dem Anbieter", "Перевірте повну ціну разом з іспитом і матеріалами, правила скасування, пропусків та повторного іспиту. Порівняйте графік із роботою й доглядом за дітьми. Зберігайте договір, чеки та сертифікат; не сплачуйте в надії на ще не погоджене відшкодування.", "Gesamtpreis samt Prüfung und Material, Storno-, Fehlzeiten- und Wiederholungsregeln prüfen. Zeitplan mit Arbeit und Kinderbetreuung abgleichen. Vertrag, Belege und Zertifikat aufheben; nicht auf eine noch ungeklärte Erstattung vertrauen.", source: courses)
        ], sources: [courses, funding, procedures]
    )
}
