import Foundation

extension ResidenceGuides {
    static let studentResidence = DirectoryGuide(
        cardSummary: .init(ukrainian: "Вступ, кошти, збір 218 €, робота й продовження", german: "Zulassung, Mittel, 218 € Gebühr, Arbeit und Verlängerung"),
        introduction: .init(ukrainian: "Для навчання понад шість місяців громадянам третіх країн зазвичай потрібна Aufenthaltsbewilligung – Student. Це не те саме, що віза D для коротшого перебування.", german: "Für ein Studium über sechs Monate benötigen Drittstaatsangehörige meist eine Aufenthaltsbewilligung – Student. Sie ist nicht dasselbe wie ein Visum D für kürzere Aufenthalte."),
        sections: [
            .init("admission", "graduationcap", "Яке навчання підходить", "Welche Studien zählen",
                  "Потрібне зарахування на навчання, яке визнає закон: зокрема, звичайне навчання у виші або окремі передбачені види позачергового навчання. Просто мовні курси самі по собі не завжди є підставою. Університетська Zulassung і дозвіл на проживання — різні рішення.",
                  "Erforderlich ist die Zulassung zu einem gesetzlich erfassten Studium: etwa einem ordentlichen Hochschulstudium oder bestimmten außerordentlichen Studien. Reine Sprachkurse allein reichen nicht stets aus. Hochschulzulassung und Aufenthaltstitel sind verschiedene Entscheidungen.", source: studentOeAD),
            .init("papers", "doc.text", "Документи й подання", "Unterlagen und Antrag",
                  "Підготуйте паспорт, фото, рішення про зарахування, кошти, медичне страхування та підтвердження житла щонайменше на три місяці для розрахунку витрат. Для першої заяви OeAD також називає довідку про несудимість із країни проживання. Заяву подають через представництво за кордоном або, якщо дозволено, під час законного перебування в Австрії. Якщо рішення затримується, віза чи безвіз через саму заяву не продовжуються.",
                  "Bereiten Sie Pass, Foto, Zulassung, Mittel, Krankenversicherung und einen Unterkunftsnachweis für mindestens drei Monate zur Kostenberechnung vor. Für den Erstantrag nennt der OeAD auch einen Strafregisterauszug aus dem Wohnsitzstaat. Der Antrag erfolgt über die Auslandsvertretung oder, wenn zulässig, während rechtmäßigen Aufenthalts in Österreich. Verzögert sich die Entscheidung, verlängert der Antrag Visum oder visumfreie Zeit nicht.", source: studentOeAD),
            .init("costs", "eurosign.circle", "Кошти та збір у 2026 році", "Mittel und Gebühr 2026",
                  "Підтвердьте кошти на 12 місяців. У 2026 році OeAD вказує 722,58 € на місяць до 24 років і 1 308,39 € від 24 років; до суми додаються витрати на житло понад 386,43 € на місяць та страхування. Походження коштів можуть попросити підтвердити виписками й документами. Збір за заяву — 218 € під час подання; його не повертають і при відмові. Перед поданням перевірте нові річні суми.",
                  "Weisen Sie Mittel für zwölf Monate nach. 2026 nennt der OeAD 722,58 € monatlich bis 24 Jahre und 1.308,39 € ab 24 Jahren; Unterkunftskosten über 386,43 € monatlich und Versicherung kommen hinzu. Die Herkunft der Mittel kann mit Kontoauszügen und Belegen geprüft werden. Die Antragsgebühr von 218 € fällt bei Einreichung an und wird auch bei Ablehnung nicht erstattet. Prüfen Sie vor Antrag die aktuellen Jahresbeträge.",
                  source: studentOeAD),
            .init("work", "briefcase", "Робота під час навчання", "Arbeit während des Studiums",
                  "Студентський дозвіл не є вільним доступом до ринку праці. Для найманої роботи роботодавцю зазвичай потрібна Beschäftigungsbewilligung від AMS, навіть за малого обсягу; для роботи до 20 годин на тиждень її можуть видати без перевірки ринку праці. Не починайте роботу до з’ясування потрібного дозволу.",
                  "Der Studierendentitel eröffnet keinen freien Arbeitsmarktzugang. Für unselbständige Arbeit braucht der Arbeitgeber grundsätzlich eine Beschäftigungsbewilligung des AMS, auch bei geringem Umfang; bis 20 Wochenstunden kann sie ohne Arbeitsmarktprüfung erteilt werden. Klären Sie die Bewilligung vor Arbeitsbeginn.", source: studentWork),
            .init("renew", "calendar.badge.clock", "Продовження й навчальний успіх", "Verlängerung und Studienerfolg",
                  "Подайте продовження особисто не раніше ніж за три місяці до завершення картки й обов’язково до її закінчення. Потрібні, зокрема, актуальне підтвердження навчання та Studienerfolgsnachweis. Якщо прогресу бракує, з’ясуйте з органом можливі законні винятки до закінчення дозволу.",
                  "Beantragen Sie die Verlängerung persönlich frühestens drei Monate vor und jedenfalls vor Ablauf der Karte. Erforderlich sind unter anderem aktuelle Studienunterlagen und ein Studienerfolgsnachweis. Fehlt Studienerfolg, klären Sie mögliche gesetzliche Ausnahmen vor Ablauf mit der Behörde.", source: studentOeAD),
            .init("graduate", "arrow.right.circle", "Після диплома", "Nach dem Abschluss",
                  "Після успішного завершення відповідного навчання студентський дозвіл можна за певних умов один раз продовжити на 12 місяців для пошуку роботи або заснування компанії. Можливий перехід на RWR-картку, Blue Card EU чи дозвіл дослідника, якщо виконані їхні умови. Зверніться до закінчення поточного документа.",
                  "Nach erfolgreichem Abschluss eines geeigneten Studiums kann der Studierendentitel unter Voraussetzungen einmalig um zwölf Monate für Arbeitssuche oder Unternehmensgründung verlängert werden. Ein Wechsel zu RWR-Karte, Blauer Karte EU oder Forschertitel ist bei erfüllten Bedingungen möglich. Handeln Sie vor Ablauf des aktuellen Dokuments.", source: studentOeAD)
        ], sources: [student, studentOeAD, studentWork, renewal]
    )

    static let workResidence = DirectoryGuide(
        cardSummary: .init(ukrainian: "Дозволи для кваліфікованої роботи й зміни роботодавця", german: "Titel für qualifizierte Arbeit und Arbeitgeberwechsel"),
        introduction: .init(ukrainian: "Шлях для роботи залежить від кваліфікації, пропозиції роботи, зарплати та виду діяльності. Тимчасовий захист уже дає окреме право працювати.", german: "Der Arbeitsweg hängt von Qualifikation, Stellenangebot, Entgelt und Tätigkeit ab. Vorübergehender Schutz gewährt bereits ein eigenes Arbeitsrecht."),
        sections: [
            .init("rwr", "briefcase.fill", "Rot-Weiß-Rot-Karte", "Rot-Weiß-Rot-Karte",
                  "RWR-картка призначена для визначених груп кваліфікованих працівників: дефіцитні професії, ключові спеціалісти, випускники австрійських вишів та інші групи. Зазвичай потрібна конкретна пропозиція роботи; AMS перевіряє відповідні умови. Картка, як правило, прив’язана до вказаного роботодавця й видається до 24 місяців.",
                  "Die RWR-Karte richtet sich an gesetzlich definierte Gruppen qualifizierter Arbeitskräfte: Mangelberufe, Schlüsselkräfte, Absolventen österreichischer Hochschulen und weitere Gruppen. Meist braucht es ein konkretes Angebot; das AMS prüft die Voraussetzungen. Die Karte ist grundsätzlich an den genannten Arbeitgeber gebunden und gilt bis zu 24 Monate.", source: work),
            .init("blue", "star.circle", "Blaue Karte EU", "Blaue Karte EU",
                  "Blue Card EU — окремий дозвіл для висококваліфікованої роботи з визначеними вимогами до освіти або досвіду, трудового договору та оплати. Не плутайте її з синьою карткою для переміщених з України. Офіційний портал порівнює робочі маршрути та поточні пороги.",
                  "Die Blaue Karte EU ist ein eigener Titel für hochqualifizierte Beschäftigung mit Vorgaben zu Ausbildung oder Erfahrung, Arbeitsvertrag und Entgelt. Sie ist nicht der blaue Ausweis für Vertriebene aus der Ukraine. Das amtliche Portal erläutert Arbeitswege und aktuelle Schwellen.", source: work),
            .init("change", "arrow.triangle.branch", "Зміна роботи", "Arbeitgeberwechsel",
                  "На RWR-картці зміна роботодавця протягом строку її дії зазвичай потребує нової картки. RWR+ дає необмежений доступ до ринку праці без прив’язки до роботодавця. Перед звільненням або новою роботою перевірте саме свій документ і правила переходу.",
                  "Mit einer RWR-Karte erfordert ein Arbeitgeberwechsel während ihrer Gültigkeit grundsätzlich eine neue Karte. Die RWR-Karte plus erlaubt unbeschränkten Arbeitsmarktzugang ohne Arbeitgeberbindung. Prüfen Sie Ihren konkreten Titel und den Wechsel vor Arbeitsbeginn.", source: rwrPlus),
            .init("other", "person.crop.rectangle.stack", "Інші робочі підстави", "Andere Erwerbswege",
                  "Для дослідників, самозайнятих, підприємців, внутрішньокорпоративних переведень та короткострокової роботи існують інші дозволи. Обирайте підставу за реальною діяльністю; контракт сам по собі не створює права перебування.",
                  "Für Forschende, Selbständige, Unternehmensgründungen, konzerninterne Transfers und befristete Arbeit bestehen andere Titel. Wählen Sie nach der tatsächlichen Tätigkeit; ein Arbeitsvertrag allein schafft kein Aufenthaltsrecht.", source: work)
        ], sources: [work, rwrPlus, permits]
    )

    static let rwrPlusGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Вільна робота; окремий перехід для переміщених", german: "Freier Arbeitsmarktzugang; Sonderweg für Vertriebene"),
        introduction: .init(ukrainian: "RWR+ — строковий дозвіл на оселення з вільним доступом до роботи. Підстави для його отримання різні; перехід із тимчасового захисту має спеціальні умови.", german: "Die RWR-Karte plus ist ein befristeter Niederlassungstitel mit freiem Arbeitsmarktzugang. Es gibt unterschiedliche Zugangswege; für Vertriebene gelten besondere Voraussetzungen."),
        sections: [
            .init("general", "person.2", "Звичайні шляхи", "Allgemeine Zugangswege",
                  "RWR+ можуть отримати, зокрема, члени сім’ї певних власників робочих дозволів та люди, які після RWR-картки або Blue Card EU відповідали умовам зайнятості щонайменше 21 місяць із попередніх 24. Конкретний шлях залежить від чинного дозволу й умов сімейного возз’єднання.",
                  "Eine RWR-Karte plus kommt unter anderem für Familienangehörige bestimmter Arbeitstitelinhaber oder nach RWR-Karte bzw. Blauer Karte EU bei mindestens 21 Monaten entsprechender Beschäftigung in den letzten 24 Monaten in Betracht. Der genaue Weg hängt vom bisherigen Titel und den Familienregeln ab.", source: rwrPlus),
            .init("ukraine", "checklist", "Перехід із захисту для українців", "Umstieg aus dem Ukraine-Schutz",
                  "За спеціальним маршрутом потрібне чинне право перебування переміщеної особи та 12 місяців повного страхування через роботу в Австрії за останні 24 місяці; місяці можна сумувати. Також потрібні загальні умови NAG — достатні кошти, страхування, належне житло — і підтвердження німецької чи інтеграції. Порогові суми змінюються: відкрийте FAQ BMI перед поданням.",
                  "Der Sonderweg setzt das aktuelle Vertriebenenrecht und zwölf Monate vollversicherte Erwerbstätigkeit in Österreich innerhalb der letzten 24 Monate voraus; die Monate können zusammengerechnet werden. Hinzu kommen allgemeine NAG-Voraussetzungen – ausreichende Mittel, Versicherung, geeignete Unterkunft – sowie Deutsch- oder Integrationsnachweis. Geldbeträge ändern sich: Lesen Sie vor dem Antrag die BMI-FAQ.", source: protectionTransition),
            .init("process", "building.2", "Заява й перевірка AMS", "Antrag und AMS-Prüfung",
                  "Заяву подають до органу з питань проживання за адресою в Австрії (у Відні MA 35). Орган перевіряє документи, а AMS підтверджує місяці повного страхування. Перехід добровільний; для переміщених він не має квоти. Якщо сім’я переїжджає пізніше, для неї діє окрема процедура возз’єднання.",
                  "Der Antrag geht an die Aufenthaltsbehörde am Wohnort (in Wien MA 35). Sie prüft die Unterlagen; das AMS bestätigt die vollversicherten Zeiten. Der Umstieg ist freiwillig und für Vertriebene nicht quotenpflichtig. Für später nachziehende Familienmitglieder gilt ein eigenes Verfahren.", source: protectionTransition),
            .init("effect", "arrow.right.circle", "Що зміниться", "Was sich ändert",
                  "RWR+ потребує особистого продовження до закінчення картки. На відміну від тимчасового захисту, для отримання RWR+ не можна отримувати Grundversorgung. Після переходу можливе возз’єднання сім’ї та, за виконання умов, шлях до Daueraufenthalt – EU; попередні періоди захисту безпосередньо перед RWR+ можуть зараховуватися за правилами BMI.",
                  "Die RWR-Karte plus muss vor Ablauf persönlich verlängert werden. Für ihre Erteilung darf anders als beim vorübergehenden Schutz keine Grundversorgung bezogen werden. Der Titel ermöglicht Familiennachzug und bei erfüllten Bedingungen später Daueraufenthalt – EU; unmittelbar vorangehende Schutzzeiten können nach BMI-Regeln angerechnet werden.", source: protectionTransition),
            .init("cost-and-result", "eurosign.circle", "Збір і рішення за заявою", "Gebühr und Entscheidung",
                  "За заяву на RWR+ сплачують 218 €. Якщо її відхилять, тимчасовий захист і право працювати за ним зберігаються. Якщо RWR+ видадуть, за чинним роз’ясненням BMI тимчасовий захист теж поки що залишається; зберігайте обидва документи. На RWR+ можна претендувати без квоти, але її потрібно вчасно продовжувати окремою заявою.",
                  "Für den RWR-Plus-Antrag fallen 218 € an. Bei Ablehnung bleiben der vorübergehende Schutz und das daraus folgende Arbeitsrecht bestehen. Auch bei Erteilung bleibt laut geltender BMI-FAQ der Schutz vorerst bestehen; bewahren Sie beide Dokumente auf. Der Umstieg ist quotenfrei, die RWR-Karte plus muss aber rechtzeitig gesondert verlängert werden.", source: protectionTransition),
            .init("other-titles", "arrow.triangle.branch", "Якщо потрібен інший дозвіл", "Wenn Sie einen anderen Titel möchten",
                  "Чинна FAQ BMI для переміщених описує прямий перехід лише на спеціальну RWR+. У вересні 2026 року BMI оголосило майбутню можливість відмовитися від захисту при отриманні іншого дозволу за NAG; саме оголошення ще не замінює правила подання. До заяви на навчання, сім’ю чи роботу попросіть компетентний орган підтвердити, чи нова процедура вже діє і як зберігається право перебування до рішення.",
                  "Die geltende BMI-FAQ beschreibt für Vertriebene den direkten Umstieg nur auf die besondere RWR-Karte plus. Im September 2026 kündigte das BMI an, künftig beim Erhalt eines anderen NAG-Titels auf den Schutz verzichten zu können; die Ankündigung ersetzt noch keine Antragsregel. Lassen Sie vor einem Studien-, Familien- oder Arbeitsantrag von der zuständigen Behörde bestätigen, ob das neue Verfahren bereits gilt und welches Aufenthaltsrecht bis zur Entscheidung besteht.", source: protectionChangeAnnouncement)
        ], sources: [protectionTransition, rwrPlus, conditions, protection, protectionChangeAnnouncement]
    )
}
