import Foundation

enum SeniorsGuides {
    private static let care = DirectorySource(name: "oesterreich.gv.at · Soziale Dienste", url: "https://www.oesterreich.gv.at/themen/pflege/soziale_dienste/Seite.1210200.html")
    private static let health = DirectorySource(name: "Gesundheitsportal · Bewegung im Alter", url: "https://www.gesundheit.gv.at/leben/altern/bewegung-senioren.html")
    private static let representation = DirectorySource(name: "oesterreich.gv.at · Vorsorgevollmacht", url: "https://www.oesterreich.gv.at/de/themen/gesetze_und_recht/erwachsenenvertretung_und_vorsorgevollmacht/4")
    private static let visits = DirectorySource(name: "oesterreich.gv.at · Persönliche Dienste", url: "https://www.oesterreich.gv.at/de/themen/pflege/soziale_dienste/1/Seite.1210130")

    static func guide(for topicID: String) -> DirectoryGuide? {
        guard topicID == "seniors" else { return nil }
        return DirectoryGuide(
            cardSummary: .init(ukrainian: "Самостійність, довірена особа, спілкування й місцеві послуги", german: "Selbständigkeit, Vorsorge, Kontakte und örtliche Dienste"),
            introduction: .init(ukrainian: "Старший вік сам по собі не визначає право на виплати чи догляд. З’ясуйте потребу, страховий стаж, доходи та місцеві послуги окремо.", german: "Alter allein bestimmt weder Leistung noch Pflegeanspruch. Bedarf, Versicherungszeiten, Einkommen und örtliche Dienste getrennt prüfen."),
            sections: [
                .init("health", "heart.text.square", "Зберігайте самостійність", "Selbständigkeit erhalten", "Заплануйте з лікарем контроль ліків, зору, слуху та ризику падінь. Посильний рух, силові й координаційні вправи можуть підтримувати функції; обсяг узгодьте з лікарем при хворобах. Удома перевірте освітлення, килими та поручні.", "Mit Arzt Medikamente, Sehen, Hören und Sturzrisiko besprechen. Angepasste Bewegung, Kraft und Koordination unterstützen Funktionen; bei Krankheit Umfang ärztlich klären. Zu Hause Licht, Teppiche und Haltegriffe prüfen.", source: health),
                .init("plan", "checklist", "Складіть особистий план підтримки", "Persönlichen Unterstützungsplan erstellen", "Запишіть одну відповідальну контактну особу, лікаря, аптеку, ліки й алергії, запасний ключ та спосіб покликати допомогу. Домовтеся, хто помітить, якщо людина не виходить на зв’язок. Перевірте доступність житла й дороги до лікаря. Якщо щоденні дії вже потребують допомоги, детальний порядок заявки описано в розділі «Догляд».", "Eine Kontaktperson, Arzt, Apotheke, Medikamente und Allergien, Ersatzschlüssel und Notrufweg festhalten. Vereinbaren, wer bei ausbleibendem Kontakt nachfragt. Wohnung und Weg zum Arzt prüfen. Bei täglichem Hilfebedarf steht das Antragsverfahren im Bereich Pflege.", source: care),
                .init("representation", "doc.text", "Завчасно визначте довірену особу", "Vertrauensperson rechtzeitig festlegen", "Поки людина може ухвалювати рішення сама, вона може оформити Vorsorgevollmacht на обрані справи. Її складають письмово у нотаріуса, адвоката або в простих випадках у Erwachsenenschutzverein й реєструють в ÖZVV. Довіреність набуває дії лише після встановлення втрати здатності вирішувати відповідні питання та внесення цього факту до реєстру. Обговоріть межі повноважень до підпису.", "Solange die Person entscheidungsfähig ist, kann sie für ausgewählte Angelegenheiten eine Vorsorgevollmacht errichten. Sie wird schriftlich bei Notar:in, Rechtsanwält:in oder in einfachen Fällen beim Erwachsenenschutzverein erstellt und im ÖZVV registriert. Wirksam wird sie erst nach Eintritt und Eintragung des Vorsorgefalls. Umfang vor der Unterschrift besprechen.", source: representation),
                .init("contacts", "person.3", "Уникайте ізоляції", "Kontakte pflegen", "Запитайте у Gemeinde, бібліотеці, клубі чи сусідському центрі про зустрічі й активності для старших людей. Перед участю перевірте доступність і вартість. Якщо людина в кризі або не може подбати про себе, потрібна медична або соціальна оцінка, а не лише зустрічі.", "Bei Gemeinde, Bibliothek, Verein oder Nachbarschaftszentrum nach Angeboten für Ältere fragen. Barrierefreiheit und Kosten vor Teilnahme klären. Bei Krise oder fehlender Selbstversorgung braucht es medizinische oder soziale Abklärung, nicht nur Begegnungsangebote.", source: care),
                .init("visits", "person.crop.circle.badge.checkmark", "Коли бракує контакту й підтримки", "Wenn Kontakte und Hilfe fehlen", "Якщо людина живе сама, запитайте соціальну службу землі чи громади про Besuchsdienst: підготовлені волонтери відвідують, спілкуються і можуть супроводжувати на прогулянці. Окремо уточніть Heimhilfe для покупок і побуту та мобільну Pflege для медичних потреб. Умови, черга й доплата залежать від землі й провайдера; Besuchsdienst не замінює медичний догляд.", "Lebt jemand allein, beim Sozialdienst von Land oder Gemeinde nach Besuchsdienst fragen: angeleitete Freiwillige kommen für Gespräche oder begleiten Ausflüge. Heimhilfe für Einkäufe und Haushalt sowie mobile Pflege für medizinischen Bedarf separat klären. Zugang, Wartezeit und Eigenbeitrag hängen von Land und Träger ab; Besuchsdienst ersetzt keine Pflege.", source: visits)
            ], sources: [care, health, representation, visits]
        )
    }
}
