import Foundation

enum SocialSupportGuides {
    private static let social = DirectorySource(name: "oesterreich.gv.at · Sozialhilfe nach Bundesland", url: "https://www.oesterreich.gv.at/de/themen/hilfe_und_finanzielle_unterstuetzung_erhalten/4/Seite.1693914")
    private static let socialEligibility = DirectorySource(name: "oesterreich.gv.at · Anspruch auf Sozialhilfe", url: "https://www.oesterreich.gv.at/de/lebenslagen/Ich-ben%C3%B6tige-finanzielle-Unterst%C3%BCtzung/finanzielle-unterst%C3%BCtzung-sozialhilfe-bzw-mindestsicherung")
    private static let familyPayment = DirectorySource(name: "oesterreich.gv.at · Familienbeihilfe beantragen", url: "https://www.oesterreich.gv.at/de/themen/familie_und_partnerschaft/familienbeihilfe/Seite.450233")
    private static let childPayment = DirectorySource(name: "oesterreich.gv.at · Kinderbetreuungsgeld", url: "https://www.oesterreich.gv.at/de/themen/familie_und_partnerschaft/finanzielle-unterstuetzungen/3/2/2")
    private static let ukraine = DirectorySource(name: "BBU · Ukraine FAQ und Grundversorgung", url: "https://www.bbu.gv.at/ukraine-info-faq-ukrainian")
    private static let aid = DirectorySource(name: "oesterreich.gv.at · Beratungsstellen in Not", url: "https://www.oesterreich.gv.at/de/themen/hilfe_und_finanzielle_unterstuetzung_erhalten/2/Seite.1694100")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "benefits": benefits
        case "family-benefits": familyBenefits
        case "basic-support": basicSupport
        case "aid-organizations": aidOrganizations
        default: nil
        }
    }

    private static let benefits = DirectoryGuide(
        cardSummary: .init(ukrainian: "Перевірте право, відповідальний орган і вплив статусу перебування", german: "Anspruch, zuständige Stelle und Aufenthaltsstatus prüfen"),
        introduction: .init(ukrainian: "Не всі соціальні виплати доступні кожному мешканцю. Sozialhilfe/Mindestsicherung і Grundversorgung — різні системи; умови й суми залежать від землі та статусу.", german: "Nicht jede Sozialleistung steht allen Bewohnern zu. Sozialhilfe/Mindestsicherung und Grundversorgung sind verschiedene Systeme; Anspruch und Höhe hängen von Land und Status ab."),
        sections: [
            .init("identify", "person.text.rectangle", "З’ясуйте свій шлях", "Passenden Weg bestimmen", "Запишіть документ про перебування, склад сім’ї, доходи, майно, оренду та вже отримувані виплати. Для переміщених осіб із України першою може бути Grundversorgung; право на Sozialhilfe для громадян третіх країн зазвичай обмежене вимогою тривалого законного перебування. Не подавайте однакові витрати у дві програми без повідомлення органів.", "Notieren Sie Aufenthaltstitel, Haushalt, Einkommen, Vermögen, Miete und bestehende Leistungen. Für Vertriebene kann Grundversorgung der passende Weg sein; Sozialhilfe für Drittstaatsangehörige setzt grundsätzlich längeren rechtmäßigen Aufenthalt voraus. Gleiche Bedarfe nicht ohne Offenlegung bei mehreren Stellen geltend machen.", source: socialEligibility),
            .init("state", "map", "Уточніть правила землі", "Landesregeln prüfen", "На офіційному порталі оберіть федеральну землю: відповідальний орган, облік доходів, житлові витрати, додаткова допомога та строки різняться. Подайте документи через належну місцеву службу й попросіть підтвердження дати заяви. При відмові вимагайте письмовий Bescheid з причиною та строком оскарження.", "Auf der amtlichen Seite Bundesland auswählen: Behörde, Einkommensanrechnung, Wohnkosten, Zusatzhilfen und Fristen unterscheiden sich. Antrag bei der lokalen Stelle stellen und Eingang bestätigen lassen. Bei Ablehnung schriftlichen Bescheid mit Grund und Rechtsmittelfrist verlangen.", source: social),
            .init("changes", "arrow.triangle.2.circlepath", "Повідомляйте про зміни", "Änderungen melden", "Початок роботи, переїзд, народження дитини, виїзд з Австрії або нова виплата можуть змінити право. Повідомте орган у визначений строк і збережіть доказ. Не витрачайте спірно переплачену суму до пояснення: можливе повернення.", "Arbeitsbeginn, Umzug, Geburt, Ausreise oder neue Leistung können den Anspruch ändern. Änderungen fristgerecht melden und Nachweis aufbewahren. Strittige Überzahlung bis zur Klärung nicht ausgeben; Rückforderung ist möglich.", source: social)
        ], sources: [social, socialEligibility, ukraine]
    )

    private static let familyBenefits = DirectoryGuide(
        cardSummary: .init(ukrainian: "Familienbeihilfe й Kinderbetreuungsgeld: умови, заяви, взаємодія з Grundversorgung", german: "Familienbeihilfe und Kinderbetreuungsgeld mit Grundversorgung abgleichen"),
        introduction: .init(ukrainian: "Виплати на дитину мають різні органи, строки й умови. Для переміщених українців правила змінювалися у 2025–2026 роках, тому перевіряйте право за поточною датою та власним статусом.", german: "Familienleistungen haben verschiedene Stellen, Fristen und Voraussetzungen. Für Vertriebene änderten sich Regeln 2025–2026; prüfen Sie den Anspruch nach aktuellem Datum und persönlichem Status."),
        sections: [
            .init("family", "figure.child", "Familienbeihilfe", "Familienbeihilfe", "Перевірте постійне проживання дитини, ваш статус, роботу або реєстрацію в AMS і те, чи отримуєте Grundversorgung. Заяву розглядає Finanzamt Österreich; підготуйте документи дитини, проживання й свого статусу. Для повнолітньої дитини окремо перевіряють навчання й дохід. Попросіть письмове рішення щодо вашої сім’ї.", "Dauerhaften Aufenthalt des Kindes, Ihren Status, Arbeit oder AMS-Vormerkung und Grundversorgung prüfen. Zuständig ist Finanzamt Österreich; Unterlagen zu Kind, Wohnsitz und Status bereithalten. Bei Volljährigen zählen Ausbildung und Einkommen zusätzlich. Individuelle schriftliche Entscheidung verlangen.", source: familyPayment),
            .init("baby", "heart", "Kinderbetreuungsgeld", "Kinderbetreuungsgeld", "Після народження перевірте тип виплати, страховика для заяви, строки, умови проживання й потрібні огляди Eltern-Kind-Pass. Дохід і зміна отримувача можуть впливати на суму. Уточніть, чи й як виплата сумісна з Grundversorgung та Familienbeihilfe, перш ніж планувати бюджет.", "Nach Geburt Modell, zuständige Krankenkasse für Antrag, Fristen, Wohnsitz und nötige Eltern-Kind-Pass-Untersuchungen prüfen. Einkommen und Wechsel der beziehenden Person können die Höhe beeinflussen. Zusammenspiel mit Grundversorgung und Familienbeihilfe vor der Budgetplanung klären.", source: childPayment),
            .init("ukraine", "exclamationmark.circle", "Особливі правила для переміщених", "Sonderregeln für Vertriebene", "BBU публікує чинні умови для українців, зокрема зв’язок сімейних виплат із Grundversorgung, працею або AMS. Законодавство 2026 року змінювалося; не покладайтеся на старі рішення чи суми в соцмережах. Перед відмовою від Grundversorgung попросіть у обох органів письмове пояснення дати й наслідків.", "Die BBU veröffentlicht aktuelle Regeln für Vertriebene, insbesondere zu Grundversorgung, Beschäftigung und AMS. Das Recht wurde 2026 geändert; alte Bescheide oder Social-Media-Beträge nicht übernehmen. Vor Verzicht auf Grundversorgung bei beiden Stellen schriftlich Datum und Folgen klären.", source: ukraine)
        ], sources: [familyPayment, childPayment, ukraine]
    )

    private static let basicSupport = DirectoryGuide(
        cardSummary: .init(ukrainian: "Житло, харчування, медичне покриття і орган вашої землі", german: "Unterkunft, Verpflegung, Krankenversorgung und Landesstelle"),
        introduction: .init(ukrainian: "Grundversorgung залежить від потреби й рішення землі. Поліцейська реєстрація та Ausweis für Vertriebene не замінюють окремої заяви на допомогу.", german: "Grundversorgung setzt Bedürftigkeit und eine Landesentscheidung voraus. Polizeiliche Erfassung und Vertriebenenausweis ersetzen den gesonderten Antrag nicht."),
        sections: [
            .init("apply", "building.2", "Подайте заяву в землі", "Antrag im Bundesland stellen", "На FAQ BBU знайдіть Grundversorgungsstelle землі, де фактично проживаєте. Уточніть різницю між приватним та організованим житлом, потрібні документи й спосіб подання. Візьміть Ausweis für Vertriebene, Meldezettel, дані родини, доходів і житла; попросіть підтвердження прийняття заяви.", "In den BBU-FAQ Grundversorgungsstelle des Wohnbundeslandes finden. Unterschied zwischen privater und organisierter Unterkunft, Nachweise und Antragsweg klären. Vertriebenenausweis, Meldezettel, Haushalt, Einkommen und Unterkunft belegen; Eingang bestätigen lassen.", source: ukraine),
            .init("scope", "checklist", "Що може покриватися", "Mögliche Leistungen", "За рішенням землі допомога може включати проживання, харчування або грошові кошти, консультацію та медичне страхування. Розмір залежить від виду житла, складу сім’ї, доходів та землі. Попросіть письмовий розрахунок і окреме підтвердження медичного покриття; не припускайте його до включення в систему.", "Je nach Landesentscheidung können Unterkunft, Verpflegung oder Geld, Beratung und Krankenversicherung dazugehören. Höhe hängt von Wohnform, Haushalt, Einkommen und Land ab. Schriftliche Berechnung und gesonderte Bestätigung der Krankenversicherung verlangen.", source: ukraine),
            .init("review", "arrow.triangle.2.circlepath", "Переїзд або зміна доходу", "Umzug oder Einkommensänderung", "Повідомте відповідальну службу до або відразу після переїзду чи початку роботи й запитайте, яка земля продовжить допомогу. Зміна землі може вимагати нової заяви і створити перерву в житлі або страхуванні. Зберігайте рішення та листування; при відмові запитайте про письмове оскарження.", "Landesstelle vor oder unmittelbar nach Umzug bzw. Arbeitsbeginn informieren und Zuständigkeit klären. Landeswechsel kann neuen Antrag und Lücke bei Wohnen oder Versicherung auslösen. Bescheide und Schriftverkehr sichern; bei Ablehnung Rechtsmittel erfragen.", source: ukraine)
        ], sources: [ukraine]
    )

    private static let aidOrganizations = DirectoryGuide(
        cardSummary: .init(ukrainian: "Соціальні консультації, їжа, кризова допомога й перевірка пропозиції", german: "Sozialberatung, Essen, Krisenhilfe und seriöse Angebote"),
        introduction: .init(ukrainian: "Недержавні організації можуть допомогти з конкретною потребою або направити до відповідального органу. Їхні послуги й вільні місця різняться за регіонами.", german: "Hilfsorganisationen unterstützen bei konkreten Notlagen oder vermitteln an Behörden. Angebot und Kapazität unterscheiden sich regional."),
        sections: [
            .init("find", "magnifyingglass", "Знайдіть перевірену службу", "Verlässliche Stelle finden", "Офіційний перелік містить Caritas, Diakonie, Rotes Kreuz та інші загальноавстрійські організації. Оберіть місцеве відділення й запитайте, чи є соціальна консультація, продуктова, житлова або медична допомога та чи потрібен запис. Допомога не завжди фінансова і не гарантується самим зверненням.", "Die amtliche Übersicht nennt Caritas, Diakonie, Rotes Kreuz und weitere österreichweite Dienste. Lokale Stelle wählen und nach Sozialberatung, Essen, Wohnen oder medizinischer Hilfe sowie Termin fragen. Kontakt allein garantiert keine Geldleistung.", source: aid),
            .init("prepare", "doc.text", "Підготуйте ситуацію", "Situation vorbereiten", "Коротко опишіть термінову потребу, склад сім’ї, статус перебування, доходи й уже подані заяви. Принесіть тільки документи, потрібні для консультації, і з’ясуйте, як оброблятимуться персональні дані. Якщо загрожує втрата житла або немає їжі сьогодні, скажіть це на початку розмови.", "Dringenden Bedarf, Haushalt, Aufenthalt, Einkommen und laufende Anträge kurz schildern. Nur für die Beratung nötige Dokumente mitbringen und Datenverwendung klären. Drohenden Wohnungsverlust oder Hunger heute gleich zu Beginn nennen.", source: aid),
            .init("avoid", "checkmark.shield", "Перевіряйте посередників", "Vermittler prüfen", "Справжня допомога не вимагає передати оригінал паспорта сторонній особі чи оплатити «гарантовану» виплату. Звірте адресу та телефон на офіційному сайті організації. Якщо вам пропонують підписати незрозуміле зобов’язання або віддати доступ до банку, зробіть паузу й зверніться до незалежної консультації.", "Echte Hilfe verlangt nicht, Fremden den Originalpass zu überlassen oder für eine „garantierte“ Leistung zu zahlen. Adresse und Nummer auf der offiziellen Organisationsseite prüfen. Bei unklarer Verpflichtung oder verlangtem Bankzugang erst unabhängige Beratung einholen.", source: aid)
        ], sources: [aid]
    )
}
