import Foundation

extension TransportGuides {
    static let accessibleTravel = DirectoryGuide(
        cardSummary: .init(ukrainian: "Доступність маршруту, допомога ÖBB і запасний план", german: "Barrierefreie Route, ÖBB-Hilfe und Ersatzplan"),
        introduction: .init(ukrainian: "Перевіряйте всю подорож: вихід із дому, станції, вагони, пересадки й прибуття. Доступний поїзд сам по собі не гарантує доступного маршруту.", german: "Die ganze Reisekette prüfen: Anreise, Bahnhöfe, Wagen, Umstiege und Ziel. Ein barrierefreier Zug allein garantiert noch keine zugängliche Reise."),
        sections: [
            .init("route", "figure.roll", "Перевірте кожну пересадку", "Jeden Umstieg prüfen", "У планувальнику перевірте ліфти, платформи, час переходу, тип вагона, місце для візка й доступний туалет. Для автобуса уточніть у місцевого перевізника, чи підходить саме запланований рейс і зупинка. Якщо потрібен підйомник, не покладайтеся лише на позначку доступності в розкладі.", "Im Planer Lifte, Bahnsteige, Umsteigezeit, Wagentyp, Rollstuhlplatz und zugängliches WC prüfen. Beim Bus den örtlichen Betreiber fragen, ob genau dieser Kurs und Halt geeignet sind. Bei benötigter Hebehilfe nicht allein auf ein Barrierefreiheitssymbol vertrauen.", source: mobility),
            .init("request", "person.2", "Повідомте ÖBB про потребу", "Hilfebedarf bei ÖBB anmelden", "Передайте Mobilitätsservice дату, усі станції посадки, пересадки й прибуття, тип допомоги, розміри засобу пересування, супровід і контакт. Попросіть підтвердження місця зустрічі та допомоги на кожному етапі; квиток і резервацію місця для візка перевіряйте окремо.", "Dem Mobilitätsservice Datum, alle Ein-, Um- und Ausstiegsbahnhöfe, Hilfebedarf, Maße des Hilfsmittels, Begleitung und Kontakt nennen. Treffpunkt und Hilfe für jede Etappe bestätigen lassen; Fahrkarte und Rollstuhlplatzreservierung gesondert prüfen.", source: mobility),
            .init("deadline", "clock", "Дотримайтеся строку заявки", "Anmeldefrist beachten", "За чинною сторінкою ÖBB для подорожі всередині Австрії заявку на допомогу подають щонайпізніше за 12 годин; якщо виїзд до 9:00 — до 18:00 попереднього дня. Для міжнародних подорожей ÖBB вказує 24 години; через участь іноземного перевізника краще звернутися раніше. На визначених великих вокзалах існує скорочений строк; перевірте конкретний маршрут на сторінці ÖBB і дочекайтеся підтвердження.", "Laut aktueller ÖBB-Seite die Hilfe im Inland spätestens 12 Stunden vorher anmelden; bei Abfahrt vor 9 Uhr bis 18 Uhr am Vortag. Für internationale Reisen nennt ÖBB 24 Stunden; wegen der beteiligten Partnerbahnen besser früher anfragen. Zwischen bestimmten großen Bahnhöfen gilt eine kürzere Frist; konkrete Strecke auf der ÖBB-Seite prüfen und Bestätigung abwarten.", source: mobility),
            .init("departure", "location", "Перед виїздом перевірте зміни", "Vor Abfahrt Änderungen prüfen", "Перевірте стан ліфтів і повідомлення про заміну вагона чи платформи. Прибудьте до погодженого місця зустрічі в зазначений ÖBB час і майте номер бронювання та контакт Mobilitätsservice. Якщо допомога не підтверджена, зв’яжіться зі службою ще до посадки.", "Liftstatus sowie Wagen- und Bahnsteigänderungen prüfen. Zum vereinbarten Zeitpunkt am bestätigten Treffpunkt sein und Buchungsnummer sowie Mobilitätsservice-Kontakt bereithalten. Fehlt eine Bestätigung, vor dem Einstieg nachfragen.", source: mobility),
            .init("disruption", "exclamationmark.triangle", "Якщо ліфт або допомога відсутні", "Wenn Lift oder Hilfe ausfallen", "Повідомте Mobilitätsservice або персонал, яка частина маршруту недоступна, і попросіть безпечну альтернативу до пункту призначення. Не погоджуйтеся на небезпечне перенесення візка. Збережіть повідомлення про збій, квиток і чеки; спершу подайте вимогу перевізнику, а за невирішеного спору — до apf.", "Mobilitätsservice oder Personal mitteilen, welcher Abschnitt nicht zugänglich ist, und eine sichere Alternative zum Ziel verlangen. Unsicheres Tragen des Rollstuhls nicht akzeptieren. Störungsmeldung, Ticket und Belege sichern; zuerst beim Betreiber reklamieren, bei ungelöstem Streit bei der apf.", source: railRights)
        ], sources: [mobility, railRights]
    )
}
