import Foundation

extension TransportGuides {
    static let railGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Розклад, тип квитка, пересадки й права при затримці", german: "Fahrplan, Ticketart, Umstieg und Rechte bei Verspätung"),
        introduction: .init(ukrainian: "Перед оплатою перевірте, хто продає квиток, яким поїздом він дозволяє їхати й чи включена резервація. У разі збою зберігайте документи по всьому маршруту.", german: "Vor Zahlung prüfen, wer das Ticket verkauft, welche Züge es erlaubt und ob eine Reservierung enthalten ist. Bei Störungen Unterlagen für die ganze Reise sichern."),
        sections: [
            .init("route", "tram", "Сплануйте весь шлях", "Gesamte Reise planen", "У Scotty введіть початкову й кінцеву станції, дату та час. Перевірте фактичний час пересадки, платформу, роботи на лінії й останнє сполучення. Для кількох перевізників з’ясуйте, чи купуєте один наскрізний квиток або окремі договори. Перед відправленням перегляньте маршрут знову.", "In Scotty Start- und Zielbahnhof, Datum und Zeit eingeben. Tatsächliche Umsteigezeit, Bahnsteig, Bauarbeiten und letzte Verbindung prüfen. Bei mehreren Betreibern klären, ob ein durchgehendes Ticket oder getrennte Verträge gekauft werden. Vor Abfahrt erneut nachsehen.", source: routePlanner),
            .init("fare", "ticket", "Розрізніть Standard і Sparschiene", "Standard und Sparschiene unterscheiden", "ÖBB Standardticket зазвичай не прив’язаний до конкретного поїзда на обраному маршруті; Sparschiene прив’язаний і, як правило, не повертається. Sparschiene Komfort має інші умови скасування. Перед оплатою відкрийте правила саме запропонованого тарифу: дату, поїзд, ім’я, можливість зміни й повернення. Квиток транспортного об’єднання має власні строки дії.", "ÖBB Standardtickets sind auf der gewählten Strecke grundsätzlich nicht zuggebunden; Sparschiene ist zuggebunden und meist nicht erstattbar. Sparschiene Komfort hat andere Stornobedingungen. Vor Zahlung Tarifregeln für Datum, Zug, Namen, Umbuchung und Erstattung lesen. Verbundtickets haben eigene Geltungszeiten.", source: railFare),
            .init("seat", "chair", "Перевірте резервацію місця", "Sitzplatzreservierung prüfen", "Квиток і місце — різні речі: перевірте, чи резервація включена, чи її потрібно докупити. Для нічного поїзда перевірте тип місця або купе та час посадки. Збережіть номер вагона і місця, але перед відправленням звірте можливу зміну складу на табло.", "Fahrkarte und Sitzplatz sind nicht dasselbe: prüfen, ob die Reservierung enthalten ist oder extra gekauft werden muss. Im Nachtzug Sitz- bzw. Abteiltyp und Einstiegszeit kontrollieren. Wagen- und Platznummer sichern, vor Abfahrt mögliche Wagenänderungen am Display prüfen.", source: rail),
            .init("disruption", "arrow.triangle.2.circlepath", "Якщо поїзд скасовано або затримка буде великою", "Bei Ausfall oder erheblicher Verspätung", "Якщо запізнення в кінцевий пункт за квитком очікується від 60 хвилин, запитайте перевізника про вибір: повернути вартість і не їхати, продовжити подорож без доплати за найближчої нагоди або пізніше. Якщо зв’язок втрачено, попросіть підтвердження нової поїздки, особливо для Sparschiene. Не купуйте дорогий альтернативний транспорт, не з’ясувавши умови відшкодування.", "Ist am Ziel laut Ticket eine Verspätung ab 60 Minuten zu erwarten, beim Betreiber zwischen Erstattung ohne Reise, Weiterfahrt ohne Aufpreis bei nächster Gelegenheit oder zu einem späteren Zeitpunkt wählen. Bei verpasstem Anschluss neue Fahrt bestätigen lassen, besonders mit Sparschiene. Teure Alternativen nicht ohne Klärung der Erstattungsbedingungen buchen.", source: railRights),
            .init("compensation", "eurosign.circle", "Компенсація після поїздки", "Entschädigung nach der Reise", "Для відповідного разового квитка в далекому сполученні затримка прибуття до пункту в квитку від 60 хвилин дає 25 % ціни, від 120 хвилин — 50 %, якщо ви не відмовилися від поїздки з поверненням коштів. Для KlimaTicket та інших проїзних діють інші правила: не рахуйте відсоток за кожну окрему поїздку. Збережіть квиток і підтвердження затримки.", "Bei passenden Fernverkehr-Einzeltickets gibt eine Ankunft ab 60 Minuten Verspätung am Ticketziel 25 %, ab 120 Minuten 50 % des Fahrpreises, sofern keine Rückgabe mit Erstattung erfolgte. Für KlimaTicket und andere Zeitkarten gelten andere Regeln, keine Prozententschädigung pro Einzelfahrt. Ticket und Verspätungsnachweis aufbewahren.", source: railRights),
            .init("complaint", "doc.text", "Подайте вимогу й скаргу", "Anspruch und Beschwerde einreichen", "Зверніться письмово до відповідного перевізника: додайте квиток, номер поїзда, дату, час прибуття й чеки за необхідні витрати. Для скарги діє строк до трьох місяців після події. Якщо відповідь відхилено або її немає протягом місяця, зверніться до незалежної apf. Не плутайте скаргу на збій із добровільним скасуванням квитка.", "Schriftlich beim zuständigen Unternehmen einreichen: Ticket, Zugnummer, Datum, Ankunftszeit und Belege notwendiger Ausgaben beifügen. Die Beschwerde ist bis drei Monate nach dem Vorfall einzureichen. Nach Ablehnung oder einem Monat ohne Antwort an die unabhängige apf wenden. Störungsrechte nicht mit freiwilligem Ticketstorno verwechseln.", source: railComplaint)
        ], sources: [routePlanner, railFare, rail, railRights, railComplaint]
    )
}
