import Foundation

extension TransportGuides {
    static let bus = DirectoryGuide(
        cardSummary: .init(ukrainian: "Посадка, багаж, пересадки й права при скасуванні", german: "Einstieg, Gepäck, Umstieg und Rechte bei Ausfall"),
        introduction: .init(ukrainian: "Міжміський автобус може не входити до регіонального тарифу. Умови бронювання й права залежать від перевізника та довжини регулярного маршруту.", german: "Ein Fernbus kann außerhalb des Verbundtarifs verkehren. Buchungsbedingungen und Fahrgastrechte hängen vom Unternehmen und der Länge der regelmäßigen Linie ab."),
        sections: [
            .init("book", "bus", "Перед оплатою звірте рейс", "Fahrt vor Zahlung prüfen", "Перевірте точну зупинку й платформу, час початку посадки, ім’я пасажира, допустимий багаж і правила перевезення дітей. Якщо автобус і поїзд куплені окремо, не припускайте гарантованої пересадки. Для поїздки через кордон перевірте проїзні документи й умови в’їзду.", "Genaue Haltestelle und Steig, Boardingzeit, Fahrgastnamen, Gepäckgrenzen und Kinderregeln prüfen. Bei getrennt gebuchtem Bus und Zug keinen garantierten Anschluss annehmen. Bei Grenzfahrt Reisedokumente und Einreisebedingungen prüfen.", source: busRights),
            .init("ticket", "ticket", "Перевірте дію квитка й зміну бронювання", "Ticket und Umbuchung prüfen", "Перевірте, чи купили квиток саме на рейс міжміського перевізника: KlimaTicket Ö діє не на всіх Fernbus-лініях. До оплати прочитайте умови повернення, зміни дати й імені та можливі збори. Збережіть підтвердження бронювання офлайн, якщо на зупинці не буде інтернету.", "Prüfen, ob ein Ticket für genau diese Fernbuslinie gekauft wurde: KlimaTicket Ö gilt nicht auf allen Linien. Vor Zahlung Storno-, Datums- und Namensänderung sowie Gebühren lesen. Buchungsbestätigung offline sichern, falls am Halt kein Internet verfügbar ist.", source: climate),
            .init("station", "location", "На зупинці перевірте повідомлення", "Am Halt Meldungen prüfen", "Приходьте до часу посадки, зазначеного перевізником. Якщо автобуса немає, перевірте повідомлення в застосунку й на табло, сфотографуйте час і місце, попросіть перевізника письмово підтвердити затримку або скасування. Це допоможе відрізнити запізнення від зміни платформи чи раннього відправлення.", "Zur vom Unternehmen genannten Einstiegszeit am Halt sein. Bleibt der Bus aus, App und Anzeigetafel prüfen, Zeit und Ort dokumentieren und eine schriftliche Bestätigung über Verspätung oder Ausfall verlangen. So lassen sich Verspätung, Steigwechsel und verfrühte Abfahrt unterscheiden.", source: busDelay),
            .init("rights", "arrow.triangle.2.circlepath", "Скасування або понад 120 хвилин очікування", "Ausfall oder über 120 Minuten Wartezeit", "На регулярних маршрутах від 250 км при скасуванні або прогнозованій затримці відправлення понад 120 хвилин перевізник має запропонувати вибір між продовженням/іншим маршрутом і поверненням вартості, якщо ви не їдете. На коротших маршрутах права вужчі. Попросіть варіанти письмово до того, як самостійно купувати заміну.", "Auf regelmäßigen Linien ab 250 km muss das Unternehmen bei Ausfall oder voraussichtlich über 120 Minuten verspäteter Abfahrt zwischen Weiterreise/Umleitung und Erstattung bei Nichtantritt wählen lassen. Unter 250 km gelten eingeschränktere Rechte. Optionen schriftlich erfragen, bevor Sie selbst Ersatz buchen.", source: busDelay),
            .init("complaint", "doc.text", "Коли вимагати компенсацію", "Wann eine Entschädigung entsteht", "Саме запізнення прибуття автобуса не дає автоматичних 25 % чи 50 %, як у поїзді. Якщо за умов відповідного довгого маршруту перевізник не запропонував обов’язковий вибір між поверненням і продовженням поїздки, може виникнути право на 50 % ціни додатково. Подайте скаргу спочатку перевізнику з квитком і доказами; якщо спір не вирішено — до apf.", "Eine verspätete Busankunft gibt nicht automatisch 25 % oder 50 % wie bei der Bahn. Bietet das Unternehmen auf einer betroffenen langen Linie die vorgeschriebene Wahl zwischen Erstattung und Weiterreise nicht an, kann zusätzlich ein Anspruch auf 50 % entstehen. Erst mit Ticket und Nachweisen beim Betreiber reklamieren, danach gegebenenfalls bei der apf.", source: busDelay)
        ], sources: [busRights, busDelay, climate]
    )
}
