import Foundation

extension TransportGuides {
    static let taxiGuide = DirectoryGuide(
        cardSummary: .init(ukrainian: "Як замовити, погодити ціну й вирішити спір", german: "Bestellung, Fahrpreis und Reklamation"),
        introduction: .init(ukrainian: "Тарифи таксі різняться за містом і землею. Вартість з лічильника та погоджена наперед ціна — різні способи розрахунку.", german: "Taxitarife unterscheiden sich nach Stadt und Land. Taxameterpreis und vorab vereinbarter Fahrpreis sind unterschiedliche Modelle."),
        sections: [
            .init("order", "car", "Замовте і звірте автомобіль", "Fahrzeug bestellen und abgleichen", "Користуйтеся офіційною стоянкою, диспетчерською або застосунком, де видно перевізника. Перед посадкою звірте номер машини з бронюванням; якщо дані не збігаються, не сідайте й зверніться до сервісу. Для дитини, великого багажу або авто з доступом для візка вкажіть потребу під час замовлення.", "Offiziellen Standplatz, Zentrale oder App mit Betreiberangaben nutzen. Vor Einstieg Kennzeichen mit Buchung abgleichen; bei Abweichung nicht einsteigen und den Dienst kontaktieren. Kind, großes Gepäck oder rollstuhlgerechtes Fahrzeug bei Bestellung angeben.", source: taxiLicence),
            .init("price", "eurosign.circle", "З’ясуйте ціну до посадки", "Preis vor Einstieg klären", "Назвіть точну адресу й запитайте, чи діє місцевий тариф таксометра або погоджена при замовленні ціна. Окремо уточніть очікування, багаж і маршрут до аеропорту. У Відні місто пояснює обидва варіанти на сторінці тарифу; в іншій землі перевіряйте її власні правила, а не переносіть віденську ціну.", "Genaue Zieladresse nennen und nach örtlichem Taxametertarif oder vorab vereinbartem Preis fragen. Wartezeit, Gepäck und Flughafenstrecke gesondert klären. Wien erklärt beide Varianten auf seiner Tarifseite; in anderen Ländern deren eigene Regeln prüfen, den Wiener Preis nicht übertragen.", source: taxiTariff),
            .init("confirmation", "checkmark.seal", "Збережіть домовленість", "Vereinbarung sichern", "Для замовлення через застосунок зробіть скриншот запропонованої або погодженої ціни, адреси й даних поїздки. Якщо платить інша особа чи організація, до виїзду з’ясуйте, кому саме виставляють рахунок. Не залишайте паспорт чи інші документи як заставу.", "Bei App-Bestellung angebotenen oder vereinbarten Preis, Ziel und Fahrtdaten per Screenshot sichern. Zahlt eine andere Person oder Stelle, vor Fahrt klären, an wen abgerechnet wird. Reisepass oder andere Dokumente nicht als Pfand abgeben.", source: taxiTariff),
            .init("receipt", "doc.text", "Попросіть підтвердження оплати", "Zahlungsbeleg verlangen", "Після поїздки попросіть чек або електронне підтвердження з датою, сумою й даними перевізника. Одразу порівняйте суму з таксометром або домовленою ціною. Якщо виявили розбіжність, запишіть номер машини й час, збережіть бронювання та зверніться до компанії.", "Nach der Fahrt Beleg oder elektronische Bestätigung mit Datum, Betrag und Betreiber verlangen. Betrag sofort mit Taxameter oder vereinbartem Preis vergleichen. Bei Abweichung Kennzeichen und Zeit notieren, Buchung sichern und den Betreiber kontaktieren.", source: taxiTariff),
            .init("help", "exclamationmark.triangle", "Якщо виник конфлікт", "Bei einem Konflikt", "При спорі про ціну спочатку письмово зверніться до диспетчерської або платформи й додайте чек, маршрут і підтвердження ціни. Якщо підозрюєте порушення правил перевезення, запитайте у Bezirksverwaltungsbehörde або Magistrat, куди подати повідомлення. При безпосередній загрозі безпеці телефонуйте 133.", "Bei Preisstreit zuerst schriftlich an Zentrale oder Plattform mit Beleg, Strecke und Preisbestätigung wenden. Bei Verdacht auf Verstöße gegen Beförderungsregeln Bezirksverwaltungsbehörde oder Magistrat nach der zuständigen Meldestelle fragen. Bei akuter Gefahr 133 wählen.", source: taxi)
        ], sources: [taxiLicence, taxiTariff, taxi]
    )
}
