import Foundation

extension TransportGuides {
    static let localTransport = DirectoryGuide(
        cardSummary: .init(ukrainian: "Маршрут, місцевий тариф, квиток і пересадки", german: "Route, Verbundtarif, Ticket und Umstieg"),
        introduction: .init(ukrainian: "Місцеві правила відрізняються за транспортним об’єднанням. Оберіть свою землю нижче, щоб відкрити офіційний планувальник і тарифи.", german: "Nahverkehrsregeln unterscheiden sich je Verkehrsverbund. Wählen Sie unten Ihr Bundesland für Fahrplan und Tarife."),
        sections: [
            .init("route", "tram", "Знайдіть маршрут до потрібної адреси", "Verbindung bis zur Zieladresse finden", "У Scotty або планувальнику місцевого об’єднання введіть адресу чи точну зупинку, дату й час. Перевірте пішохідні ділянки, пересадки, останній рейс і зміни в реальному часі. Розклад перевірте ще раз перед виходом, особливо ввечері й у вихідні.", "In Scotty oder beim örtlichen Verbund Adresse bzw. genaue Haltestelle, Datum und Uhrzeit eingeben. Fußwege, Umstiege, letzte Fahrt und Echtzeitänderungen prüfen. Vor dem Aufbruch erneut nachsehen, besonders abends und am Wochenende.", source: routePlanner),
            .init("tariff", "map", "Перевірте територію тарифу", "Tarifgebiet prüfen", "Не кожне об’єднання рахує однаково: у VOR тариф прив’язаний до маршруту, в інших землях часто діють зони або «стільники». У місцевому планувальнику порівняйте квиток для всього маршруту й окремі частини, особливо при перетині межі об’єднання. Квиток одного міста не вважайте автоматично дійсним у сусідній землі.", "Nicht jeder Verbund rechnet gleich: VOR nutzt einen Streckentarif, andere häufig Zonen oder Waben. Im örtlichen Planer das Ticket für die gesamte Strecke und bei Verbundgrenzen die Teilstrecken prüfen. Ein Stadtticket gilt nicht automatisch im Nachbarland.", source: ticketModels),
            .init("purchase", "ticket", "Купіть і активуйте квиток до поїздки", "Ticket vor der Fahrt kaufen und aktivieren", "Порівняйте разовий, денний та проїзний за фактичною кількістю поїздок. У ÖBB Ticketshop можна шукати наскрізний квиток із поїздом, автобусом і трамваєм; перед оплатою перевірте, що включено всі частини маршруту. Звірте дату, початок дії, знижку й правила активації чи компостування. Перед посадкою перевірте, що цифровий квиток дійсний.", "Einzel-, Tages- und Zeitkarte nach tatsächlichen Fahrten vergleichen. Im ÖBB Ticketshop kann ein durchgehendes Ticket für Zug, Bus und Straßenbahn gesucht werden; vor Zahlung alle Reiseabschnitte prüfen. Datum, Gültigkeitsbeginn, Ermäßigung sowie Aktivierung oder Entwertung kontrollieren. Vor Einstieg prüfen, ob das digitale Ticket gültig ist.", source: localTickets),
            .init("climate", "globe.europe.africa", "Оберіть правильний KlimaTicket", "Passendes KlimaTicket wählen", "KlimaTicket Ö і регіональний KlimaTicket мають різні території дії. Перед купівлею перевірте старт дії, персональні умови та чи охоплено ваші регулярні маршрути. Для окремих туристичних ліній, Vienna Airport Lines і деяких спеціальних рейсів потрібен інший квиток; звірте офіційний перелік винятків. Онлайн-покупка KlimaTicket Ö не обов’язково діє з сьогоднішнього дня.", "KlimaTicket Ö und regionale KlimaTickets haben unterschiedliche Geltungsgebiete. Vor Kauf Startdatum, persönliche Voraussetzungen und Pendelstrecken prüfen. Für manche touristische Linien, Vienna Airport Lines und Sonderverkehre ist ein anderes Ticket nötig; amtliche Ausnahmen prüfen. Das online gekaufte KlimaTicket Ö gilt nicht zwingend ab heute.", source: climate),
            .init("change", "arrow.triangle.2.circlepath", "Якщо маршрут змінився", "Wenn sich die Verbindung ändert", "Перевірте нову платформу й альтернативний рейс у планувальнику. Якщо доведеться їхати іншим перевізником або за іншим маршрутом, перед посадкою уточніть у персоналу чи транспортного об’єднання, чи чинний ваш квиток. Збережіть повідомлення про збій і квиток для звернення до продавця.", "Neuen Steig und Ersatzverbindung im Planer prüfen. Bei anderem Betreiber oder anderer Strecke vor dem Einstieg bei Personal oder Verbund klären, ob Ihr Ticket gilt. Störungsmeldung und Ticket für eine Anfrage beim Verkäufer aufbewahren.", source: routePlanner)
        ], sources: [routePlanner, ticketModels, localTickets, regionalTickets, climate]
    )
}
