import Foundation

extension WorkGuides {
    static let jobSearch = DirectoryGuide(
        cardSummary: .init(ukrainian: "AMS, вакансії, CV, співбесіда й перевірка пропозиції", german: "AMS, Stellen, Lebenslauf, Gespräch und Angebotsprüfung"),
        introduction: .init(ukrainian: "Почніть з консультації AMS, паралельно шукайте вакансії самостійно й ведіть список заявок. Реєстрація для пошуку роботи не створює автоматичного права на Arbeitslosengeld.", german: "Starten Sie mit AMS-Beratung, suchen Sie parallel selbst und dokumentieren Sie Bewerbungen. Die Vormerkung zur Arbeitssuche schafft keinen automatischen Anspruch auf Arbeitslosengeld."),
        sections: [
            .init("ams", "building.2", "Перший візит до AMS", "Erster AMS-Termin", "Візьміть Ausweis für Vertriebene або інший титул, адресу, CV і наявні підтвердження освіти та досвіду. Попросіть визначити професійний профіль, відповідні вакансії, потребу в мові чи курсах і дату наступної зустрічі. Якщо працювали в Австрії, право на Arbeitslosengeld перевіряється окремою заявою та страховими періодами.", "Ausweis für Vertriebene oder anderen Titel, Adresse, Lebenslauf und Ausbildungs- bzw. Erfahrungsnachweise mitbringen. Berufsprofil, passende Stellen, Sprach- oder Kursbedarf und nächsten Termin klären. Nach Arbeit in Österreich wird Arbeitslosengeld mit eigenem Antrag und Versicherungszeiten gesondert geprüft.", source: ams),
            .init("search", "magnifyingglass", "Знайдіть і збережіть вакансії", "Stellen finden und merken", "У AMS «alle jobs» введіть професію або навичку та місто чи індекс, налаштуйте години й актуальність; пошук безкоштовний і без реєстрації. Вакансія в «alle jobs» не завжди дає кнопку прямої заявки: перейдіть за вказаним каналом роботодавця або використайте eJob-Room для оголошень AMS. Фіксуйте дату й посилання, щоб не надсилати заяву двічі.", "In AMS «alle jobs» Beruf oder Kompetenz und Ort/PLZ eingeben, Arbeitszeit und Aktualität filtern; kostenlos ohne Registrierung. «alle jobs» bietet nicht immer eine direkte Bewerbung: dem genannten Kanal des Betriebs folgen oder bei AMS-Stellen den eJob-Room nutzen. Datum und Link notieren, damit Sie sich nicht doppelt bewerben.", source: allJobs),
            .init("apply", "envelope", "Надішліть цільову заявку", "Gezielt bewerben", "Складіть короткий CV з досвідом, мовами, контактами та доступністю. У супровідному листі назвіть конкретну вакансію і 2–3 відповідні навички. Додавайте лише запитані дипломи чи довідки; перевірте PDF, адресу отримувача й тему листа. Зберігайте надіслані версії й відповіді для консультації AMS.", "Kurzen Lebenslauf mit Erfahrung, Sprachen, Kontakt und Verfügbarkeit erstellen. Im Anschreiben konkrete Stelle und zwei bis drei passende Fähigkeiten nennen. Nur verlangte Nachweise beilegen; PDF, Empfänger und Betreff prüfen. Gesendete Versionen und Antworten für den AMS-Termin aufbewahren.", source: application),
            .init("offer", "checkmark.shield", "Оцініть пропозицію до згоди", "Angebot vor Zusage prüfen", "Попросіть повну назву роботодавця, робоче місце, години, брутто-оплату й назву Kollektivvertrag. Порівняйте письмову пропозицію з оголошенням; підозрілі вимоги заплатити за найм або залишити паспорт не приймайте. Якщо незрозуміла Einstufung чи утримання із зарплати, покажіть документи Arbeiterkammer до підпису.", "Vollständigen Betriebsnamen, Arbeitsort, Stunden, Bruttoentgelt und Kollektivvertrag erfragen. Schriftliches Angebot mit Inserat vergleichen; Forderungen nach Zahlung für die Stelle oder Abgabe des Passes nicht akzeptieren. Unklare Einstufung oder Abzüge vor Unterschrift bei der Arbeiterkammer prüfen lassen.", source: contract)
        ], sources: [ams, allJobs, application, contract]
    )

}
