import Foundation

extension WorkGuides {
    static let workRights = DirectoryGuide(
        cardSummary: .init(ukrainian: "Посвідчення переміщеної особи, студентський титул і початок роботи", german: "Vertriebenenausweis, Studierendentitel und Arbeitsbeginn"),
        introduction: .init(ukrainian: "Перед наймом перевірте саме свою підставу перебування. Ausweis für Vertriebene дає доступ до найманої праці без окремого дозволу AMS з 21 квітня 2023 року; інші титули можуть мати інші правила.", german: "Vor Arbeitsbeginn die eigene Aufenthaltsgrundlage prüfen. Mit Ausweis für Vertriebene ist seit 21. April 2023 keine eigene AMS-Beschäftigungsbewilligung nötig; für andere Titel gelten andere Regeln."),
        sections: [
            .init("status", "person.text.rectangle", "Ausweis für Vertriebene", "Ausweis für Vertriebene", "Покажіть роботодавцю чинний Ausweis für Vertriebene. За даними AMS, з 21.04.2023 для найманої роботи з цим статусом не потрібна Beschäftigungsbewilligung; роботодавець може перевірити це за офіційним посиланням. Після переходу на інший титул перевірте вже його умови, а не продовжуйте посилатися на правила для переміщених.", "Legen Sie dem Betrieb den gültigen Ausweis für Vertriebene vor. Laut AMS braucht es seit 21.04.2023 mit diesem Status keine Beschäftigungsbewilligung; der Betrieb kann das über die amtliche Seite prüfen. Nach Wechsel auf einen anderen Titel dessen Bedingungen neu prüfen.", source: permission),
            .init("student", "graduationcap", "Якщо маєте студентський титул", "Mit Aufenthaltsbewilligung Student", "Для Aufenthaltsbewilligung – Student із третьої країни роботодавець подає заяву на Beschäftigungsbewilligung до AMS навіть для geringfügig. До 20 годин на тиждень дозвіл може бути виданий без перевірки ринку праці; понад 20 годин діють додаткові умови. Не починайте роботу до дозволу й стежте, щоб навчання лишалося головною метою перебування.", "Bei einer Aufenthaltsbewilligung – Student für Drittstaatsangehörige beantragt der Arbeitgeber die Beschäftigungsbewilligung beim AMS, auch bei geringfügiger Arbeit. Bis 20 Wochenstunden ist sie ohne Arbeitsmarktprüfung möglich; darüber gelten weitere Voraussetzungen. Erst nach Bewilligung anfangen und Studium als Hauptzweck wahren.", source: studentWork),
            .init("contract", "doc.text", "Зафіксуйте умови найму", "Arbeitsbedingungen festhalten", "До початку попросіть письмовий договір із посадою, місцем роботи, годинами, брутто-оплатою, застосовним Kollektivvertrag та датою старту. Якщо письмового договору немає, роботодавець має видати Dienstzettel негайно після початку. Порівняйте його з домовленістю, вимагайте виправлення розбіжностей і збережіть копію.", "Vor Beginn einen schriftlichen Vertrag mit Tätigkeit, Ort, Stunden, Bruttoentgelt, Kollektivvertrag und Start erbitten. Ohne schriftlichen Vertrag ist der Dienstzettel unverzüglich nach Beginn auszustellen. Mit der Vereinbarung vergleichen, Abweichungen berichtigen lassen und Kopie behalten.", source: contract),
            .init("registration", "checkmark.shield", "Перевірте реєстрацію до виходу", "Anmeldung vor Arbeitsantritt prüfen", "Роботодавець повинен зареєструвати працівника у відповідній касі до початку роботи — навіть при geringfügig, строковій або короткій зайнятості. Попросіть підтвердження Anmeldung і перевірте фактичну дату та вид страхування. Реєстрація geringfügig сама по собі не означає повного медичного страхування.", "Der Arbeitgeber muss Beschäftigte vor Arbeitsantritt beim zuständigen Träger anmelden – auch geringfügig oder befristet Beschäftigte. Anmeldebestätigung, tatsächlichen Beginn und Versicherungsart prüfen. Eine geringfügige Anmeldung allein bedeutet keine volle Krankenversicherung.", source: registration),
            .init("change", "arrow.triangle.2.circlepath", "Повідомте про дохід", "Einkommen melden", "Якщо отримуєте виплати AMS або Grundversorgung, повідомте відповідні установи про початок роботи й дохід за їхніми правилами; уточніть новий розмір допомоги письмово. Окремо перевірте страховий статус сім’ї: нова робота може змінити підставу покриття, але e-card сама не доводить чинного права.", "Wenn Sie AMS-Leistungen oder Grundversorgung beziehen, Arbeitsbeginn und Einkommen nach deren Meldevorgaben bekannt geben und neue Leistungshöhe schriftlich klären. Versicherung der Familie gesondert prüfen: Arbeit kann die Grundlage ändern, eine e-card allein belegt keinen aktuellen Anspruch.", source: amsChanges)
        ], sources: [permission, studentWork, contract, registration, amsChanges, basicCare]
    )

}
