import Foundation

extension WorkGuides {
    static let selfEmployment = DirectoryGuide(
        cardSummary: .init(ukrainian: "Gewerbe, Neue Selbständige, право перебування, SVS і податки", german: "Gewerbe, Neue Selbständige, Aufenthalt, SVS und Steuern"),
        introduction: .init(ukrainian: "До першого замовлення визначте реальний тип роботи. Назва «фриланс» або «Werkvertrag» сама по собі не вирішує, чи потрібне Gewerbe, яке страхування діє і які права має працівник.", german: "Vor dem ersten Auftrag die tatsächliche Tätigkeitsform klären. Die Bezeichnung «Freelance» oder «Werkvertrag» entscheidet allein weder über Gewerbe, Versicherung noch Arbeitnehmerrechte."),
        sections: [
            .init("activity", "briefcase", "Gewerbe чи Neue Selbständige", "Gewerbe oder Neue Selbständige", "Опишіть конкретні послуги WKO або Gewerbebehörde до старту. Регулярна самостійна діяльність може підпадати під Gewerbeordnung; для регламентованого Gewerbe потрібен доказ кваліфікації. Інші професії можуть бути «Neue Selbständige» без Gewerbeschein, але з окремими обов’язками перед SVS і Finanzamt. Не припускайте, що відсутність Gewerbe означає відсутність податків.", "Konkrete Leistungen vor Beginn bei WKO oder Gewerbebehörde beschreiben. Regelmäßige Selbständigkeit kann unter die Gewerbeordnung fallen; reglementierte Gewerbe brauchen Befähigungsnachweis. Andere Tätigkeiten können «Neue Selbständige» ohne Gewerbeschein sein, aber mit eigenen SVS- und Finanzamtspflichten. Kein Gewerbe bedeutet nicht steuerfrei.", source: newSelfEmployed),
            .init("status", "person.text.rectangle", "Перевірте право за своїм титулом", "Recht nach eigenem Titel prüfen", "Rot-Weiß-Rot – Karte plus для переміщених, за поясненням BMI, дозволяє самостійну і найману працю. Якщо маєте Ausweis für Vertriebene або інший титул, перед Gewerbeanmeldung уточніть у Gewerbebehörde вимоги до конкретної діяльності та документа про перебування. Для громадян третіх країн потрібен доказ права перебування; сама реєстрація бізнесу його не продовжує.", "Die Rot-Weiß-Rot – Karte plus für Vertriebene erlaubt laut BMI selbständige und unselbständige Arbeit. Mit Ausweis für Vertriebene oder anderem Titel vor Gewerbeanmeldung Anforderungen an konkrete Tätigkeit und Aufenthaltsnachweis bei der Gewerbebehörde klären. Drittstaatsangehörige brauchen einen Aufenthaltsnachweis; die Anmeldung verlängert ihn nicht.", source: displacedBusiness),
            .init("register", "doc.badge.plus", "Як зареєструвати Gewerbe", "Gewerbe anmelden", "Якщо ваша діяльність є Gewerbe, подайте заяву до Gewerbebehörde або через GISA. За повних документів вільне Gewerbe може діяти з дня подання; регламентоване — лише після потрібного рішення про кваліфікацію. Отримайте GISA-Auszug і перевірте дату, з якої можна працювати. Федеральних зборів за саме подання немає, але можливі внески WKO і SVS.", "Ist Ihre Tätigkeit ein Gewerbe, bei der Gewerbebehörde oder über GISA anmelden. Bei vollständigen Unterlagen kann ein freies Gewerbe ab Anmeldetag ausgeübt werden; ein reglementiertes erst nach nötigem Befähigungsbescheid. GISA-Auszug und zulässigen Beginn prüfen. Keine Bundesgebühr für die Anmeldung, aber WKO- und SVS-Beiträge möglich.", source: startBusiness),
            .init("svs", "cross.case", "Уточніть страхування в SVS", "SVS-Versicherung klären", "Для Gewerbe після отримання права працювати повідомте SVS і перевірте початок медичного, пенсійного та страхування від нещасних випадків. Для Neue Selbständige у 2026 році обов’язкове страхування зазвичай пов’язане з річними Einkünfte (не оборотом) понад 6 613,20 €; діяльність треба повідомити SVS у встановлений строк. Якщо очікуєте менший дохід, з’ясуйте можливість добровільного покриття і не вважайте себе автоматично застрахованими.", "Bei Gewerbe nach Entstehen der Ausübungsberechtigung die SVS informieren und Beginn von Kranken-, Pensions- und Unfallversicherung prüfen. Für Neue Selbständige hängt die Pflichtversicherung 2026 grundsätzlich von Einkünften (nicht Umsatz) über 6.613,20 € jährlich ab; Tätigkeit fristgerecht der SVS melden. Bei geringerem Einkommen freiwilligen Schutz prüfen und nicht von automatischer Deckung ausgehen.", source: newSelfEmployed),
            .init("tax", "eurosign.circle", "Повідомте Finanzamt", "Finanzamt verständigen", "Повідомте Finanzamt про відкриття діяльності протягом одного місяця й отримайте Steuernummer. Оцініть дохід, ведіть облік рахунків і витрат, відкладайте кошти на податок на дохід та можливий перерахунок внесків SVS. Якщо обставини змінюються, уточніть нові авансові платежі; дохід від самозайнятості не є зарплатою з автоматично утриманим податком.", "Betriebseröffnung binnen eines Monats beim Finanzamt anzeigen und Steuernummer erhalten. Einkünfte schätzen, Rechnungen und Ausgaben erfassen, Geld für Einkommensteuer und mögliche SVS-Nachzahlung zurücklegen. Bei Änderungen Vorauszahlungen klären; selbständige Einkünfte sind kein Lohn mit automatisch abgezogener Steuer.", source: taxes),
            .init("vat", "percent", "Перевірте Umsatzsteuer", "Umsatzsteuer prüfen", "Kleinunternehmerregelung може звільняти від нарахування Umsatzsteuer за встановлених умов; у 2026 році її базова межа — 55 000 € річного обороту. Це оборот, а не прибуток; за звільнення зазвичай немає права віднімати Vorsteuer з покупок. Перед першим рахунком з’ясуйте свій режим, особливо якщо клієнти за кордоном. Ця межа не скасовує податку на дохід або правил SVS.", "Die Kleinunternehmerregelung kann bei erfüllten Bedingungen von der Umsatzsteuer befreien; die Grundgrenze 2026 beträgt 55.000 € Jahresumsatz. Umsatz ist nicht Gewinn; bei Befreiung besteht grundsätzlich kein Vorsteuerabzug. Vor der ersten Rechnung das eigene Regime klären, besonders bei Auslandskunden. Die Grenze beseitigt weder Einkommensteuer noch SVS-Pflichten.", source: smallBusiness),
            .init("classification", "checkmark.shield", "Не маскуйте трудові відносини", "Dienstverhältnis nicht verschleiern", "Якщо замовник визначає робочий час, місце та спосіб роботи, а ви вбудовані в його команду, назва Werkvertrag або «фриланс» може не відповідати реальності. Це впливає на відпустку, лікарняний і соціальне страхування. До підпису попросіть AK або WKO оцінити фактичні умови, особливо якщо маєте одного постійного замовника.", "Bestimmt ein Auftraggeber Zeit, Ort und Arbeitsweise und sind Sie in seinen Betrieb eingegliedert, kann «Werkvertrag» oder «Freelance» die tatsächliche Beziehung falsch bezeichnen. Das betrifft Urlaub, Krankenstand und Sozialversicherung. Vor Unterschrift die realen Bedingungen bei AK oder WKO prüfen, besonders bei nur einem dauerhaften Auftraggeber.", source: freeContract)
        ], sources: [displacedBusiness, startBusiness, svs, newSelfEmployed, taxes, smallBusiness, freeContract]
    )
}
