import Foundation

extension WorkGuides {
    static let employeeRights = DirectoryGuide(
        cardSummary: .init(ukrainian: "Оплата, години, відпустка, лікарняний і завершення роботи", german: "Entgelt, Arbeitszeit, Urlaub, Krankenstand und Beendigung"),
        introduction: .init(ukrainian: "В Австрії умови роботи визначають закон, колективний договір і ваш особистий договір. Не існує однієї мінімальної зарплати для всіх професій.", german: "Arbeitsbedingungen folgen Gesetz, Kollektivvertrag und persönlichem Vertrag. Ein einheitlicher gesetzlicher Mindestlohn für alle Berufe besteht nicht."),
        sections: [
            .init("pay", "eurosign.circle", "Зарплата й розрахунок", "Lohn und Abrechnung", "Попросіть назву Kollektivvertrag і вашу Einstufung; порівняйте мінімальну брутто-ставку з договором та кожною Lohnabrechnung. Записуйте фактичні години, надбавки й понаднормові окремо. 13-та й 14-та виплати залежать від колективного або особистого договору, а не автоматично від закону. За недоплати зверніться до AK швидко: договір може містити короткий строк для вимоги.", "Kollektivvertrag und Einstufung erfragen; Mindest-Bruttoentgelt mit Vertrag und jeder Abrechnung vergleichen. Tatsächliche Stunden, Zuschläge und Überstunden getrennt notieren. 13. und 14. Bezug folgen Kollektiv- oder Einzelvertrag, nicht automatisch dem Gesetz. Bei Unterzahlung rasch zur AK: Verfallsfristen können kurz sein.", source: pay),
            .init("time", "clock", "Робочий час і перерви", "Arbeitszeit und Pausen", "Звичайна законна норма — до 8 годин на день і 40 на тиждень; Kollektivvertrag часто встановлює коротший тиждень, а для графіків існують винятки. Якщо робочий день довший за 6 годин, належить щонайменше 30 хвилин справжньої перерви; зазвичай вона не оплачується. Записуйте початок, кінець і перерви щодня. Якщо під час «перерви» працюєте, повідомте про це й перевірте оплату з AK.", "Gesetzliche Normalarbeitszeit ist grundsätzlich 8 Stunden täglich und 40 wöchentlich; Kollektivverträge sehen oft kürzere Wochen vor, für Dienstpläne bestehen Ausnahmen. Bei mehr als 6 Stunden Arbeit gebühren mindestens 30 Minuten echte Pause, meist unbezahlt. Beginn, Ende und Pausen täglich notieren. Arbeit während einer angeblichen Pause mit der AK auf Entgelt prüfen.", source: workTime),
            .init("leave", "sun.max", "Скільки оплачуваної відпустки", "Wie viel bezahlter Urlaub", "Базове право — п’ять тижнів оплачуваної відпустки за робочий рік, також за неповного робочого часу й geringfügig. За графіка п’ять днів на тиждень це зазвичай 25 робочих днів; у перші шість місяців першого року право накопичується пропорційно. Дату відпустки погоджують з роботодавцем. Звіряйте залишок у розрахунку й не підписуйте неправильний баланс при звільненні.", "Grundanspruch sind fünf Wochen bezahlter Urlaub pro Arbeitsjahr, auch bei Teilzeit und geringfügiger Beschäftigung. Bei Fünftagewoche meist 25 Arbeitstage; in den ersten sechs Monaten des ersten Arbeitsjahres wächst der Anspruch anteilig. Termin mit Arbeitgeber vereinbaren. Resturlaub auf Abrechnung prüfen und falschen Saldo bei Beendigung nicht bestätigen.", source: holiday),
            .init("ill", "cross.case", "Якщо захворіли", "Bei Krankheit", "Негайно повідомте роботодавця, що не можете працювати, і зверніться до лікаря. Роботодавець може вимагати Krankenstandsbestätigung навіть за один день; діагноз повідомляти не зобов’язані. Уточніть тривалість оплати від роботодавця, а після її вичерпання — можливе Krankengeld у страховика. Зберігайте повідомлення та підтвердження.", "Arbeitgeber unverzüglich über Arbeitsunfähigkeit informieren und ärztliche Hilfe aufsuchen. Eine Krankenstandsbestätigung kann auch für einen Tag verlangt werden; die Diagnose müssen Sie nicht offenlegen. Dauer der Entgeltfortzahlung und danach mögliches Krankengeld beim Träger klären. Meldung und Bestätigung aufbewahren.", source: sickLeave),
            .init("termination", "door.left.hand.open", "Якщо вас звільняють", "Bei Arbeitgeberkündigung", "Зафіксуйте день отримання Kündigung: від нього можуть рахуватися короткі строки. Попросіть Endabrechnung, перевірте зарплату, невикористану відпустку й Sonderzahlungen за вашим договором. Якщо підозрюєте незаконний мотив або порушення строку, негайно зверніться до AK чи Betriebsrat; окремі оскарження мають строк лише один-два тижні залежно від ситуації.", "Tag des Zugangs der Kündigung festhalten: kurze Fristen können ab dann laufen. Endabrechnung verlangen, Lohn, offenen Urlaub und vertragliche Sonderzahlungen prüfen. Bei unzulässigem Motiv oder falscher Frist sofort AK oder Betriebsrat kontaktieren; manche Anfechtungen haben je nach Fall nur ein bis zwei Wochen Frist.", source: termination),
            .init("mutual", "doc.text", "«За згодою сторін» — окреме рішення", "Einvernehmliche Auflösung", "Einvernehmliche Auflösung потребує вашої добровільної згоди: підписувати її одразу не потрібно. Тут сторони самі визначають дату завершення, без звичайного строку Kündigung. До підпису перевірте невиплачені суми, відпустку, Abfertigung, умови про неконкуренцію та загальну відмову від вимог; за сумнівів покажіть документ AK.", "Eine einvernehmliche Auflösung braucht Ihre freiwillige Zustimmung; sofort unterschreiben müssen Sie nicht. Den Endtermin legen beide Seiten ohne normale Kündigungsfrist fest. Vor Unterschrift offene Beträge, Urlaub, Abfertigung, Konkurrenzklauseln und Generalbereinigung prüfen; im Zweifel das Dokument der AK zeigen.", source: mutualTermination)
        ], sources: [pay, specialPay, workTime, holiday, sickLeave, termination, mutualTermination]
    )

}
