import Foundation

enum WorkGuides {
    private static let permission = DirectorySource(name: "AMS · Beschäftigung von Vertriebenen", url: "https://www.ams.at/regionen/osterreichweit/news/2023/04/keine-beschaeftigungsbewilligung-fuer-vertriebene")
    private static let ams = DirectorySource(name: "AMS · Beratung und Jobsuche", url: "https://www.ams.at/arbeitsuchende/arbeitslos-was-tun/beratung-im-ams")
    private static let allJobs = DirectorySource(name: "AMS · alle jobs und eJob-Room", url: "https://www.ams.at/arbeitsuchende/arbeitslos-was-tun/jobsuche-online-und-mobil/ams-jobsuche-hilfe")
    private static let contract = DirectorySource(name: "Arbeiterkammer · Arbeitsvertrag und Dienstzettel", url: "https://www.arbeiterkammer.at/beratung/arbeitundrecht/Arbeitsvertraege/Arbeitsvertrag_und_Dienstzettel.html")
    private static let pay = DirectorySource(name: "Arbeiterkammer · Lohn und Kollektivvertrag", url: "https://www.arbeiterkammer.at/beratung/arbeitundrecht/Arbeitsvertraege/So_viel_Lohn_steht_mir_zu.html")
    private static let holiday = DirectorySource(name: "Arbeiterkammer · Urlaubsanspruch", url: "https://www.arbeiterkammer.at/beratung/arbeitundrecht/Urlaub/So_viel_Urlaub_bekommen_Sie.html")
    private static let trade = DirectorySource(name: "oesterreich.gv.at · Gewerbsmäßige Tätigkeit", url: "https://www.oesterreich.gv.at/de/themen/arbeit_beruf_und_pension/selbststaendigkeit/13/Seite.1090200")

    private static let startBusiness = DirectorySource(name: "USP · Gewerbeanmeldung", url: "https://www.usp.gv.at/gruendung/EAP/gewerbeanmeldung.html")
    private static let svs = DirectorySource(name: "SVS · Versicherungsanmeldung", url: "https://www.svs.at/cdscontent/?contentid=10007.899587&portal=svsportal")

    static func guide(for topicID: String) -> DirectoryGuide? {
        switch topicID {
        case "work-rights": workRights
        case "job-search": jobSearch
        case "employee-rights": employeeRights
        case "self-employment": selfEmployment
        default: nil
        }
    }

    private static let workRights = DirectoryGuide(
        cardSummary: .init(ukrainian: "Перевірте свій статус і право почати роботу до підписання договору", german: "Aufenthaltsstatus und Arbeitsrecht vor Vertragsbeginn prüfen"),
        introduction: .init(ukrainian: "Право працювати визначається вашим документом про перебування, а не лише громадянством. Для Ausweis für Vertriebene з 2023 року окремий дозвіл AMS на найману роботу не потрібен.", german: "Das Recht zu arbeiten folgt aus Ihrem Aufenthaltsdokument, nicht allein aus der Staatsangehörigkeit. Mit Ausweis für Vertriebene ist seit 2023 keine gesonderte AMS-Beschäftigungsbewilligung nötig."),
        sections: [
            .init("status", "person.text.rectangle", "Покажіть роботодавцю правильний документ", "Richtiges Dokument vorlegen", "Для переміщеної особи це Ausweis für Vertriebene; AMS прямо пояснює, що Beschäftigungsbewilligung роботодавцю не потрібна. Для студентського дозволу та інших титулів можуть діяти обмеження або дозвіл AMS. Перед початком роботи перевірте саме свій титул; якщо роботодавець сумнівається, дайте йому офіційну сторінку AMS.", "Vertriebene legen den Ausweis für Vertriebene vor; laut AMS braucht der Arbeitgeber dafür keine Beschäftigungsbewilligung. Bei Studierenden und anderen Titeln können Beschränkungen oder AMS-Bewilligungen gelten. Vor Arbeitsbeginn den eigenen Titel prüfen und dem Arbeitgeber die amtliche AMS-Information zeigen.", source: permission),
            .init("contract", "doc.text", "До першого робочого дня", "Vor dem ersten Arbeitstag", "Погодьте письмово посаду, місце, години, зарплату брутто, колективний договір та дату початку. Якщо письмового договору немає, роботодавець повинен видати Dienstzettel. Перевірте, чи дані збігаються з усною домовленістю, і збережіть копію. Запитайте про реєстрацію в соціальному страхуванні.", "Vereinbaren Sie Tätigkeit, Ort, Stunden, Bruttolohn, Kollektivvertrag und Beginn schriftlich. Ohne schriftlichen Vertrag muss der Arbeitgeber einen Dienstzettel ausstellen. Angaben mit der mündlichen Vereinbarung vergleichen, Kopie behalten und Sozialversicherungsanmeldung prüfen.", source: contract),
            .init("change", "arrow.triangle.2.circlepath", "Як робота впливає на інші права", "Auswirkungen auf andere Ansprüche", "Повідомте службу Grundversorgung, AMS і страховика про початок та суму доходу, якщо отримуєте допомогу. Зарплата може змінити допомогу та страхову підставу. Не відмовляйтеся від попередньої підтримки до письмового підтвердження нового покриття.", "Melden Sie Arbeitsbeginn und Einkommen an Grundversorgung, AMS und Kasse, wenn Sie Leistungen beziehen. Einkommen kann Hilfe und Versicherungsgrundlage ändern. Frühere Unterstützung erst nach geklärtem Übergang beenden.", source: ams)
        ], sources: [permission, contract, ams]
    )

    private static let jobSearch = DirectoryGuide(
        cardSummary: .init(ukrainian: "AMS, вакансії, CV, співбесіда й перевірка пропозиції", german: "AMS, Stellen, Lebenslauf, Gespräch und Angebotsprüfung"),
        introduction: .init(ukrainian: "Шукайте через офіційні та перевірені канали. Реєстрація в AMS як шукача роботи не означає автоматичної грошової виплати.", german: "Suchen Sie über verlässliche Stellen. Eine AMS-Vormerkung als arbeitssuchend bedeutet nicht automatisch Geldleistung."),
        sections: [
            .init("ams", "building.2", "Зверніться до AMS за місцем проживання", "AMS am Wohnort kontaktieren", "Візьміть документ про перебування, Meldezettel, CV, дипломи й інформацію про досвід. Попросіть визначити професійний профіль, доступні вакансії, мовну чи професійну підтримку та наступну зустріч. Уточніть окремо право на Arbeitslosengeld, якщо раніше працювали в Австрії.", "Bringen Sie Aufenthaltstitel, Meldezettel, Lebenslauf, Diplome und Berufserfahrung mit. Lassen Sie Berufsprofil, Stellen, Sprach- oder Qualifizierungshilfe und Folgetermin klären. Anspruch auf Arbeitslosengeld nach früherer Beschäftigung gesondert prüfen.", source: ams),
            .init("search", "magnifyingglass", "Шукайте вакансії без оплати", "Kostenlos Stellen suchen", "У пошуку AMS «alle jobs» введіть професію або навичку та місто чи поштовий індекс; звузьте результати за графіком, формою роботи й датою оголошення. Пошук доступний без реєстрації. Для збереження заявок і контакту з роботодавцями використовуйте eJob-Room. Не платіть посереднику за доступ до вакансії з AMS.", "In AMS «alle jobs» Beruf oder Fähigkeit und Ort/Postleitzahl eingeben; nach Arbeitszeit, Dienstverhältnis und Aktualität filtern. Suche funktioniert ohne Registrierung. Für Bewerbungsverwaltung und Kontakt zu Betrieben eJob-Room nutzen. Für eine AMS-Stelle keine Vermittlungsgebühr zahlen.", source: allJobs),
            .init("apply", "envelope", "Готуйте заявки під вакансію", "Gezielt bewerben", "У CV вкажіть досвід, мови, доступність і контакт; документи про освіту додавайте за потреби. Зіставте вимоги вакансії з власними навичками й запитайте, чи потрібне офіційне визнання диплома. Зберігайте список заявок і відповідей для наступної консультації в AMS.", "Im Lebenslauf Erfahrung, Sprachen, Verfügbarkeit und Kontakt nennen; Bildungsnachweise nach Bedarf beifügen. Stellenanforderungen mit Qualifikationen abgleichen und nötige Anerkennung prüfen. Bewerbungen und Antworten für das nächste AMS-Gespräch dokumentieren.", source: ams),
            .init("safe", "checkmark.shield", "Перевірте роботодавця й умови", "Arbeitgeber und Bedingungen prüfen", "До виходу на роботу з’ясуйте повну назву роботодавця, адресу, брутто-зарплату, години, договір і колективний договір. Не передавайте паспорт як заставу й не платіть за обіцянку роботи. Якщо умови незрозумілі або відрізняються від домовленості, зверніться до Arbeiterkammer до підпису.", "Vor Arbeitsbeginn vollständigen Arbeitgebernamen, Adresse, Bruttolohn, Stunden, Vertrag und Kollektivvertrag klären. Pass nicht als Sicherheit abgeben und keine Gebühr für ein Jobversprechen zahlen. Bei unklaren oder abweichenden Bedingungen vor Unterschrift Arbeiterkammer fragen.", source: contract)
        ], sources: [ams, allJobs, contract]
    )

    private static let employeeRights = DirectoryGuide(
        cardSummary: .init(ukrainian: "Зарплата, робочий час, відпустка, лікарняний і звільнення", german: "Lohn, Arbeitszeit, Urlaub, Krankenstand und Kündigung"),
        introduction: .init(ukrainian: "В Австрії умови роботи визначають закон, колективний договір і ваш особистий договір. Не існує однієї мінімальної зарплати для всіх професій.", german: "Arbeitsbedingungen folgen Gesetz, Kollektivvertrag und persönlichem Vertrag. Ein einheitlicher gesetzlicher Mindestlohn für alle Berufe besteht nicht."),
        sections: [
            .init("pay", "eurosign.circle", "Перевірте оплату", "Entgelt prüfen", "Дізнайтеся точний Kollektivvertrag і вашу Einstufung. Порівняйте брутто-ставку, надбавки, оплату понаднормових, 13-ту й 14-ту виплати з правилами вашої галузі. Зберігайте щомісячні Lohnabrechnungen і власний облік годин; при розбіжності зверніться до AK швидко, бо строки вимог можуть бути короткими.", "Kollektivvertrag und Einstufung erfragen. Bruttolohn, Zuschläge, Überstunden sowie 13. und 14. Bezug mit Ihrer Branche vergleichen. Monatliche Abrechnungen und eigene Stundenaufzeichnungen behalten; bei Abweichungen rasch zur AK, da Ansprüche kurz verfallen können.", source: pay),
            .init("time", "clock", "Години, відпочинок і відпустка", "Zeit, Ruhe und Urlaub", "Перевірте погоджений тижневий обсяг, перерви, графік і правила понаднормових. Відпустку погоджуйте, не припускайте, що роботодавець може односторонньо замінити її грошима під час роботи. Якщо регулярно працюєте більше, ніж записано, фіксуйте фактичні години й звертайтеся до AK.", "Vereinbarte Wochenstunden, Pausen, Dienstplan und Überstundenregeln prüfen. Urlaub vereinbaren; laufender Urlaub lässt sich nicht einfach einseitig durch Geld ersetzen. Tatsächlich geleistete Mehrstunden dokumentieren und bei Abweichungen AK kontaktieren.", source: contract),
            .init("leave", "sun.max", "Скільки оплачуваної відпустки", "Wie viel bezahlter Urlaub", "Базове право — п’ять тижнів оплачуваної відпустки за робочий рік, також за неповного робочого часу й geringfügig. За графіка п’ять днів на тиждень це зазвичай 25 робочих днів; у перші шість місяців першого року право накопичується пропорційно. Дату відпустки погоджують з роботодавцем. Звіряйте залишок у розрахунку й не підписуйте неправильний баланс при звільненні.", "Grundanspruch sind fünf Wochen bezahlter Urlaub pro Arbeitsjahr, auch bei Teilzeit und geringfügiger Beschäftigung. Bei Fünftagewoche meist 25 Arbeitstage; in den ersten sechs Monaten des ersten Arbeitsjahres wächst der Anspruch anteilig. Termin mit Arbeitgeber vereinbaren. Resturlaub auf Abrechnung prüfen und falschen Saldo bei Beendigung nicht bestätigen.", source: holiday),
            .init("ill", "cross.case", "Хвороба й звільнення", "Krankheit und Beendigung", "При хворобі негайно повідомте роботодавця й уточніть, чи потрібне медичне підтвердження. При звільненні попросіть письмові документи, підсумковий розрахунок і перевірте строк повідомлення; строки для оскарження або стягнення коштів можуть бути дуже короткими. Нічого не підписуйте як «взаємну згоду», не розуміючи наслідків.", "Bei Krankheit Arbeitgeber unverzüglich informieren und ärztlichen Nachweis klären. Bei Beendigung Unterlagen und Endabrechnung verlangen und Kündigungsfrist prüfen; Anfechtungs- und Zahlungsfristen können sehr kurz sein. Einvernehmliche Auflösung nicht ohne Verständnis der Folgen unterschreiben.", source: contract)
        ], sources: [contract, pay, holiday]
    )

    private static let selfEmployment = DirectoryGuide(
        cardSummary: .init(ukrainian: "Перевірте право на самозайнятість, Gewerbe, SVS і податки", german: "Selbständigkeit, Gewerbe, SVS und Steuern vorab prüfen"),
        introduction: .init(ukrainian: "Фриланс не є просто роботою без договору. Перед виставленням рахунку визначте, чи це Gewerbe, вільна професія або трудові відносини та чи дозволяє це ваш статус перебування.", german: "Freie Mitarbeit ist nicht bloß Arbeit ohne Vertrag. Vor Rechnungsstellung prüfen, ob Gewerbe, freier Beruf oder Dienstverhältnis vorliegt und ob Ihr Aufenthaltsstatus dies erlaubt."),
        sections: [
            .init("activity", "briefcase", "Визначте вид діяльності", "Tätigkeit einordnen", "Регулярна самостійна робота з наміром заробітку може потребувати Gewerbeberechtigung. Для регламентованих Gewerbe потрібен доказ кваліфікації, для деяких професій діють окремі закони. Опишіть конкретні послуги WKO або Gewerbebehörde й попросіть письмово вказати процедуру до старту.", "Regelmäßige selbständige Erwerbstätigkeit kann eine Gewerbeberechtigung erfordern. Reglementierte Gewerbe brauchen Befähigungsnachweis; manche Berufe haben eigene Gesetze. Beschreiben Sie Ihre Leistungen der WKO oder Gewerbebehörde und lassen Sie den Weg vor Start klären.", source: trade),
            .init("status", "person.text.rectangle", "Перевірте документ про перебування", "Aufenthaltsrecht prüfen", "Не кожен титул для найманої праці дозволяє підприємництво. Зверніться до органу перебування з конкретним описом діяльності; за потреби уточніть зміну цілі перебування. Реєстрація Gewerbe сама не створює права проживати в Австрії.", "Nicht jeder Titel für unselbständige Arbeit erlaubt Unternehmertum. Legen Sie der Aufenthaltsbehörde die konkrete Tätigkeit vor und klären Sie eine mögliche Zweckänderung. Gewerbeanmeldung schafft kein Aufenthaltsrecht.", source: trade),
            .init("register", "doc.badge.plus", "Зареєструйте Gewerbe до початку", "Gewerbe vor Beginn anmelden", "Якщо діяльність підпадає під Gewerbeordnung, подайте Gewerbeanmeldung до компетентної Gewerbebehörde або онлайн через GISA. Саме подання не має федерального адміністративного збору, але членство у WKO і страхові внески можуть коштувати грошей. Для регламентованого Gewerbe право почати може залежати від рішення про кваліфікацію. Попросіть підтвердження чинної дати реєстрації.", "Fällt die Tätigkeit unter die Gewerbeordnung, Gewerbeanmeldung bei Gewerbebehörde oder online über GISA vor Beginn einbringen. Für die Anmeldung fallen keine Bundesverwaltungsabgaben an; WKO-Mitgliedschaft und Versicherungsbeiträge kosten dennoch Geld. Bei reglementiertem Gewerbe kann der Beginn vom Befähigungsbescheid abhängen. Wirksames Anmeldedatum bestätigen lassen.", source: startBusiness),
            .init("obligations", "checklist", "Порахуйте обов’язки й ризик", "Pflichten und Risiko kalkulieren", "До першого замовлення перевірте реєстрацію в SVS, Finanzamt, можливу Umsatzsteuer, бухгалтерію, умови рахунків і професійну відповідальність. Відкладіть кошти на внески й податки; вони можуть нараховуватися пізніше за отриманий дохід. Якщо один замовник визначає час і місце роботи, попросіть AK або WKO перевірити, чи це не приховані трудові відносини.", "Vor dem ersten Auftrag SVS, Finanzamt, mögliche Umsatzsteuer, Buchführung, Rechnungen und Haftpflicht prüfen. Geld für später fällige Beiträge und Steuer zurücklegen. Bestimmt ein Auftraggeber Zeit und Ort, AK oder WKO um Prüfung eines möglichen Dienstverhältnisses bitten.", source: startBusiness)
        ], sources: [trade, startBusiness, svs]
    )
}
